PUID: ENC[AES256_GCM,data:OMV7FQ==,iv:IzEQ3M0LFBIZU/01BEXD267avjGSCceS7SVM8DkOFzo=,tag:S/bMXPSdUwmFy+ReDh2vhA==,type:str]
GUID: ENC[AES256_GCM,data:f4hmpg==,iv:rNBS5F0A3cQ6dJOSVST76sTrn5yB+ssAUGf0tqS/mwE=,tag:6r0RnnlGjJ0r8Ei3aJmIdA==,type:str]
TZ: ENC[AES256_GCM,data:tYP/r4bXob1o2iQS8J5byd/p7Q==,iv:KAfX8USu3xBl3iqm7IymmklpONFRzSwqtBVueeO8NIM=,tag:hVnsNOW57BeKfrCkRXteRw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:Jopuv6Wd0G9kXtz7Y6nIFdI8sT1J,iv:Mk+SXZPaZJKIIefhge/29/NMbocjR+4tGxChq7G0E4k=,tag:ZZA4+PzpBNKT/RkUdiYkzQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:RNN5qKFdNrzL3Pbr,iv:CJ7QNoOgWwfft+ziyYMPsG3l94b4RCSVfO+d/aAe8QU=,tag:96YnlltUXV4QItzRloM3PA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:5MheI0GPLI2W7Q==,iv:0gOVWIbXVxcaBqZfKEfgIjFO6OHIRjPEWs6Mn4uoOpo=,tag:rCAelXmcyZS1BxGE4sjTFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSUNvN0sxNUVreEJURHNF
            QTJGTFR2LzNkKzMweHdHVG56RkVqYmF6OW1jCllUcTRUbGZ0RUdyME15VHI1b1Nl
            U015NjY1N1lZZnArOTFZM0Jkd1ZKMFEKLS0tIFJnYVB3QWl5YU1OYXNjdWRCK3VW
            bUlGTVg2ZjIwNjFJNC93VFJHOENzZEkKVMxJGQvtvCtgAo6Ke9lHRL0hqKrtQJtE
            UWCyNyEYy/gx6YcoanV86hM7DrmOFSsbi69Ps5k9DrJtzxoCQrDQnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:dYmdk7I/7yaarW79F6ifX0fVsOFeLdxpYqIfWvU5OJ53FWaewJ4hGMPhvLtb8Yvf+usZru+gQeXeIXx1vec3UylYU1D+efR5GW6iR1FRoMU1oZRzliyOwbX289LLHkx+qTfmeoAqlS4BmFWaY146F/w2Sb4lyehaj1L/I/fNapA=,iv:yTt0zQPUauz+nZUVJw2jufvcKUeNhDRb//X9Ebc2xYU=,tag:nKPlUNM6kiHBvBCrvTI4Ig==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
