PUID: ENC[AES256_GCM,data:SWNqoA==,iv:Odih5/Nhj6KlMIwCPGGJ641wiFER84kkVKsdWV+Hf2A=,tag:e/3eVuTKODc6ztQHeW251A==,type:str]
GUID: ENC[AES256_GCM,data:OgzXZQ==,iv:edcYoNa04a8wDOVkbCgRfYzgS1j6o9h1OVqoOP7R1Y4=,tag:726U6YTdAWKC/lVomY/ubA==,type:str]
TZ: ENC[AES256_GCM,data:Nhy09XUjGuo+0QxNRlp0oVrH0g==,iv:5if8fp8levK/fuV1dBmB3IVzLvG/dQ6If2wDV6E+R9E=,tag:q+/IZ/25duoNh6ubmGNu0g==,type:str]
BASE_PATH: ENC[AES256_GCM,data:OmI5kYt2mVTVA2JPJLY74seNmI3c,iv:WloGCAvjbRehI0LLw8gm3JubPEdfBWnQD5TWYu6Ms9g=,tag:vgLBk3uY+Y0VQkMEP0+Oew==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:Zrcj7biQRi39wo3A,iv:FHZqVgKkhDVGjv11G8gufTyxrxwfx64At6z6eOm7QSQ=,tag:554WmwQydwN87J+CdANu5g==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:0stbuh90ys1gCA==,iv:WePD+7WMLDnk6i3xADpIA38F7+X/k7Vqb9tx8IYS8KI=,tag:S2/08uqprQYP1jTjh5Fybg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSHJVNTRmckZWZm5kaGgx
            L3hZL0hPUUdrMTBYS1FteWdNTWovbm9kemwwCkp3eVZySW1yUHJCZWZ0N0hLS0lI
            L0dFbTM2TFFkT3lYUlgxWWdiUGtLTHcKLS0tIEtrNVFOWUIxa1dPWUZLa29NQUhm
            ZzFiaEJaUEd6RTc3TnhTdGtQNXdmYnMKKoWc/aXSnmdmP1KWZxKdtQsJRF8BuR5U
            rADU7jKg27dWw8r6xKcUtC8dknVPlcDqDL1mo9kCfRZNHeNQy0iq9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:s/jBMx+1gdqXW/CGGNqSilvn2JIOggcqazcNqQgZ75e5jxYTy4adzpwv+rFwJ1Ic+R9p/GzlMzNH4NxxT1VCSn+6kq99TxF9BDmCxiFbLeI2QgNGYx/X1gjVVMwbe0sKKinRyVqoWlBmy2rwsR+3YOCUzaU7pR7I75EWIdGEUH8=,iv:KT3wrPuKPE/bl3WLyUmznj/xSU1KbJJrLU3z3xEG3BA=,tag:i0f3thWrDCuM0a5Eel4R3A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
