PUID: ENC[AES256_GCM,data:kol89A==,iv:q4Vcg5DVapD0pLFN5yTOCZ0yQ5fSPZbhvEL27cHGz/o=,tag:9Zb+ztTCdS0c/ZOKRNB2OQ==,type:str]
GUID: ENC[AES256_GCM,data:+RJ+pQ==,iv:srypFwClIKpI8S8DPMgXuDNOss+4hC+aFDPDDElmeE0=,tag:47tcVs51IAnxEHM7O/eqpw==,type:str]
TZ: ENC[AES256_GCM,data:2Qt8QsyjiuvUY/jl0j6eWXXxzQ==,iv:7YyoNPkNCHI1JM/SGzuz/34pkVd5Iga3KGDhmkZ59uc=,tag:kK8MFssho9jOTuVjXsFH5A==,type:str]
BASE_PATH: ENC[AES256_GCM,data:g0HhTaZ73+0dTRnBxFp+puwRPxcs,iv:82ICc8f/5uZ3uSh8USsuREbmsx0qCjnln7kPG1Qkd5c=,tag:pXFDnh8n3KjwNoqhDk2IcQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:Y8CFqZrHhnAMY1nh,iv:5n6QhfCZqM4Jg7QvWQRsKzBL6RZ7OVhRKIJ5lwcM7jc=,tag:3XiykedEXK44kF1KuwsTHg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:tP9IB8sKFA5bfg==,iv:MeL21+JhAil35EcvNv2Tnqkcgv8CdYsg4v/ErY8fH3A=,tag:j0etKYeMiQDY2he2/znN9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxM3ZQRkRtTzg4Y01neDNx
            VG9jbmtPOWI4b09VUi9BajVIdjVXZkVqdlgwCllXMnRJY0pGUk1Da0wwa3UwYkVi
            YjlvREw5TDJVWk5CdDFiemFHSUN6Q0UKLS0tIEE1elNUcElOalYveFFSV1dCVWtU
            NmN6WEtxTWRBYUNXNUZqUFRoenV6b3cKxQYLsZRD+57udnAodLN8ejPCoag1APJW
            Idft+6ZuyEIvYYekdGY3URNnn6QxHvop5qo1t9J/DZLCvUO60eLIqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T18:25:26Z"
    mac: ENC[AES256_GCM,data:b2sLITPlrZKTZprMWjhxcE6QM4+fdu/2HVoh633cVgSGCEnSFNRC0MvFtBhB0upjJ5CdTCBa0m2VRl0zNTg4GT1WcyAuZihGBFNgDJTcR1qngZJqNnLxLmvn+ooxTfQ3PcXOCVepXOAl+e2sEklhL+1FsBVrAwkoND7tYqQjj+s=,iv:9kf7aw+6OWltl7c26LeVcegkyuO/15Oi7CukAmxHnBY=,tag:v5+/wKbYkpk295838CUszA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
