PUID: ENC[AES256_GCM,data:HOw0pA==,iv:oP8ir0FKVBTknx2XR/oz92uLQ2DnDhCxMIgh6E0dvkc=,tag:1S25bGEg0P+XPv2zB9j12g==,type:str]
GUID: ENC[AES256_GCM,data:8JxW2w==,iv:zB6GeSq4PEgbuJYuxzdJ5O9QcYiDaS118oCuxoJCH3k=,tag:r+MikAUNh4uHvFa1kY/4ww==,type:str]
TZ: ENC[AES256_GCM,data:iktNg0x2STYKCam4kD3Cwvb6oQ==,iv:AL7p8bZNZAL64fwlfwplr49+2kcfYDRgYp8YfRkMMYM=,tag:xhRt0bwcMkJLMoycYCD++w==,type:str]
BASE_PATH: ENC[AES256_GCM,data:LiCc+8N7vEEtnXkiqm7S+d+pDoDW,iv:zAvql5yLKSlIj6xWu163fyl5iC1H+IeJWywUDxuvvvI=,tag:MBawJoqszAZY39aRSthprA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:iM1r66bZbG9R11eB,iv:dWfItINJIykiqrOV2YLyyOPjYSpnl+n+jOuRv7MMUa0=,tag:779QY3Q1WKTKOjSt7hWXOA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:mFEu2dFbEsGbdg==,iv:AHt28tNjL6sMQe5sRNVWKVL/YMRB4zooAxs96LzFwrw=,tag:hyJThujbpZ0qwYlHe8/41w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQVh6elJuVjlPa3Y2eVBO
            bENvNXRHMHo2RDJBNWhTK0pxaWFIVHNSaUMwCjRKbnhFTFhwU0FMZXhjRXBaT1li
            eHEvclR5VUFYQjBKQTlaMys2WTlRSlkKLS0tIEhuVytFNmNzTk1sL3A3RXhWWWVC
            aW5Mb0FQRUlwNU5rZi9tamQvcWlMakkKlks/VQmWt8RGXLuFlMsNdjFcEcGKzOGE
            1OcDPZIpStC2AonwAmPmmJpe3DZqdyr4hQIWNlVJXoRZaZTBZDsJMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:UfJHaiw7bJd2sLvnaM3l4yQAvUAsbeuUI1VcCGSzvXJ4VUi2hfVzsNtb/H9U4aDvAaaRnscoJ4x0DK1yICDKfaU1dW1zx+4mVkYHwipnkKCtLbAnZvMK/8bNLUQGByS7XVprY7s6vssyr9EljNzD3HfQENImw6T38lpU3r1pL1c=,iv:6RqBEJLBrPic+vVQk0Q64a59PeJ8LUIiY5gtzvYFMDI=,tag:WW+fqZiRsFhPWY0rhWvv7Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
