PUID: ENC[AES256_GCM,data:RM6jbQ==,iv:h/RZ+HpKjJrpi93HBUCgzQiU4n2+lE08kFkHdf3YdbI=,tag:T+k0croTb9+1eCK41VXJTw==,type:str]
GUID: ENC[AES256_GCM,data:nB/WZA==,iv:ihpu/B4XN7LCmI/oDZ2zCcDpq963OZn2L7iLdrE8z/E=,tag:8nTvXsBrufrWq0XXpw5usA==,type:str]
TZ: ENC[AES256_GCM,data:9HU7smmxBiAwFoaRZxp6EqfBAA==,iv:kRiyoIMHiuRrYO/9U4ScfyiB9bbA904IO/qZebJj83g=,tag:Z2UNajkOMgqLgbOkfb5oJA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:c87FJjbmoTAIVEwGKHU6/O61ryLi,iv:s073/Vn3DpauLEDt4in/J5tmNiAM87i8SmyMdtAGX5k=,tag:sddK+Ix5FTSCEEvgcTm/WA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:Hl3BU/MUYb0U2oFZ,iv:ZDEbr+GdHsu1sEfU56vF5x4dwQc2Otzg8h4iW03q2Zk=,tag:La8drg+hz2ePKh3qtu0cgQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:nOhwJw20zFSxrg==,iv:CMXdYy8O9aIZVNFu0BdDZAVctcWCKpjMuMckbZ81318=,tag:Xo4Qm6QLjqnBEpvtkid4yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdFRnUHpER1QyOWNOVkd6
            Q1BwbFZGcTdub2tiTmZhelZza2RURG1IWVNnCjJZY3hqZ1N3YnhsQ1U2WDFZSDd1
            K2laODg1VmR3bTNRclovNmMrVlcyUkEKLS0tIGh6ZW1WV0VaMG5BYjViM0p2VXlX
            bkhXQUJrd1hPSzNMVGJ4T0FjWm4zeHcKnXcE8z4B4Oiekg5QheUnM5zBgXCxtin/
            C7VePep/5AjIfRRX/d1xNXANiSgy6r2D07YcrGr+XKXh+shRiEixRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:Uwr7WC1bkdk7s9ZKLf0uekukcOb9hFxE0kAxqfakBRrRTa6m+dL/k15nQ1GHIUe3Ou4ogFFzEYOYLi+3dVYXqVoUXeoRXlLFwJj3WozGYrHMWX2vr6APqRtl/yQIa9y0czVybqpFWYyUG+XxcWe6DurnDOgnnsJCRoOFq0YsyxY=,iv:NcHP/8GTado3MdFgQzbchdY7i1uspvFusBkZWhOEO2Q=,tag:MSrV9FS/tfU6uFL89gCaBg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
