PUID: ENC[AES256_GCM,data:Kyq/rQ==,iv:o9QzZ0vemZLsmO3ZJCeQ7iPxA2JUrXK2P27zOSX1RnA=,tag:txb7BJXO3KtvNutQy0LeGw==,type:str]
GUID: ENC[AES256_GCM,data:Q+2XBw==,iv:CJ+WWcmJpYbCDA2O8gn59Fk0hTxoMT34Ka1ljGj6Wb4=,tag:2kTVCGw1/D1d+hqcBTVjlg==,type:str]
TZ: ENC[AES256_GCM,data:zQZTu0vwv3+gkGVeEkozhfyK9A==,iv:tV5tzlspR3+7AzNsDZWup2FZ1M+MXoFJ2LO64vsYcq0=,tag:Zp55hJv9UEQAZg9ltGJHzQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:jrVLPsvGsIyi4JTgJQgYXPGVsu8V,iv:DRTZPVOg9UKvyGc4UZgp05wWGCFKkfB74iAtYuXDybI=,tag:eCQp/OH2U/mymTah5lhlyg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:uwjVznxyKUqNGbG5,iv:fHBF/sX0o90W9z0+sRBaGdaH9bd5wdlNfb5pPPDY+TQ=,tag:pYyZ3qzZLjIwKzOJrI/uOQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:xkn4rcXWMkKHHg==,iv:9wU+bikT/OvbEF3eAmuTsf7O9m1hEaarYYQVC/hx3vQ=,tag:3CGUJ+F1vkUpjzoTRyQN5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZUZPMEg5NjNJSTJhcTJq
            dklGWjMwcm1TbmdXU3hKM3FNMnl4SWdNVngwCnFWZlhkRDVYZVlYejVXY0lLU1la
            NGpuejZxcWZScTU0ODdrWEllZmJseTQKLS0tIE8zd2k1ME5uaTV6bGkvM1Nna05Y
            STVEemJtWUlWZnZCMmtDTmN2K2JkMVEKmbxEz6vLHfs22Uzx7KA9ayPobHSe0P9H
            5CbIuHgTmd+UBNwyeLmroUJpJdEFqt7eR/F/qCgJAnxvE2WYWuHmlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:D7oWXyiSidzLyBQghtrCzcGm7tvxv7KWJPhKgGStBs3QQ/a5AuBF4BWL1jbUdaaB/rSqdXKagBjIBIm8lTTFhWHLHrnwxv+3Z+ygNlMMZKguq6BUBkZh/E48SSncODUiPcSLSI9L05TXg/9n8/jJc2AwzgOj1KwRZFnvd2DrIFA=,iv:34K3xU/CVm2qUQdf9am7PTaa3MA6TMZLMXFYgyc9uRg=,tag:RbuNvOrVGRLA5lkhp2LISA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
