#!/usr/bin/env dash
# This file is auto-generated by openmediavault (https://www.openmediavault.org)
# WARNING: Do not edit this file, your changes will get lost.
. /usr/share/openmediavault/scripts/helper-functions

set -e

# Make sure that only one instance of this shell script is running at
# the same time.
LOCK_FILE=/run/openmediavault-iptables.lock
if ! mkdir "${LOCK_FILE}"; then
    omv_error "Locking failed, another job is running"
    exit 0
fi

trap "rm -rf ${LOCK_FILE}" 0 1 2 3 5 15

case "$1" in
    start)
        ;;

    stop)
        iptables -t filter -F INPUT
        iptables -t filter -F OUTPUT
        iptables -P INPUT ACCEPT
        iptables -P OUTPUT ACCEPT
        ip6tables -t filter -F INPUT
        ip6tables -t filter -F OUTPUT
        ip6tables -P INPUT ACCEPT
        ip6tables -P OUTPUT ACCEPT
        ;;
esac

exit 0
