check system $HOST
    if loadavg (1min) > 2.0 for 3 cycles then alert
    if loadavg (5min) > 1.0 for 3 cycles then alert
    if memory usage > 90% then alert
    if cpu usage (user) > 95% for 2 cycles then alert
    if cpu usage (system) > 95% for 2 cycles then alert
    if cpu usage (wait) > 95% for 2 cycles then alert
