check process omv-engined with pidfile /run/omv-engined.pid
    start program = "/bin/systemctl start openmediavault-engined"
    stop program = "/bin/systemctl stop openmediavault-engined"
    mode active
