# Alert if disk space of root filesystem gets low
check filesystem rootfs with path /
    if space usage > 85% for 5 times within 15 cycles
        then alert else if succeeded for 10 cycles then alert


check filesystem filesystem_srv_dev-disk-by-uuid-48dc7932-00a4-4aa4-81e9-ea7dd62d1626 with path "/srv/dev-disk-by-uuid-48dc7932-00a4-4aa4-81e9-ea7dd62d1626"
    if space usage > 85% for 5 times within 15 cycles
        then alert else if succeeded for 10 cycles then alert



# Try to auto-mount a filesystem if it is missing. Alert if the filesystem
# is still missing after a given time period.
check program mountpoint_srv_dev-disk-by-uuid-48dc7932-00a4-4aa4-81e9-ea7dd62d1626 with path "/bin/mountpoint '/srv/dev-disk-by-uuid-48dc7932-00a4-4aa4-81e9-ea7dd62d1626'"
    if status != 0
        then alert
    if status != 0 for 2 cycles
        then exec "/usr/bin/mount '/srv/dev-disk-by-uuid-48dc7932-00a4-4aa4-81e9-ea7dd62d1626'"

