PUID: ENC[AES256_GCM,data:Qz19Lw==,iv:GvKbbRNUIyUvHzfVOMD7uxO4P+c9PGm4PTCdxWbbhd0=,tag:TveDJcqRPmJKEnAuvU/guw==,type:str]
GUID: ENC[AES256_GCM,data:pQYgzQ==,iv:t9rS2eAGPN2ViEZvgq8lknIsIn85ni/2vuKnCc+EcMY=,tag:ZPJ6E8n7YOdo+zd89rm8zQ==,type:str]
TZ: ENC[AES256_GCM,data:MCqPQ7dvb3fvowLXZ0uZ+MP8FQ==,iv:IDFA5Yk6wEPmfYgzs3cbPAmXaZ0Viux+th/oZAX74rc=,tag:TjMuxOt2ouyGphUYhdeK2Q==,type:str]
BASE_PATH: ENC[AES256_GCM,data:CDsGGhHEIw5RIu8/FLToxlOefBI6,iv:ke+YFz0N+Z6/PjqNEkmXzKoWDlkTKh64VZGktZEcrCY=,tag:IDd4GKO/g32/kG36W5mmuA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:R4hL3mXj7avZMHCA,iv:cWmAdVq6/nvRvIi73Iab4mubyaWhWjA4VQjHE9Q13a8=,tag:uTWoGHOaTBDY8XG5+L9RKw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:u3xjfvbhR/FNHQ==,iv:dw3U1A5J3iZG0M2eX1y7GDCbWbqd6rTf0KrTdF5PqU8=,tag:0J0tuMgWvrl9FQ4+pLdeiw==,type:str]
PIA_USER: ENC[AES256_GCM,data:H8Qz3qAz6Dk=,iv:A4jT6HoniwkKzGP+aAlXYuFjOVsAunpvJNu8CPMV0iY=,tag:dKb3YchdJeGAy8Mu+x+Aog==,type:str]
PIA_PASS: ENC[AES256_GCM,data:KbdwEONujjINTYeN4vm5,iv:631uAy/oixXXkzBCnM/6anKGuXSctkMyflqLO382mUw=,tag:NBSENZDYvAgC3LDbZ+5fIA==,type:str]
QBIT_USER: ENC[AES256_GCM,data:Iwo7T3vDNv8=,iv:4TZdl/iXmtwbF4CInXdhmyxXq4vJLYzQ//KmdVIAQac=,tag:kADXpUCnARr8GARXJew/UQ==,type:str]
QBIT_PASS: ENC[AES256_GCM,data:7gyrke/H6VP9+Q==,iv:8xJnDPxmlzmRkjiAUHd0ovgZ0Tj9wC7yF2xdqgxNhOc=,tag:QVU7OSgeLJ2wQwHQFNJZyA==,type:str]
QBIT_IP: ENC[AES256_GCM,data:rJna/a8ddXa8FurcUSyOGn0=,iv:SI2d9tR+VzfvapKmV5DQM1NYXYtrgxOOyP2OyB+32ws=,tag:iT++s1/IdUyW7ajeOI1LHA==,type:str]
CBRE_USER: ENC[AES256_GCM,data:oRQsonvc+4o=,iv:rG4Qn6C/bUcyIeBxdmWNZqtrNyEnpmuCSzI7QbJqfZ0=,tag:iLL7oO2ftxrpBXPzmyX9FA==,type:str]
CBRE_PASS: ENC[AES256_GCM,data:XG6dAduvwpHgjg==,iv:5CbvaBmN5lr82SqPrpcZgAhf7UTTEuGMHTor8lIBhnI=,tag:YM5s/Pxe0UugPZDvXWYY9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ODAwWlVJOU1zQlgyLzBV
            dkxMT1pseHhQdnlBd2htRjFFTUNDQnpoc1djCkVTTXZFV0F4V2pBRmdzUjU1TEtG
            ZjA1M2V0VnoxTVB5VE90NFdjWEFuZEUKLS0tIHhDT0prNnpVTWNhbW9YT0E4aTdN
            eHR5VXk4bUJIZU9HT3hycytUdk1oN2MKjzGQnRx5cOpZ+cltf04w7fgnXE4trTaT
            ykuX2+Ow0+U9PYgZ8KzqvKe+71ijltX/3ODyY6hxDXvnX1m2QmxXUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:18Z"
    mac: ENC[AES256_GCM,data:xYQjNd4j7dyBDLGjaTYaZtovs4ZGr9tbXBGMjumykuWVCa0uNXmIY8ffUPC/uZqeAlLMfDTvO1mHGG0d07Iy5mWONB1QumjrNY5Ch25ZRok0dzpuqDJFiri0Jbz7p5nsx0sheWVI2z6wA1kFPDU+w1GrRQSXj1gI2El/pWCB6+M=,iv:vitaIg05rSc2nrgqDyDYFHNy6qxECm6HE+nUUXu3j10=,tag:Nsr7Uu2cX2u9WPWpqrxzeg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
