PUID: ENC[AES256_GCM,data:XRcquQ==,iv:HiTjbnpggOeaBCEkdCiDB3MWQJDsV+sY+8gD/m4J8Cw=,tag:FoCneaB55WndyMcAofjpZw==,type:str]
GUID: ENC[AES256_GCM,data:pzcSbA==,iv:6BLiIN1+vNpxt+lrTpaU89PUneXLvaXI6ZOMnaDWEps=,tag:jbUbgd5t44T1lqs2cf5ZXA==,type:str]
TZ: ENC[AES256_GCM,data:f6UYvSGNNAr/jRS6zhakueTyOQ==,iv:bcFFZ3vdmYFWdRu50kDiIrK6gSMuPnQ9f9J86k0Pwjw=,tag:5TFMi+3Oi1DX5a0xppovBg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:RZ0SSzXh7yupKYcoee6uFGAlgVNj,iv:ZXpL7g59S+CHJ23hRpfqtz0dL8dF3FK1oFXZ7kUQHms=,tag:8oadnbN1q2CZD6teok82BQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:qhLE9yS2gw5dNDWQ,iv:TgLxwHY8cP2euiwZvD1wBPbNrmUde1A4pRsHPIi0E0c=,tag:6b0ou4LLSnWVXqAfgPFsKw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:71BMiOjsaRnhjQ==,iv:VyAB8UP+xkSZF3hrN3yLh9wgqDs3iOaPW51on4gQbdI=,tag:dPxLmeKl75ORTR2ncjsBQQ==,type:str]
PIA_USER: ENC[AES256_GCM,data:oHE6FfKinZk=,iv:C22DV0ejH4P5uMsvqjrg1lCWlnpugR8iBcJb2Yb11/0=,tag:6jonBb4nHLZ7XxOIzn6PkA==,type:str]
PIA_PASS: ENC[AES256_GCM,data:qGV60rv/bVQyaf9CTqRL,iv:HaKEphTNY/T0wc2SMEVh0SOaXo8vgIUoNpFZ7MxNYdU=,tag:7OwEcwby6I1y9xY0e/IQ7A==,type:str]
QBIT_USER: ENC[AES256_GCM,data:aNWW+pX9kEY=,iv:6ICRhaf6pqSvxLSfNgkkwJQ5+Qp2+CoZPJYiVDqZaII=,tag:u/ihNEAY0DTGTZpL2mDiIQ==,type:str]
QBIT_PASS: ENC[AES256_GCM,data:ufoz+tJXGZseUg==,iv:DuoBLzALW6OoO9oH2mxGXnbLi+vOCs6k9V+5msqMNvQ=,tag:YQ827yFxTkL7W4fHH71hTQ==,type:str]
HOST_IP: ENC[AES256_GCM,data:46K6B2LYflWXHApnpy+zY5A=,iv:7CMFb2eUsdi66tcMWoexl3lrTKzKXOJ8P55NkXRiLXE=,tag:NotjonkQ/Gnh5DYTSGXwqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5blJMRTNwYVFIQ0RYVE9R
            ai9aMFJrcEgzZzVrZExYWmUwbm50WHB5aGs0CjRGSDFvYy96ZEg0M2pWbUV0YzFE
            aU5sQWlCemNrT0Fmbk9mQUlwU0ptVlEKLS0tIGczMmppaTBNaFY0bURiYVdqclEw
            RU9oQ2dLUHFIU0dLZTdoU3VPakRxK3cK06CyqaTo/6lS6C2ZPfYWMEoA9F3AmIre
            vx47KORtdQGGo62wB3e6Menf1mxRGxRuYBnqnGRnfI2wmSOIfNguEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:6u3xOht6CUggw+2g59NW1anxl99M1j2SqGiRjle1rAxXNfxENnR7M1rTSTKE0pY615R8eeObMpSuQ+CAcqcKrvnVDc5LhcgZ7Im3sbYe7Q+zz7yZBvwBblbzMu/S9wbYIs25GRGYZQbqcp45cS0bkvnkS7QojLrS1QLcB2BI+eA=,iv:NNWYHyxV9u7TNDRGnRulFZh5dx3W3a+QQ7C0FyQ32/Y=,tag:29FSClh7gDZtyooNFEdkjA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
