PUID: ENC[AES256_GCM,data:QO25ZA==,iv:wNz7rRfouwQPLAyPH8S5wCyDyoZwwepXzyJ91EdFaxA=,tag:pHPfXElm0xFfmWOOrmda1Q==,type:str]
GUID: ENC[AES256_GCM,data:+si8GQ==,iv:ZEsOK8kBWx/LL7+3StXUpXVRgBTxR0txpw65BjDl4E8=,tag:OCDygDt6pLIyEXefMxy4GQ==,type:str]
TZ: ENC[AES256_GCM,data:t3nKwUFcfmpkdpz6bs+Bmp+09Q==,iv:4ULl1PtPfpfsHeOTSahA8psZLcCD4ktpjNqtujM2MaE=,tag:IFBFAMei2X5NQ5VOGkA/ag==,type:str]
BASE_PATH: ENC[AES256_GCM,data:FD7uHUccKSdvZFU31WE4b+Sg8prW,iv:zbQ+qc5maw0ik89j9Hl4HhVY9yNksrS6tjK4Tmhr1QU=,tag:DJz0JRyLm4sdXarOGI3xEg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:kOR+k9XBwOfGv0Es,iv:PezVyQTamm3NhnD19hGSv6QP98Rw58107bCMaetDDZo=,tag:JkzP5Igqp0MkglfTiWyg2w==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:QJxx+1OifnE5Xw==,iv:fVchVfT6E7DESWBwayhHOWIOfr4jQdP+jEUPcZ9+VQg=,tag:cK5YqcY48/25KEku4+If3A==,type:str]
PIA_USER: ENC[AES256_GCM,data:FzNxf/NtBFc=,iv:BObO35UAasRm0K8fwWljM3jrKSD1xvCTDKBnFHunP3I=,tag:fWDK1sA1jRuiz+TXz928NQ==,type:str]
PIA_PASS: ENC[AES256_GCM,data:gV653nPgSGQmwkZGl4zu,iv:ZqhEn20F2k4n9NZB5dxx502jHvPulPGB8dm7iy2WaCo=,tag:N7rI6yGVmOkGm8ErJH8iig==,type:str]
QBIT_USER: ENC[AES256_GCM,data:frbXVIWFwKs=,iv:iDfR4kkh+0/RmB84DB4dlce71XsqLwijyfu5rGE4p7A=,tag:Mlwq/0P7FwFKUVc7t+SEHg==,type:str]
QBIT_PASS: ENC[AES256_GCM,data:wVw47oSr6aT/7Q==,iv:+bdIFu6Py1ZgiiFSvSu9R9HIxJJKXMwSOxMSGM28VSw=,tag:MGUNBtQbOnC2X0bleNJKBQ==,type:str]
HOST_IP: ENC[AES256_GCM,data:K23peuAFL35TI72msI3vUow=,iv:kb9ehaYk3bzSnyvzai4j/VM93OINTiohKgszhPjcAdo=,tag:UiMaDr6sWNAP+weyJuLopQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcm5ranFQbXFDZFBBaGFJ
            d1ptRGFDSmdlZnpwMWErT3g1NmYzblU2UGowCkh0Q3Nqd09KVUk3aFhSS1Q0T3FG
            TVRHNGlYSXhieFBkV1ZxMEZVOWlnTjgKLS0tIGhJTHByMkJuQUxUK0JQbXBsQy9z
            Tk01RnVNZ2JhYktZcnFVZTJrYWtKeDgK2WfY6RWFKoviPek55IHbL/p9W/Lc6Wo3
            X/CEMp14/RmPKOGApBcbHWLihCdTafZKW12gLrg5MRVarnhZ9ZwcCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:4JwkhOnj6ZC02euSqqPzOHv5xbZZdbkOTUi3I56ROTgQXhy1x/DrtuGTywBCv28rDoPrkdI3XP5cQQD4LVToDJFEi9mVcCG5wr2ZmbwiF4WruKMSoPS+tn6Kdsnvkz5P8JmPTY0c2gQVA0+9ZpqV/Qd4QjkMz7ENOyVTo5EBk5I=,iv:wzFOt8PJsrT9mWeFfpyICnJ+4xpyj6Ipl7iVWmEJ2wY=,tag:MfxaA9coljxAVdMMPnA1Yg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
