PUID: ENC[AES256_GCM,data:EcjzjA==,iv:auMfgXvSfuMRuOnngXblLAh2ORjGkbAh5ZfYNwyieEk=,tag:Oj8O8V98kACDAov660YPIg==,type:str]
GUID: ENC[AES256_GCM,data:nfVvQQ==,iv:DsiPzxg1ZUKuX21ehGrWWxoFY/QyOtNtpcCU6zmRbTg=,tag:Vk5Is5b0eQrHzTWhy7Rs5g==,type:str]
TZ: ENC[AES256_GCM,data:bGOdVpoAigxtNllvJ7UbO8wJVA==,iv:+Ysvgt0Xa8St42uSj+RBDXCuxaPupMflv1ITSHZgj6o=,tag:v7pOuWCpyxb2zWyo+D5ZDg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:DkCbtlRlTEHH2hZyZ6CvvCqLRRws,iv:mH90UvkKt2741cPT3Wy66X7cAPCJnQCAf9ZPC8CfN/4=,tag:vWPQaMcK8EpVxbRXE0JulQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:v1sMS4T7KqiLw2mm,iv:0RwZzhoPhPBszTbecb26P02HqK9EMiopVXkh0QzJTPw=,tag:d8wLTv+bLF4QvNQf3eERJw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:POn3zp0s7dDvTw==,iv:q/K/M0ERCxb8DDTyoMuRmnGcm/wmaLgSe4zFmTS8lFM=,tag:NnIB3WAdhRXBoa+QyqNaRQ==,type:str]
PIA_USER: ENC[AES256_GCM,data:E1P2DaRGnpg=,iv:gaUp3nAtuFaz/p5VPNXV6Q9PBTy/+0sXKbJSkqltt60=,tag:YSjQ1lmoxUC7lX4AWtligQ==,type:str]
PIA_PASS: ENC[AES256_GCM,data:+XcZbEim8PapiSSVd3Sq,iv:uymrtsciTzS9U86vir9CUDjwzEICYisoNMfuJtaUcTA=,tag:k36ZdQC4YyhNqz0ZmPi5bQ==,type:str]
QBIT_USER: ENC[AES256_GCM,data:2AQF1QixOuw=,iv:Sqk9bKRuuKT0X5o0LoF2WYVoalv4r0dBnpX9UyY5bg4=,tag:vkGJnTRtag907i2qfZvFtg==,type:str]
QBIT_PASS: ENC[AES256_GCM,data:dfDjbkj3plDkLg==,iv:N/3OjzY0mY+1LWeielQK8+TjjSKPYr3ViJyVqCX3kCQ=,tag:Eoay+xNQhjfxT7VbD7n8sg==,type:str]
HOST_IP: ENC[AES256_GCM,data:+Qt0c83GR7VBCYiG7lDX3vw=,iv:C7Cfekq/NQHyFvbxGRDAa6cMePgDFxflZt0x/37667M=,tag:PIylE/GXWJcOA0CZ1l0a5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZzUydjZKYXBQbWZRNGxw
            V21QT1NLTDJBR1p4OExIRVpVSnRMN2wyZEQ4CkI1OThjNUoxR1EvQVpYM0tXNGtN
            TVkxajFOZm9LWk92TkZLc3pUM0ljRHMKLS0tICtOZ1NVdnNua2hzYldFMW9wb003
            Ny9pdFlkZGVOQ3h6SGhHalh4a3ZHMjgKK2Jo+Dfk7CYOzA1EBThgXrlk8WtlqAEk
            8Y0bOIMWFCBRuyROQ+7oDBFFbIclSaJeDPy+WbVf7SEszgL5k+ijbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T18:25:26Z"
    mac: ENC[AES256_GCM,data:WOgMx86maV1hYi4ll7zMr7C6bLcynoiW8dTmt8jZq4dkMg0bcGspxvlBwuJUJOEiOpaAc5aI6akDZlB92hMwzdSc5oNrRPz+dZ594OCA+SjumTnFRIh8Ft1GyXS4tOPPoU08zdzA4X8KvpXBxaWjHnPhn84Q/2nUg1CrCfm4QUA=,iv:UOtDhEaa1xea17+jKlKB6YGtlWArkuRXFdtPjNeCOY4=,tag:qHIjMZkEDdaU3WF3uf//LA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
