PUID: ENC[AES256_GCM,data:AucUAg==,iv:ETfwDNM+H93CAnxWh2IsYFxAgIYkwEqLIqEKL5jGQC0=,tag:tAS/Wm59+zqTXHlTTq07ZQ==,type:str]
GUID: ENC[AES256_GCM,data:jSrfcw==,iv:VPsOI3GOSlUk5xyO2MPSuhy2zQVakXCN4BcJfiy0Obs=,tag:TaFstQQeF5EU3EAWL0FzhA==,type:str]
TZ: ENC[AES256_GCM,data:/jTbQBKLDlVEoNZE2YL8TuwZ0Q==,iv:e+UhC2S/Df0yMuI6wwhEtMqKiGII5ZA2+3ZLGrs0JlQ=,tag:agMTh+etuvyd0nk2W9Hq3g==,type:str]
BASE_PATH: ENC[AES256_GCM,data:E5NARZSF/+0WY+JSSD8RlBvcYPwr,iv:GmwuQufB2t1ZdzpJVUxiPAxHX845QwsQucFL3D3oUjs=,tag:SKcG//Q2T/w2TYggRV5+uw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:vNDcnnQiamqHnhhP,iv:OzywEzfjTP34rEMjvRHskBRxLlgpuwtrUtp8i4m9flY=,tag:Oax4BrWeQqQ6SxqMEEEZPw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:/BfxgfsPosDepg==,iv:cSG+1wMzId1ODASgYIcZEGIusBMaARbsXtvD37P02SE=,tag:L1obVFYewotqtR2EShlsKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WkIyQ1dRcHh5VGQ3N1U4
            UVo0RTA0YmpYbW5hWDNhUFRldDM1NUZSd2dNCmNtOXFYREhYZXNtQStQenhLT0p2
            UEdsYXQwUFpHamdnclZqekg4bjhqQ1UKLS0tIG9qd0dyTjE2QVZUTnVueTF6YkFy
            L1IzVGRVMDc4Uk1nMEUyV0wwSVVSdkEK4BJSIyzBodgzGc8VcDpBzGRhtNtSP9XD
            9AxFZsdASvF2oqp3URo9WI6wHxyLdDNTrqt9hf86xKkF/WuSevKgMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:hQwmvkws8X8fycjq+5BZghjo5YeKo9a5A0KYLKi3jhKG6Wq7pQ4S7gu8TsKVrMWq/8CByKXtNr27olPVOyQltUgQ+3RMDXat5NUjzJoltQbiQ07SYn+l+KLjmPXE8TttpBp1NVOuOxmG8aXLPHbPW5b5oyGgBIUUmU1tJoHSqG4=,iv:UJkjwoqzC/DWQKveVgieVg+Vdot70DiziXFoIvTEPxM=,tag:TugzAuaoXwzAVu3YdlLr/g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
