PUID: ENC[AES256_GCM,data:kEuAHg==,iv:vgK+ffprk8XP7WwadVhED0Et87mH5e+Buy2CiR+H4zg=,tag:R+uttb/T52hoVFMAjvULtw==,type:str]
GUID: ENC[AES256_GCM,data:S2QCAg==,iv:rHqWhPPWdR/nLrQEUyXZfCcGGGnx2k91KF5Lp/tYsLI=,tag:n+DTXQZs1W1xJTmOM7I57Q==,type:str]
TZ: ENC[AES256_GCM,data:eGL2oQtTXJ+i0YaqLT88TdGDKQ==,iv:p5CZWKvU4POcNsmYalbbI7HVTYe9D6dXtv5p4x+9rPU=,tag:Yr6K6p4fbovj27Ah3Zxu2g==,type:str]
BASE_PATH: ENC[AES256_GCM,data:8lM23ULDrkNBrf9w2kY0VDVv8Hmd,iv:QuFOutwzaBpcy8Ri1z9COyXseRnqR8DeQSJ5G8VyPAc=,tag:gLYSJmeLuz58GsjBbL4o+w==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:fF52FZ+3I+hxZvvC,iv:RjTDsbbazVtl2P3a/ePrrgQW1OgJFzlkNf07HMeIbLQ=,tag:QLjP4hbELoCVT7Hru19nUw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:W/HbfXgkaO9yCg==,iv:t2H5GfsSFrTM6MHiQaDF2x51NGMfIET7rU1kCa1Fe3k=,tag:69oVhLcUBhliJIPD8xIjYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSG4vSlZDU0YxSFFHL3Bu
            aU04RE5ybUdzWVQwNlJQVWFzZm0rNnFBelhFCnNjVnlwQVNoTmVHVDJmTGlQU3hX
            a3ZvdlB4Q0dKUVJBZXJHaDhsUGFKbzAKLS0tIHYyTUVYKys4c2U2YVlCVkkyc2V2
            OVMwNG9rdUFka0RUTlpyWW51WVg3OTgK2z7cqB0ruXO9nBqgnTqjncW8CsuYnR1J
            0/Nt0TLbEXFwSi9C6FOtNmWDnQUPLqE+h/abi+kSgWjUU43MaOUfoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:+qiWmFYLVvH8Ky6gIMGEpUsxbwDgVt3kXo9hFtTLWi4xtvLHvN3cCsU7/4l3FoQ54elyC5M8ran6DMz0apHIIDkDRnsrtHRmfI9SBBzArC6nnYKAd9xJwAy0jvVmRrM+DGPChtV/z+R/R0nQacJPIrgCE4B4y9BtTq5mkHSr/9Y=,iv:oHfyscfWz4GWm6DuQq7IYWRxxs5fu8FRAPKChoD3WEw=,tag:rV1XWy+q+O5ZMz4tu884Eg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
