PUID: ENC[AES256_GCM,data:tKnCpQ==,iv:rJG12uMYHzjbjPYv9FVS/qGw0Agu19q4WKbX3o6iZxk=,tag:a49vwV+XRpG3DKSBvZBlEg==,type:str]
GUID: ENC[AES256_GCM,data:ae+CDg==,iv:S4D16tLg5NRLd9xtQyGnEdw92oazHHY6Vba6GyVR5Nc=,tag:rPwNIseJdwuvH9M8exnz0g==,type:str]
TZ: ENC[AES256_GCM,data:aW4lf+RpkuL0XwpJJDOUEQp17g==,iv:BTjkk0u59mQxceTJUs2XPQTFYHY2OF7aNbiEa+c82BA=,tag:z4psU79nkh/4lb2qWBe2aA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:Epk3PPzNtA3rUHGAK0Su05TReaJ0,iv:jEoYrqs/xeCpoty4Rnt6EvI1FlB0+Ai5UE1eDCxfewM=,tag:KCAK5v273moku4PyI/LP6Q==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:J+xq/VW1phW95VNS,iv:0A2aQzO3Sl0+/S6EqdSrISAwkf4Ro/rPP+fpE+cjMcA=,tag:nrWT1X2fCayv7orxsAPVNg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:sB6fIkV/1hsi4w==,iv:tjEIXQ5j+N1KQ+m+ot/MeKLaa3EJUCxhfdfeJJ8DyAk=,tag:yTCLh0G1PZf+aebT6YrzXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUkNHTlRMOEpsMHpzOFV5
            YjQrYTN3T0xGSkFIajQzcnlNckRaS1FNWHlNCnFmUWxBNERqdHRuUE9RTjhFL1R0
            WWtkQ2lXckhRaDZCczcxa21Jck1Td0UKLS0tIFdEUDhLc09UVDhFTjhkUWFWRFEv
            cURSVVZhdUttM0NTeGtsc1Q3aWdBQlEK7vCds4foR1GV+EZsseC18zetBtkJLcxd
            euPtQcoxK1HIWHpR1Pivf1eFv2Y1THSBpXDYlDGI0J1Sir5pDUG2pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:mEaClZUqUFQISRf9YJvHsMC9xcESZyfjFB06sUrx6RqZbX8VrSpGst6vBnlAb76LGAmPhLLj+IOOyGFfNzr4rjUgCKUzpjeIIiUx6j76kOoIF2CdH+YaQQq8QK5Lxhrt1Xia7D6wBF9NPGTfbU5KYmi6INvQxK/pm8x1WIWUd44=,iv:r2xyKZXgUJpRnp53SoX5GK8jugFcXEi7zjiJbc45dBk=,tag:Z0c5GpHSy0Fwwf4OabZC3Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
