# Default server for HTTP (port 80)
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 404; # Or you could redirect to HTTPS if you prefer: return 301 https://$host$request_uri;
}

# Default server for HTTPS (port 443)
server {
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;
    server_name _;
    ssl_certificate /etc/letsencrypt/live/secure.theurer.dev-wild/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/secure.theurer.dev-wild/privkey.pem;
    return 404;
}