services:
  spoolman2slicer:
    image: ghcr.io/bofh69/spoolman2slicer:latest
    container_name: spoolman2slicer
    restart: unless-stopped
    environment:
      - SPOOLMAN_URL=https://spoolman.secure.theurer.dev
      - SLICER=orcaslicer
    volumes:
      - ${BASE_PATH}/spoolman2slicer/configs:/configs
    #--------Use this for advanced CLI arguments (adapt as needed):------------------
    #entrypoint: [ "sh", "-c", "spoolman2slicer -U -d /configs -s ${SLICER} -u ${SPOOLMAN_URL}" ]
