PUID: ENC[AES256_GCM,data:0KF12A==,iv:U0B1KyC/t+wbE574Sf3YITej485onyIBy0Zne27XvHQ=,tag:MR1PxELxNaJMh9Z14GDJcA==,type:str]
GUID: ENC[AES256_GCM,data:2gA+2g==,iv:TcSZfGTmbIUX5Y6km4h9KK6Pl8FjU+37JikbAzzD7J0=,tag:0L4YcXDmBoyY0HPS8OkrLA==,type:str]
TZ: ENC[AES256_GCM,data:/04G3HeOTCjd+z306hmL0lHmKQ==,iv:oy34SxA8PxoqCZSqnGe56xV41+nN1uuNROIaaupcLrE=,tag:ycGqk5/561cIbf7Ge5MhOw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:UIIYkCxI9ZWSyjISITTGRCiG2H+K,iv:coWPMxg3b4QvubEZj7thYStDmL9ZXx9UxO+2gjowTGo=,tag:AIcr7fRy/84z1POTTqjIWQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:mEqAEoW7Y9noCtmL,iv:pbYpIw+jw9A4NGZ+YhfDP4U2xQ8l7FZL9+aMaDhVCJE=,tag:Otr1mqjA+3JJJ27ns3+TmQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:Gdfh4ZXQ+H6JEg==,iv:hMAzK2lHJajOfYvSYu3Vq0VhnA2k2Eb6kRlFEVWvauQ=,tag:1ue4WaLEHreH4X8OEjrnfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRWRCSmZyU1BobU9TR2kv
            Y2dUY2FxanBGVU1KSUtXaHA2TEU5cCtDTm00CjVaRCsyUGhNZE1ENUMvbmZER09R
            emJDQXlhWGp3djh5MUFwd21yZi90SEUKLS0tIHV4QllZWGRnUnJYZzNaWlNjWERl
            L2RUQ0srVktxd0NkODZNdi8yUWI3aUkKDuJQ2GJbtDq4tvXZIy71M65SHAwQQB+2
            9kYRCygXdcR5Rn1+X7hJTyg70IUFPkDJ6G3x9ukGZ1hRDPi6w/VTsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T18:25:26Z"
    mac: ENC[AES256_GCM,data:c3o0hQSKhOVDdmjodoP8wBQXwrQa8Z57QRqedEkOPmbgGT2nF0Ufhk6HU9nLgE3bubAmYSq7Uh7EaYc4MCIWevL3pc8rpjNbaUw7vn/6fQfwI4FyYGj3P0leiFDxkZ7gplnpJlp0dVBEp74DfbtCtDJgq5iGYH3NgovIRpUQ1bM=,iv:O9hp80T1OGNTfsmqsbF9LLVV8gVjkg6nIWBqytLR07o=,tag:+ohhfb69egpoBSmowgMg1A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
