PUID: ENC[AES256_GCM,data:a9dXmg==,iv:FjhEKDNHY9dQYM64hzcgyTQEid1g/REOXi9oDSNpQcA=,tag:40i7A0t4PfzOL+Z3XQzHAg==,type:str]
GUID: ENC[AES256_GCM,data:Ec8CQQ==,iv:iHvM065KXa/F7KMCVLTObf5e+G/QXI6q5ZMIOyJEcIA=,tag:+74zI98Tr4myBsNpUJM9Hg==,type:str]
TZ: ENC[AES256_GCM,data:DhEaZY3ygSRRuVoywJuAlHm4TA==,iv:lDO1ORO9y/MJ15uNZN04gYl/m/g7OGRUklVmekMRO0s=,tag:QnSAXaKiCMylPa82omm4zg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:BElH2Q3VWObhIRJx5/6+BovRkaL1,iv:1il5ZX+NwrMjaxBVdqZ0YUiLgVc+jIeSKLqReJXOX3o=,tag:XDEizvOEd+RYTspirrFHTQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:fTRW+yirbBwN/zMq,iv:T0ejUJm6+MKRj0fV+UIIne8VrHy04u8Hbp+ah4ASJLo=,tag:Z0VThLtHOsQU9FKxhh8sqw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:f5xSFzG0yaVqpg==,iv:9cY3PL1s8QHGqNU5X8ItX/1dq1QFhNsI8UE759/IA3g=,tag:EgrNNd9C142cQozqfwlcjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdUFiMU5BZG1NelYxL0tB
            SGlvdHphQXQvcTZjMWJKR3dGbVFXck5VYWljClFnUFovVEtxUFNRWTYxb1lQdnBQ
            SmpxUWEzS0x6aHp5ZElIUEwvU2RJdVUKLS0tIEYxTEpWZlV4bEJTR21MN2F4QlA0
            ZldtbmlTUU1Cd2ROeTJpNkdkdkY1WlkKuVQF4dAWID8xGFG8r7x99/90kMHTe07C
            MqWd0zPdB5la/HNiOiHReRpzZJvxTffFflCNqkWgtm10zIF2mB5H8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:17Z"
    mac: ENC[AES256_GCM,data:gbu/F+NBd2OaLYtozFtc6YyyPFiNU0US94GQS4dq7SCxIILv9OgtaTMuPNwXA/r390+kb4nzuPXm8k1kjP4a1R5kFPsI4y52tNEjONFDwsY3/kU1VOZx8GlngSqMsqIdIV4Nh3uHQTBYuj5MkwXsIWLcoZEqYy9PKrXdcYEKbag=,iv:ztOqWPuJx2S1sFQAM8fRO4vyB0qL5BjCdt7LeRQSQsQ=,tag:XzBDEtgPe390V87mIcEAKQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
