PUID: ENC[AES256_GCM,data:VkHkTA==,iv:RgPxRC1nCG2U6drnZ3FcUc6ZjY0qrDSlj42zVoXpLOA=,tag:R0l06L65Y3aEwL/OjvgXfA==,type:str]
GUID: ENC[AES256_GCM,data:q8ymUA==,iv:yY5DPfWpojzPlAUEJ+JIk7cujADp5HHheRY/sD0jkwo=,tag:T+V308x4M2I0Z9zbngHvTA==,type:str]
TZ: ENC[AES256_GCM,data:ojP/GHwSXYZ0wMyjmYriaI97EQ==,iv:9lOALBIGm4zi6Q1FuYKXThbDHEopO0m5QV4wfrBvse4=,tag:oTRPD42cqVoEq/GRHs6EGQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:/4MISK+6eiBge3qB9ffTnOBhDuP+,iv:s4S1BMwyvwIpH3CZy09e3uv9+qn1rKvJxli231VCvP4=,tag:B3hEJ2A9JNDh45f/ZfYJ/w==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:gIVzzt1+WYIiACPY,iv:+pduXF75rlvuKgHjHqo1EwNJEdaWtZ4MptIDWR6sGRs=,tag:TDtmq4kXaPyRlCdH1ke6+w==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:YYsN4NK99SsxFw==,iv:kz1fWNZvdgPjuq+QYYt0cFZDWGINMGy85iRR81pdZBg=,tag:j8EYqzJDENbRSWAKcJnMjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma2RzQUt2U2RYSnpudWZa
            eG1NMmhlMXZSRUNCQVFTY3dLUml6T0xudVFJCnNCN2RKRHB5TVA4cWE0djk2cllX
            U0JHUHhEaUE2aXp3M2hPc1J5ZUs0TkkKLS0tIGRoaUJtb0xyVFF2aGxKZlBtU0dw
            TGZ6TDlmVXJNaGpsRWlkVGxqK3JUdGMKKbFnMkkMCiJP/2e/baQdpsw6GwuLOI+y
            S4YWniyEJzBtKtFt12ZabVUhvq2as8IDVO+BGEBM7Cgr/FjYUvFA1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:HurKXLe+hVlUKBp25cBzfhNpOXGA4KBlT139khllCLVBf0V9nJc09NxoRtsOcgvbMlRbU33DvbwUfaMrHMGo+pxC69p54MSWy23hF6+jmvX1OMZLhOJ+uqOfbdet2Iy3dW+ciIjgNjfTBRVQftd3eSZEbACsoVUfaB9S//6oHlY=,iv:2IENQ78uxKkW122VvD/86qBmFUD7T5tre37LYPIXqxk=,tag:wGEhdiI5xMB8omXA2x8j1g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
