Tunnel_Token: ENC[AES256_GCM,data:TWDM/eWa8i/mPLlELp7GIztABy07ruzdBgZZ2v/++ltndV882mwmYEhuiWrA2wfwerUfCuIuFJiRpbS7qPpgxl8CXckAnEhXJ3r4WcbIvuj8dln+OGr8xr3bOWhecrdN2hlU+K4PejW3EoRudHdoLmOlCNVGGpASXo017Ca9hX8ZZmft+XXTBxVvuz6N0tui8vXtAAwfn8kCvGl2jrLkODXN6YAQ0Xd0mqnAk47rcKnrruzqIkN4dQ==,iv:iccURwTeTOe72JxsYYuGMhptd9X9ZXyERH7j/2qa34c=,tag:aCtEvCDPmGgMEYdAPi00uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByR1o5czhLTk5iODVjK2t6
            R1dqSitpNGR6Mit0MEFxNFVWUkxaclNrTGg4CllOZUIyeURaWW82cTF3TVpzTlg1
            ZUpVNkJkR1M0UDdRMGdwK0QrK1JmdFUKLS0tIGYyQi9ZMmpyZFFmVUExNll1T3Zv
            alJHaGdJOTE5U1l1WWhYdnVsVnpSb2cK0kv26987e3azXGkCZQYS816XsjGg5mVO
            KVpCoESIKBaLhOvKCM2OT9CztpqVvvgP7ZxFTumde8nrN+xfV86SEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:tVEcJ7jlSKUwMU2GFnM+myjPII6nAWPqPOGE1tLsfav863/N2QkZmXwggkcpeFvtyHWti+9ey01VzP5TQoj6VdNzdhNv1i0sOW6sNk4fdOaZiegc1z1XFoZpffH9rx0xX52zmL8eYFW5WLYFEk3W1CWShEq5Pjjjll5JVE+LmTM=,iv:GNhcPHsv0A5I2ObBzMMrTlv2WT6jyZZjmz1rkBp/sIg=,tag:z8NCxgEcZtC4If1Wk5EVZg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
