Tunnel_Token: ENC[AES256_GCM,data:w1kLLv9yc5J/GEyjQGwSOcx8gJS+75h6mvIb/sdpVQ7ovmtI7yym444Rb7LwdIsWgsMWpnUGo4HtW2T3Ei1DUSR0yG8BkOhhHKHRCfK9wbDIJe8MszsN/fOGa6zLAF4r489NLSqaSlWIC0KyM70cUsASclv7ol7TwhZpBGJNyRb7eNStyL956u44xoJXHuC/v7XVZez9rSvAvPF6nqZNmjJm+rxviZ3U/QMf7o9vBA4/H62UnG9I+A==,iv:GGaWgjMk8PO7k0BDradqYggHK7b9dytgVpoOqwnSG8A=,tag:EUJXD3D/oacqekGkLzoDJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWHlMVERBVFNrR3FTeHBH
            M0lYaGxKTG5sRldQU1NEb1BBanJWdm9zTFdvClgwQWVaTFpFNkFTNDluYXd6aGZ0
            VE9oZHloL0JQR29rRGQ3eDlQWlZXUWsKLS0tIHQ4djhrU3JOSmJIbkt6b2xwdFF6
            Um9obDg4M0taVG54SzRib2wwekVhbkEKV3dhLssJ6oVv54u7Brj+xKRJeDWvNwOg
            dn2VA187XD27CXedaN1v56wBdP/Jpm1Kpsj73ocmw0Gb6BLLPWJJiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:zGHZoRd4+UPskq9Tr/T161paZjdoGNnX3GTxiMtlWYeztYnCogCIcOJe/TBjBQ+uiQZvMvU3c57/4LwjOLscaD7L3iZwaKWVHmhIlBwiKXH9JhVi2nN8If/iU5YHukbO53lpPs7gBxf4AryDFgpboGQ7CVXWiyxJCTyg9KZXr3k=,iv:ewdpfzLZ6fjBf5j0lX18hZ3RvyeakqeU6L1irzPv2kk=,tag:82o94E1tT+Hxot6Sk7NoDA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
