Tunnel_Token: ENC[AES256_GCM,data:1uFCMQvT2Rm7HzohZ4WL6k249by81kMNGYmFq5tUA3QeEEKWnyyOiDtMKl2yUAeqhkPnypAZfzQBuO01upOTJXrcdTJ65e5PHQfZ5wI4R2buFwPtwHHJc6dfke85IUHrHyIefxkGQqPL2RQ4nqD27ijb2E3N/NaJMEMYbKZvCN1tN43hJGoAE0T4cH2jWCzspl1jsFo6U9saar6rIUw6XVaDvZ0yWO8K4oRN1RUtHZO8dQCoBp/9qA==,iv:9DDGUjUfx3krbCmcepXBbg/VTqqMSM+8t9XNnV1+ir8=,tag:8cXbtwPzhW5IvY/HsYyfmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTDhUc2hNSnRXREVJcm5q
            QmF4dm54TWJQdWRMYkhyTlZDU0U5MDRTdUJvCk52L1RINkRDc2ZUMWRPZm0xZnZE
            S2crdXVIZFVDTFVqVnFKWG91Z2dUUXMKLS0tIFlHb0pmOUdrbmVYbnRqZWtzQ3Fh
            TmFWazhialAzZWNyaUdPRjR2T2xSdWcKw7blvIfeAdbe0rvOrpaoFXmTp2jP+hNJ
            /z2XrBBlMQdTAY7E3ynvZ3G2E/bjoYcvMlTqa7O9AfzCXAqa/QrX3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:eiv8sQ9GiWhqgG976l2u33F5vgDB1Dys6lqY6LeZc16Tjk6YMYVQZhqdt/KP2wn5cWCblZ8EKVMDeTRLJmgkWg3xzCv2YF7/qh8l1Q/iyJtS+bfhxz1z/QFkfL+BnuFkFsDOfnD8k82NGLHG5fv6JVIdHMzeFQhTnw8U4/8x0RA=,iv:E8Le5W8VwZqFbTx00UYExpkiT5FxcYMPrwgnn3IajOI=,tag:pg+lM09U/Ziy6BmcUoWa7g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
