PUID: ENC[AES256_GCM,data:Q8j2wA==,iv:HjHr5/KiVo3M074av0XBbOTEd7GZ+PbgYj6mBevXaCw=,tag:Pvg3PBNzJf8lr/5kik2unw==,type:str]
GUID: ENC[AES256_GCM,data:7UjO/w==,iv:CgtiZFX9JuFGTSUjOCK+KmVPW00p18qU63zDqmqB27k=,tag:4U0s3/MAc7ZbV70SbV7AwQ==,type:str]
TZ: ENC[AES256_GCM,data:IoZezqElrQAsg7cgDjBlTmLv3A==,iv:sOmHpXo+NvisRxF41EPeZcY4v+bWlyOVkD77378jtIs=,tag:1CtAzs+vECqOSaLtsgI4OA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:S43DZH/VwjAAyX9HSDWfE9MlhLrG,iv:Eqo8pxu3SqSloAPpHFfar3Mp5o9i5X+IxvubS2fDsNE=,tag:3Y/33fegLhbZw0AurhST/w==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:Z5uGNDVe2OhwaubN,iv:K2RXBlX9na7Djivxfae/oipnQGModn1k1mk/gFEoj3M=,tag:dYlL+tdT0kdT7ZuoXMRxlw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:d+HsljdQB6a6oA==,iv:6UqZv30lEzB59O/B6j0BI8WSwgzge4gZRh2QVgQXeNM=,tag:fxCGNYpp8ZQeOl28/MBVQQ==,type:str]
PIA_USER: ENC[AES256_GCM,data:eG35B9+pupw=,iv:lNDOUswtBfjc5qax3ZQpCScG5ncN769IdEA597UEny0=,tag:T2aMIZm9amuywrQGBdwLtg==,type:str]
PIA_PASS: ENC[AES256_GCM,data:Qj7QNiuGWAF2qxm415FY,iv:Cbflb7QOub1uGyDzWvarkRPt8mS/Oi9aca/AsBCF9ac=,tag:SWpnVXvoF4duHfZJTwx0LQ==,type:str]
QBIT_USER: ENC[AES256_GCM,data:CrCiRawrr1c=,iv:Qm+ezUegjROSHNa/A/h/1Cft83kY4GSNUGjyUsjOKHw=,tag:UOM6lJBPxw5FbyimAfo4yQ==,type:str]
QBIT_PASS: ENC[AES256_GCM,data:9SEa0E1Y4lhkNw==,iv:S8vM6G1rtCNil8M/fxCVi1gXu6KyomW3vam6TvxQKrQ=,tag:FidsGUG79JUZybYHzw2gJA==,type:str]
QBIT_IP: ENC[AES256_GCM,data:hukZAftpai4Ojasj7xy6E70=,iv:KQI6mhEn8e1VGzqNl/WFElvrZo/mGpAXx1lLzSqzt20=,tag:V6XraXEuCpJg39UpZBwTbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZGFac0s2UnFIT280TEJV
            d1U5NmpzNHNtZWZLOWp5ZWNEbFI3d045ZlQ0CnBRYnNtWkZHUk9KaTcxYVFuVzZO
            Z2h0Sy9FVWw5VHJRM1BXNnI5d1FUb2cKLS0tIGVJcXpsdzNzTDNZYWtaOGdIZUNy
            cWhmNFd0OFZrVDBlbXZpSkhaK2tHQXcKpu7LMfpw+gMcDPOSykd/I7HzamIbmR8b
            xPgayQf+O+QamgilT4plEYdI9xb7Bctw5yARfYHznW+lPfnoxbTkAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:b7rbbAJ17hhw7lAmUwFccI/R5dXppK1zrfwHTzZYicS7Le2AVZmDhYP8NyMSDulFvgPuasUjoNWczfSeLtp5Ftujen1qC3Jb43SK3eplYvPctLI6vyWdsJz2AWUgwHZzEJCdhVas0OFCRETJjsqNJH2OmfBi8gMkyxcN4TM/ix8=,iv:x8OTIGB20FOLie9Cq/dO4egw6HV7UXPkC/KdHFk5TCY=,tag:WP0bs1MuEQaF50opmpiHIg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
