PUID: ENC[AES256_GCM,data:79I6ng==,iv:wGOR7YfgkQ1ZNDN72PxnBlu8036lOqgalhGsZRWu2Ag=,tag:Yu8fenvI9Rul1Uw6tl5Gpg==,type:str]
GUID: ENC[AES256_GCM,data:MqTEzw==,iv:T+EElNXOS8BoMBmc/PwgpY9OzuWvLjv9C7kvcmOvpQo=,tag:TjtTpkppSUnOA6dKk8CurQ==,type:str]
TZ: ENC[AES256_GCM,data:okUzVXK9LaekD+8YN2dk7csEGw==,iv:Xc+Fyv52Hi/mj84CI6AmZoGJOTDkHQ3LfUudOmcx9MI=,tag:pF+oYHvpIw/b5KPMhFnFmQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:fSeJaXkthiet9N8ZcFMfIBaTrmYp,iv:pe1jy49ur9qIKqKoT8EYEhMwgd6SY6RtMZ4snbk/6tE=,tag:ALPA6N0CXgdzPzNA/m67gQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:6Xn4e9eP4FQT0ueM,iv:9gpFNl9xb0NmdIygZVb4MD06NWoGe5P2UCo3LF2S8H8=,tag:H5PXuspqRCq+6ik+TRslFA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:JWvN0FidgKVIMA==,iv:cyoo5rv68JZ+G7HMn923prM3gT8kCZ+8gOS1tAF7CRE=,tag:nmI9CNT8ZWuWKoazITRjlA==,type:str]
PIA_USER: ENC[AES256_GCM,data:5igTrwF6tHo=,iv:7XT3e3Dcs/+/R5Pdbog/+8zdXq3MESrV/vuwo6Yb+u4=,tag:KawmSzjFQ5pVmKxV1KTC3w==,type:str]
PIA_PASS: ENC[AES256_GCM,data:GNrg1JeyiSV4N1LybY6b,iv:OivuaMUoweqLOMwTK6As9Ot/wBz+ZiOJrpi/fsa41hM=,tag:8tTeR5nHtZ96Pb9aQ8tqdQ==,type:str]
QBIT_USER: ENC[AES256_GCM,data:FF/SO358KMA=,iv:eHa/bMVSGRlLwte1I7aTcLoChkHzBV6p3/d6ySws0JI=,tag:5g91bkmxep4HBjAscELkIw==,type:str]
QBIT_PASS: ENC[AES256_GCM,data:9bwUfhS7hNUeLA==,iv:7BIZUpVgM+VfUUM6OqueZdBd51Ko0VyROiXWkT2tNx8=,tag:XJbk379UbbjrLJ4CHA3TsQ==,type:str]
QBIT_IP: ENC[AES256_GCM,data:sczEOZjA9ScHnP7RMHHAxoE=,iv:TN8IXzNY1+yDqLgBse1h56J/+MKa3P0atZEF/n+Lfjw=,tag:7nNQCYJLFi0Ya4bKl4pM1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsd2g0Titzb21WOHFaVlJh
            a2dabm9KcmlKNXFnTndMT1lLMUFuQ3ZCeFJzCkI5Ry9yQnJjZnMrNEt0SmJIRmNW
            RGxvZ3JPOGlmZVhLS1pRSVVaVzBlVFkKLS0tIFpySGZpM0VUWVMyWjZ4ZjdZMkt0
            WTNsL25IVTJOTEcrVE9IRGVrMVdpZkEK/8fh4LuNe5baEymccYFECFIYGzmno2pG
            gudihASfi9HcgXiQFv0o9JSk6/B4p6Uvd1SskIGnNrMPhxBxvRteyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:c5TIH/+QWRIHjkJGNzmQTeN+44SPCmfu1/N8evEAFUPWwo9DmiWIx9cqNiXnHg6PndWtVOCQnwNbZV4l5HnEl9ZQQKUgH33XuwO8pxYBQJD5DE2vlAFVa3BfZXXbrOM/5cqPqZr5yScWOYXeWo+HnUJK2ka8sLxsi91AxaW0xAc=,iv:y0tii35jrLTPsXsoaVAtAIrhqYbJQgC7zjFaOiZbhCU=,tag:WK2ckfIxWhoBf3ae21WoDw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
