PUID: ENC[AES256_GCM,data:vNmHBw==,iv:s4XIPN6CLrxtegG0n4Z2c6oXLL7vI4/QEckTe5ztPQw=,tag:SFGtj4iyb+f9yaPSz4zGOw==,type:str]
GUID: ENC[AES256_GCM,data:dfLs0g==,iv:34IgbyO9fae+c/NrPOfHpBNdw3nzvsj9/I5yrjIsXJQ=,tag:q40l3qVeo/EMmVG4NDO84g==,type:str]
TZ: ENC[AES256_GCM,data:wLPHv7YF4RgziATHGoM9yDBpSg==,iv:vYSpzSCvU/cRK3dlIoDceyyKFVwfLpwdqQMK3xO466Q=,tag:Fw8QGeqOE1rfxNJprvhZHA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:MZHBpbFTqBV1DowPX1BclgoP68dc,iv:ITs3/MxBB8uzD461W5SLnQSM0KZjAzgyP0RMeGDeE1s=,tag:2aviPkdN1BBOw/EFy91E1g==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:eRgB+7ttN3S7WBk+,iv:Euid9OOs/46dBNYuqX51F0ydtm2sX7K/Y8a/3aqodek=,tag:leJIDM2/askPrRJDpFbalg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:Bo7yjRZQEtvPlA==,iv:0d4cfQYVRD92NBnUEKzXGVx7N15fVtlljoj7/jOHb5o=,tag:hkZBwJ32nukI01xnXoEqOg==,type:str]
PIA_USER: ENC[AES256_GCM,data:11VgBqgZATU=,iv:vmN4n1dZ/ySs9ps22Cs+lWVhvj5oi/M4Ysahx+5G014=,tag:4kyVw2M+IE3VXYYf4vP5tQ==,type:str]
PIA_PASS: ENC[AES256_GCM,data:vrnrQOm2BAAhPcTkQ12g,iv:wIdeJF+xxE+5wI+PWHYkUk67qyD4QxZNpRQMMMRwFJE=,tag:S2z3ZjkqCg9Yqqrw5r5MPA==,type:str]
QBIT_USER: ENC[AES256_GCM,data:iFelKgLdWiM=,iv:yabW53tEgldGAMhxHvek8uTwoW1GGiSkoJ0Bd7cCPW4=,tag:bzad5OWE5JZG4wDTdoWZfg==,type:str]
QBIT_PASS: ENC[AES256_GCM,data:mhuawS6gTXyK1Q==,iv:NonPwzx99eecPmp6Fc1kV65LRANS/BZpwkUSV59FgdE=,tag:53nhTszGF73yU4UEixykfA==,type:str]
QBIT_IP: ENC[AES256_GCM,data:v+Vsw441n19Kzn9C7+auF3c=,iv:SxDc9+q8uBlnST80W6GSxHGo7gRnFD1kcbvyHo1k9bs=,tag:jUkpb0E5S9hHUEg+c9M87A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRU9waU9YQnNJNFB4Vy9y
            a1hjZXFFRmk4N0pwdUQyTTRtelozMUJMS0dnClIyaFA3U2xyRFp5S1dNT3c3YStQ
            Q2FHN1FPclNKMGhpMzFqcUVYR2gzeDQKLS0tIDF0K3JuU1dTQkFFdFp1MjFDajd4
            L2pjUmRPb1N1cTRYMGFUZElubGtVM2MKNrTqLT2hJF1IpsjCS6MqP8aO+z/M4hRR
            QyycpNVHSvnQWsFnMz5N8J4iteBoPsCiQk0AFHn2pn5QMnj6N5wIcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data://uOLyIy0uwRE313B04lXUPJItrXBtGJTChbYGs13kCe+yjSbcO7Bzx3j74+kh9DIt8ojKf0LRx6BOQRpzhZlD0ZOSUUPd3MQFmLm8VDbN3d/E9abP47LElxcXNBs+EtvRRgr+IjKYMmHevc7VjjKP8FEJ5LitBloUNjyWYKdw8=,iv:fFFXoOXgtahUULW/33zqCa6LMwM78L3jdbhXiC8qGaA=,tag:CzapI/NOIOBEyuWjXsCgNw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
