PUID: ENC[AES256_GCM,data:iezrxw==,iv:Z7N8/0VkUuHTZellkTmNQr8FgRF+MXT6Gxor0SeW9Gw=,tag:sl1aHYkWGnIGrsSQTBmYEQ==,type:str]
GUID: ENC[AES256_GCM,data:e9+9CQ==,iv:ib9wKjBsPAddo6QthgCqp6iOTxwPSm8pN2J4mQ6znx0=,tag:WA02LFJniuDYJlZnSwdRnQ==,type:str]
TZ: ENC[AES256_GCM,data:Hq6og/FrRorlVZbaRvHIcb/sOw==,iv:Y24Pjen+jZ9WIzW82W4VOkbsP8ZsITRjrmxJ3eV2DtY=,tag:W4NrA9HlRsYcCJ2XORX10A==,type:str]
BASE_PATH: ENC[AES256_GCM,data:vj3Np1OCobqzGG064qPnLOjXYx8s,iv:eZUhw22FBtZuycPIecaAhYqFh0ux9Ke75VjxufzNRmY=,tag:ZCgu//gHcZ06OsqxRqee+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZHZrMDVBT1RkQ3NCRFZN
            RXQxV0FhVmVEa2RVQlRuaFN2TlNnMEhJMDJZCldZSUx4aVZWbHk2dWVmUForcWVk
            bG1FdmZpR3JiazU0NHdCR25BSG9HTEkKLS0tIDZLbDZCbHhxaFJvSEY0MHFPNUJ6
            RmJaNnNDVk5BYmZDV2tRemVYclhwamcKXpd47SbV+Fz0gZ0TVroGfQJUg0+McGtl
            gOL1AjpJtDJDOjOo3JWqm/rhsvfOuTUHaaRvkT/IY9LDRqJgFJ4XzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:17Z"
    mac: ENC[AES256_GCM,data:y4xUZmossHFO3JN26fV5PTpckT1TKeG/zoYkyBXwSTK3hHImwnu4KyYV74eRIEUPsbs+8CbJzqO9QhNqzrQpGCzk3XL4Rjw4Bj6sMcIoi5HPRaP9176Za4qxAo8MRc7RoffPq6mU/NSB9PRgUVzcSfEsd7HVZW6kINrcUZ6tVL8=,iv:pg/L/6s0DgQ6162FCHZHrxprWXNNy/Zjs4ibMMUzqhs=,tag:fS3r3cjqAbcSQSlu8/w8qw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
