PUID: ENC[AES256_GCM,data:0ZBkAQ==,iv:jvIt3HLFnME6UwyEZhSCQ2YvZ/BtVf9Dd7OfguafL0U=,tag:pwJVHB9evwD/eBJW287Utg==,type:str]
GUID: ENC[AES256_GCM,data:RlnBHg==,iv:XpLcjc82LOqe7KAQC6V8WZewmrlA0pb/nOuYoaDU+d8=,tag:14niyqDQWMgc8F54OVBALg==,type:str]
TZ: ENC[AES256_GCM,data:kB9qqL/Y98S8dJMqTsSELLJSBQ==,iv:AaoP1NjJBJsg9ZfALe7sTHrWpggXHGKQ9goDDzB9W8U=,tag:R3GNJRbRBC8P8rO1uAV55A==,type:str]
BASE_PATH: ENC[AES256_GCM,data:I6q1M7aqN3zd02NyH/1BuD8OpE4S,iv:kAO2nPMXhBHXlEuRtfv1sN80VEI8zjPsUcjUaEcn5mk=,tag:x6GH69fCyXIU53X4TfPb1A==,type:str]
PASS_HASH: ENC[AES256_GCM,data:c22qNWFf+Fuh4urx9rxhe3ivwgMIrmIsUgrRHuEwo3TGiq9SEc5W6pKLnGH7LLQVS6wwrB5WqUpGRrloXATt,iv:lppSeO14oOLUklwRiiKzGDGyrrD6bhMQLpE3qg5KJBc=,tag:uerTZUs1ABox/ubetFrt7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkenpYejdWODhOc1dXcHRo
            MStkbGZrd25yS2dNVWVZMnRKbjBsY1FsYTFjCjJleFZEUXFRV2dsSDFKelpXRnRr
            MUhiZTB2akk1cEFUcEVFRUJYN2lIdmMKLS0tIGtQL042R2NYckpJWnZTSkxNNGJM
            TjRaWnlnTWdnVmV1aDJxOVBxSEJkYTgKrLKUDgJHhX0OWewVM7phNaQ1fviyWMdv
            ufCf2hy4V+IPWOjUfToPcspy/P5qMhmFRTWu9Oh9m8NrfGEzc+Aw8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:vJn/FiZvAJStIS8NNPZ3L2Y3bx5RrcPu8sqhctk328TKPhuK9RrJ5fQdTZvGkUlL0SNouuxXqGM+QjzIEG5mHNK6sju8OCIvx/NXffeDLbHr2GhXEynxYapmch0/DcTymtlG+0mzIeJ+G7+8iKq4KYEv3MMZ4GVhRRkXZLyK4+0=,iv:YmBBnD9iYv/aJ2EPwKOAAfYG9WrMz2Xau8gKN3wXVsA=,tag:C1igGFjxnpFkbnsYbsOm4Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
