PUID: ENC[AES256_GCM,data:un7pCQ==,iv:4g8YrjiZ+JlfAS3R/QmoCkoDaolQiRBrtNRER1yE42M=,tag:COmcTXe71f1vU/3q5IMaOg==,type:str]
GUID: ENC[AES256_GCM,data:yWSclQ==,iv:ERxpm/sLy+irEKxq4P7E0h1so6RwJM5n93bVysmfyGo=,tag:Ss1L0CrgAMD3d+MuVjxx6g==,type:str]
TZ: ENC[AES256_GCM,data:TePWr5qh8sii+p2nv3uaCN9mHw==,iv:D51lSgDb6tK6sRXM5wjobB2ymaXvl5NgQxAi9XYB9HY=,tag:nZrAjbSJzU4uynpDCegNwg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:oGwaUjkkXylTMchDAyYH79ZmHxpP,iv:2Brx7loHyFzuUW7WWd/vXkVElFj6evkOzpxARLiuMmc=,tag:Q56N5pDk9713jDNlH3CyhA==,type:str]
PASS_HASH: ENC[AES256_GCM,data:HCxowOvMwIWq0VIK0E5lk59siyeg1cAKNaUXPcev3GLEfzDVEc/NFSKUThKqdrjQMbDcJf/vki7hEg1Y3Ql1,iv:IfVe1oui7SUC4cSIB7qHaUBR/eh0k4WK52cJtxB4dSo=,tag:IcydeY89nbXEzUxTayfh+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZHpYUEdySDJzL3EwMDNs
            WjZ2eEZoZkRmZVhKcDBUWXowQzc4WGdUVTBNCjJSL2dMSkhVNkx0L3J2WFluY3dr
            VUM5eWR4aEM0dGhrTFo3NFZjTHJhN1kKLS0tIENWeXk0aVdISEI0bmNGYVFPNC9o
            R2dmNUdMUW9yUFBzOXlaMXpQRjFrNVUKRy9o3MJVxREwL7nBB3kcArct60XUvOZR
            erFdq+kkJNl+ZUZTve2mFA7YUeXA3Wa/kxNxubZGYl/MGrhTkO/fRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:06Z"
    mac: ENC[AES256_GCM,data:e49icvonUhFojAuiEeL6rzTAPfTaGgbju7yobnsT736dXrL2YZS5CTWdmSoFxJcHnr9+RbdrjmgLZkR2IZ/0rj87X3gpeoCk3Wu/QWVkUlVns0XLOQ6B2iyEL37cqJXJjSObn2Q3N4kafMZvvuGcs3H9fs/E+PXod1MiPC2zsOA=,iv:oUTwijxf+cTGGXsGDuR0swbzKCk87ViiTYwEvMVu+Ck=,tag:GQ3rbPFJ4OxLsca9CavfWg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
