PUID: ENC[AES256_GCM,data:ExlPXQ==,iv:XUQFMjBwQ0M1ByKNhn2JZrJ+Hb5ms7RDfOI8FPAZCGQ=,tag:gSJO45Sbj6/z6cns5ZFEhQ==,type:str]
GUID: ENC[AES256_GCM,data:Aj8hQg==,iv:MPM+pe6hGqRr7gwbtlKlnSL6Dc72BVx7w+tF7Zfu1/I=,tag:OqosC8sSqYtl6Bafrh3mkg==,type:str]
TZ: ENC[AES256_GCM,data:qhUg5CbZTn8zeAVax2I6KB6JBw==,iv:CS/1JegbBqYiduWalOMsEks3Xn5nfbImXxTySYKEHaw=,tag:4mVwL4gratlHEQRjzDkqUQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:6rgQ+BDy0ghfBqy+fU8TpQnHt1EQ,iv:TykQjSMo+6G5ym2SVy5ABFQ+b5Qeohj6O5uxpqVXWU4=,tag:yg4XT4j0+zUTxFymnbkxoA==,type:str]
PASS_HASH: ENC[AES256_GCM,data:3QYXs8OM+0bGbEQX/rNd7hOAZqLaypJi2cwoEliE3woeh4k/LcLw4hyqH/RWv2wuRfMYe2pmkgM6JXhncjBP,iv:NjRZ6jgNpcKNYiY5r+32cSVhoz1oI1Gqnpgs/6pMVtk=,tag:J/KIBLESm38O2wHQc4zoKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZmtWbXVMQXJrSkt3eDRy
            TVR0aUpOR1NjdDFTZEREQVl0Mk15dGpnSUZjCmFmRHpXQ0NRTk13SWlpT2FLbG51
            MGxRWnhUZis5Z0VGRUlKMC82N3VOVkUKLS0tIEZ1NWFuUDhoeGI2dEZCZXoyVEs4
            dEx6Skw0ZU1PYzRid1E0NG1hNFRMVEUK7w6PBUHV6J/vnJZTtq0YPsNhm/bIG1k9
            nXW/y1foYYFxiKgk0iwza2oy5UJFDCQacc35OjTEcxvxmlLFIwI35g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:VGlG0W6doyuR0x53d6AKUmuH0vu9ISTklmOLX4cbNuCXlSgrd1WGLURdBVTl5pPLTznDP8Lj2LdqrJ5nTlI8O+AnMkp1nkidbWb1fXAN2ks3YXFQTEQsOlCTq8xBtrUZ7cOtcuIOSBwYR7FMPIjbUxEThS/kLQLbSpMCuWXBhH8=,iv:GoZzxja3f6JsmJNlDLomPi97hJyMJwQJqSLY72YnfHU=,tag:SkScJmKYwYuwwkp3BYNRGQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
