Tunnel_Token: ENC[AES256_GCM,data:cOvC5O1UGgX9pV2MjVMvWwEH6eaGI/e0Y8ZpQjOBVMXjTMvINNtQxj+KxSTWHjT0nNuRdCnwkNX40dcw7r9DGN3ywDCANLV2bxkJfQ/HEA45kvh/hLYU3HyO+AGZ7/bI9gBghV0GoBu8fNZToXdRogVeSYhzFVCLOL6LNoB7SK4ukj1pqFg86E+yxfqPdvzSp/hob4omCAj55BWUmcmmNFiMT9h6PW4hA6QsAY75rfxw0F//9A35rw==,iv:Bxcq8IfF+OfrCSlQx/4oOocEytBA1jiP6M+6MYKQOWk=,tag:NK08GxA62JYFROlvE2TSVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFT0MvckxDT3gwTXZjdW85
            T0RRcWRMa1RjVE55ekRqVC93dnhaeGRKSERnCkQ5dGZFVUE4dnhiWTdpZUZNaDhq
            em80dTJWanNxZHp2K3BIWEg1Z2FITE0KLS0tIDdFQ0RVNGt5WmVPcWoxRXY4Z0g1
            QTB3WHFWa05FSXByMlB3cjNtWE5wczgKfphqiAVpsx/SUlTY2FpE154AUu0/z4Dz
            SY0mhV5ZMIs5c1eBArBfFc/IVqcCjCvgNzq75JmaMTkHknn0ldv4Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:0j2ydyZghjd7/4M3oCoXEuh2b98Nzp2GOe9Zr0efSFoCmOIUEMD6nTaWI9J621WSl96EkeBC/GDFeZfzjCSMLLtnGzccoi8LkXvwwEAJNyu95nd0LEYa7VwJT2bCYIDoznS2i7cuPsmf/Dztr/U6mjl4MncAvPLSTk4QTHQveR0=,iv:v4YeV0JhdcU5Pz729fIPC49kpzJOURPT1CH68a4QMz8=,tag:kYD2kCwsw5XIsTmQwGJ4nQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
