Tunnel_Token: ENC[AES256_GCM,data:9LObWQ7+gHdWmHj/3VxELBOba7FX1mzRn2zEgc7aSs8PP/aKzBsXh+f+KPcxTyEGr+QniehlzEKNDANdG7ZgOm1QOFL4H1pt3PiuVFC+Qa/1o4P6ZJyh3bTreb6GmCpe0d9PmIQCWAhrfVUphF4mH12QY0dH+JbWQYOxX+85vXseuxzFROO3GLy21hD8MgnwsBGwRZ368iSLQ+yKcuweJnrgi2YTC270vgx4n1OQcv39tVzTgCVPbg==,iv:GUbJB7F5K9MaB1Fp7zIymuG5BYxkEvl9li4F8tS704c=,tag:hMu0q1e8bsaw44FAn543lA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcGp6Y3RjdkVwRzlibnN4
            cHpncVg1VEJBTVNBczhhRlUzbTBIdVVoSFJRCmYrMXBENGg4OHc4bzlmVDAvRTVE
            UldxNVJPbFhSQVF1U0s1cCtucTFXNnMKLS0tIE8zY0llZ0E0L3IxRStjUkExQWRx
            RGYzWFRHWVN0c2hIVzJTdE4vbnJhRHMK10HkfeLxl9KBQZ43hAefDvLYTJdvqxd9
            bEEinPH33ai2wx4CnV7PegOM1sRRZnSqKTuEGpVibyctbfjs06H6XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:5YmYKvlEGWd1mXAsx0ILNNNdAJWZlA9mP/IwQqojE3W1sGoR8In0QAQhtGG1ru0ez+egkhMT5jN2Zs+/VX8ghydI1mVm4XkvACjgcKkl/mBweMw+pR8wfwPFNeOJUsf8EoqVRy9M2GmZlHj8kwLCnltw77vG44xWI+aKw9EHoGE=,iv:lECOkCgT6JLfmXK3e0A2in3XHahq+CBcQAl/nbfjP9Q=,tag:GfhFDsXEBOkeRI++qk/lpA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
