Tunnel_Token: ENC[AES256_GCM,data:6euKFkcFR7xoWQSCAI1FaCtJmFNS+OBYsq+Y+Z31Yb0FPQFWOwTiVdieFCvVfVgYx+HU7nsE6xBxbFDBVCtrEsnlDmSIJ1flAEJAuR9wzV7STeU40CuQCr/4AM05WLNmEG0LKaOTDBFC/58HIRmCXIe9AXNykaDCSUtQx8tzsrSaDUySzJUFL4n2aR/tACwXncUFHEeqlkcjsPZJvWgHCe0hBDLAQ1UMxVzKpTils2Ug1t3PTDkAaA==,iv:hIht9DntBFqZtsyXggsGrIt12/S6JXG+8Hqvli8b/34=,tag:skIjvoXnpp09ooTedx9tFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4R0JCVG9EMXFGNnBFa1k2
            OEVkQmU0M2lBbjRNT1lXSVlnRDdNTUVud1EwCjhZSDhQVFFkMkE4YVlDUmJoelc4
            dWxPWjF3blJxRHNqdFh1dDhUeEJTalkKLS0tIHNMSDBxN1pCTjAxdFJ2SVdEak13
            K2xjSUNzQXdKcDZENDZGSnNLR1Iyam8KfPjMobu6w5swO1F4OMJKhi3TwzCM2nHx
            O9xaZ6E/xLsS6owQ7T8rn9m69IjRl0VmLpUoOfJQaZ5biDnoySBp+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:XdXnx6wjD8UK3a1dixbfNWADYcm1uxYEHM5UYuunm+8cgQroKaAQ129rSPPGYyODzg+LZ0ck9vFNdU1E5m5o4vOnx3HTpBc1kELbaZ5lHDha7VOqnUhyn1RA6nlqsjAnWNKp+SVHzXqxjp2HdZ8QGOl2Go9vQyvd00cu0HpKWTQ=,iv:MLTQhVH+CqeZVhDU6iBjuIBSeYoF0jgljAyISKdrST0=,tag:ovsdkqFAmPhje2uSUJH1Rw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
