PUID: ENC[AES256_GCM,data:zMolpA==,iv:ZFn6ODz0HQo1v3TeNhQAbuYGDPkfh0WT2XlXUdX12m0=,tag:gEF6o2yZdve7HGcaQzFxxA==,type:str]
GUID: ENC[AES256_GCM,data:IgfxJQ==,iv:RkkVMigzuQ9UBPoq/+5sPTQ9TgOzca32Z++ow8NEoVw=,tag:iQWKc2G81VQSys1C4/AzRw==,type:str]
TZ: ENC[AES256_GCM,data:gPhMLIYn2KU60CW4te9xCgIAWg==,iv:OU15IjM68s0HbopjzXKj9dBOiojKd6nP74dFKJDUFfA=,tag:xuyqlERFszw9cf+Vl1B+HA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:ZUOquT9BzpnMspupLlqeu1+5O9fI,iv:ac2ENRpiv6+WR/dxJK8+H9jreQEJ0gmPOC9HNUj5ZBM=,tag:5r8KLhDqV5byINT4Vi0oUw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:Q0sJ7Bru4H9WTkaq,iv:6VRVReRbO8C9rxoJxkK0LMPwG/S3uf0h5UpSrhBKVpQ=,tag:lZNEpNO4s67BhLE7w/43wA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:l8wCC3J6pDljiQ==,iv:NW1WjxgNE8TUbIx2/8MiMHztWDQ3fXgAMqmhhkTgA/I=,tag:k01NLPPJkXBD5Kz8EE8A9A==,type:str]
PIA_USER: ENC[AES256_GCM,data:vWEwGDdP7sk=,iv:maGcCGeOomYay8Pab+ejqgBEY6cy4wRnK/NLQMBsbEk=,tag:299psqUH4+V3Mk73JpXsrQ==,type:str]
PIA_PASS: ENC[AES256_GCM,data:8qidKftkXfJiUpnnu0NU,iv:M6i3WFAnqqBwCX9H/q6hj9/pMeOF8IZtGz82zlERJuU=,tag:6VHjDE6fhI1pV2klHY1Q5Q==,type:str]
QBIT_USER: ENC[AES256_GCM,data:6hjpIGUGRsg=,iv:wODYnNpLVtgwH7Otpk080hgFv707L9vcmvx00MIohxA=,tag:QC1O80NXBnYPJTnMQJgQVQ==,type:str]
QBIT_PASS: ENC[AES256_GCM,data:MPDqzZR6ULUGiw==,iv:u/VftjFwgVB7PKsa94vDgcLDvoz/5PmV3+rbXNttOsw=,tag:fCXVIUOg6u94anomspdfmw==,type:str]
HOST_IP: ENC[AES256_GCM,data:lUTadfu2zqtpzq/RjXSpZ8w=,iv:/vQF90h0jspovKWBMRbk9EFUa0R1y9KmS59virFE1sg=,tag:maACFskpFlrI//DybCRFFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbGEvZkwrQXU4dnJnREJy
            U2hRcFYzakYwdTJQZVF0b3Y1YzduK2xCQldFCnJqUUczVzlKMHpGVUkyaUdTeDZQ
            cFJ1V2RadFdRWEdtZHkybWduTHBTL2MKLS0tIE5LTDNrbXZDVEIwQ0tsQTJIQlVx
            UVdFWlVPVFlVTlpIWTVjOTRQdm40N1EK/F6i//MG2xDF2NaiXEz9+tKRpHORJNTa
            23rIqpvddSsiTk2IXbgWGvHfZ0utRolq3mgt09WV1YVXO5ILcmrgJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:V5d+6wIMAVv+e1wpX5msdK6/4E93KcIV5s8PHaTq1+kDYtnN6+M4OEoBhTVdr6iICrRrmPhcTJ0LJLh8lcz4h2EXqCS51hLfhj2aWeE5Vx3BvljF7+ojEb6wiaNwWEw8aojlxyo2olh4eRvHbYt2YE9l3FudzBZcn+D3O9Tc+Ps=,iv:Ujf7khQKNENEl9NY8FD9QxnDd6r5+aAtPNlA0mYA9l8=,tag:uA6BrydZd9OkoAH/yn49JA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
