PUID: ENC[AES256_GCM,data:7Ui7EA==,iv:v21klPadoqJuqZbul6TWs3Y+OWuTkcj66m3ko4jnoEc=,tag:A0r0oVb2vTwVwnaxzOHBNQ==,type:str]
GUID: ENC[AES256_GCM,data:QtpXFw==,iv:OjbuYOfs0vjARWrsUIyzwXbpKosWS8CgiUzwNZ/rbXQ=,tag:4lGStMDeZZ+keUjeaOg52A==,type:str]
TZ: ENC[AES256_GCM,data:/roTpghpeqmqHva9ifl+GdnxVg==,iv:/1SZY/ropegiigxK/RmKaZZ+7ZFa8ZMmBVk9o9TttpM=,tag:gvXdo8MtIIzImFtvV5NZdw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:JpNvWt71VNyrMHaRkAaaHhGSUmNc,iv:A2gAXiwzdKGaWQat+LIwXJUTWspux2NRKxuNbP5N2kE=,tag:M+YUSejRd4ypczgab4HV8Q==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:pmnwKmmLpjwMPzmh,iv:eBI+sfdhu5mhwRhzhKygBOzlez4DPvgphPo06qKk1q4=,tag:dPSsZANX61x8zUccK+gofQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:JNvFdK8Et/X9+g==,iv:I2+A3pxxzevsFmYmHMuYkJjtRoKQhrJaORmD/sT+CZU=,tag:m6lD15c9fyb32DYDHfWsSQ==,type:str]
PIA_USER: ENC[AES256_GCM,data:inQmxGUzeWU=,iv:G9k+ckP15MMh1r4KtyhgN+jwYg9sAvBFXnc2+NHEfig=,tag:dMOSbhoksPWWwJVeo4G18w==,type:str]
PIA_PASS: ENC[AES256_GCM,data:r3iS6FedzpClnxt3AGSz,iv:INqiwtKpwaEvtdCJF1imotKCtAswBER+2RThFdg5ItA=,tag:HDzlF7nG0ik6JjwGTf0uag==,type:str]
QBIT_USER: ENC[AES256_GCM,data:yepghXYS3Pg=,iv:iHVV0/2MF1prVBI20/lXpjSV2roCzkj0OTJbstEAwdg=,tag:+2N1sP3R8FUVDhoGfX0zgw==,type:str]
QBIT_PASS: ENC[AES256_GCM,data:1RuuMGISUHNiFw==,iv:opu60QftyVg8sIFi4AJGBtMDNBuHSviYnW7W9upJM/A=,tag:viwowczjoU9yKcyys3DN3Q==,type:str]
HOST_IP: ENC[AES256_GCM,data:nfpFG4D5TVcVvYp4r0gVGQs=,iv:SUzZMhOm4ETG7alKUhxq3evgsL3QAn9BahPyOXzMh2E=,tag:YHVwmS9SuKAfN8YphZ98fQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnM20xb3RWemI2TmtBaWEv
            Y2NPQXJhdWYxQzlqRGxOdXRhd012amZsTjBVClVPZklPdEFibzc4SVFpaFI3eURm
            UEdpQmcxNUpFNjIwQUYvRzJUS3piYk0KLS0tIGtyOUFrZStvaGFrUjlhOVpLYldN
            eldubGljWEQ1SDMxSCtKN3JEbWNrQ0EKqFLCY7Y3kOrIkrhK2kfiT8rKniSNMzaR
            IYhXmUqxEfF6RdoJ01ZvM+y6PeHbPPpfw7LnSLGrq1fAkXo0Jfdz8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:C18BHR4rqXyLOy8udoga1W6tY9DF0oNgHSdTNZ5Z2mfu1VQ9dMiF7lsbv57uxLATt96RW2HodctiGYqUivOO8V1Wj1tZrEzBxf6pLG7IdG/RbybPuYkC3J0oUZ7ESOzHMGeKA6/bEY9JC+4Z04wXcaHx8Xw679S6v6w1DUcj1KQ=,iv:fpewPdEldcfAQmdZCGIKFNIeVFuYUenfjfOkjqvEB3Y=,tag:XtxPoHfLJ6dz/gz1G8qcgA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
