PUID: ENC[AES256_GCM,data:OHAPbg==,iv:by5b7lznpdAk6ZoLWX6KJidTYvZcwKJ25IAhP07rciY=,tag:UaIXUkDAuoG/wThWb1iO1w==,type:str]
GUID: ENC[AES256_GCM,data:Z2RsVw==,iv:VJt8xq8T/dxZC3i2D5s3FstzA0DyM/PmRZE+Xdw9AIc=,tag:kkeDJS1GcQ/NoQr9MszU0A==,type:str]
TZ: ENC[AES256_GCM,data:XDqKeqnabO94jr9RMbjRZpPZzQ==,iv:c69ITBsMmlDXh6g0QGlHY49FsT3uE/4tgBwUNY60rQU=,tag:cSAq5RZVi0l9wCbwk1TBQg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:6eP9Kge9MYr6NfKZx4f/sM3ufO/7,iv:6siuCOgxLuzD3pWOcTSmH7GPoifhECl6knxIayHrbtc=,tag:/l80jZU5xDSmaASVbERp8Q==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:LAjiBeUfszZO5k5E,iv:4mNS/HMiyMAjTKH64eHWCwmim91aiVeTYd29PjjIzz8=,tag:e3GvKbjt5NiSu3+JRhi/iQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:jqTY3F4TKURpXQ==,iv:AdLGUgme4rkUl+441fdwgMlOtRxR8fDiTDFqUPh5m1Q=,tag:tt/VYLd3OsV8kBtOoBNuKg==,type:str]
PIA_USER: ENC[AES256_GCM,data:T9jySiXmaW8=,iv:wEqg4SsF/zXlwp+TppSjQ7bYI4FUnb3qBzusydA/5RI=,tag:cMQl9KTgmqsVU9zA4uNGQw==,type:str]
PIA_PASS: ENC[AES256_GCM,data:EFq3nU49ddhRGHsFcs0E,iv:+EHp/yC6Ds/gkXaYX3tqB0hcm1qyHAm5fVXuDzSj8ow=,tag:7OJLD+Z1mreiMZT1xnzaBA==,type:str]
QBIT_USER: ENC[AES256_GCM,data:jZjEqNi4H0c=,iv:NWiw+47Xkc77szwhyX2YDWY/G9LI/Og7M6cRPer2+kQ=,tag:vZYZa//+2gtuTl+8cDZDUQ==,type:str]
QBIT_PASS: ENC[AES256_GCM,data:8kSdcQjwmVI4aw==,iv:zuI2nXChZtGoOOMBrrYnrpYrCbKUC4rCCZK7eN1XS8o=,tag:yHmDEDu4YC3sAJ/pR0dz6Q==,type:str]
HOST_IP: ENC[AES256_GCM,data:Gc+ixkFpp0wG9z0UGSOAaJA=,iv:wBQ/KAh5w+spJRFr1FjcWZYIlKLtS/vhF0LDsl5lV78=,tag:pW1wFEeNKYJbfNB3aicVRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGR0hLTnVZL3VMM3Vhd2gy
            SXFoWXRENklHRzRLVDhIR01saE5MMnllNlY4CjRMMURIZDU4RHNhRXZZTjZ6bnk1
            RUlCWDJuOVpCbU56ZzNBcjBhbTlCNmsKLS0tIEg0Ym5velArdUtzNXB6YkNMcXhJ
            OElMdUxXWXlVL2diZWg2bTB0N0hZNHcK0zZqxBDrE4tuO+HnY1q1jraht8IdhJu5
            fLC6wkBtm528qBrcxWu1fOq4s41QDGyT1luwMPpQwNcs7lh5W4lL4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:XesS6qpZQEnASUVRhXw8Ajl88JkLbpvwgAsMBAZdo3N03PF0PLqTASFD/aVf/ZakVj6a2MC1JSfks9ndCufGRCURburxZP6gmexRRLBHkfPO12pktBYgJU9yrJuGfeYfF54WYPPTwDkwtCFDuFSpzRGJbbuX3THd5Tskf8bT1m0=,iv:oeI3EjHBEGR8IrfQOPF1Ci2BPTnuz4Pzpk/LQk28QBI=,tag:bQWE0STj86hrSBjrQk8w1Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
