PUID: ENC[AES256_GCM,data:j8/SJw==,iv:2QzAfupXbOcfjofNl2yblQQXgEqf2t8lpVePK1beUgI=,tag:IVXRiKvOV1oUycO7vXXLHg==,type:str]
GUID: ENC[AES256_GCM,data:7s+GJg==,iv:h6AOAzCYeGo/FrOgEkE/aclqJ4zmh7utwDqNwx62I9w=,tag:ft/seDwrFM+Eku+bxTlZjw==,type:str]
TZ: ENC[AES256_GCM,data:OiDEZFDRlH84WEppEN8QCN8WXw==,iv:SxrCbLol+7Pi3w4eTnSNQZ9AwaScoCzxrSoIUJwECGE=,tag:HImn3HOjvz+1feQovPuF6A==,type:str]
BASE_PATH: ENC[AES256_GCM,data:a6ykKjhAVXMgEbOGgnYsyZ8cCMzJ,iv:Jk8cqF80KkxKhMXKICoYetm3VPrzrjOc7Mk5omOgTTc=,tag:q0pfTrrnry40uV/yv89qMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdDRtYVJFQS9UT2JnY1cx
            ZmhGUGZDWUNqQ016bEpXTlRPMFNrTEJRZTNJCmRSQUt5M2dMUHVJYldXK1R0L1pP
            eHVtUHA4UldyUkp1MUlFL05TN2NzZjAKLS0tIGE5K01zVlBBOFV4RE8rYzgyWnRz
            WkRFWDVCZklzbGdGVzhoODNvWjBCTVUKuI3YzDrU0w4g/FyX+9GvkQcZGU619G1p
            +y/xUKHIDsoQpTRiKzFG3sAwAqmKTqmq7AI5n07YbAVFfyUzf5wAJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:J1D7uCwSRR9xzzCrkZDoEvjZ6ORCSdD3B9IU2a/h4T/UZggKJbTb839h8yhVXy0BTjBT0Zc37CHs9WtSD3jYB9FO7Yjp4FRkWmppExw2uKe5p7jLyupDFOoLuxOGh5y7YwEvPVJot89K6j8DHKp9EdaqcL4iBEsLLYvyrCaD8Wg=,iv:otkZVgAhirKfd7hBTDeWYLy31MPAp48fRUaBDI7ukWo=,tag:LbPOu3RGsYTjyCZfnOcNAg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
