PUID: ENC[AES256_GCM,data:L36gWw==,iv:QZXrLLoi3lkOJlSqrhaAjB4+rozmHZuBtG1qZNzDX5Y=,tag:m/YKKSeo3JYU6Tm/zdkO3A==,type:str]
GUID: ENC[AES256_GCM,data:Hop3mw==,iv:AACJKoLDtIW855wrQi1CGp+Yxx8DxEJ/Vt2fFsPimz0=,tag:S8Cq4d8QVzR/qSOHTjy3tQ==,type:str]
TZ: ENC[AES256_GCM,data:8Grp0Dp2smhP/Zc6AhwCfKvpyA==,iv:IPhesvOhsdaAHknWQvQiTmQ/IeFGIHvNs0q9sipTHc8=,tag:wMhgOu1AUMLPadaw6eCL5A==,type:str]
BASE_PATH: ENC[AES256_GCM,data:URGuZkWdkJpk+A7n48iKjxlTIO6a,iv:sZYpNESVmhxLegK4Io5ODHu8U4mq7+shje3EYxjw1vw=,tag:YfAvZoG4QWvPWdAcJlyZjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTHY1czB4Tk9WM0tmbzE0
            aFZ6ZFpla1lYZG96b0xTdWl2THRONkhxTVEwCm9QbWMzK2dUT2hadXZDaXBkeGJD
            eFBISkMzb2dndkxnOXlPQ2g3a09iOWMKLS0tIFdYeDZjcXo4cXBHR3cyb2RxUmcw
            ZDZtNUVucEo5R1p2SGVSQmEyRkN5YkkKEpT/KVCvgkBRGaoeW6wSug6MJmClT58e
            G4nE4uWVpQMk1b66sHnrU1AWKPQ2Oqc6G7D5ZbAmKXpFcE7WRMbs0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:lcXCnQ0b3O1fYHQo/K5lA1ZpMZUwLygH3nTCWiqkpdF9AI5IXm50um5qoEqGbtrsaPl7yTk/KfwMovJKE185tm1WyV8cfbfkTnD0dsUqTM9t+6qT21vPUeYJ03X6JSMggwqIgd7MmfhFH8HA3sCWPaByD+ow2391+MjaYdahZjo=,iv:wSsjSwUJbs2Xay5QB42/SWoL7pCsYNxY35VJnjK1dPk=,tag:fl/g4DCzhnL2DsTSVJy2hg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
