PUID: ENC[AES256_GCM,data:Mm9ZVg==,iv:GdC6Se75OVXQOLuR+dWr4k2HzB1+6bqblrMH4DA8cIY=,tag:OWNqrhCADodNfGuQY4URCg==,type:str]
GUID: ENC[AES256_GCM,data:9/od5w==,iv:bILKQtim0c3ZTAYktvro2IDLHY21P4RjQRvnYC4kHi0=,tag:boKFD20CGR/MAly/5RokQA==,type:str]
TZ: ENC[AES256_GCM,data:Cr8EYEMN/lRr2JqVsdkNZsWdkg==,iv:d/irguUSKg40edfhjZ7jFgr1MPk3tTxX8e5E1narByI=,tag:hzP88/65lANhdX9CSwOZ7g==,type:str]
BASE_PATH: ENC[AES256_GCM,data:jyPEBSdeZn53MaUwPrN3nMcar8pW,iv:SaWm+Kws2VosHMqtbairttKInswFkD3U/UxbwBMZLQM=,tag:VONc30Fk2XWVweUrpUbfrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQemRrVitBaFdkRGpvZUEy
            Wks2TVNFNTVpRjdFWkluK21pTlpQY09kVmlBCmM3b21OVGxEemY1N0g3Y2p6ZUpt
            Rm9nYUh1VjIyMFdwRTBTdmZsK1BNT28KLS0tIDZ1Q0c3dmZIOHN6Q1lOTHVXZXBa
            SkR3ZmFFb3R1TDlFdWNEMEVuWVIraTAK5f3GvDFnIugdQjK+gEkbyov7B/nchoQB
            N3L4927G/eHFT0A3rWTcOGG47nv4d3Kn/4nGLJ/G8wM7Yjb5G8Qomg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:ZtHwoKu/xh1VWvTRRqLyC6jRPAH/g2N+xCBBLi8DB/bdRNnGvR+nz1809KTDHVAKN8N6Q88SzYpU89pI+akvSReAD7vuuDQyCuSC36Dm4cL24oJyBiX9vZtHddK1BlpBX8Oli9rwn+QbcQvgY2bbzQbmD1zX4O+yjCcPSB1//SM=,iv:BYMwSvWL3EouXhF0A5Gx6R2Qca87XaU+Opje0pGZd0A=,tag:GRAsuq1QMlb0GtX8p5cNTQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
