PUID: ENC[AES256_GCM,data:kPcZlQ==,iv:hgY4lOpMZEHjQs9r6YI9zNitSmksArOFSCaJDJFDK5Q=,tag:ikrCPJX9LJlc4Y3N1QO7Yg==,type:str]
GUID: ENC[AES256_GCM,data:yqKvCw==,iv:JCbjQNUkflzIfTDTFgpBqCgz68TPZuOqHT/UGJ4HZ48=,tag:gONtefwffGRqaC14OTjmwg==,type:str]
TZ: ENC[AES256_GCM,data:WvAH3v3XAiUo6TonfssYuj/lmg==,iv:M0JHefooQtNXkAcL+j9jKlJ67yMqdtSbs9J3BAmbDZc=,tag:NHJlLxAaqY2VyJvIDxD7BQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:LAKafIgJyEw7CF0jnOUhyk2MenXM,iv:5pdGcfznWL3E4BmaDeBaVHqTSV4/UE6pNfSkQdoQlnQ=,tag:Yb6oyUabSjiNaCWQUSbeyQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:miA7S0uTaLTlZc6G,iv:HnnZrLicv0Em5KnKF5JiI7mr4+wpAAJpIL1cowWCTvc=,tag:mf0TU9b4L90wkMt83eUCJw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:c6dKaXbidWOFXg==,iv:p3hoAQ/MY7FMcTZDGaSKjqBXepl1KleVUR9fnEaaIcQ=,tag:WjGV7DlGSpDTyIrwMFqsxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERVMrTUxlelcvL01hRlBH
            dGo4ZXFEZFcxZ2FEUkR2SGZjWU9uempQaXc0Ck5WUkVQRGtERE1FMUc1azFYU3Bs
            UEVTTVZLd1lBd0F5Mk9PQUlUZHhUYWcKLS0tIFdaMWRKdmxoNHN1cERqZndZcWkx
            MEIxeTVLa3dLUEFGd2FRdUw3aGZmRW8Kw4SRIF/y/4K4a+tIfBa6rJbBdV8b8Q7U
            a3WB2ZRQ98tqz72f8yvf7UhZe9BkJml3k9AI+knERyT9tz9kIpwiYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:AqancOm1322WvaG/tzc1xAFnoTBqIv6DYF0jbZ3vXPVc4zXEk/92kHDapv4CFdsgdwxRDbFzWJ0o0wYcd39btsEms5mgFxYsU5I72Q4OE11YuWPTXGUruuRF6a8U1JY0yz0ApHnm/WYxSegZk6QKsOc3UxkJXuj410olNtZfsFQ=,iv:wlGckWC1FWF32tLknpkxNeYfBE00J5JxqCI4GBWXAec=,tag:phP7T1q7DX9w/19cefqWFg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
