PUID: ENC[AES256_GCM,data:s55NgQ==,iv:h506qEa+4POIWpY8CKKG5YoG0RJ/57cOU2n0g4TYR3U=,tag:io07TN/83YvagWL0vWFWPw==,type:str]
GUID: ENC[AES256_GCM,data:6ca75g==,iv:rrvse2og5iV8rkrPrx0JwRRP0m9yQisgYxiaaMC3/hQ=,tag:4juQrTeMexO+uZyU2Wr4Bg==,type:str]
TZ: ENC[AES256_GCM,data:VY33sssbbHtPZyBCs2L/1gOLow==,iv:Kp5WnaSiUlcMgcdYrXOqFG4D1gc4EZMm/mmP9xUwrZU=,tag:nFqTe7kBO0QJFwj/RZyZdw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:H3FSTangMk5EtRo+vfyGNUDjw7MG,iv:sz24GTZ2tE2YOvCuGbZMs/GOaM3Wd6gzLfTkcGDE354=,tag:ePNbeg88UaSEIdpzft3X/A==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:iEkEpLubgrmFTo1Q,iv:jwJ8IOZ6Y9rNHjZBEhJ/8KuTcaZuV+VTDmoCOaW3Bno=,tag:qbAzkehpucES32lxyoKUJQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:CU95CjsKcJWjQA==,iv:xFqXD9Z5dGKiEZCLHTMV90LOm6gMqixi+Un5wK3LRcg=,tag:LTAd8r5shz6HuUvXK04vEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Z0JXdW5LcmV5Y24wcjc2
            K2l0VG5oaTQwRnBjVklRNzZoeVBUOWg4V0NBCkc1RzNCYngwV0N4UEYxdTRIaENO
            encxNlVRcnBaYVNxaDFQcGZld0t6ZkEKLS0tIGZINFZybFVxR3JoeHJIa3daTlV2
            eXJJSVpvbCs4QWJjbGVPajExb3hLVmsKqF+WbWDEVFXFLBrd4QqxQNNi1mh1rdHT
            7iqwlZX+3O7Xr7QkDmkdjgbEMafS9rJMiulGSUOboHzounzcCcHdIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:CNULE16WtVtD2d0Scgqx8EeKi5GFV2mkJ5vSOELSFjZxBUVCa59CAf9FWRVNNfonlgFm5G9vUbLPtLcUD/ecDLpaZPbp4yubvv+snoEgBh7ReoNYqVTAjtXacvgwgxqSFqK9CIZSMOtfvMrF6zWdQA3SscTNofZcULsaH23SUcg=,iv:dryUzuW+99pCShtCf/rxuWfPxoOMs06HDY0KrXknOJo=,tag:F10tNiEwHDNx+uXtExT1IQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
