PUID: ENC[AES256_GCM,data:PbZsAw==,iv:Ifxj3hYJhJgIiE+Jq3ywf/HyrXJjOaOt+tGuLqzzOZM=,tag:BCeopteiaEpXPXErZ5d8Bw==,type:str]
GUID: ENC[AES256_GCM,data:BNSztw==,iv:qdUlCWMpdZaXjQSjqzmw/OalKnppP5a5gHy/xkcVaxI=,tag:23F4BoRr7zJKLVJmKQDcDA==,type:str]
TZ: ENC[AES256_GCM,data:ftwHtpR2QLY7YyxBiya8HugZDQ==,iv:oI2nZcCfSkMLSxhPLq+stMq3B5TdPuydv2hZoHnjfds=,tag:wxL1sgLkpjFcKTA00ROi+w==,type:str]
BASE_PATH: ENC[AES256_GCM,data:AVc+5juxOuRkq9/ylH9XG1VcjSa2,iv:B1XdpOskNGYmXOR7GRok1npDeNYa/+tOm1HVdvOdJys=,tag:FOaFMpAjnYNIgCzuQnXtgg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:N1sj4oG4645BgGnS,iv:WUvqwCUr3vMkotkvKHSh6OeDFQblEt7fMAZnY2Ikzc0=,tag:I/TMQem4mQ0KcxIgIj4pYA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:QavxdAY/jrwnkQ==,iv:rwxnmn7Tj3Cct7CJyaBA8GfcUdLDooCaXLauBjkXpxs=,tag:l0zSUjQ5LjvxtYoA8h0zOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQN2pvQ0V4VUkwczdzeEpz
            SzhXdTFWekFnMTQ1WlhuMEYzMjdIKzhNV240CklPclROT2w5SmV1aHlRYkdOendT
            YnhPY0ZsVk9CRnBtbnlhUU5pbEQ0a3MKLS0tIE5QZmt4Z2F3V3ZsTGI2R1VhMkUw
            NTAzRkxBYUxYMmVkT01pbkJuWlQxcVUK3mZo5a+fwTRrpv++FOMPpn8HOYeROx1g
            fqOUNCVfKJpnopPua1TRB8GrDgs9clw4ViLzjdsECAdqSFCo+laUJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:tufQrvy48AT6/cWXBe3reOTAYei9sGqLF6zTsI6VAOekX1AfP5pYLJJL3978vdhQK8AMuI7TTDVNTKLIhGmKdmV7Y8ZU6bjinOHKOP/1PrDevP1eNzBfj/BtVWsWhHtXrFbljSMnbzqeX5n/Q5d4y2vWCby66NrpHnY2/GuMcmY=,iv:VTc3Csa61otcyWNPcuLlPUwFuY7ZnN8H+YNo72tHq4c=,tag:cwwOkPeubUbnT8DD+VoOyw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
