{
	"raw_uci": "ENC[AES256_GCM,data:6FfQ7E4txdnKd4rJCclVEQ5zoTny4MgBQ2+bxQA5718PpYf3WpYmI5qe4G8Rw2sV+fR8oEDF6P8WTITArk70n9sWFd1B1kHV/NSF91Jrg5o2hTMBdJPfOeg8CbzFHNcnKZC3cgLffXZ4k8K9vMuGmOnbMGBrBD4Qm3J7QCSQvUaHfgqGV+xjzswiXlSofzpGfEKNWd/81EKzxSoNSpA/RE+iriAxWNFgBR7xb9kwjbrawRA+JTZAvO1PoqFkH6nYjGffBBmOg9m1Z5A9BAQGNQ6BbE9MOmgIlGYyGmo=,iv:qdlR0sJ+Or+OjxyJhp80l792JPliNo2Xvua0kYSXUP4=,tag:e99e9MpwzMpZRVUM2Z5xHA==,type:str]",
	"module": "ENC[AES256_GCM,data:ezmGhf7/k0M=,iv:vVntNxTtPP8xGIwr0P7FsLfVnGd9XHH//EdL0HWIIx4=,tag:lY4IJIwfoSzMOr4b5M9Xpw==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYkdVb3EyVGwydEkxaEJK\nMy9hSmJqdG13RTloSkY5VlpYRjJpdXFRSlUwCmJJL0ZnNWp1c2JUVndJWmk1UXVk\nL1NkRHI1Kys0eS90RUh0ODZNYWJkR1EKLS0tIER3ZE4xWnRZZWtxNlIvT2hMWExx\ncktqQ3A2VjZsMXlrSXFwbnJMZHcycHcKBFaJyn8ktcTLh4u9dKBj8mM+7rRlO3UM\n/2/XFlkJx6csZSEpct0YSVWZMnUKh9RAW6hgwZG6maw8XBlVnMyOjg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-09-25T07:13:58Z",
		"mac": "ENC[AES256_GCM,data:CtwKhm7BdVY411Y2oaFvr7aMahHUM3GeYoM4qJM1OlA+ScV4kie4dFEqOySPNmj3gRvz2JvN+b1BxP2GbO8PwtyERdtPOgK05CnmlVju4MXFGmWrPGjlqemhPrp3ZqmLv6DoMlYILntkedwPFEI9/5K5eeYTiw8VayImZmAZch0=,iv:3c+Jf8DFe7hYLPhBLbrA+YWnizTp/ggc4zXnIREKnKY=,tag:B7pXZoONc9YTG814eky+Qw==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}