{
	"raw_uci": "ENC[AES256_GCM,data:0ofISzaWDAidmzzSlx96+ThJ7nEMg5YSN8ZSpdld9EduVcqwkoCA52LNu2mWC+h3AgY32+7nN0K9xm4UMq41hXCyw9GA0bxPHr4+/a/Y8lno9F9q03BbwovRSS3CzbI7T+EuTFgjNb67IDx1IRI/wfoVOeb5S9asEkBAP9btcvcTnYv5iwGxNpTrO0fdL+T7UX/eAMOJtCadak4P3vfpKw/6mUGkqjOueTHls0Wuwnazer10MIeG5xz4UlI1T/hIalbDmUhbTrVZ0QqpQu8iMiZHWMxPlIDa0U+R4yg=,iv:6ofkVwCEUVFVAOd0Kb+V8aPi9PLIsQYoVM3Jd9a3oqY=,tag:iCdAKy7T8a2YqNksvr9DGg==,type:str]",
	"module": "ENC[AES256_GCM,data:FJqiKrO4dho=,iv:2ea2tqUspuKoXQWPrZSElkeJvbEF/0iJHylmOAD0jsY=,tag:aDo73nP8pVoFpfryJxLXpw==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YWJ4MFBwUVBvZGpTZmtR\nR1VrcWFCVlFDL29keVFyU0N2NmIwSFM1Z25VCjlUQUd5WkZ2U3V2Z0JQb2M1Kzk1\ncFkxUnQvbUp3VXBVbjVPV3daL0RoQzQKLS0tIGNXNFJoSGg4NC96UHhxais2b09p\nZUpwN29UQVppR3lwdTkzTlgxclUrUVkKVfDrvYCKSGb2DyNi1vrOwoPtBC1afTNJ\nI+HD2aVHEtSVKlPuWbSvekMUn/BZgxItY4WoLWvCo+yIlEtcPH/KDQ==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-09-25T14:38:04Z",
		"mac": "ENC[AES256_GCM,data:0UctYjNYcXbCsAGfXNUfEhE4eC/aTdsXOkHvgsNv/MMOdntTf6YyDmKVX4efXboq8YhQBRVjQ+POuj0OM1AfpLF8WfSJT8hdpEceyiqOcwA8q3OE+glYDlGsEansDVd/A2pNMS1oUBzOnIoy1SuYuQL/CjbX6q9V9l3yLlKGqkI=,iv:hBen1pCbiLPYCSezmM/a60clw+9297l+9sIRqRPDcEU=,tag:/hvr9FBJfC5Ls2M++2w3ew==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}