{
	"raw_uci": "ENC[AES256_GCM,data:8UVvQEsJGBvmS8ppNexw6sFAsT9mhjqGaNV2gUbc+VtZX814jFQurerRojMhxh8C8uTbdq2t1rnHiSpO1V5Ozd0l0lmrlGIs/BXWhDeOGgTt5bSvFDocDqITMZINyyeOF8PCVeBmtSd4czx6ziFtBVjlkEVb50XyZaX/5P0/8+T+vokwFGbcuB+f4WcFq51fq9aZxjSsuOo0JqPeCOKQoDj7YkupSBONFC/5w97jTWyJAWLjjE4oICsy6xUBZnEiQw4Xp/k5B+EfyijdHUqYn4tF5BgrKMaiNjs5Y2tLY+Rk8jnfilAskTxw4cEc8w1/lc72TqGY83boFip2Myf5GSFDLI8rl4ar3Cr0Wk+GTKC45boMNWbbbvTwZ5g5UlJqsVTwL5qnEz5I5Uldd15evHyF5LOZld24015GB9C6SlC9zq6COBPr+vv7vPhKIpJE6ApRmm125UEun6OQ676LG3/Ps7RaotorlqiBtQJTGbWcOqszDxmSHKWb8L+oVcxth0FoL5n62/M3b3+w4OmtnYMQsLhhwnSz3WOw6Q7udjRsC4ZrY0z3qx8PzaI2RW2DzsurwDoEFUwxj8j9mGokwc0SngvxqjkEuEgPlXQ=,iv:p0YAmcMt5rsg4y0Hs8x9tNt/yjQIR0xsAegEfELwHhs=,tag:dU9DrzCAgyfDbEMTtR0yKg==,type:str]",
	"module": "ENC[AES256_GCM,data:5EYa5VYWtK8=,iv:Xbdce+6BBjjiZ1fizuibFudTjM/u0EG3So6QzKRSP0A=,tag:JGmdKShXcJkmkE+dU149Hg==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZ3U0UjNydE5yaG56ZHRY\nWEIzS3lEbXd1MGFQc0V5QlUwd3VDaVJXVXowCnNZTlU2bXVKYy84ZUI1WjlpSmhm\nb1IyUTVIVXQ3MStmSzQwMExBdnMrSFkKLS0tIFllN1lqQisyNDQ1QWpzMWRnekpM\nS3o1am5vYTJLZ2lrTyszQjdPRytJQzAKMrsO1KwVfjvsQzoh2hZqSLM7d/T+GVdr\nwmWuEa3Cj7mYoEo2oE78M8Fn94zoKUxc58IFDMPy6kHuCNnP6pSfLw==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-09-25T07:13:59Z",
		"mac": "ENC[AES256_GCM,data:MwaPs6oKBvtO42Ue3+/5gg6t95Hq8ZFx+KJCxxIqX8cgw+vUbOfDUN4u0eUfxtL1wNmZ5ZdjBGvHN7GBtQwzX5FLZrtHv1V2EQQiN8rpXj8T+4z/fybjL+C8/7w8OwLl7cIMfVyUVFL3cdH3i3MS+w/OnyzGJ+Aak1bYRx8+s2c=,iv:5sauvbGaoTJQ+lUq8ai81qEOU5J7SyvLfzXKiwp1Sww=,tag:RnfWOUQCc2eI9GtwllR1iA==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}