{
	"raw_uci": "ENC[AES256_GCM,data:EQ4xk1dpQNfaz471oTlbbbegAUe79s6RQSIfp4ZdmxqTnRGFvUsaLmZM/swotAI5BbPve8c9nUjxiiqEqhC/6z27nhDULPbzi6aoeimtcgPnLIp9GN8I4MsyNDHp5rpRh8I+rS0X3SnekSs40uV+vCVvjwDHmDDc4EtLYdON8ZsAshfUad/Ws8VSG4eB9YzECxWvK1jfO/oDMtG8aaWG+aEoPH6IoEqaMWjZxzD77bg6Yx1d3vqrKHeF4NYZEMHrfW/ntA1HzjWq3pebMBwvWmD+0gi/NTelVtiEbBJ0VCFkDMmim9gilJr7A4F/KwjHojyFP6xJspCQDzePrhLLfapYSCTVsh1R+zNW2E0NJTU7WZgpI5sl+SU4YyibxU2VJC6V4IDJng37tQEGV+UpiLfm7u/v5HYgBj4IcQXRTVMW0mqd9oDV6jY7BjZSWFJzu85SvHvYI//8e/POSYp1AFF9vs7NUNLwVF6izUpHCCqoaUK9nbn+q7nhWJhFz6+FIfn4PNaVry8nhWVn3QR9hNtiM7oIFi49121BQsO5ckY5YcpJuLtq2RMpryt0qAgBDITsQdU5/d3MnWMeA5nbJCpmdMMWN1ed+Eg6Ylg=,iv:S5Q+tlLHADGpL2WQz9HGCrcVpPiENUWgX9Qeo8e3O3Q=,tag:fd75fnKk9a6ZAIMz/R0XtA==,type:str]",
	"module": "ENC[AES256_GCM,data:LjPJtyxvzCc=,iv:9dNEty0AGzDivkaR9/Ds8/sNmbtLOpRMDND/GP6VqMs=,tag:fUeA86ysGKGUwdxtInPBYQ==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVnRwQ0pSVGVBeXROeXB2\nbFc4eGpmaHFrcUFDaTJqS2tSM2lUZGo4OFhFClpNaUZKRlJ3WVhwUWU3SDFOUHg4\nMk1VNVJRR2ZoeU9NdGtwZi9jaC93a1EKLS0tIEh0Yno2QWN6Z1dHYWhER0JKcmhz\nZFVGcmFRRVVPZno4dFQzSTJFSUV5eDQKr5VoHBKDd1t0SVj3g668DkApPamGthq3\nmY2TtauIluqtutvL/ey0XH0cvG5Id6fyYcyFu201cI06i4SPE8+A/A==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-09-28T07:48:40Z",
		"mac": "ENC[AES256_GCM,data:6GFy88bfySxclWA6s5YDrsfm5sBIv/Nc2ISG/R4cnvXuYqbfUltr8gVkni5ioS+SkAkW16aQYDQDK1j8R7G5NLDYK8Cpbi7YBKqo7IzcxzBNvOQJYRAJy5tmfd0njpcwQUBFXYekITcDSc6OmtMMo9ONkw5LenkdHGqW+RgNwCk=,iv:fMdEGQ19BWUGgt5FFc5o94SS5YL4a5/amuf9s72S764=,tag:5Iz2qCzjvFU2tqPh/C6iEg==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}