{
	"raw_uci": "ENC[AES256_GCM,data:lFwIpKQeSqVVh/33KM7dwN0q0k0kyA0RamprFbllSbCBaP22pvsEjsr6Dwg4MT6hnegOBowr8KDNrDbPcKPAyUdGqz3GvAiO9RmNkjmzpEtiWw7RsIe6KvEqpZbe0hGxgS2jvTawv7unJU/VuO1d5ZMTaUzGQ8xwDb3Xwr/SzSTsVyQbwj1kwv7zWXQ0qYixXj1huhzshYuhhlPEJQQBu5OAEOeBcznoUSXWi2e5AuX6JTcwccdGDrXX0GdU7eB66DpmuwdFaknGujIyIsvqZ4uPllMWIX7EUjhc3+lEJmRMjYni/QaOa1Wc3gb9RMA61yIkXCyi1ZYvzgP8tRNiSHZOK9HSrORTPL6K/q05nPTPpVVceMoZsHkZ8ue5l0B33C/iL+Sa5nWBZEsup44I7iyg2yBAbTPNvjjuk0z+SSMOhBwA02rGJy19lZnYX6n4APxqAw/2+Zk7HtYxKplxqW6Fr8nCmk/9eeeYpv7P8RIPqHSzMvabivAbE0KVXHsg4IbA2+FpltRh14+vdnMVECq94bAIZ9hRl7By8PUXuFb32cw+rFiLfweulrpM8FZeHnV+KudqXr3ZQZBHDgxQ84nmhLwE4bTllzmMUZs=,iv:KgEjivm/hAV7zGjQePtK4yaTsUNBh5qj3ODJw3HX8ms=,tag:5+BPgQlWs+43nAHHl+3hKg==,type:str]",
	"module": "ENC[AES256_GCM,data:hvPvFpuylHQ=,iv:2+7/K+XQpOzimcM2s+8LBIYNTeGfUBMSLmnJARfDDrA=,tag:rZXRoVDzV69VFpzl7GbsDg==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMjIvcldQZDRYeHZPYkJk\naCtRUzRaOWNWU0RjNHJmbVNQYWNKRzBQb2xrCmpwL1BwZmt2UnpIenRCV1MyVDd2\nSVJETFZIU0pOUmErb0FONXM2RFJSMjAKLS0tIDdOZ1BhT01SZU5DRXhTLzJHTWdJ\nRU90bGVLZi91VG9YNDd6V3F2MmNFK2cKMb5zt6eYq67Tqj4ccPmXK0UlGkTB0ujI\ns/wLXo/0vnoAuKGkZq+JiFLQVyriGCEU68M2VtUummeuUpaCTjymVA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-09-26T08:30:37Z",
		"mac": "ENC[AES256_GCM,data:/YpePq6ZjvgKMdKo+QxxV193Lv00Kb7XVVsO9YdSloob784ZLu0Wg6C5k405Z+FudTgfplZgIAszMLz5hC5KD0mtr0tYTAW5krQ3XbcSeJe2+4/riRdhdJwf2WAzv5Yv0qApZnQ0CHtiYeRxaqIIzuwIjnfHzp0pumJKAqtcsC4=,iv:pFPWd1TSUwpDip5AOH/NpR+5OTke/w0cHn9DbSMne5Y=,tag:eiJPx5tuECsbwCNOWeWXBA==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}