raw_uci: ENC[AES256_GCM,data:tJwXbakXp5S94msdkR/hulve7wnGFs2mFaO6WJN8hJsIWeC2rCc+AgE9meKlYUYimNc3MB763QLHgqhEablMvTdjtgP0Zh4Ur3jWGd5nMW+t4bgXmTuAoIkTfROAXZ7a0tF7tciKOyJaSgX/Oh0zem2CABn1J8vGUuEhRTeniuvkpj6I9Ga5NZqpUhOYQfrGSknyKviSMIHPW9dsDdszQaDl/NJR6ygjzz8q3aBiKZUOtibE0hXCzgPCHngrvyEOO84bW4t2agYeLrpLagSCKMmWBELGs7VfUd9XgScOziAwHCN3+f5jiDuvv8pz9uMmubtkf6vm3kTwreBZsSjam+VsC+6mTnkaEEPkeR0siGk5xRfpXYJYameTxdoSgIN1082qiFH8D/9NIGv6qnVk0y5w4q2gV1W2wpA1c3eEILgFKYqXgf45W16v5Qeqywe15ifigHY7Dm3h96sHI69VC08dMGHeNSz5p0uSSRtj2tl5zwEOVo2IhYOqsHbBBhRywTjxjhPzf1VpiSLWPsUh4z112xUnEZi+w5O1NtqA75qm6XiXV3dUlYlXeFZ9F9Vi+C9h4CY2rofvVn2FjYTQu6HnphQjb+l1NVPAkAD+X0CGbkIe8W4Wqaym0+cv41fUYLrAO9W5U/cowwwD0kQJHKO03Hf8NmWU3Cv7xAS7dFqQLLQk5jYkS4KWRP59pQ25X+LoMZmG34Yhe8VSP8WrtwrvU+4I4LS/icsGgH2XTPWAh2O7BGse7HLG4GoovesI7gN7bds2JXlxW/gWG4mub/JC9vyUGslmLh8DkuhveIifrwRRQn53q66cA36gxwCgnNAcXT82kT4sZJII6VbFQHOUP9Xn0JhVBasRyp2hvrV1DUuOj3FqWp4W6PYHvB28E64qsHErOifLbRcfAEFyVQASd04A5mVTjRP8SFyBLbTCJW9j8Po7uCTksInC3oeOQHHNgxi1Ww5sSbTF/wKu3CJMUhd6ApA8,iv:D/k1ErKr05pQX2ROXwB8j9Apa+QZZ6muyoXvQGomkSQ=,tag:gTAWVLE1RMODfbZ1gGe/rA==,type:str]
module: ENC[AES256_GCM,data:qqNjP1BvO8o=,iv:ZfvCEKfjkQ/qcaiI2x2Ov8+5ZrtErXWp1C/AkZAmkZg=,tag:uHNyAFmvIF33z3iKRCDt4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRUZheDZRNEMzWkJUUUxT
            MGlNaTAydHdmUUdIMFpJVGxRbTlpR1lVU2tnCnBUYjk2VEk5WTU3enJrVFkxdFpY
            LzRra0dXMGRWUEhBUW5OMXJqTjRITmsKLS0tIHNLQUhpeVVTMjA2dEc2NHdIbzZv
            SVVTdlRJcEV1blVJNlpRVG1wWHc4TTAKimiqIt/c8bWU+2xcSt9AEjZlUzbc35pm
            8LiVUBEZ9zz+ITW57k9HToAjrnmYwg+Yj3VjG5GEbuMmP3lXdEtk0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T19:03:03Z"
    mac: ENC[AES256_GCM,data:LMChlMoMBBaemxPLB+r2tdFUm/ZKMQ2NUhi560822u2YFYuqPTbL75UfPa7WMYSROe93vdqkHpwRBT95fsMXZfMZZMmiBAfQgMBLMh0LRxmgHnUNKAMIVZ2EEyDy/rRJhl9SEjGp2oThruTjGVwskPiajrqzgcvzRexQ7c7VQJM=,iv:9qkW2R9MXTW+fEDbDcUVtG47emiH/r58ae9ZODoqh/8=,tag:RtgCem+B3gM6QtOc5zZjPA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
