PUID: ENC[AES256_GCM,data:UwUBcg==,iv:ML65I92QP3DtFSz4sQ1sPHZxtYrGkeiNxIGe/WUwM7Q=,tag:1SZZCMx0QBIMKpZQ5LoTvA==,type:str]
GUID: ENC[AES256_GCM,data:chEnbw==,iv:XgbIC9xw2K7N2+LPIqMX0NAs1HtxqNecB5wSs3onUDQ=,tag:7vYpagiGuMCIipRAjPtetw==,type:str]
TZ: ENC[AES256_GCM,data:5+lCGmwdS31O/mDe04alErigXQ==,iv:Gu2ekaxMuok8Hs0YV6hCRp612jQYzvLNgvig4wNkCZc=,tag:ybHBnpJa/nhAQgzjJ4tZgg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:iazbdctFHCTWLRRHkWXQsOMsD3d8,iv:wBBgyMQdMgeY9CNDObC+TMnpWq9e67bBJzpRcJgQdhc=,tag:zqWEZCjiG0PO+At8pom33g==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:oRiYllz0DxpTpWRB,iv:z4pFVIYN5lfuPHiZCaFvh3km5uG8WbZSQbecZYNQ3kA=,tag:hfdhrF8HiSjJJiUCaUWdRA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:shocPfLuZmpyaA==,iv:ayQj9ossdnrdnhaRlyY3tgRQ6lJz8swusZWiMsiY2/M=,tag:AdcUw5C1F1jWXTQWF+8nTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMGd2aEg3bnQ5MytZalRp
            WWluclVUTUE1SGJoQ28zL2tERmhaM3FJZnc4CkZnbGoxTHNqZnR5Q2lOMmMvdVpy
            STVPOWx2cHhxWERkdkJ0aXRWMklhME0KLS0tIFRUb1I2U1NJNFZrZnZHMk0xZXJ3
            cm1CTkpPWkg4enI0bE1rVHFmVUFpUE0K1nGZmpHamH0QF+OWYHKKq8d3KWEKES5R
            WmgltGAEZ2p3gCquwD71SI5cpQZyppT0FrgsgJfiAjE1Og+DVoF61A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T18:25:26Z"
    mac: ENC[AES256_GCM,data:yp9MtDZb4MYFDsSUUG8l0ORs/FQqc87w3AL9U87DCKtHynxwGWTbXtm5+VdQsIx2CHXWUa4mfNCurq8PyiEp+wAX5Q8u2Dej27lPACVtZUAbpwOh0a1c2yu0Z0IEDw60B/JPFsbA9b7Ui/uzq16BPFxNeOmyg/KDT2B+ltiROWs=,iv:vqz+AzWvGa2Of73rqDQves4dESnFWLun9hoyX5cccZM=,tag:pfKTk3Xe0tfuOypyDCccFA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
