PUID: ENC[AES256_GCM,data:q2UD9g==,iv:NJRkqO6zCUMdc1a0h4MuB/virBLu6krAwJ+dTPYMzx4=,tag:jW+xwdDIe4dAOhNwC0tu2Q==,type:str]
GUID: ENC[AES256_GCM,data:xdthzw==,iv:CX5dWUEg+y37Kw1UrNYRUsSgFajZx6Xqh55temxo6Po=,tag:E6yCPGjjs0D9WQDt/QG73w==,type:str]
TZ: ENC[AES256_GCM,data:9G4jEl9Qgkdil2dFRW1KBZj4+w==,iv:b+xOUyncDx0DiQgcLrwZT7MPuo8KR8O/n1Mv7AF1FhA=,tag:sTME++Fw13xeD2s6P5bmMw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:B7nTy6Jn4iCySPS/kBh79trP1YCy,iv:6K+L3rOZ51wg7IqOsRxX803HTdgD3Xx55E24a2UmGYs=,tag:KoKnfT4w0iDBez71IZ64Rg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:H5hiIWFar3zK+9gQ,iv:3JuM//YfM1G8fiTQLA02zOMW4fuIJB4esBE2EHXZQjM=,tag:JTTuDLnDzcJ4GTkxGcyjlw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:R+vSws57eLZ/Dg==,iv:jCxatFIJBuw6fIs9iIqOWhM93ypxLFRiRbqmmQlP0JQ=,tag:vMPDBkCGAIAfuYhdLyUirw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Z0NZUXBEdXlSZDVKUmpB
            bmF5QzVGaEpyNXpBWUhkNVpRbWI0RUVLUldBCkcxVzdwaU9Ha2ZMczd2dXRKMnJt
            ZjEwNTBzMExYMTIvd1Z5MEpUeGhsSjQKLS0tIE9jNmhJeDR1TWF6Y3RjTDErUHNy
            WUtIend3V21ZSU5GVHFlRlFDZGF4enMK9P+U2DJ3sRw8DlFkYQZTZgNhA4VFHppj
            IUBI+bnP8SEAKM69iyAbLtmdl5pyyUPiTmwiu+y5Cp6J91kbExYMlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:ho6AiC6DYzahthzn7QWO96kBA8sld/PzLNrRxeoK83ONtFqo3xULa75cudkpPCuYghXkCg2lDDt8ScHiGGGqYKZ0KFut0iAIPST1eTe5WV8cEyqbXrq/kbrWa6VNzXTb42elsMHrDiMOGr1a1q8a7RrLJSTGVwUxfRfhoo1452g=,iv:62Kg7KF6Psn+vlC+Lcw8sMWSNfC1i5M5FT2ZLHxYOIM=,tag:2aaYOmPmZKzgaHFcd6e1rA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
