PUID: ENC[AES256_GCM,data:y9BPoA==,iv:k2FRyFgpWJR5OI+LBU01MM1jeJgL+lRstWX2hVfISSs=,tag:0XtjC5PQqjMjbyWHZuJxCQ==,type:str]
GUID: ENC[AES256_GCM,data:xqGWHQ==,iv:QGX3a0/iD1mkDbLCl5vYSOXAubib283UZHSDOcc81Gs=,tag:sUscC1mKiYIqltVRk4sL0w==,type:str]
TZ: ENC[AES256_GCM,data:dbs9D7e6GKD9tK62TesbI4lAJg==,iv:z2WdFf3rWGexIJDEJPJcw857kVXZqxCsA7HRjw1Gbac=,tag:NIlDZT4VTfWs22xEZeSaBg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:dML9qD8JdPzlo8iefapF7jVcPuhK,iv:Ua5tJTeFpJEA4M3fTuxJAlTWau4O4cAsqY+I8BnW8cQ=,tag:GwJFrR4fPrBpPTCRH2PgVw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:Zz6vgSeLrYoNTXTg,iv:AZhgYc4RRrN+vzekdcImTkpzF9s8X+HLTqy21Epq81k=,tag:MDCEVXhnLXKkXTUMQ0BlhQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:zjpOoyTpncKrJQ==,iv:ylYrSuP2sX21pPpJkVbd5MQ+ooi3SSZAzQjt2b2w1ds=,tag:3oZVaXYJqvmZqglC8T0jLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZ1QrK0JYc3hGeTdxNlJO
            OUZpWE9UNFBIdVpocHhZZ1A1Z3JzRjhNZlZJClF6YUlSNFFuSjdtOCtxYWJOaTN1
            OEU3SWFVMjB2T3Y3STE1VnlXbE1RR1kKLS0tIGJzakdGZ3FobG5NNnRhQ0d1TXFi
            U3N5MmxQMGtRRkp0RXA1V3Rack1MZnMKMa4MpOhrNSKTN5FkJXowaZebb/AQgR8j
            3P6eAj+3A9Fej4c3++OJxGnRNmQ0DusWhuqJDejZucX5JF632jD64A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:sCeAu7A+wQOA5PvXvO1hu/01nIJ5vV/EZnBlWWKfweiUZAyjObkcyWw2Z1ydtoLT0h8yExmMS6cYlgV9OqSX4J20/qSREw6Yb/D38ZBmLh8iYdB4v1h8D6ml1ZRGv+TSZGX6+dZHy1yBLrQ7okz/wDzjf1WvHYlIqnSz7IP/unc=,iv:GBymMY/ArM+POLM+q7Jcg9NtZQlSBbh9r4VNMKw8gC8=,tag:oYev6/v6V0g9cG8j34moVA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
