PUID: ENC[AES256_GCM,data:5u38Kw==,iv:NgD196thDw7cu6DgzuavjNyVdvIMnjDpHrRjGJhZZho=,tag:aLo5K4+ZUl5meGvzeBamAA==,type:str]
GUID: ENC[AES256_GCM,data:lMhkFA==,iv:N3DpeFr0BqTpVEb/Y2vd+fr1oydTMqu84XZ1giv2dUI=,tag:2rwW8tpS8xbw5zJN/8FtaQ==,type:str]
TZ: ENC[AES256_GCM,data:JrN39SZzT9kLYptSCdED8ZfskA==,iv:7gs7A84DyosUwzVpHdtqiniMuPmtfs2j2MmsXiPPPsc=,tag:Kml/6v58DgjNaV5vHHzEEA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:Wx5ejINNYYUkpQdk30LrlKL3t46X,iv:2O5F4iZA4PaY0JdCsvpT0iSDsE1qyh5UTByhGLrEg8w=,tag:4hrRibvCaVH9xjBc276hWA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:8bVMAGagaRx/2qVP,iv:2On8g5CMFdGnzc+bVkltmhj8tJO2t1gnbmglUs4Sb/c=,tag:9piggJ5flAGPZ/MHabEtJA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:X/L/qHvo0BO9rw==,iv:P6+n8cnRmOAiz0cb4dRa7T996Z4kBwRUvXnNuaNERNE=,tag:gacwtzSTmcQtLfssUV2kvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMWhFd0xTT3VpcFcxS21P
            UVQ3TnlIVUs5RlIrdDQ5RVFNS1I2NklsYTIwCjRYSnhiL1FFUGJ5UXh1SzZRZkZu
            ZEpocUs4ZEtTUVJUUlEvRkdadFpjT1UKLS0tIFNveGhDOHEyR2hRd3hsa0c1QlpM
            cE9aeFBIOU8ycFVvMVFKMHNVZDFna3cKKyJ2cff+H5ciBH+a4j7Z7N/68zQ4EyZO
            lD+Mnz5TkxwBLuVc49FuPaE0a9//vXIBIPq8Axd9RWnJBXf6k+xtTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:aG8phSuiglxQ0AT3x4LrZjrP1rsIFBtgoxkHwUg6+vMJZDtGWTpfkPtk8Ui/fTlL6Ujgm+zfLo2tVSRHTD4gT1wxk7iP1x+/wKz7ddaY16MU/y1N4HdQ/fWqL4+VFg8uflA0NfMVbPpBt7FXcj9r6QSJ7tdkOfPkeQYo7SSASJM=,iv:2vj7VOJqlxivH5Y7NpT+ENaiCbrsHzAybrJr21vEPmM=,tag:kLSOApIqoJ6vQS3mvIcysw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
