PUID: ENC[AES256_GCM,data:Gy9wDQ==,iv:qOcLpraECOyFdAu44bv1Kz2FKQET5KAanghumODG7Ic=,tag:DVRriPlw68rHvn/pvt3Ruw==,type:str]
GUID: ENC[AES256_GCM,data:lknX6g==,iv:GbUOAixn/kxweYbHAZRg7j8o9x1QvcJPPkj9I64gRMM=,tag:xYjiyd1urTD0l0P4bEnf0Q==,type:str]
TZ: ENC[AES256_GCM,data:x5CIFPoylQQMAGqHtaB3VMLFOQ==,iv:I2adH3nmY0sJYl7Gu6PsvMWlgUB1zODANpH8NV4b4sc=,tag:elIhZe1sBFlRbOJ/lUpNIA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:27LLknRvUEaNQMN6MFFGbSmpX/MW,iv:2wEMY8MaNbZXw9/nrjfcOitLD584M1oePsm7DbEVOVg=,tag:4Qyd1xbuDgr7gHMaPVWjcw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:dmQo/7zEgM1lzB8f,iv:Jfsa16oTf2bR9hFKCwshqgfBiECUKvXHbiK9tOjfGUM=,tag:6cpQuxRykNs26DmDYJt5EQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:snZsKJRpdSGwtA==,iv:bj6rVBkfawHt7svf/s2vTEB7x4/RbSXBtTxdbvGgRPE=,tag:Sqr/K+koWEeiVfYxHu6wbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTHZWWGlzeDhTd1BJRDdM
            a3RmTlYyeE9xMHFFS1dyTWgwRzM1NHFhK1I4Ck9vMTRPZ29PWGNXWVJQM3RCWERk
            MGNzWnBXOUFnbEtzdFc5TTgreUN5VVkKLS0tIFVJQ093eWJuYVhrNzVnc20xL3Vp
            SGFJVFc3TmMvZnVnWjBTeWFHcG5WVzQKZjsT+p+ZZBzVo0YlgQvexxDG/LlTulw3
            h8u+Zxn71QA1DuLaeahSwce20TWt/8nLFMIknzAaqwof41vslYXN0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:P/B4+PA/xkSdENBC47I0Jc1+1qyPafrq0jaI6sVQRNLDkvWl0iTo9bcalkntA0PQJMWsxVStSVc6TBgMoOplScYYjRZw/3DTASTKEm/oWnkw4qMTRDzPQNcB4p5RkqGo5Dck/dmzLQ26rePyEgTIzjuYs5UiQwm7vg3H5fW++50=,iv:mNl17TH3ZbIenj68E12JnJOmv9MU1yTpiX6BINdls8E=,tag:RaTnybwfV74br0kCfCy9/w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
