PUID: ENC[AES256_GCM,data:TkG8YQ==,iv:wssE67DyzR1KFO83rhJk53l/l3YPMUl0xYBjdURbBp4=,tag:oiFaCLPYS9wSavumsu1c0w==,type:str]
GUID: ENC[AES256_GCM,data:jCc8dA==,iv:42ojmitEQnMEUZdMV9wC0tVUP/jRpOlZcY3LcRgo/BY=,tag:/aUP/ebaEajA9q0Zu4gDJQ==,type:str]
TZ: ENC[AES256_GCM,data:RyTKgqwTe9259Yr+JBZc6BVCng==,iv:oJtOAbbWdbI9iLmrYdOXIv15eXETu7OklUd4RBnrdgA=,tag:wuw5lo83dTFRhd9Ts6yttw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:tmbaG0mcoaQOsXVFCTH3wOa7P5et,iv:JX0F10fOa3zlOPcTtgKKKtLWX1ps1gqeNbhSGoVFmP0=,tag:Reoundbi6M7EnMqLTBqHZQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:d65IikyTadKXo/Kb,iv:Q3mu7k74WXEtziIAch4x6sytQbYCFymRl7tQQc+Mmwo=,tag:niZ0Mnm5UyT6keN3d1uvig==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:1SKCiGJ/465JMw==,iv:KaUKRiDd+FQOIwEUO+kRxNb91NH6VK27oMN2TJjx3Pg=,tag:4dMOncTinu2f99Dxe5nzTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMzlpazBzMm5wYVF5M21F
            MmFOS3lkSHVvUStMRi9BcEd1Z2hzYy9yWWw4CkJqWVU3Y1V1M0NMUEhsQWZMNGhB
            eldDSjgxZElKbjZ2NEVuOWNmTHpvT0EKLS0tIFVRbUpsMWpTTGRLNGR5WThPZVR4
            ckZOZEVzQm1tWjVWSm5aQUY4QVdMZDQKP85/hGEB+cpYuuZLVR6c0Mk2h/A5vcqO
            5Cw7jBydEZKXA2V5Vd91apC2UoOybdnKr/cm4DKsDKY2bgvYq7RMww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:17Z"
    mac: ENC[AES256_GCM,data:8AZ8oyEv2Wg3e8nDIqFWVRCtnFoVhJMvEYjUN0lvfOFohdLFiYhpjAvprSGf15O1jrnisOZppz3nriAX6qnC+rMoo4Bs0/cEn+AkIIDr/2nwcUmVg6/6c89ZzEYP/cJdUdpfVT3TO6Cc7HHVyBcdKmcTLLZQWNIHZ6ZRaf3XaZo=,iv:IHbgErHdSU4Pa78A9m6q9gAS/3pyDSEhoK0qsujHvk8=,tag:UsDUSZVa8MHI2GLpKYwI+w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
