PUID: ENC[AES256_GCM,data:2sAG/A==,iv:S2JUp5hMA26JyDyuv+AlSePqp2mic2TIWu2q7x92GeM=,tag:48/c7pFIdxTmg8YY9Uu4qg==,type:str]
GUID: ENC[AES256_GCM,data:JL+8jw==,iv:Rfp9vGFGroxDB2ugVIionLXpMPegAFmZs52HKkCxNUI=,tag:xQzHG8AMjy1Yq3PTWFaNwQ==,type:str]
TZ: ENC[AES256_GCM,data:M85ZsUMHpZmTDdG1GHpDOiNxvw==,iv:E9kOwLgJQUjaUsD0sDz83N1nSbXC7/C6RHM+yWrbKG4=,tag:d/yRJ1E3zIc1QuJlEyn5Vw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:AgtoxyNTKEHlpPUE7emW9QlpEXmD,iv:WWMLqDOvVu5WOrQsh/iNIYquKKxE9g5ewUuF0J+PqFQ=,tag:xSkVuUCxZ+rQ8uyeq6Lw8g==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:TA/qv5wBW4GiKT0C,iv:YbT2ak1NaLXFTzRk3f9LkWf7FBOeWt65F6gi/B8KC/U=,tag:zpTaybbcTezfRT1gHFYkgg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:emgK2otXPiiPvg==,iv:35ERH46h0nZkhxM3BJH0lTyrqIgM1nvsssGndxmS6lU=,tag:qZYB5pR+TB8tg/JUc1eKYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdWd1RVFNY2FUeG1EZkM5
            Mi9sZlMwRVhxdHZZT2F0WE1OWEc5bU95bEZFCjZqN3MzUHVGN1NDZGRwSERKTHpr
            Q3dkYjdaK0dlYmlHK0RXREVRRHBiN0UKLS0tIE12UlRjaEJkSnovb0QxZFdOVHVx
            dy8zMUg2YzdpbkZ1SjAwU0hwMG1qUkEKyHnoW/h6wLMMYsqcl1EE09VqN4S9SGR5
            K7VZWUgClppTkJX9BbUu1Ia4o1DnirNReuUYtBt9VLIVT3wll7rv4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:O5MCyHkZhUukEsh8YqhPxqSYzWJ6z3sSS/8s0FzckHHn8TxHfdR6oPxhLm84cNk8la5gTwe3GID8kE7j04rbp8cgc4CU4HQv3U1yIm8joQw+CigybkGwicArTdVvY/xmTbuBG7ArgUpSmTvRZbibaHO0znOP2cAGM6U78mehkNE=,iv:SwiM+zTwIMdnHjblfJod+DirOu/rMTCzVXhmKGwmRR8=,tag:TjdeAI02u9bGTUSDR/OhAA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
