PUID: ENC[AES256_GCM,data:7UMKlw==,iv:DNu1nfFVzTl10I4BkzIeajv+GdSFIg+ad7QXLz8ByOs=,tag:1aQWoZP39FkPjNh1SgzBnA==,type:str]
GUID: ENC[AES256_GCM,data:MhdNuQ==,iv:6HsvpEwyrUhxMGyARWXQNi+a92PhorlOZApLC7mqyGY=,tag:/BynL4uyem2JRNYkhThh3g==,type:str]
TZ: ENC[AES256_GCM,data:dqJfoseBbihRE0LS34NdNEU/pQ==,iv:aGbn0NPicffSueiMu/dP1lQHj2wAl8bbd+rYTrIZWG8=,tag:aX8Mhs3FOOykRcf5JweCYA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:6x3PWJcRmFgxwWUIBhWZ9cK2BE8h,iv:8ZtQKCGTph+SiRgD9Gy47re/8XvERYJZrVcWUWZhH64=,tag:ic5ObmsGelG9MqFvqIdC2A==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:j3ZB8NOovviIGJnw,iv:yxMADDrv2LyNoiDMCYl1t6uIdvRj6XEoayJxDEYlsP4=,tag:gb+M/6sd+XPFqPfW+WHrtA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:Itt79bIcq7q02Q==,iv:GrIJmIAnTZ+nwrIVHlEuRXR9IZYIR4gXQA1sRr4qyl8=,tag:JoyjrhxFl9lS+M79bqZ20w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RCtnY3lvUzNnemwvVkhx
            Ti9CRStKTTZXY1VnaGpFb3pMaUtTeEtCalNrCmVDUjJEL2ZEdmYyMkNuTFpmQTJp
            ZVNRK1hkNDZGQ1U3SERtQWk0SThhYXcKLS0tIDk3NWFUclBCOUc1VTFmSXZJNkdl
            U01XcTIycTNUbWFQc0s1OEF3ZEtYS1UKA4A0TfzXBY+TaKS+z3k9+AjsC2edAf8Q
            24q6A5+RSM9VdNhcNQQeuVjDNQqaKDlqs0ASElUW5cmL0ZVJd4wD8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:nzCZz0r7C3ohaVUsVpYZxre3s1mVpKp4X6p7SbLRYn2+vUc+gP/Os74BQCjJxso4iTVAm3iJTijpgX6X8LTG09ILBHLDZGfFCUBd+OaPSg9II9CarR+E6PgJeLQGi0Ov453W3kWwnw4Ddd5FdyiFRwUbNTgdQIiIxcFwjlaUsGA=,iv:M9JuTMHDjm30irvyZIlXinu/u+FlEzqzfqaO/z3R/C4=,tag:RwquK4UR2Q22h1bO+IjZTQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
