PUID: ENC[AES256_GCM,data:3JCWXg==,iv:TlAcpaOmTysOb+6+68kB7RS4SIjLetfQLg3YBwbDiMY=,tag:bWfCKYZ0kHqNSF7fWHovVA==,type:str]
GUID: ENC[AES256_GCM,data:hDZWpw==,iv:MoLKgID+H7sW3SPXLDYImYEAb/OtJcH2YedGW6r2hGI=,tag:6R6TV1+ST8leSaMnw9IyOA==,type:str]
TZ: ENC[AES256_GCM,data:YzSAuYJVlEExWQa/Mc35N1EZjQ==,iv:NLfOL0LoM1KB7ohyVUZN+HWHpS6xHVuLKmRdOBepUgM=,tag:bqhJ8XeXA2sjIsjU94sDyA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:Q3i/g3SiAO+A8hmymaHjnJvbvDZq,iv:UHgfub67+Id+b7pK/yypmOSvvSgil/anKwanVWBTO/g=,tag:zeXHY3TvL5wrzeaUyI3Brw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:e7jJ8A+KpA7Sib0V,iv:4vgfxMWjk6yyDLSteO+R2yUEDpLvAwHN4flPGz1w0EQ=,tag:tonLCnHLTFGx1yQFqBkvqw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:aQdChAsDU17lcg==,iv:v5gHYrEBrPA2tJ0jHdofo39Tub15NZN6/+IJbW3pj10=,tag:qvRqFXMlppcqr6NwL4OT3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQzNaK0RvajNieDZXWVEy
            WUhZc2M2MFVqZ1hORUNONWF1eENjYnpXNnlzCk9jWGRXNlVXQnZnTTBuNXdhaU5Z
            aTVxcWtGZUZHcFlyRFAxOG9XekZKbmcKLS0tIFo0ZWxxYmd4cjdxYnhQR2FBQ3Y4
            WEFXWjRXeDg0bGZ4QmNiRWFIYjhuN2MKlW2wdHBCn3nCwGtV3m7wtMlJlNMJqdZR
            RB1i/NpFqJWwjw1NMQBZX87yL5rLC7bRpVQw8ARFrWZ+2CAYmdXrXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:RxKEWN/yjSBbMWEU0I3UPaCeotlSJ/D7qiDKhuo8QEJPTmhXuix6rpNuHDHqSFjs6ObI4PwjbSbH0qYoZJ4cYQd5kzuuNTvyMqwQhoeFSxGQHutl6Zw/bjlJPUjgyjDrzlGsM77UDvqRqpPx46gsEexYVLCZWF96p1BC8ymldy4=,iv:JCEayOMwaih5eM9BOVwzWtrcthtAr1qK4niOOwC74RA=,tag:H872otarWwS0MKD4YEmrHw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
