PUID: ENC[AES256_GCM,data:AHaXSA==,iv:PaWB9nYG854CfcFlRQSo9kqBP+q3wzJMHx4ehND7YpY=,tag:ol2a4FCTx+Y7wTs8iqy2OQ==,type:str]
GUID: ENC[AES256_GCM,data:Vr2yFA==,iv:Saz6ihpZWqc9FePGDfaClvekbOulLKEEszAeU5/O6fc=,tag:20VTEdTJi0FWw1Yt2rzdyA==,type:str]
TZ: ENC[AES256_GCM,data:AWx0vysfVnEgNjFvyzvbtN2ghw==,iv:+0f4vt7zq0Ftwz6++MtBBYUE9PVC264VWvDfMZeU/WY=,tag:xc6sPaEF0+HfYsfR4d0iOw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:zM7eQIe8Jgwt+TEzKJq+YaUISkWq,iv:qYPrL75ASfQpGIPprfg444NOgL5/uwHnf96M/iyuzow=,tag:FZNHYKTX4hFs/RIkvsOSVQ==,type:str]
PASS_HASH: ENC[AES256_GCM,data:3rVkJuuGSAN0+D6moy6Oswjc7DKXyr4MYfAQ8+6w2Ck+D71/fgJHPCE8sUBNwrZHa7mYkJLoRCoNz+JX66Ll,iv:50iKwVLD9Ew+qEkDLof3kncOXWvcNeOlGK5KaKIxHms=,tag:dHNA5ZAwa31z8t+gHLahTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VGMrK2NMemR1Z0I0WXc1
            dWIxSkpaa0xsbm11SytyZ2M0bkNheUwwNUdrCnorNGlNejhYemVFUndhc1VqdlJr
            UzNIVDh5ZHZiN1Q0WXFOVmtINnUwRHcKLS0tIHlGN2xVNDJaVEhXYWxsWXM4d3pp
            aWUvaDBCVHBHUmxyTzlHZ1ZxOEpTT1EKuxwNFOjSaJgG//IKjR7RfOcv0tTHKQjC
            am/+x3Aue6yaNUfytNvKCVQ+JhLKznfr2uXYtnM5/9gw+jeqanhrcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:3fo0XLE0+QSDqKX153wKcduiEUvpzTLhZHZj9AuF+p/LIqkHqlZJnq3edrSu8YSSlQ1Z9TgPjuIu3MMxt568jUNQfR7YJmSnoj0A+AkGWGqfOETrd4YmmWGApDzkbq494Jwaoup4DBJph+nsjGL5ndCKKAfAHjkNDftmYZV+OWo=,iv:uS/O2GyyBlyZ68IIkNYw7DBpjpOtVE8OnZYrAoabOYI=,tag:esuwz4KktrcFDRWLoivkew==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
