PUID: ENC[AES256_GCM,data:bcNapQ==,iv:0TXyUFuDYsPFHuSDIOqkkyOz569Mfqe+Ce5gsUiQnWY=,tag:5Q/F160UZwghPFVjjBjAMA==,type:str]
GUID: ENC[AES256_GCM,data:Xi24kg==,iv:0lj3aMgBtdoeSs2cnOyh+j7R0i/kzjgG8/5WBavb+Aw=,tag:OMd4lMmKFjualYpzsPcLlQ==,type:str]
TZ: ENC[AES256_GCM,data:BFo6uNepV3r0g/ZmPJRAua4xSQ==,iv:56MXjM8WCODf0PKLraAXmQK48cuaBFmwgtg8G6q5jXw=,tag:lFYQUpumtfounocVZzPnNg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:AXc47i5GtLGKLE5otM0+4MorrTFx,iv:OHa+SyZ30ZfZxP8R2ldBnjCc/DMjmG8nbPoqXQbelco=,tag:DLXneQJmwnVm9SSqvBTFwA==,type:str]
PASS_HASH: ENC[AES256_GCM,data:hZE+t5K5xT4fd26zE9cKjBhOabsH3BhJDg7L0NsgS2qqarDJqh7u6WERXcxoy1x96mtzuWZvoWix3674gIn1,iv:OVd4XXfScS6mbnT5bFizMQVcoBMxO9mT23sH7GJov+s=,tag:EyuCIVkpBqpavTXj9DNFgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUVJGNzBwUlpyVHdpOXVT
            RDBLM2RsbXdreU9jdllMVmc1V0ZyRVBRYVYwCjE1ODhacVZkTlFzNlZsdFBEaE1W
            bU9iRVF4dkNnNnFoWGJnN0xNcStwK2MKLS0tIGxONlh3RXZuZDduUEtneDB1UGYv
            ZnorbTFBK0JiWGs3LzRJMldlYm5EY1EKfIGQxvSXUaCa/JC7+3K08tz6gH3Yeehk
            Q3g1OqSE3/9xxJdMVtP/7j5KPgQz8/YpD2AugpUIu1Hq7JjB0sz1iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:Pdw68hpN/TQlCV2DKtrZCPN0yABgx/iPtIqN2++xVOIPGwhcT7TAI2ECleYAR7db3AWf5PRoe6w9ejiFQRBdzJWKGtFEDHxQVM5fc4SPHxJGhhPXeq7ySYGw9cYdiifPYYqow9fqAg+j9dD/sz3RsDuAKOjO4SlNAJBFF1+4SSg=,iv:J+VWd41szWsaGvX98xk3kQT4Qs3f5sx1gpzg7a49QR8=,tag:8kPSfys/5egMZGR8hLLk1g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
