Tunnel_Token: ENC[AES256_GCM,data:V+OlOUMxVwfTzw4gEicb6kuN2mrF65LrzkTt6BzfZAfDAdAlSzRyBjVE5lV7vnymdl7UJDlGMjeaTx8Xw3PlozgZnfWSnFrSMJsTcD18D7+BJXNEt9paiopsLNcyC3jA0ftBtB5VFEdUiuN0kUpKv/dwNzUAcEg20qYnyjSOV7Z77C1LqD/n6wda8xQovgzYHXqMey4u4qJ3YllE8kZ+8TyJ7I57x86AKIIo8/TdBtaO0x/yW4IrJw==,iv:PnnW1SYQfZU2GId6EtU8Ed62B/hY2JTtZkTY+QZToaE=,tag:SCb7UpIQICd2DeTc9XJe/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTVdBQTRSeklxaEFOTVJI
            dEFtUDVOU0grRTN3anVaaTR2ZktIaGhiWlR3CkVKeWZiYURvOFZWMGlINmhqZ3dT
            QjB4UGx5VERCNFZpNEFIQ0NnOU1EaHcKLS0tIG92UzJqQjdUNXpYY2hYVFIwSjdk
            V3V1WWxOblBsR3BGN0lmRHJYQjZEeFUKWpJpLcLywWOCTGdOhgCa8/6L0e86h1Su
            FLI9xrxNBfyPCyYSir0Bu18IeoHVUQVViL6c8ivKsokr1UCrfMyd6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:08Z"
    mac: ENC[AES256_GCM,data:vuLpvpCT28xuHKRP0M5mwgwo+fmeP2JQXq9NmcewbevXp1ZC3woNnx3uLW80a8xS4Dq6hv1bKcfDQxrZaIi6Do33P8gpo5neQbP8Lts7U4sWOoHdmJtp/3EYQBVj9rwD4pq803Nfhe8D68SLZQsvhAJR6s2QsOS8RgVdfBvLszg=,iv:a7iG5+jUr3VrLAmVsRavZ7IcoqQm0RQmrEI7+Fy/gYw=,tag:gFpyrnKFQPkcOT9t9ITRAw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
