Tunnel_Token: ENC[AES256_GCM,data:VFjEKWnT192XkMiCVxgbLqs0/ggnwUy+1xKwNqTJproHnxPNH2lCNUBCkcBe5vm3RJjV2FYSJUXFzNvPBUseaTTfwI/xDu5CLTsr0J8Os20Ma8um7J/cGCyC2ipwnKyHqE7z5cMaRPYo0y7GJDQglvfuV4qkKoorEDgSI5n/Wd+SCFqACDo9/Z1kfADdUTNBqGqEWsdyvItg129VO6MfDeRtqphS9CNye6WxY2bEKz062QRtVFXi1Q==,iv:jEU3dWvA2fk/+5gW5xumLfQ4HnwKhfW4HWqR7UmRxhg=,tag:Yrv0CZoDLZc5PaPm7Vthdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NFoxK0UxSjA5aXdTOEJ4
            dkYxcTNPRzNlaHFjMGxYdUJ6dG9tNjdqOUM0CjFRaTZxRXJ4SlpiYzA5QnVmZDRr
            ODFYQU9pL0UzSVRxQnlySHZESHZrUjAKLS0tIDh1dkNEamJ5WXBrdWd1MEhqWjVJ
            Q1JUNHhjWW81VHQzVDJwTVdDNmxIMlkKaN8QPJmQlcZKWvG7M8mrk77Fd4x4+3cB
            pMpBkYbMXsOvlDz7Yqltz0Iu9Yfi/JCNse9fnuxWSwEACWZeIpcWPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:SjXKhmMZNJD5iPBVxJMnOwmhiKc2n6Xsl6Otedj47iGAj2TarFR+DIF+L0UXH4y3sQ+JOhG6SXSroB3FmNdP7pseTlbRqv9KslRCHDF1ddNT8jQVzpSLC5jGkaeo/GsE0mc24KoChY8+OcgFqHCklFJfltcJeHW37IYiLvjJ/qE=,iv:P0JbP2Dvu7b+NY539ZiLmJFBLHXw+FnzbVgG2wShsT0=,tag:59mwsaV83ghtDVBKh9dEvg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
