Tunnel_Token: ENC[AES256_GCM,data:XH6ySgCU9biuhvbXF7nHj9nCIMxaciLlrwzWnNiDZdctIeQBWaxnA9oTq6JI0vWMFUF3t1CJbSp4paES3wVVBo11rPXfwVPQTY1TMYjxLD3QPHEpiRf64o5pU1wVa7svChdlocAaf7WB72kkaC1KX/GyQ7GP4FGCMpHYuD0Wa4qm5mvjSL+SPMyelcEbtszFI3R2RSpEj9fxvjPmrMEmeIzRdjrWMRD/XMXIuQexI2IYOHJG7EV82g==,iv:zsjJAbYMOOZjj7r1m9QzmKVy8Dixz+ayWKHC7wgJMoo=,tag:H801aq8ijaHHH9eeMiKMHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Sy92eUVHRy80K0laUUQ2
            WlNpTHVoSWIxZk9WTEx2TDUrSEhXY0xNSlUwCndEVDFMSU0yeTNTQ3d4UWo0MUQ5
            QXpJYVRqY0crQXNLVkF3dFdpNzZhMU0KLS0tIFdmUGRMdTg5R2lkeGlSR28wSE9I
            T2RJTUdlNHliRGtUUDhuUTBSQklGcE0KjRpfsQFyiHzc4eEGczH1u77MGlMAO8t3
            5mDbpsHhEYhiE2BVv58rZXDaIvuelL6yyBV1RPS6ucLmWhijpT3Y+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:06Z"
    mac: ENC[AES256_GCM,data:N5jdJYALw8UkZp5fm6qWh2l1cP+uXnhynpdQ6iyCxABedpKo1cF2MG/iwDcyVxkQy3GIiUn9c/CVDaRI4gFXZmoIL/mYceePLfsCbyluYCFqHlKj/xbAchkcPrC+rhs1qjjX0nWLrrdo/E+HBvIcSpHk41Pz+EEbO7jvl2Zy9uA=,iv:C0DIvlz2p0RHoVVea5L9dPbuS+tZmWXCfKWq99Ya1aY=,tag:8vRCdFGNiJt8PbJbN/N8CA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
