PUID: ENC[AES256_GCM,data:ZIGjOg==,iv:0Wd2z/G2oiMPAB4lsaEOMWcjYXaGlnpOio9Wm6nDurM=,tag:MNlb+0TefDeVzx6CGAV1Xg==,type:str]
GUID: ENC[AES256_GCM,data:vK1ybA==,iv:VGkpyNdRUEvNycpNIw3wEtpdHcDW92Oz9B0Zl33Zp5g=,tag:Rxl6xoJB1MQjJu/w58L8HA==,type:str]
TZ: ENC[AES256_GCM,data:1dDrnLo2bUr1RXeRwlTmMJl0yw==,iv:eAJouWU4BNE73M0IQaGyq0RjwMkoqwL9FMBSpFH8mIs=,tag:BSxkBx0/tvC9kjodhJxCZA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:cH3o7ILwthMb3oVESD88RJ+Y0W3b,iv:91QwriAZ8t6GAO3FA2mT0XjnEZ/x3IkX8E4Xihzz9Tc=,tag:0xjpH4o4jVGRZRcbAjyNqQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:wx754Dtt6nZRKaEe,iv:/0Pyo2hVc1X9tTg0RLSbx/BqPWz8+L5mQc7P5csFh04=,tag:7ruWRNmQFFE77t8AIKOzqA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:c3EM59WWToJzmw==,iv:2QB+dMKPR082EAYcigbrVeklerxiUfrtIcYlyq1J1D8=,tag:w4ivaAllDpIZPp9FA/xDeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQW16TklYVkd4SU9pV29y
            YXpBK092WkFqc2NQTkZ4ZHp1dVhIbVllNUFBCi9qUGw1eDYyY3FqVG0rSFhETWNo
            UU5IRUZRc3hHK2gwZVVlcFFuZmh4bUEKLS0tIE11T1lVZ3lzaTBuU09tR2JVbDhn
            WVFCakhieGc1VW5rRldWaXRPR1R0Q2sKu+ycvayjJwXTzPfROhs9+tjlZkK4y0q2
            b4WhTCZea/xJ0B9UPGNChPhYZR7enxHNFgpAz1iWF466pSd279DeMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:U/XUmvqAVGQKVB43MoIM2cy876sWs2Mfp7Nq49D0TPoJYscEX/Q6Irdoz/Z2bN7yElGq57Z4zOpIrZrVc5hHJF/E4Wpuupra1BBote9IFZq+ihZ4MW4mJSQqxyUa2traF4cHoAZ3Sc2a/N8i0El3dHQPRxxsgOmOgeSTPWctBFo=,iv:TQY8pyBRUPjL8CVh7zh2fQkrbd2rtqaBwsZbjzQQI1I=,tag:si+N+jfYYSzWKB9sMMHBRg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
