PUID: ENC[AES256_GCM,data:etO7kg==,iv:QhHJVaNy92Zuse6yv7/Gel7OzKImw+hmKUAHIbC0jgA=,tag:P+i5b06lQhaLw0s0DflomQ==,type:str]
GUID: ENC[AES256_GCM,data:qpjCYg==,iv:AJx6Gohk1J4e+Bn/558jTI3atPd8kodBQFUA8pwvK08=,tag:Gu5RjfDu24iNHLuydBZHFw==,type:str]
TZ: ENC[AES256_GCM,data:pJZPjQmyZb9IUM9AsKzt0XCvDw==,iv:SKnV1q9tO6hO4v4XTUqrARV8ytfLEDK9wmurhmcZ/SE=,tag:IH8pKIy7en33pvQCbQfA9g==,type:str]
BASE_PATH: ENC[AES256_GCM,data:Sm7Fgsbbb9aVgi9NpmhkvqoZCXw9,iv:LlGDOfJI3vpjCblHHe/eKxVqEAm9KjsRq096L956FEA=,tag:vReSvrRadatx7fhVSCDCEA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:DKBNkgmWhTK/5R+E,iv:hzdonMa8/qUHZQDTfqs3Sl13MCpXxa4vsTApxaHtm98=,tag:YK4dlKn/WRL9Ra471witLQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:OOw9cTkFsAloeA==,iv:xgkIHPR7KOoc55PqYwb0wAPvDZN4MIyVqHQNr7finwg=,tag:rjeDi/qCMchB7MX+HhRHGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UHI5QmdHUlNhQjlNUjlW
            cUhscmt3ZWNlSm1CMXl0dFdBNm1VUmcwYW1BCm44dTVwejJlNkV4MDVGVThLNlFZ
            dGU5Y21GaGQ4R01vQkwxbHRLRElzTjgKLS0tIFJUTEZ5bmtRNk9qNDJjTzd2c0U1
            OTIyUDFrYlBoLzFXVkYxUnYzNUlqQUUKZka71MClTYT18raexHUuBLnR7H9lWPKX
            nThI3xxlsrqnjkXykXmkTpa7w9sRWfTVPFa/NgDEwYLsaUxiFO0uZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:cxjgNyj86iOiMxvrJuh3OixRvsQT2RiOlWBsjjkqsUwLjEHCCKPpWQeolQRWRQlQ3pO03FWABOpwYkA2nn+2V32rLhdmejbevrkK0HtjBk1+Tm9VZxd2+VRqM2XOKAekoTn/WfMqhfY8eiMF9sogAXB7Eqqxo1bWXAxrTqwggO0=,iv:FfDtinNS61Q+Z57eb8xLgzedB7wCO5+rM88leTRAPMw=,tag:vJdH/45pdrUfU7uhZ6j3LQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
