PUID: ENC[AES256_GCM,data:veAQBw==,iv:Ah5BWQPHcOc0Olqq7f7LkjBn9eilGJU6/cvkYLs0W6w=,tag:UGAnWXI66MHA2XYdb9ADYw==,type:str]
GUID: ENC[AES256_GCM,data:pAYqEQ==,iv:DIAgds06z1MLrf7Npkko/D8hP+O4ViwdVhTcEoEh4lM=,tag:3FCjS7TxqBf5mAHG890YVg==,type:str]
TZ: ENC[AES256_GCM,data:McNY7gfRhueUT+vC6vGRPDg8SQ==,iv:mDbdR542UcKEuB6uqQxpyZHxzzAn32tqKGZBlrEpYVQ=,tag:ztRhTxm0nnBIndtXG7fkLg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:7JnFdqOAiGUQNCTs2kBCoyAUBA/y,iv:V6UBE7K+0/0G3HKX10C8Z7FDfuHiEzrIyAu5SHqSDJI=,tag:2AEDzMAgVN+OTgLI+aBCww==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:NiVTIvjjkd6/5cdA,iv:MUKuETcjsDCSjUUykc7v40G0d5/Znu2mhkHa1eMxZ3s=,tag:Mw4i5+CaTmhoT6W8zQOTxA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:Va5H0O+B8EfpxQ==,iv:ATiIaIr3U+j/oUPxRXbXx7f8mP4r9YxnHZIyZSAhG2o=,tag:3/DkjjABbKjqwuaVif8BWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cVJqSVlCSFFNb2FMWTVN
            eDYxZ2xOUkJoR1FCNUptQk1pZGc1OHRoMVNJCitpczd1SUZ4YWpTNzBoK1czUzBZ
            eTRHQWlCWEhtNUZzS1BjeENQV2t0TnMKLS0tIG5SMEVtWlV3L0ptQW10SHdpQXd5
            V3FNUnlMWUJhdEkxbStNY1ZSVkE2K2cKiThMA31qdjtQbdCr4mGaWIsfht+BgmH/
            Qqrj/GkRDK10fvCJhJGPhd2G3FLaYlnwAFBGLD75XOAgSZo3qIml5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:lkcrgjB1jM9BuFklF2cAyuzFvJxrZak1wrWGzPZTi9Endy0o1Ry4nb9+M50G6f6/NvNT7kxRqPYbxu4hzugs6BxrW21FZfoYqrh1+nf2y6q+Bfyuwcaj6dZJGnzGgMkLlHC+2pooyvPWjr+7MDVMm2E2f1z8HCARavdlcqwH4ag=,iv:KGXYRlvWHm2RTcGfqAdeUF/lW1UuCIFZlcFR/orBfHA=,tag:47Po4gz4N04y01URWR0cJw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
