netgear_password: ENC[AES256_GCM,data:+plBYym0XNBWiw==,iv:veSMF+HaRjhp5wmeQ3qlt+H/DGnaqTwAKsNDdu0oCDQ=,tag:6oyDstc+wlYmHiP7lxwTpQ==,type:str]
netgear_switch_ip: ENC[AES256_GCM,data:Xjh7zN9I7mIrqP+UxQ==,iv:CNOtT0n4NIif4LGCMqeLM3HWeCBikOmNWsrRLy5HTvA=,tag:JqCZnADk1whEcX47gVCnfQ==,type:str]
password: ENC[AES256_GCM,data:o1ZemMrxoZo04Q==,iv:FSOBhvaOcZX4UMzUCi4Sj1QOZfxeuqgWkzItK28VMX8=,tag:tT6i8Dd/B1HqcYRrULFcRw==,type:str]
switch_ip: ENC[AES256_GCM,data:d1HzCnTK8HZoZpV5bw==,iv:/ZbZboWiElalGhFaz0429WsDSmEW1VYJ0cVNBblg8NM=,tag:YC+fpRGydcz3HNad6B3RNA==,type:str]
username: ENC[AES256_GCM,data:1z9Bk6lh8a0=,iv:gRBHpDBr55Jwt5g95nmpcNKLBA4FyYm1PCcvhoisH0k=,tag:hsU/TdIU/OYxNIFP9mU3mQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcGQ0d2lEVXlhK004Y0xi
            ckpqTWpCa0plWUJaS3FZTkwvZlFFVmkzUWprClBrS3FOU3BtUmRVMVp2aTc2UG1R
            bmk3UGhlNHBONGpOMjliZ05YSHFaSWsKLS0tIEh1WlpCR2lDYXNXQVdWaDVlNVdN
            MGd0aytOYUM1NmdBL0ZHajhKR25UWFEKl7Uy3FvX9f+cfMQys9P9Pos2DW9sgs1V
            MSGvsnHzaVFpHXEK4ZHk1ICP+emkEDot2/ZYewI8Z5vCWe7hLxjE5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-22T15:35:36Z"
    mac: ENC[AES256_GCM,data:Fc7O6uSqP80RrGNHKAP+2BwR7jQYfjRWPoLArUoP/rKigyr0VMpRItJdqcPOBxfyKKAfhbKB6FfB8EH123NlwPALdyJbmv7wxow0x8uFHdsq/Xam8xQAGfHwQZHolhzhPsEvxgZ1JoOvJtkP3CABirdLTqsJLrewFLme8/N5guM=,iv:sjP3TbPQhcjwLxWX0Ri+5JLorBEV7dt18JBcl+NVIXs=,tag:64JuePIsVXPEuWqqlovGtQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
