switch_ip: ENC[AES256_GCM,data:g6r6G7QFbtJfW1UZFQ==,iv:RIYVa95pNXSbNIfEcLsjkhFvJ1CpCBomgtQ4DNGvzoU=,tag:OcBRNbk0Fz3BhHf6/J25fg==,type:str]
username: ENC[AES256_GCM,data:KnKauCNIrT4=,iv:dVjAqJc9SmOEmKo4cK/GsYSDmhRfxkmnLYQxGJpI6dk=,tag:uiPiZdQeh+13a61OmMiZog==,type:str]
password: ENC[AES256_GCM,data:EK1f5/ZBMKR66A==,iv:fqpmLTuebFA5Te07QDKyl6Vin5zGI1jWA83+Z3OXhBM=,tag:ciqcE3JS0Gpf3lxqWQ6PxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaklCTHBqSEtNOGhZZGNV
            K2VDOFVmTUt4WmZUSlJmWDFXbDRlRm1VMURrClhPbGVKemdXbUsxa3Y2WU9JSUYw
            QWUwZDlSRWswS2JYS3ZXRTMrLytUV3cKLS0tIC9WRXlveTlHQ0J5S1ZEejM0TEI4
            UFduaFpBVzQyaTN1enduTkJ4TEVma2MKdnlpUlaKVBCPvgz87J0orDqi4ZTW2HDe
            Kh3wr/s5rkw3q+DLOwRrLt/epYMbtDJMRPipA+eXxprZnLKMm/dCig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-21T19:22:56Z"
    mac: ENC[AES256_GCM,data:Oqhi9UNZDuIgdhiSZNsZLQ7RpL8t/n9AyItaGrehPOar1RnNJ/vfxRC6Wai4XH6ZddtSDoS3v+ENlniUSjXGJMrAeoStAhqlvR0FCsWbYbTSo4S2YTt1VbHQjIoNeWO36ZmBN+GcnODL0P/YeEBEnKgiqn7MCzu0nb9vG/VJ0XM=,iv:/WjciF1sj+R/UDaAlX864nPxfgr3RHePhbz712q80wU=,tag:mC5f3fguut4NQIWYjQuKEA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
