username: ENC[AES256_GCM,data:nSND6Xhg+/6JYDjYx1jCdMvn6cWgiQnsJCcjzDE4LDDxUQ==,iv:n56AzEHhW2qs0r56s9TQRVUPI3vnZvnaqRXVp8ZhB8k=,tag:x0x6+LNsY5vfnC898hMobw==,type:str]
password: ENC[AES256_GCM,data:UY5BbG3eh4qwf4hsSDsQ,iv:iMZrwCQA9oocqoUagL5d/c//mLFX5i5lbFU/gG7cJJ8=,tag:9soYpSFsYOlz1tKn9d6YCA==,type:str]
api_key: ""
token: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSDRwMVBxSjc5MDA1NjZN
            d0NSVGQ2VzMvK1IvMmpqR0k4Q2VaSXlWSFFzCkloZmRHSHV5TWIxSzVnRXNzTEVM
            UUQ4NXRxSVRDcm9VZUtZallMcUpucmcKLS0tIFIxTUVoMG8wUEpXTGFPSFpXOHdU
            aDByNnllRHpwaElhUng1V1J5RnkvR0UKZr2YmEbGjpvd4cIh+3k4kLkAAlc4LUwI
            i9VB1OI+WfKF1xfLX++YLVtwdQ3ZV7wbgG5zRnCqdSMa25LK8nr+hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-05T20:57:11Z"
    mac: ENC[AES256_GCM,data:b7iwjKg3y7ihCsYZ2EVxoMFEaaIXsBk7ROjcR4JN9kgTpyCtnRl8y2z7xmAT4eLlF9CH0WwL/3g5B7xGzpqKqui4wqqyOXpLa+jDUGxEJ4aZCU2IMpsDA6fM7DUrEuqu4DG1Y8JVHtGwbc9SdLHamPkULwZUFCBvF3BrlSYwwMo=,iv:5A+Eg/YKafPN4P9sW8m4EG0fko4CZE4/qcanxlFwZ1U=,tag:iObsRrvTAHRd8ROusaZang==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
