snmp_community: ENC[AES256_GCM,data:o0dbgfdpfmY3zCi96rDH,iv:i51fMxyZn2omFMTSCXW7mq3+vQNg1kiv5mB1wk7jvLs=,tag:dFX/QsiZMGHt2YiPqwFv8Q==,type:str]
snmp_version: ENC[AES256_GCM,data:JRg=,iv:jVwkLLImcaWobxViyRGlgoEvE5HVzGSSazQbcFCD3Mc=,tag:UCTRXwUgVOLFr/r3eHoocw==,type:str]
targets:
    araknis_router: ENC[AES256_GCM,data:Cysr5e4tKyGFT34=,iv:AsbEY1rc0rjS84yd4/NvXoJ3Y+K3IfVkdsY23a2c2as=,tag:qcvBK7rE5e6uSk73haPgCQ==,type:str]
    araknis_switch: ENC[AES256_GCM,data:hZMN4EBdWEFVudAxwg==,iv:oIPsDnkT8Kt2D0ZuZL/yv4xaEuqVrcQlejEZl7QV0es=,tag:0yl4+sbHfVX+krZECWl4Jw==,type:str]
    araknis_ap1: ENC[AES256_GCM,data:5mkP6IuyQgblmClYzg==,iv:u94c6BiJBy0xx8jpa9XlH5TIPpti7Y75lx4BUQw3VV8=,tag:GoqOY6Yw7Ar/25wei001KA==,type:str]
    araknis_ap2: ENC[AES256_GCM,data:g7v+whBbXk79XBw4mw==,iv:r3QL1qBHm7YfZn7jGEyOj6GZWdJchdD1jUJOTgQtDDc=,tag:oMZSsMA8sdwMGHS39x/wxg==,type:str]
    araknis_ap3: ENC[AES256_GCM,data:6y5mybLAN3+e2h9EFg==,iv:5giyV9SzriFUv7tOOSwo1tHc2sW79/PMZ5LpM6oo/hI=,tag:dnzk+YQmJnO4D18UJqZgMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZGhBM1N4T2tKS1YvQlRH
            c3NyakpCaU1pakxlQlBSd1h5TTBLbDJDZ1g0Clh6dGV5UnJoN0NLL09hcnJ5VFA4
            MDlkNGlzaXBOU3g3Y09lZEpmeDdLemsKLS0tIHUvTnJ3RDV3VE9DMDcraFdNdTJv
            aEl2YnROckszYUxVR2ljUkkrSm9TbFEKaqeNcc1skTWEU4IzdjmUB5hf7QdiRa/g
            fZyGd97lqkeWfh1LKBTq4gjfhdGVYVcXOZOVDAccgAXGkbMk3E3QaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T04:31:00Z"
    mac: ENC[AES256_GCM,data:cPktTQ58M1q6EmM1X//1iC8+z160F5EV4u73fJwXn7nxiAzrwz+XCq97yQcFZMKcE5gcnqpCiZL01+HEFWZXZ6gvVwHFE+/woGJk+q4I+Jw3FIf5Osn4SzJRGaNsXwcjE2yEqBQ4ePUaJsmL+YDOy7W+v+D7cn7cjhr/kqUwiyI=,iv:jRgIKvuxxDSjGwixX5ImjJRZtyuVofGdYo/OQLtB/6M=,tag:+Y+7ZupGViny4aZmT74etg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
