PUID: ENC[AES256_GCM,data:vgOW/A==,iv:csBxHpivpVYgniBOwGgK5cVrOpAF064ejBqBq3cFOsM=,tag:81vck1Pr8Fq39Vzzyq8s/g==,type:str]
GUID: ENC[AES256_GCM,data:Wrsz0A==,iv:toBF+gUZuMagkHirAq1Ftb6Q09/2B8nykhGZbe9a1/8=,tag:SOFBS35rsloAmH7296YbBw==,type:str]
TZ: ENC[AES256_GCM,data:5+UTWX2i+lMDsfNDBBAt/CAJcw==,iv:Okf2NZuV1gA9xtCSIfg84PY5IozKDKcHKjMmpznfNLY=,tag:LdpxXUlAbWJIj9P6UShymQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:CFhZYD9MWewhDMHHHIhRpUP1Hzrl,iv:DcX4GunmPtzSomL38ixKCoweW4mKC/v7xXPihjDyLAc=,tag:hdbFG0rzINAW8xOMmE4HGg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:Djz5RHTBd80wPhMR,iv:2LySnR0g0WlfBVhFs1bth6vXRTGaIsODO4DBItD3LTk=,tag:IrcnJ4spm0C7rVK/ygLdnA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:yaGGp8otg4U8Eg==,iv:OGHlY65eL0uOEyUeswJ8I1Xnq3tZY0Io/7Lhu7QBp1g=,tag:PRCt0md1hlp87alG97Bzzw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNUFsaDZYcktmeU1zV2g2
            NDhGQTBPbWJ4Z3lwd2xkcDMvaWtiTno3bDNzClhEMzhMVk1halQxM29JcDIrUnpa
            c2RIZ0ZuT2ovYjVlMUNreTJNdDFRblEKLS0tIENNYzhVL1BmcnhCaG84VXhxeWRR
            NDdCVDZmMjc1RDFsR3lmQmh0dUNQKzgKUu7IcrNECWHNWJvkzm26yGM/EfpV5Ju/
            d70INYIIWCmsjpVqTX0TffRr7p3pK7PTyLlNdbEq/y7VvfI/IQeO+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:17Z"
    mac: ENC[AES256_GCM,data:F+z4sD8IzZMojlHfSujdrosZhoR9otimQdK5INw4GUBkDgNmW/RqhV1lhkZx6ACdZ56trH/51uZ2QPfGnUGhsTvmv13/212lsx/vBAKWv8g/dHL1esrDkZichgHPjSKGIQ7gHwsluIsEJszoumiBgEqggogoabPG3/IpxqikApw=,iv:K4v8W1c6/5NcYvg31LHQA9cLWsE61nhZYGM7fuaIZ6s=,tag:u7PwcxdI9oDNMV/e7AmTrQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
