PUID: ENC[AES256_GCM,data:GOfY1A==,iv:AZnf+NW1/hGlHQzq+wUTp554QFZ3Wb2GtEYNchreh1Q=,tag:6WEeGWszrXU2llyjurO4ig==,type:str]
GUID: ENC[AES256_GCM,data:IzY9Nw==,iv:447NEnR8QqUDcDEip+OwIa28+uyJMpeZHuO/EK2FJM8=,tag:M3kcAVQ2IvCE7+zF3dpmDw==,type:str]
TZ: ENC[AES256_GCM,data:pTYUUZW0B8nW8XOmXmwFJ7Xm8A==,iv:wD9Ay19LTdU+JfxJZVMmzmwF0mUWL4SljxeGHoezrbQ=,tag:1eyFjPX+G9xMdVQiZUxPMg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:3wPrEuqANI/PXIwx5qPhglGb5/w4,iv:r9cltlEd6U4lXJuCzOPe8lTFd7J9ZKlFIoV1grA0NqA=,tag:ojZiBW1mSh33T7NL8Q5LjQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:EUD7jqKPz1HKWzt+,iv:MFHjvR184KiJYl4XAa94cyxFpXXFUOu+MzuI1Gqydt4=,tag:7oGuybaTsXWWRdvULsk5+Q==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:iyo/2DnChXrA/w==,iv:UvgH0yWKEIdWiIdFaVpwxU3M/y6rZw0CHblPldk+3oQ=,tag:Lva2vqoarfYn7nqA+00rgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuY2FmMTloU3JsSHFEZS9X
            blV2d1ViZndUTVpiMVcxOHczaGl0dmErb21ZClF4NUI4UkFlRzBsNk1MWEpiN1o1
            M2VRS2RuMnJ5M3pFNkNZOTJ5NU4vUUkKLS0tIEg4QVJTRXN2QnVOSm1yeXozeVky
            SkFleFpXRU9ZWTIvdUdwUk1DZ2sxbFUKnVuTrrYDtERUN+8KgRle5+wQRBMnSMHe
            RfuQleQZuqKXiJoC8FH04BQR3mXSBXMAX0jwoNvNPnTk/46R7sTYmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T18:25:26Z"
    mac: ENC[AES256_GCM,data:6pI+wgWbBlQzbehBTWwoKNWSqkbPeqRoeyRKTuWFV5MzWlZCxeZCutzLET3xYypy/GQuxkSGVrGqExQb2jonAU35flKviyC4xMxioywCHqlwDvUdeqRrb1APL08VLgsyVfkBYQ/DYe914VqU9QUVaLjJHE/uO05QHde7/Je2rII=,iv:4QJYTKio6fHrfjkRbPYub3g0b54acnGnpF4tZM8Ub0w=,tag:U3BYGTiGa6rNKsVRbUntHg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
