PUID: ENC[AES256_GCM,data:sYk9rQ==,iv:jVrCbo9elm9XwS/XAahvhx+CRiCM15JX928CfHWz1+w=,tag:DNApuW4ik/OrRk06+j6DFw==,type:str]
GUID: ENC[AES256_GCM,data:Bz7slQ==,iv:Nknqidjji6rC6Kuhq2jNNovNXjd05TEHLx9RA1ie8oQ=,tag:rrgowfr6a1fO1vuS+zx3iQ==,type:str]
TZ: ENC[AES256_GCM,data:DHdPnoeI0suFlUzoV/N/x0qDZw==,iv:FffGOog38BS8xTasZN9L8JW/NZ2Xe/5IepEEk8LJ4Lg=,tag:KASKFlr/qiW2D6BedOd8cA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:jd/NOpiW53kCyzYV5HL5fl1wdH4K,iv:/kbxpnxJZEeNKc+JNcQNLw7ymktrM1KCn4K17yPKNyM=,tag:0ErqCBrf/bG/UXO8xUCWOw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:CWI0dQkJE4TDOW6v,iv:u7TuGULnHqpnmO33b3JYlZNcH3biEXJbATdP7XJTYn8=,tag:H/2TJpKUwu4XNkYWwW0+nQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:H8yXXKTHjb+EDw==,iv:Igv8RMoApCFu81Ix6OF2KNRH7QcZkgjY0o/JLTZd6uo=,tag:shu2MbP4S2mC1qSViEYUTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aUYrTVpvT01xVEo3bmxo
            R3ZKUklaRmUrT3BncUZzZHQvZ0dDQzdTQlZVCmY5WkYrTjhnWGlOcE9QQUI2UXRw
            VDBqRWxCb0lLejFmR3VISVFEN0tnYVUKLS0tIFl5VE03K0pEekJaYTJwZkRIL2ZW
            c0pQelZFL3dQUitrUkp6QkZ2dmZJRG8KOdDvyKRaRiuDkIhyoHA9r3fI/8XeCrcZ
            1Xp0YPqqlyqqPe1fmZRaffV0UL7ToKWh66gvm411lTlbQ/c1ZJrmOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:UBWXGDteLXGYt3eQbY8VA/h34BwGz7T34ocbwADCUDVhvpjFqHZLE6cmVPrHhBbHGM00p5LaBw7fw0jMyQiYPMgu0rnwkAMhL7OdZaitQbahXLzbylj58cSpWnILoleKCu6HFO6Lx8lK5bXWpYvf/QNrcbFdy/Ic48neUoqbXMI=,iv:GP7omHyXrYVtOnI1IVPKLc9NpBmAjbKpyjfPoxKEUy4=,tag:dT44FMdR9BDKOOpTmsdEQw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
