Tunnel_Token: ENC[AES256_GCM,data:JWWaOM9H8t7afGhtEfdMctETgmDB9o6WVbkTJi4rBaiAoqeJPnQS0N8ATLXfcg8uHb4yGtNUSe1Li1On4eBCauwQtkeqN3zSsm8elXfyRYjxu5l6xpO5Lci22k5XrPbX2zZg8vTPgwTkILcVjWtT3bXAl79aJqgxiXjfEs/kQ7nG3axZziywbhYLMQLwt5a1T/Q+NzLlyrdda8ptH/ZgMpyTREMtuXjqT7vpuZvRw6Bv1S0EAW8TDg==,iv:FZdxTBTMZDLPBR+5OucYcVEmTytRr3y/aKooQFpocUc=,tag:M7G2X9s+PyrMY5/YiMtrwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTenl1aEZkczN0YjhpVVBB
            WVBSTTMySFRhTUw5WGo4czlqNHl5NmQxYVhRCm9DT2xCMis5SmpXWWlUcEl6bmRr
            VEdRMnF6MWJVaWswUDZaVVlweFJPY3cKLS0tIGd3MnVDYkxxeXIydExmU2FYT0NG
            WC9LOTRCcEQyMWtYdmxaT0p2a1lJMEEKNChbO/bOZGT0yh2O/5HmY/FpemC1M9M+
            HMi3WM0OX4R8gmxnhzNhn83InWMSyEq3Pqd6eWLESpGvGfs0CI5Y1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:17Z"
    mac: ENC[AES256_GCM,data:pN3bvS4Z216aSPFZFpfHgSjEjGjJwEfmB6XDraPdHDZjS/vFBX6+i5AYbEnTWsFZz1v3GKe9Ypb5qpWgvO23DjkliwBtlPoCS1cZ2XvQMI7tSr76nSR84LH4CfBL0tOlv5ZeV6Qh9w4roks68Ios8bHCGKFkSagET61tEpkrf54=,iv:omjV9zyVz0BXtXKzBIcqb9L0dP1+5yTgnyXPs+J14Vc=,tag:hwBch5HWluOpVobDwYPNbg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
