Tunnel_Token: ENC[AES256_GCM,data:967BzrbmkVxWqu7/oLZNa3fVhkmjNE26PYfW2N4J/OpU2VoLOkop1g6h6/qUKHYQUMLerzfEbMV5H+FJYu64Lf69UE5bzgNo6k5QiBgt7ntStPup/xeongO0k4hYBf6E00VJIkP7njqWedb0mCcfZNKtZgFiRVZ4FwXR3fcNzU/j56BFpCLG5dGsNk+TXN+NXrH8Di26NmBuc7ixG/FZn5mhWGIXBNi5m3VSBcK7zWpbpBNY/Mqm4g==,iv:KS1GeVVmQyqgeRT26NV0Q0PcGe/ZgXqpZJENjSRmSjI=,tag:rHdbfgZuoMTtBI46DFbxpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOE1SZ3JUWjBaVkI0dkFi
            V1ZXWUswUDdibzJzdW1kWGtIclA2TXFuTldrCnUveUkyOE5KT0lra1MydUVOUkE1
            RUNIRW80dVQwUk0weStmNU03NytzNzAKLS0tIGtZdm1tSVpYTUxOK0FoR21PMUlz
            SjNnM2RweUdYNVArSnZSRU41eldHWFUKwfBUG727Qnk3b/9PdXddYmELyk/AGjJT
            wLqZ/iNuXM28ZMYnf/TxijYCb3RcjEDQUpDjTxKO0YKOf/y6UzveVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:+pGB3b7F/d9WCy7OT66AmFCJjpYOi6SVS5QF5no7sDUHUvIKjzBoM1u3rDsMRKQCuVIZFttW37OAyDrYfxnv0KRhSZ7iIOaV+OTOhQ+19kGypnJT3T1hoZQpEj3ZSTxq+G91lc2ryAKynu7bqUTtcIOnuPRWHm9Ki0/KJkYQsAA=,iv:YXQd4o4LxtdAt4Sqjns1rSaxQ9wCWRfPJZt6hv8PvLY=,tag:fG96coflchr+OBJcqRlUFg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
