Tunnel_Token: ENC[AES256_GCM,data:Xckb1pcd7z+sUTNtD8DnrfFjzyUeLWqAGuv4AFLBMpecFL1uEx2nF8xGXRiqVQZ3HluuPusQppe6VpfHdp4BhcTVScdOzZceABHlwty93W2Wm+Cm35RpwfEUjwqCe1zYCcIYp4usAnj6AbWtyAn2ceSZ9XNc/7g0c9JEibhuz2Dwb8KHHAS5ITYgMJzR17YkFhc3eXcu2NfNRi55MMIxXYOevAwj+fn30kQW2UWe0rWGtB4nPLhAyQ==,iv:Gn6eaz9P26TItpc4jfJCJm1Gg3NkyGYN8O4QPJrSIHs=,tag:xPokT9JLuQ2FNAfUvjYpXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzV0FQT0IzUytNZ3lnMnNT
            MGVMaytuRzV1NHh0RDRlUUhjNnAxdkV0THhjCmFrQ2lTZVhnQWNJRnpzdWFRLzlK
            Y2RIK2Y5elF6ZUt4WEZ2QXJtZURndE0KLS0tIHQ2bzNxdGhHVXZVU0ZZWVJZMnZ4
            b3gzK2lPb291TGRRV2VVK1ErcGFDVDQKXdRMH9kFt+sY6lRBXVMF5qxPkzQNIAi2
            i98oo2XIz1UGR6vkUY59lKtDQfnwHLkvIGlhsF1yjQFp8QfyRXZwcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T18:25:26Z"
    mac: ENC[AES256_GCM,data:aXVU2m+0StVdiVpT6pfWTblELRhEO94DXsRrrWvBwFsK36zExAObBElpRfMJYAXTv+rotuTnhLIcmJV3SN91iuQeT1HLPGj+CLXfLuVCi+gYcwL0Yo6CeD4w3KSVGZ7Ox9ZxfWgexg+iss0VE1/jMcoEJ2WWXP19eHyoOw4IULg=,iv:0V2KsZzkzDMZz3nbQnmmOM5CbrkSa45jaN813p+Hfao=,tag:FoTeuBEvkvwS1B/s57lr3Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
