services:
  vpn-proxy:
    image: ghcr.io/meek2100/gp-proxy:main
    container_name: gp-proxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      #- DNS_SERVERS=192.168.1.185,192.168.1.186
      #- VPN_MODE=standard
      #- PROXY_MODE=socks5,socks4,socks4a,http,https,ss
      - VPN_MODE=proxy
      - PROXY_MODE=socks5
      - VPN_PORTAL=lehvpn.snapone.com
      - SPLIT_TUNNEL=true
      - ALLOWED_SUBNETS=192.168.1.0/24,192.168.10.0/24,192.168.20.0/24,192.168.30.0/24,192.168.40.0/24,10.25.25.0/24,10.20.20.0/24,100.64.0.0/10,100.100.100.100/32,100.115.92.0/23
      - LOCAL_SUBNETS=192.168.1.0/24,192.168.10.0/24,192.168.20.0/24,192.168.30.0/24,192.168.40.0/24,10.25.25.0/24,10.20.20.0/24,100.64.0.0/10,100.100.100.100/32,100.115.92.0/23
      - LOCAL_DOMAINS=secure.theurer.dev
      - VPN_DOMAINS=wirepathsystems.local,snapav.com,control4.com,nxc.local,resideo.com,adiglobal.com,adi-dist.net,ds.resideo.com,control4.dev,workbench.control4.dev
      - LOG_LEVEL=debug
      - LOCAL_DNS=192.168.40.185,192.168.40.186
    networks:
      gp_network:
        ipv4_address: 192.168.40.155
        mac_address: 02:F5:58:97:8E:88
    restart: unless-stopped

networks:
  gp_network:
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      config:
        - subnet: 192.168.40.0/24
          gateway: 192.168.40.1


############### Development & Testing Info ###############
      ### Example values for testing ###
      #- VPN_PORTAL=uwmadison.vpn.wisc.edu
      #- PROXY_MODE=socks5
    #tmpfs:
    #  - /tmp:size=64M,mode=1777
    #ports:
      #- 8001:8001
      #- 1080:1080
    #volumes:
      #- ${NFS_MOUNT_POINT}/globalprotect-vpn/entrypoint.sh:/entrypoint2.sh:rw
      #- ${NFS_MOUNT_POINT}/globalprotect-vpn/html/:/var/www/html2/:rw