PUID: ENC[AES256_GCM,data:tSODTQ==,iv:l+OhuTmCLfMjeZzR5Bq4RiCxAMZXcJ9e612uGm24yTs=,tag:tsXzU8O6CU/jzcKaoz3PPQ==,type:str]
GUID: ENC[AES256_GCM,data:q5KlOg==,iv:Vnf4SEFdN8jM/vm/xZfCfMcGJzVGDCsAPj3h65HxoGE=,tag:9lY7L5IoCSgXNGmGqQnsuA==,type:str]
TZ: ENC[AES256_GCM,data:SqRJD12KkthAHZ9v67jM8Z62YA==,iv:Oi0TLTh5YDXc/73qpHDhJ4SNtFei3E7PLL1fZLhDqwY=,tag:yEkumxBV/IhJhrMCPD5+lQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:y/sCwLe95wmeWUIzsMXHTOfNKr+L,iv:RBFqMWs+SnD6gtt6gLXEpWFLv7+65nKK+r2+UPZzTqs=,tag:zPPVouFNG7GHOZmimTvVLg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:wHqoOGY6PVWZEvMB,iv:0Go4CZXie+VltSqif6kT0FICMQMl7tfMJzP86FCPseA=,tag:F0RVeC+DQkQa8htK8Ib6Qg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:pQglB53gKeN5lg==,iv:7ahG0kCrXgbWB6YuDTImYDiyKPs+fCVClysjdnvXfuU=,tag:mqsODGQh4XvqzM4HVIQELQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQWFQTHZKWXdWaWhMb0c4
            cTJrMWVwOUh5S1JSeWNYWGpjYVRYN2ttRkRrCjA4cEMvVTB6cnZIU2c2a1hkR3dL
            dUdQSEdHck00cytXS01HSWpiTjdBNXMKLS0tIE1GaUhZSFZRMDR2dGZIbU1RS0FE
            ZGVBaTZwL0d1aU50ZEEwcjdXK1VrazAKXr3nwsAYNZXvKUvMMlTdGC2E3FR+6RbE
            3WSmEi0G89ElDkemn+o8b1jCeTBTlefUViBWdaO/LY4ANWF1ZXqnvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:pIvDuFaBqV1i1uHmsMqKY96MmEsoUnxlJqdSvQ3kZmnfVbBXhduE3/IYy7SONjiMLRnpJktQLCq74nuKxRjn8PsqcS6qgODq2KRgn3u5Y5/mLdiF5r6BvJgqYcVt99iK5PT9KW/pmlp/H/YoHmG9Wp0lBVbx5ZbUoOfCvOrrF5M=,iv:J+7okOZt5uIVbatymzOU0+/vppaigEy5pjsGKmI4S+g=,tag:OiRblNUfumVqOFmFHDInlQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
