PUID: ENC[AES256_GCM,data:fKWZiw==,iv:nD3f1wTX7kBtR6MHAgKVoHT+ouX3/RrAGLMflh+2p0A=,tag:+pdm/s5KoVa9Dz2Ll664pw==,type:str]
GUID: ENC[AES256_GCM,data:MbZNgQ==,iv:eLsOK0rMr4zzDMX6HYDaMv4zDJg2+6eWRKXfrjlA9M0=,tag:bYH27i98PEUmie7ZcQ/5DQ==,type:str]
TZ: ENC[AES256_GCM,data:MiCm1NvRkQGk8mXo8rH84kWx9A==,iv:OelJ1qb872YCjz5ITRIjizqOqIii55GAXcicrDAB1oM=,tag:rVlKcohNuc3ACUVosTmk1w==,type:str]
BASE_PATH: ENC[AES256_GCM,data:jfdgmNghfe5SVrQYcYUunuZdBDU/,iv:66TLYtbOXFnIG13Bb0vhVKuC80VWBYq2vAmhE0773Zk=,tag:9l0M5LSz/Ayu62Ua5/lddQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:PlIaM7PMFxmXlVYw,iv:Y2lZVnGETUjE8EDyHEiic1XoQb0nVl4Ay3OwRbSNGCE=,tag:dwtw1P5Y1AYKIWwYbnmNIA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:MfjO/SRPmSDWGA==,iv:sfHSyYB9FnW81vBtnecXD4HjRwuunhYxMB0V2CDh1mk=,tag:BZJjiCal1R1fMm2B5JJhnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDL211WHJhSGxoK0J5VlN4
            QUFXenRXTk9jYjJzZFhMV3hXZ0dYQU9JdkV3CmNDb1pZOWcyanhOcEFUR0tiQWZr
            dzJtOHJCREJaV0RRZ2l5bTMzcjNlWkUKLS0tIEpIdHp4M0Q1MEhSK1ZLdlZjR3Fq
            M1R0MENFWm5JRU5CZWFLWG91UzZlMWsKQTovlS+eFzGd0nOC79hCy5POHjSEJIsx
            QFXiXIUUn13SsLsGehfpfzrxM9wFpTIrlUaqCCILY2wBn878CCz2sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:BKFGXqGjLL65tUV5hkWeNW/61fQequNQmpcVyFplCzXHW8aLaHpdvIESo3vCssgOMumb8BS6woozLE0f+BWMaVpclh14BHiWfrV1NmTAPegvQPF1ir2Yi28H9r+XX7iJygTCN9ASTKW5D9HK6X4pvY/dXHW8Tjb7xPY6rGyJ/S0=,iv:t4VD6kOlgqy3MfDN1pDUhhR/d2+ugyHPaCvQOduxJP0=,tag:L3HBh852+ggXR2+ZFbNyaQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
