PUID: ENC[AES256_GCM,data:uvcMJA==,iv:gG3I805/KCVQ3vEPW2ucmd8Cale+MFslcqYHDuExUcs=,tag:XTQyD03x1s4U1HURSpnw7w==,type:str]
GUID: ENC[AES256_GCM,data:ClTZUw==,iv:+TByc7NDJwWgVr79l9vc0KSt1JoCkjX4xe7IztReN/Y=,tag:J0IYSwjZ5SZWYS2Hofy+Gg==,type:str]
TZ: ENC[AES256_GCM,data:+E7vqUoBb3rU5EYeVdCsSN+dNg==,iv:uuXhpShCDklL5PJc9qXwTX6eDDvI3X6e9eHYYXAF7J4=,tag:bjOPrfu+nj8aKT4tRtzjow==,type:str]
BASE_PATH: ENC[AES256_GCM,data:vlAowiB7zhVimpO/mbJECM/w1rD8,iv:pEnuQXHuMYqgQKruIoPjKzNf+DquLR1Wxcys9tEOzxU=,tag:1ezs6Tpd6eqLUaM7lN59yw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:2BrDyPoJVcKJb2++,iv:ILOs7ZwjJQpiLGJNTCsCEn03mX5cMU+rJXAud0EEQpY=,tag:vAMoyEnPbYYHHWvaebNpeg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:X3fOWNeHEfAJSg==,iv:Jms6X0u/inyqv4Bg7VikjKPBmJASP/YIgKWNDTYK2h4=,tag:1gp+mE1qHubVsfTHWqeBXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPN0s3b0RyYW5hNEorRXAz
            VWxHWE93SU5GRlNKbk13RjIxSkJkY0VXUFVRCkphV2d1NjRaRHk0dFdNOHNHdFVQ
            bTM4WHRmZ0V4RDJ6Y0dldll1MnI0dTAKLS0tIDVGcW9NbHliaUhQWkJKZ3FSQ3dL
            VjIrN0IrNFo0cmkyaDlxZklIRFgzZGMKyP7sRaHawjX4SRufNjk/qBB1CsTmJQgc
            YEpnUvjK7+0AX9MFbdrQztMCUdgpqRqOCGjhWcKa0KS60FAuFlEBVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:rt4K3iB1I/iSEz1zo+P+KfVdnm+wgVjP1XBdEEbyTgOGhuN+GdOBCylabRtZrtdqVETy16DgGWHwnQS7ptqcfZ7Rx7s2zeloeEkvQimRUMQmiksV52rlCU8pUGPKobJyN8xLsCIKIuyyzhYCVgSmD5dQn73QLDlogyT/JaD5ZZo=,iv:Mw/kftdUkEnbCywZni+u/3wxH5qf/Xsesxx1j4+m5TY=,tag:Ktd+YRt1nie2mb8RekIW8A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
