PUID: ENC[AES256_GCM,data:wd5jbA==,iv:Q9PyJAPAwGClTxI9yblXwi/SxeQ7PhKGXFlO7FkVbO0=,tag:sRUQaqF7cgQNZ4ePWhd4IA==,type:str]
GUID: ENC[AES256_GCM,data:IAf1kQ==,iv:gdRryCTpTWqS9PgxHUBkZMzkFjTH1vCbTfUL+GbBSE8=,tag:NzOf7W5YA/80ev6Wv14usA==,type:str]
TZ: ENC[AES256_GCM,data:mDM9F5rpe1ewNpoFv1qNf5NSXA==,iv:uwVEibTADOq5l3Carzx45AodW+BRJn6S/fP/XmPd92w=,tag:zPi7fUlgUqw6+UVuscjN5Q==,type:str]
BASE_PATH: ENC[AES256_GCM,data:3/+abnm23redBQJvkxLQA3HNcA4C,iv:X4wnDJNBnvvRa3F94rAv5W4+Ksda5gJaw4GsBqE4+wk=,tag:ULEa2EPl9xqgAIYGxw/WpQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:Jt4gJVa4rPemNTfw,iv:ldD5BGdSswPlR/YWuEVdMh7pO+/JuCofEnvZa1QW/m8=,tag:JLhq2lzpbCl2ZuA4xYkfkQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:DdjrQkls/WLBHA==,iv:o6E/X9jFzm8U5BKQPJ8fxJOl+NUVMCsqsS4MF0lF3GI=,tag:w7pqoEp73nfMueTjinbnqg==,type:str]
PIA_USER: ENC[AES256_GCM,data:64HoL0xpIlw=,iv:y7MXbkO7G7mW6N7WOAE6HhJjEeegjCG7+U24QAiWqsI=,tag:U8RCu/P4gZp99xHWH2o2Lg==,type:str]
PIA_PASS: ENC[AES256_GCM,data:WR1fadkhm/QDfuzQPqa+,iv:V9+TSbLdyYv37Ho0su94s1jhGqXa67PswNTh/kPmxdQ=,tag:cyqd+3EgxsMnONJhG9QTMg==,type:str]
QBIT_USER: ENC[AES256_GCM,data:kbZSx/vHKoo=,iv:n+PNEhOD6FNNZaJMJ73OWA9s5NYmY9+MiMC0v6OrWvo=,tag:0ezWuK/bkZjNmhL+gokugg==,type:str]
QBIT_PASS: ENC[AES256_GCM,data:vOKIgf4vNjfZjA==,iv:2XRjG2b6TYgrciqWiy+THTXstGSfb8NlPEJICP5b9/A=,tag:b+7xMPvEgNjo5EDGjAUcgw==,type:str]
QBIT_IP: ENC[AES256_GCM,data:9dVEuzQuvfGNQOS+CGbSg9U=,iv:kMkDfLgwPEX7x10vLM6cAlwUQSwcu45ZlyBiL7k4Jyc=,tag:+29PwxnQy90mST/UKzPxHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUWpFa2JSTDdzeStLTHNG
            SHZueWphSTJFekdvZzh3L0J2TXRTQXp3RHhjClZsNmxKSEVRN2N3bTJRNzQzUFNk
            clhpMUZhWjNCN1dKTTB4NjVBbHlpQzAKLS0tIHJiQUV1ZWhqWmU2eTNyWHpxc2Zw
            cFFrYlArVnJBRWFFc2k4Mi9UaVhVdmsK6N8XZ2zpny8ojqzTMs+NP+a3h9Y286an
            ssPdPEgr6U+PgLKXfNujeC5+P6jETZ9vgrB2kL7nk6O//lR2RiB0jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:Q5U8wPQP2WRJviPtjWVmtMfJjwqk3yIScsWObNAF0QmJEfOKkuFrLQsvoTdL2IoMg4xWD2lHcWUm6hZqyiqNbOpuXhSmc5IG2MjXCRQRuQsP+Vi6MZJLltb4+ybFt3/j1Wucwgy0KWdKMY5nNI9P8ICZ5ZT+qYx1DSKTwuThoYE=,iv:AEOsxUuNTIrrcJe9fRCsgKt684KZUsvPbqlZBguQuvE=,tag:VIYx+Qv9I3FXIL/+xy6lng==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
