PUID: ENC[AES256_GCM,data:f6K1JA==,iv:PLmuphEIRyL3MSyoxhuGSAocURqX1Pdyqeka0yuNLNo=,tag:CHa/W0bZpKXTF2BeyaG3oQ==,type:str]
GUID: ENC[AES256_GCM,data:W7jONA==,iv:t9Q+wvGnlKb1bHjs82Edq5dLEIdyyMzDFquQwSmlieQ=,tag:yAKP3Q+YGIHC93y0rvsw6g==,type:str]
TZ: ENC[AES256_GCM,data:bEZ+pQ1ImqA1PYoeWx9LkT71Xg==,iv:GnO274Wf3xZEPWU1lMnxTkCsVh8oBfwpSYQuKqNDtzU=,tag:Yq/r4ubktGznzGrv4aGA0Q==,type:str]
BASE_PATH: ENC[AES256_GCM,data:6AduypkzonkZa0UoAm23lqpi4ueC,iv:wZ5xqq8OpDEWLv0CRo7oSNhXjKmpvPtrso1U5ePhV5E=,tag:TX4Okm4TmZWJ7ltRTCQSHQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:lPcRviXe2AyRKuZw,iv:IEQsO9mnmbYKanXAKKAENaKKaoGbsIDjuuwVNo/JbKY=,tag:yQl9QUq0u4KSV+ytt0VaMQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:HgmseMEq0O7FIA==,iv:NCpyUXbfCFV8WKUcit5IeQW6ka9jidmWAXwKPuEyN74=,tag:eFzCu/1VvoWh+Acq4GHjRA==,type:str]
PIA_USER: ENC[AES256_GCM,data:0ROkRKB9dJk=,iv:nePR1vwdpQXFYDxIj9962yeLuy2umo346hodG+wfU2E=,tag:TF16qzsGHsSrTzO+iKSpSg==,type:str]
PIA_PASS: ENC[AES256_GCM,data:SNrzDcdze6yyhhH2e9ze,iv:tCRQNgG8hkBCWtUoZdUn9qMy7ZSiSUOzfjjmbJoaY5E=,tag:zgQp7iQfGUXoGgxwblQG2w==,type:str]
QBIT_USER: ENC[AES256_GCM,data:kqUv4jJwqk0=,iv:6nRKNX0DaHZp4S6Odmd4U9TR4h2O86rld53omejTwmo=,tag:F/ynCXLnRGOn8bJgaAlFsQ==,type:str]
QBIT_PASS: ENC[AES256_GCM,data:e9h7hyR122repA==,iv:USI7hweNChzJen37zaWJULvcI9s4sy02ephmW59C0+8=,tag:Yz1mNxgZn0PCWyNVfXNm+g==,type:str]
QBIT_IP: ENC[AES256_GCM,data:eYILZ3VZD2tt50qsTWsrhw0=,iv:6O4//vdytJwdVPI331gDeLCZFH36YvGzDvYrPMgcwW4=,tag:rxbSTdFU72mZpL7XNioFWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WFVnSGJ5WktHazJtWXg5
            S3NhTU82M3hqWnBMTnJ2ckFQUDhKTTNuZHhZCjZ6SXZ5M1ArQXZpSlVtdy9taGxv
            cmplWmtFUGZsTm5xVGZrUit1bzdkVlEKLS0tIEhKeVFnTmFGcUs2c2o5d2NSQ2RM
            ZHU2L0p2NnZQRUpuMWhCZmpDN0ROeHMKeiSWrQDKp32cfNpwreqj2FLQ8M1xSS9F
            AsM37P+6YYcRd8M2mX6c+b2fr7ncyQCDt6/Sg337qQBIupPRvDihCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:18Z"
    mac: ENC[AES256_GCM,data:/p0GsvBZ7aedud1lfK68TmSNSOugQxQ85D0KBVJoP8bvqpLiHUoBzARP913xt2hi0l5Z74U+2IxSZbV9itDE4es1pfrSq+KG979z9lNAp7GsCXWcN75L78XuiTBSuVnlYDu0OYDGfMKTjj8Qfq2oDaurGtkdNzvvbVuq5XEwWKI=,iv:18YseLdQH50y1z9i3eoh1pgSefgbqbiKAKx4jhuCPnY=,tag:MMIIME4n5yT/L33FyO2GrQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
