PUID: ENC[AES256_GCM,data:3Z+VDg==,iv:XOXzEZSydfYkH3Mu/nouSxeETs+5STVfUJ6FzZEwQWs=,tag:iZG1N2kP9LYEUAfDuur8QQ==,type:str]
GUID: ENC[AES256_GCM,data:rOQizQ==,iv:zcVZWOxljyrHqLsHqRePQOnPdNLJxw18kMzy+P7jkHQ=,tag:exSGR7FC1hhJPCO9kWp9aA==,type:str]
TZ: ENC[AES256_GCM,data:AyccTLLkzjFkzGmK+THLrBdt5Q==,iv:DSQ9VULse+cWa/wzBtyOhoxBaZ+hO5SD7ZjSFrKUdUQ=,tag:um8LY91j2Vro1XX0QNzNXA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:ygIsOO509GXSgrilPY3h9TSXILI2,iv:l3wP1EjNtwvIg1VWB2hchjehG95lzcXFy+lsBVGJiLQ=,tag:F1a3mQWWfw+stWdMWyDhAg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:l4uLUeH/fuBJNA0T,iv:oTzCE1XwZVizzwyQJMiuYkURKJ0aqW+oWsS2Lb3aeSg=,tag:JYOPEOVqcUJO2qEJLBEDkQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:eTANGQheUNEo6A==,iv:EVm2apLvc/O2nguIk4F2ymJHkj8IEJsNsI0i7JEDRwQ=,tag:wEd+gOqj4BQlWVEpkbYpRA==,type:str]
PIA_USER: ENC[AES256_GCM,data:z0bF6AE5buM=,iv:FUsfAIgyoWcwrXbt8CVcIyoa8AQHbYwytumKl3bQ9ZE=,tag:zoEFZ5BFypyh1lcBmKYUTw==,type:str]
PIA_PASS: ENC[AES256_GCM,data:peBgf5F5Heq1nrRZc1H6,iv:avcXlrulp3z9c7732nhwfS7WaWKeSys/a4mzSdnDweQ=,tag:sqthUfcIn2kp7MevT6XTpg==,type:str]
QBIT_USER: ENC[AES256_GCM,data:Rr1CRr8AZfE=,iv:gJY+GRmGssy3CO+kiZq7qhb5UjZGA9c6C2uWs7jhGS0=,tag:o73T0c8k/aQ9CM2empsayw==,type:str]
QBIT_PASS: ENC[AES256_GCM,data:3YSL4TbBXPMeYg==,iv:8WMpgcRW9vdX6tT78z2NCJYDMtvAgfpNopOVdd54HoU=,tag:yGgT39gVAso7ImI3/bReTQ==,type:str]
QBIT_IP: ENC[AES256_GCM,data:XYwFPB3zyVYw/2KMTdDTnhU=,iv:gDK06X7NCXMEbVcJEdhvn7e5IjmucxxAnpStj8ee4aU=,tag:Ssf7df1alG9fC+o/1fq+vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvT1lxYmVqVXJkTFM2bTBT
            ejlSdVJWc0NhNTlVTDV5anFiME1RZFJIUUhzClloTlltaDVFcmNieDVmcmJMN0hK
            dHk5Wk1PTXNQVlp1dHM5dVZ4MTB1SlkKLS0tIFFucmU1NnB1eEd4K1VsUnJOdWhl
            NmI5Y0ZvYTBsdEdHeVFYU1lmb0pkeU0KIxSzXn/qeIpM6LROVh/Xq2qhSU9euWfD
            IxhitOLXcYw1e0ctVBUC8Oyv1itGlW0+oia52IsQjx7otU5fF5XMXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T18:25:26Z"
    mac: ENC[AES256_GCM,data:qFfJLJKKmLP0HRNQmiXEnyPQtPTNvYsGWb1W3E0kgB/7IT40Tb4xIyQT3dGK0SINof6xKqxS9nwZ9H9I42IftI8Ff09Zr7L905CixOVKw7yQrUCwNGmk1SbWyUmiqZxSlvExp2ZRbaKNIM9qKDaKi4L8YeE7dngz96JdB5kD5X8=,iv:L+kB3XOvbW9yGAqszQ2N34YfFm9qOpVNKmL+1XFOhNc=,tag:qaSTV4DCsyQa64aWqWAe4g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
