P1_IF="wan"
BRIDGE_IF="br-lan"
VXLAN_IF="vxlan150"
VXLAN_VNI="150"
DST_PORT="4789"
LOCAL_IP="192.168.1.225"
REMOTE_IP="192.168.1.150"
TEST_REMOTE_SSH_USER="meek2100"
MTU="1450"
CHECK_INTERVAL="15"
FAIL_THRESHOLD="3"
LOG_FILE="/var/log/vxlan-nm.log"
