PUID: ENC[AES256_GCM,data:JoIwzA==,iv:4lvSZuxJMxQYBIwEffjXFCnyKvKIUC1cbQL4v3otywY=,tag:SM1g45nSvNI6soYqNndASQ==,type:str]
GUID: ENC[AES256_GCM,data:VzOhrA==,iv:ADxTSgacxM7gSYozT9TtJfM3MJNhVTZt6O6aS75YYTo=,tag:oD3QMOtBDEHpXjTu/ISwIw==,type:str]
TZ: ENC[AES256_GCM,data:qFbMZJ4iM7tHVzXaUdm1JQ2u6g==,iv:bymcDA2sh0RcejtwMMKizg0fT5yMtLLaG7St74OjqA0=,tag:8PUmDQ5CG8IHSVPNZWCRWA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:tMLLV1lWOEU60RDXXQYw7iTzlPYc,iv:yBAF79fntE66GlvRMOcwRQY5hU2pvBgf0vU41qTY2lc=,tag:guJEHgsGOPdXsvneYx7svA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:uCnsFh6TD44Miby+,iv:uQSicJN59gTpEIAM0fKybbsFRcc5bPgU0mqdBkqqh04=,tag:8KiIaeSwY9tadqUY9IdnTA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:HwH8HSOpoPwL1Q==,iv:LmH4iEUs/vaegF2XDLGmAH4Qznvy/OetEepORFB6Y1s=,tag:55lcBMn9k9Ix0suC/JpTxQ==,type:str]
PIA_USER: ENC[AES256_GCM,data:gSeXh6zhQG0=,iv:cQH0qoiaee4bViAHt3BlIR3Tj0uVL+MqxT8MM33JwHY=,tag:G+dRpaftfXGWn272IEY8ww==,type:str]
PIA_PASS: ENC[AES256_GCM,data:QOfIEXXJuuKlpr5hRVs9,iv:PaocnEVY7mkvA4FajSWiBKim9dNorL1Eii+hPMtxeL8=,tag:jfBUEPsRXcJADyIIy+LucQ==,type:str]
QBIT_USER: ENC[AES256_GCM,data:GrIQ2zDO4zY=,iv:bD0p+kXNPOgt4+a87ghbFE0L9fqWwLEBxBC2AP/72Xg=,tag:Bh7v37rAiZcHg3x2tNCRHA==,type:str]
QBIT_PASS: ENC[AES256_GCM,data:MtrXYmSznPysBg==,iv:EzQ42KsTMExyu+CuEBy1WvtcvRRbuxx/RwfIaionjC0=,tag:6J8Cz/nOthF992PJoE+ITw==,type:str]
QBIT_IP: ENC[AES256_GCM,data:BgkshXKd7tKuacVD6ojEBMc=,iv:wbjsxfHEnQAhb5aK9/TazMxLSxTqR2BarPxUQ3jjQxY=,tag:LLqy3QeL0Lf7KN4bW00H1A==,type:str]
CBRE_USER: ENC[AES256_GCM,data:kWM/LjOUjQs=,iv:pgt4nE1S5DXUhQ4OiNiORBFuf3Dp7lMURLdeW+XG21s=,tag:2co3vy39e0mWWmn4R/IkmA==,type:str]
CBRE_PASS: ENC[AES256_GCM,data:n8n8/HakV+hhBQ==,iv:2PIhe00GOvQmCs0w08DvvIsT+eA3hHTCasrqRRIwbf4=,tag:60j3NGuo0aAbp9beplMLIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKV1pZZTg4dnY2K2dtZ2Ft
            KzdhRTRSelJUK2tBUURSL1QwalhFYUplTWhNCmVmbDM3YnczcC9mZG1NZFhTS3lv
            OXNubE5ZeDRqelNtME4rcXE4UTA0a2MKLS0tIGxaZEtSTHlteUxaRENvQVB6SzFO
            QWFuQ3BpTTk3VWdpUTkvTWc4ZEJEcGMK+q+278BgTkuGfFSfDszqCmKco7rWAVxt
            /TXsJlaBhDstZ/KBtVtHS/nR2Wxqfx3JdlFylV0Gy0IqUIFExKDF6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:42MdZGihKCOHIVuyHeF5QZizThCWJJD5QTFtOsCiNj7H/h5OsKqyEpIwGjk6qAju6a8kH6rJgsZG0AQ5flGDA9ovK4UoOpnY7870BoCBbXGk4yZAx0vvqGj5REMwL0HZfSbnUOSdsXHYjQxvfwjIRlgbeNJcL1ItU1WMxAyXJZM=,iv:4D2AElfaFP+INc5/gllGasQiAsefTuLY6xosEimx5yw=,tag:GiifjwKT6dI8RvVIFfYBwA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
