PUID: ENC[AES256_GCM,data:Hw7lWg==,iv:rvTfE0zFA6GTEFxwstuN1Eiur7Et1NRoTIPJIE8Pu8k=,tag:omEGk/ls8+o0SZx8rKTYcw==,type:str]
GUID: ENC[AES256_GCM,data:8yUzug==,iv:BCPB0Fx1/EH9gj4PmrYc8qamOG3z2U0PxouaI+OBlj4=,tag:o7NBPKEqfRecYOfMcg3qHw==,type:str]
TZ: ENC[AES256_GCM,data:umQOPRi7Pz4bcNXuRiedARlOuQ==,iv:B8IguR3/Q/tMN3JO6KZE/jwoebjr021Onh4PhP8fCyo=,tag:eHPhxwiligzVKDMmqa1ahg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:HEvabxmFbXDDez+2TlAxfSw1ZO1x,iv:BzZOKRXziLugvSlp87kQG90gqRI1c5QdQ5XL4jGtIsM=,tag:HHJhXXEBHdn+eo6KliRp4w==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:ZJ1ZZ7C5ngqjY6JO,iv:XjZFbVKfiO8EuwNWJ2sHgHLIY+7d1PpveqX8n31UV/E=,tag:b1pXF8bOwN/0q2A/egpR0g==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:1iSUB1beRS9xQQ==,iv:2qqil+sBdQz4fekUcmN+M2Xqprrb/goKpRq5ijv6iVU=,tag:3OpLXXa3kY4m80UMwEC9Xg==,type:str]
Secret_Key: ENC[AES256_GCM,data:TQwGN0Z3slzuQDQOeiC12es411H5/5P1CCfAjzkwzvnmui1YeJQgqBUBQ0Vo+9yTWUftQ+OomsUD1GKfRJ4/rQ==,iv:NV37qo+i8CG6KvZFeB6y/s5nLjals6+yVcpTBEkp0TI=,tag:y/Z4q/l6V37ElF4gKtQOag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacmlQc2ZraG9kT1FTRmZN
            VTRzVjR3QU40V2tJUVZwOWE2MEs4dWFkNUJ3CkdTcCtoaUlwRE9SeG9CaCtrLzh6
            MFY1KzhBQVQ3NDVDdjFqUjZIanJNUUEKLS0tIHgyMW9nL2lkYzZPcmpER1NEQUg1
            QzVhOGhZQ01sL3NQTzdyb2RzM1NSYzgK7Dm4oH8eFdBbMJeCaIqO3ft/txB0PjkG
            hpM2dEjiGI6HUT86Po9wwlvHwa5DDAdsBZ6w1v2zShp0xfTsoWlLjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:WWCa8SvTSQUepyWxwsw7GhzFk1chAP1VZxQNK3I8UFKns1gXt8OkbShHzJPzzWW1kmVDShcsvfT/iUQJ0S1adVtUSdW7vJOWhmlbKLw5x3AKgLlff69e+3XZy9+xj/eamv0/ZdofPRT0PqmI2xkeLVEz6pxNq7XDaxoNkTxTaWI=,iv:YmSzCBzdQpVlC3zedaKcSBOqWETMgaAhjWz5oMLc6d4=,tag:1x52CitdE3dTfoDwsf/zYw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
