PUID: ENC[AES256_GCM,data:wTyPUg==,iv:iqxqXDBudF/8aGolmscdS4cxNg1q+n8vDoWppVCxwLY=,tag:6JIv9ZXCebo4f802TRJV6Q==,type:str]
GUID: ENC[AES256_GCM,data:3HJUew==,iv:hTbpAIpwppT1RyZtd+eDg0pdnMf0trsDemtoNDVEfks=,tag:ZNx2fbEufk0aGKJdNZH/9A==,type:str]
TZ: ENC[AES256_GCM,data:fowyi/NfSMn+6o5yAJPZbzuWTw==,iv:+gzihaUI4feCvUeI+PBDIZR8TZ45vBZEsDVTi3IyFhQ=,tag:PHkw6IA9f9lgT7YTd6CVoQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:XTbVHHGKLvmVaW3zkdKRX4jIxRHv,iv:ZDCDyAR9KvDqyPQsgQDEnnUVpJT2XB9qqguSx4Wd7ZI=,tag:zzn5cUs9b81Zyiic7eXt4Q==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:Dor7dqBoIFxfMNm6,iv:X17VdgoyBoKpaGlTNGnvYzu/3YSueu0mvji8W8+tVSg=,tag:Of2gzPb9zmU1Uu25DT3O+Q==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:NL2osraP7+Tlig==,iv:otsa2JyAbkIAlDWIucFEiGxuINMeMn9XiBl1DJFztIQ=,tag:EonpQPdOKfgsFHKJmdedWg==,type:str]
Secret_Key: ENC[AES256_GCM,data:9ngBfIBH6Hz402eUhguVuyY0L8TwYRH9UV+bG0mOIpls0WEojYQ8+AswB8o0JC1kRUId8gjkzkaWFcNn9wMJlQ==,iv:nUbjd/nxquwEqZx6DI4S20w5rv5ruw8k6VFqhWDOJ8E=,tag:nw+1lsGmaWS3Hc4NQ7onfQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRY2x6emZjbGszN1JUS0JS
            VHdaampaYk81MXVpam1TSll6elhIaUxha0hJCjBkRjBXOStIcUNGYVQwNlpvZVFP
            enBqU0p6TXpjMDN1bUlNZ2hpemZBejQKLS0tIGVEK21kcUZrR1gyb2xOeVRFTmpE
            SGtiQ055bjQxRnIyc21KaXJHUVBhVlEKgc8oZHzHpDxDijV8QHXix5qFtrXMJjiG
            qiMEDjrgQQosYcwISpC1Sy1zLutktBktEQe3Vo+qWyKtnw+r8MIXgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:17Z"
    mac: ENC[AES256_GCM,data:ctU9maOqGjLVRo31OfVwhaEAE7fGfjeIViRQcwZYhVviXI/jV7MGY+iL+0cBJ9prs1D0/NNdCKejT5Qhi8DLe+R6R+rYOCIDIftACIzACdr/1FHqXNZm8eVqBwz0CGw+8aokmJKszmMD8hmTV7Dyg0pWn4a/MRFfdB/Sjnh5VFY=,iv:zXbxR+A/r25VEbxOSf7yjgmGwj9dzCGApfyIhSuVrCM=,tag:1kdC0JmURZvyThhPWiTxQA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
