PUID: ENC[AES256_GCM,data:Z7ZXGg==,iv:Dsp/r+YHEiL6rZKUF+kZMOUqMnvauH1RzyanAbRMDfE=,tag:+3jj0cu/kDlxniHlgc/T8A==,type:str]
GUID: ENC[AES256_GCM,data:wlClyw==,iv:wRcaUeTQmVPEsbExsak8h3thvazb7mktCgDy3zzPdJw=,tag:pg7NYPldm9VY+dY+4bBLCQ==,type:str]
TZ: ENC[AES256_GCM,data:Jn/HZHlqtFvZ44AaRRrGRXh+rA==,iv:CMZ7Mi/Kf6oYe/QpJrJcAExVBUnSQiJ23ZAL6WnzPXc=,tag:DYWdqcKYAMwr4wkwN0J1Uw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:lDY+5gIBKfuvyyRAzI5zKV1ahxCT,iv:wU54bL5lw/9XBLyS4iGPvNBW9oqO7eFAeoFNmvb0BdE=,tag:mwCTqppSQUwPwO+K7cdmKw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:9pSliyU8YNaYSH2O,iv:Z2LFPj06tdsJrn0tPIXb4FxCjYrCJnUaUfkJYdKXgkw=,tag:k1TaWfycIqUvdn/1mAdBzg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:do4vlNN4W2W19g==,iv:tI+QOM0ZVLo+jgnZg8YP/GK1OPFrmq/E2NLfm+g63FI=,tag:Unc67o0txmElgm6i7KHwpQ==,type:str]
Secret_Key: ENC[AES256_GCM,data:s52PB0GD8oVqdqQ8/Zb6YZeRCLFRlNlm6PwbDSTjh5UL3G2BR1vRBratAdhHKd/+vziXNXAObJ5s5Ey7+cuftQ==,iv:UDHLFfTFLudNRkvg5NLO1v0CiVgguvkYNrps3Zkg5yk=,tag:a3ZE6MQnza3xjmq5IzRxBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNjdCN2tVZmFQNVEwQnRQ
            UHJ6UkNKc1hDdjNnRldtRlozU2JndVBjdmpNCldKS3BMbjlZU2JRS2ZsY3RLVVBa
            cjVrK1JHN21CcDRvd2VpeTh4NTNTbjgKLS0tIEtIUDlRUWg0N0daZmFMWlo5Q3Zo
            VXlPTXhMU1FOUHhlY0NXR1VqaHprZlUKR7bzSl6TUCnUo5zg5Dm15BA541CtY9en
            ZYfCZLPzPt8GrcvlQ+5BjdG9DoumAMclCe6QQPf9riTEVnI8jZhNZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:ZXFjAkgeYNltcw3c/C4sYKlhcK9OYU4G/BzEGWoU1W5V6KIVUxtOA5z/hACC8ON2n00SE33IDalHh+gnLnDZE/XVLgR9LhrYu7QPFj7EKlXMgEysP3GrAHdYZd6t1J2W1Hvj2QruSDZz6HswWbIPfVl/rZ7PHD1y3rVkul96Wyc=,iv:hux6Z3wpfhcVjt9nXMssC6Ii19hjbuwu20ZruHAbBHs=,tag:+GQi+WSUAd9q0GL1RhhjOg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
