{
	"filename": "ENC[AES256_GCM,data:uX/XLwLfDXyVli9jcg0=,iv:1oqyPkw5OfiVVfxNw9K4R5P4kh0NLkCib3qn/HTf49U=,tag:fPCz9BZnaChJJPlozi/xvQ==,type:str]",
	"content": "ENC[AES256_GCM,data:U92PPO/A3wpzkanfsP919RPEfTJ4E/NT/NFoIn2lSEy5Qi4EXKEnjIva0s+gVp6FUjY7kWZJrVwNo0yHp44mDJgEuIWDaY1FhvjcSyynNjiYnr9/kz3fONOH5/TfnQ5QRLFU4mAK2qy/FJsS3xZeXcdssZMPmj8PEqwUNHu2F2pfagSgQLHK//m/Skaz,iv:GNXOyDBUmlvo/hAg9Z5Jlx4l8wfrv3oMO19O0vXQTA4=,tag:XzoPK2MwNjx46cE01I0ojg==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTHNaRXh2SzJLdEsrK1NL\nelVzeDBxekJMbVhMdU52Q0ZPeXBlQXgvOUVVCjQwMzI3cDlrSHVpNitJYThSVHdn\nV3RYQ3JORCtkZ3YrdW42ZDJtZWdVSVkKLS0tIHBDSWI3SFduYU1sYjBIaFdqbTVF\nMFk1U2F0a0RjT0Y4NzhDUVQrYnhYUjgKhT0/vWdWG3pBL8CxP+XpY6mO6cVTxPbJ\n93fcc3Ew8GRPvYdX1O7wDzvLPFl+L0IDt9tSdazBFb84Wh+4b0cgwg==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f"
			}
		],
		"lastmodified": "2026-10-08T22:17:40Z",
		"mac": "ENC[AES256_GCM,data:JA822xY7CbOw/m4gmBQiWwUyu/wE8OUTMNpMV1+25JuE4b5kg1gbN8EjV0tgh59vwTI7mJlHIXC62Lvn6Oxq6TSroxHtzMcnX1yum526+WG+Icivhay6regvr5uNS+AGk/bEQRC3xVaXuGZYou71A92fwggHke35eTT0tGVPWeg=,iv:yMgVBgC3BXVfMrzsZ1JNN977/jriaWeXdZq6l2FxJSM=,tag:QqzGLKA+R7oqmznepL/4tA==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.13.3"
	}
}
