{
	"filename": "ENC[AES256_GCM,data:5o9/QbiryT32Z9ep3bI=,iv:qCToI4x3OZvh1mctjGM3l3FcnP+P0jhNmb+VzRKLX9I=,tag:Hr/r3cRlqnQuk3bu8j7QyA==,type:str]",
	"content": "ENC[AES256_GCM,data:wbp3lIEO+fjiLl5ATRUSl/oQ4s6vraEpruWBx4RqVjE3a9El1rflDV4EvBl+zjHP/zCE327YRit1eDeVL+4n8+E4/LWczkYBf243hlDJxC6tLcUx0AK2BwiKUwDd5Y6y2kxeynw55R8qC78d4h8IZ9OQmhrk6bYs6S32o9E1KDWFIxAIEPcTIpKpL2eQ,iv:N2qAB1yl41IXxWxbXyD2osQ/hGADsbjkMymraQ3zIRE=,tag:sZv8vLbLjFqESFQz8DNfDw==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeEFCOWFDdDBna3VvWGYy\naGM0OXZ5U2Q3QWRMOHA4RlhudW41enpEbFY0CkVHNU5QNVVpd3N3MW9nNnZtU2VN\neDRKWkFNcDF2cUlPQWt5T2N0eGJkZTgKLS0tIDQwRGNQbURKeUIydTE1VXNZRWtX\nRmZ5aFlHWlBlVDhkKzdxN01Ld3czK2sKtArJXPWjWLOdIMkzeImWsaWDN1xpC2cM\nNJ9VO43fnppOeb7dwhMwwfHiTaWhrcx1vayoZXVXE9iQxCmsyVKiFg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-09-26T08:31:35Z",
		"mac": "ENC[AES256_GCM,data:NwbaO2KosJKMyW1TvRO9QiyREfNZjg6mYggaDOrZY/07ZqUnqyBr/9b3baHeVrXx1KOkXWP5E4Hr6Q6jfwxwS8FtfpYnp9PtpIa8wDFGAMbIfqjivUQHEiDePBrf5nrPw8Uj5kBw3RQSGGTdb+QWXSYOdbhEaA1x1JskMlgLCWE=,iv:SUQd7O/BRMzxmQjNC0Yd26OR0QDmUcm2yqKd2kfg/c8=,tag:92KlQcHiJ+6kD7V0FCFOjw==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}