PUID: ENC[AES256_GCM,data:k990qQ==,iv:1hF2lluzxUTM7I2Q4ZYoYNJmQTpbA8B+EJtJx/s66QA=,tag:PE6QzQAX0/Ub+tekHqtWmQ==,type:str]
GUID: ENC[AES256_GCM,data:tUewWw==,iv:YINtJ86IKBj5wIcPhFxGNgDeLoBL9DpRJhZMUZKVv9M=,tag:8JogjTu56m5W0OG2YeZLGQ==,type:str]
TZ: ENC[AES256_GCM,data:dzzCHCjs7Jnijm/zKorxKjVmVQ==,iv:D+AO5zPCOtbL02Rmhd/j6uTHl77lSK4l3iaBpBNgcXs=,tag:Z1oY8/68yVf8EDHwG+siGg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:HuT0AUrCMXVzNyYLkZxq6wxAdv35,iv:m/BcKxAPAdCxz9iaZMUQ7R2gd08os2Bf51W1b0Xors8=,tag:yUQRNPUKy8m4Rfwgg1Pd2w==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:XTtsspOrt8xi4DMH,iv:66SIstAdUPS54dLyeww4LAc6u6i2IXfAiQsepLAz9wM=,tag:YHUWjdUYO9GSWP1gy9FCrQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:mypGYllsMMV8bw==,iv:uxh2zuk8i2U8s4QxmmEIBAaieEEUw30KTW8QdlJD+dE=,tag:jjGdVZUsC0ENp0BS8/FOGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdkFZNm4vejBMT2hGandy
            NWg0YWxZLzE3eERBMjBiaU9oSWNTeXZxT0VzCkpxZExoWkkvc1VRV3JXeVpHMTQz
            MXFlYkp0RjE0VmRLdXB3anpJMHQxa0EKLS0tIEtSZC9mNDA4TWFmaE5mY0xyNkox
            K3ZLTkM0a205aVFwRXZyY1RTQ29iVVUKBSyCd4z9DxZrdNtyAl2lHYpXJko5qD5T
            VRc37z/hxZ1BpI0WU9gBMhwRfOD4pNtG6LsHjp7JatHjsf2mIaRefg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T18:25:26Z"
    mac: ENC[AES256_GCM,data:Illqq56syafsk2u5aw4wM7vE2iUgA3rctEpPLGz9Nhh9urbF4cBhgwxJwAmgGBhTbspTA33+9vUf2k+URRJr3dS7Vt9KyYW+VbQKGbNhrAtyngv7Xbs7Bh2tfbZKsBrm65qnETRYidG2gJMFjBeMM4oVHvRxv2wwq7/SSDkDkJQ=,iv:zD93bfLLG4s+E+hAXs+KLBAogAPrcOGavDJshVM8JGU=,tag:8eCm2MhON0+XDaInV6Cd5A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
