PUID: ENC[AES256_GCM,data:4ryckA==,iv:bhiHQshIY4FUs3wKrvg0JnUckI5rbRcEhlMnaRN5B4M=,tag:WKsczmtqEnJeGi+kWsfQLQ==,type:str]
GUID: ENC[AES256_GCM,data:yGTBNg==,iv:gKG6DcjM0m8d0ExnwFLpsm7LKYpbBmzA+phzrstL6Eg=,tag:pixzh0mnqzBr0c9VLNMH6A==,type:str]
TZ: ENC[AES256_GCM,data:uQcNAQB/+3MF2uawAWI+6OVLgg==,iv:H0HdgXmvWBfF2rCKy51A48FH/frRmOsyvauy4umoDDQ=,tag:dwhVKP5lLvceV/99oVfbuA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:UM42jw6HRmXTB5r3Yx60FUi4k7lV,iv:CykIBUt05eUZoT3iulCYCYM7/uEJ0rWAbGEnQQgB1/0=,tag:ehWcxNk3Ao51ZnxTNmtT0g==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:MTHOIymbPsKf8m0y,iv:3wD28cX95As3lz3dbhKG3nieQ5YXy/V7ACxXkyqeJLE=,tag:QcQtKnvMWe0bNjRpwqfNGg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:G7z0ymjJQvMB1w==,iv:TrhepuBKmg3cm8x+yCEQBwrrCJ61mZ04yoexJyrRGKo=,tag:PWUdo6hxw3zMGiz3FbMsAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUG9QbVI1NW1mSkZZTndy
            VUg2blBqNGM4bzBPa2VKaHpNN1pOVVRRTUZ3CndESG91a2ZxRElTK09kdTRnTVdQ
            TkJsS2dJWHdpZnZNOE9tWGRlV0syRTQKLS0tIEd2MkgzQ3k4Y2FQTUR3UDJmbTBH
            QUJJZjF5bjlaNXhJU280TW52UXRyRE0KV6dQkUhNXs5f0XSGcdYRVWD2/4BWL+CM
            B3e7VsdZC9CApeoueYZGpAJXqf6y248GCfr+XYODEIol+oqQw4rc/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:KXhWzMc4tmSEpKt8mkhA82ZmUwX5AlNNA/8roL5BS3Eg8t517ZEgKLZv8TL59TvI5DCHoIohhX6qdOrO38G5q/OfPzxbdv5wIOoTu2u6EuAReltJKFNELBJr5EUPq2QTN3sOQtqGPNijcSWEgDMedVsWqVqqwBKHTNregj/tt2U=,iv:0c4Ta0XbT9GCGM14fJkTwdKJ18uKgNviLbOx5TS3aJ0=,tag:6+yX357NBnPEdoiMbwOiUw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
