PUID: ENC[AES256_GCM,data:NIwwGQ==,iv:trFGzLpMdy9w/TYUqSY7X6h24xLD32gjiqy0bN6yYeM=,tag:PKxXL75aurRoPioJFeKKGw==,type:str]
GUID: ENC[AES256_GCM,data:8Ej3xA==,iv:86LZyAWhBdWE9vncDRTImYtUwME/2nWdBzjQ/8oxMp0=,tag:0P/l5ZxDQDbHpcn+9hpyyw==,type:str]
TZ: ENC[AES256_GCM,data:oIJqh+KohC7FPAaLVNWtDTwnGg==,iv:P6Qh4n9Sdlb0GhIwbMP1lPlJdq21I6wLhCj63DSC+Q0=,tag:20xpWMfvaIy85vAUjHvZug==,type:str]
BASE_PATH: ENC[AES256_GCM,data:XSAgbReARJU4X1hJGq19KkiREa2h,iv:J30I7+wp+WuSw+wwe8ieon2j2QbWXWo7kWVsiqat1X0=,tag:tXiD+8VnmwLfMnYCLwiWjQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:RLtjLJRyZM0Dl8Ik,iv:aSlMTZqXu+w21dYmc2TsCdeMQy21MN0wNwrzxinIZpQ=,tag:81Ud49vS1QvKYVSvKU6yFg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:INz2FdPe6uRWUQ==,iv:omj0aVeMcqlXm7dZii38Rlkk6p1/CQlo1pzP2IMljQo=,tag:t8xWgT3nhnnNeI8jHxOmrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYWk5WVhndzl3OGsxSVV6
            ZFlmNWxwWml5L2NYbElDbWk1ZnZxTnluQ0hZCk5CT0hWVm9yMFo2bXlodmtoWTJ6
            dHBRaDJQZ1htK1RpTE1udWpBeWhOZDQKLS0tIENuQXlVWU1neGRsa2JUYVNnY3J6
            bFk0SWhST1piQ2lhbTVXWng0TVI0N00K39E5UOsQbMI8ztSz+tPm0da+mxljz5Ed
            S0Pmw4r8yGAgiR1aw9VM6ga3OZeF5OD5JP6O3s9ultAB0N7tNLuIcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:lwS05nCdgvHscJRhMDKF1iFZqJUoanlW5fzs0tRL8Xe+PrYnwwoihr5+h5lyhgyNEqYEXM4z7BseTmBz1aGAZ10H1CrEtdF6pDYtGJ/V3Its5YOMqSAfk63KiGcDcMDSbNxcjLhfUK3wr7u5T1bYSu/7brEJGhKELgge7Zv2qVo=,iv:H9DUGR1/t3+7xRP+H8avTn8lA4jdDKj7zPlgJqXRBHs=,tag:yr+3jXjj0JacysvsH6E/Rg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
