PUID: ENC[AES256_GCM,data:1O8atA==,iv:PmwY5ZPjCFwq0gQ0aSESGxBftL2GZO004Q6ZD65riOI=,tag:/dLvx/T1BIVXRYPBv9HbKA==,type:str]
GUID: ENC[AES256_GCM,data:4JTFWw==,iv:Hy6YjoPsJxtyZDTD+uBfh3LyBm0x/8p2NCZwgXpjxvE=,tag:Fii3tJcjjnqUabkRnxMSFA==,type:str]
TZ: ENC[AES256_GCM,data:VlM3cT+eKKazAJtXll1J4Lm3Vg==,iv:RRsINGrysRiyfQgl10e2oPukWnMFQ7lX0zoU5jvf0i0=,tag:I9rhbyGRFO8+ll56wdLsmA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:9NkJ5sXMjNFafOcLxOAhIE31oL0c,iv:kMYBw1+RuE/FdLDEXMfCy4kO6vFSKi4Dmvj6UEUMCp0=,tag:kSeHkT2/wcw8DL/3uJG+Rw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:+f8sYbX+BDUiElN+,iv:zYa3U+l79bSinHp3HGXIMpqPaw8nwM+rMzkRZ8zq5kk=,tag:m0be1SdvjzBtKqdT3PaDXQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:13cnJq8URVSk6Q==,iv:C3bYv6Mh132/imNywKpMxKWbENYMg5anYOiTi8Dh+i4=,tag:jHDSwXRY2llN/XHSsj7vhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdFNxcjREMGpwTDFUaVdp
            ckJLUllKbHBzb3RsRklvc1g3M3p4RjZBRWx3CjBjblBRNlB0VGh6NnBKV0tOQVoy
            THpzU2ZPam9ETG9CZDRFZ292OFVnU28KLS0tIEJnVVZlbStySVhTT0xzcjNtQkJO
            ODRDVEV4cVdCM0c1R1dMSVZtNUd6T28K1aYnnmtimsAWhDas9Hjm7/D+6mL//DQR
            x12EFCim/0c/8mAOCuwJ7zXQh4xr81sKTQ1HP+Om4HN09ja4RyY17g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:D3Cn99GXNG1APjclBEu7OvIu1z/H3G561lv9Aw1RgbJElfNoLem1BZI7+91mBIv4CMJs9OsEOcyIlWLy4aS8Z8Yb0RhQ/OgMYeFfjsAAwVeO1MYLK0VZvyz1RP3wDg09iLhiLTDh43wCsXqXI24wa1/LbgygkxRKx3B5RJHJ4iE=,iv:+GeVNyUXLQO2W/QR7IV41FM4aycnduzjDe/Vgd7vubw=,tag:M2Q6dsuLeytoshFNwt9WKA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
