PUID: ENC[AES256_GCM,data:+WiDSw==,iv:+xhEFYG7vRwRHFMN3mIBe2PgUGLtfaLgDDt4dt+G2G4=,tag:QrPXnlCNH/1mFSUJCP+Ewg==,type:str]
GUID: ENC[AES256_GCM,data:AaGr3Q==,iv:nF76JlcQb9xDl8jtR7fyBAytb8fHnAuI3VO1mYqN59M=,tag:5bDVlqD5/JrrOZYqBgQggQ==,type:str]
TZ: ENC[AES256_GCM,data:PmeFMdl97OiMjaBk45fFK1aXOw==,iv:FCRbKTP850qf/OnuUllFY3KTdwMPWG4NYXnl4qJQYLI=,tag:IE+SMFejkurPzgc3/SgchQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:gN4GYzMdz4bD34VkwAlB8zpjahE+,iv:Ky3Z1596sBk3se75MGnFlB1A3WXvjLO5Q97g8n7qNyw=,tag:IoaGuQH14W1qsJmXKlQ4gA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:bGiFqKEoFL87ehTP,iv:70ThumW2CaoHvoYRgCIQPv1n6Myu1p7eyJ/5zmC22d4=,tag:J45kTZncECq6GsS+xVr3IQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:ACGb8kljHciEkQ==,iv:otreQN4vkLWa3xCBYlpCVU8lQ4eKlIW+sSHmNkR1Qjg=,tag:/banOl521AhDNplrlK8l6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cTBkK0IzOGFrL0hPTWhE
            MEUyT29qMDJ2QlBEREJ3Q1FSY0g3T0dzeFZvCjBoWERsdVJ6bDVZdmNZK2tOWEYx
            NHc5ejN4MTJHeEV6dER1bjJlQ2xtMUEKLS0tIGtqeVJtZVNETW9DSmloSk0wNVdM
            NHpJcU9hWjJqV2xKT005SDR3TkdBdFUKrw+KW95uS3kv21nYUiS+pnZK/QjSbPto
            t1xCVhz46gvEV3hslU57vArxXwI/+E7O123s+hT4fSCXVceqoZkwiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:18Z"
    mac: ENC[AES256_GCM,data:ONU75Yuxg09PK4cyOg1q/7zn3sp/7lu52EIWjiGg7KhVk/UTPcKzoFq3oJExlY4Jsp310cczWajEbEaef100WYsqsXFC26wqqSyJVYCQP5ad37pcRusI8SJngDcPmbwXzBpnbuPlA7LqLUJOq8zYglAEMbgk+wJ8s04O7KByJO8=,iv:iIVZNgfa+nyVO98lJYcEFjDPWu2mMWLUKV24Wcl9gZ8=,tag:4MIrJIqC1sAkE5FuVjD49w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
