PUID: ENC[AES256_GCM,data:aEKpww==,iv:6MIRASIVbRP7Y6pWg9zI9/XTT29hN+5I8b1h8qGqz+8=,tag:md0xjFXhbxAbEOKqalAhhw==,type:str]
GUID: ENC[AES256_GCM,data:uWtSYg==,iv:Mjs9GHHQpo5guxfD2Hs40hGTIKhmRgUl04qBZ99p0qI=,tag:Yu3OO/7+VHPYo6vzavYorA==,type:str]
TZ: ENC[AES256_GCM,data:Xj28kIEXhuiERXba5Z3TjiTNwA==,iv:/MxgyH6YZq6lL50/dUtLIZUo/wgeYSjjIwXmk3P3ljM=,tag:7Bcp+fih/i+oCn2xQJNEOg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:L8f9OBZk3KTO9rrI5+CIusKaMCS8,iv:12C3zkLj/Dtx8Z9BGqlk+i8LhUHdEhv1cgbwJ/lewOE=,tag:swDJ7y7ysy87fhUOxLIIsA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:yMwx5A6WXZMB35VT,iv:m8gx8W/+DDXoYDO6BMquO8Ju8xrgdn8TLDKpexRpQpM=,tag:9bPZFxuVptbUJb/KNaz9LA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:2r0JnURFL4WIgA==,iv:T6Hybeiu1/pMcYHHd0K2LZ93yVjlj0CJ9bXbPMtin4w=,tag:GvZLPTUbsA5i6bsiSm4faw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZVI3Wk1PTUtGYmRMeFYr
            RlJDbkNzcmcxWWMvZHE5VFBHZEc5STBBc3hVClNWa1NRRGFyUUNLeWx5RmFpQ3h6
            THQ3YTV6TDdQeTRQKzFDaDlyNml0U0UKLS0tIG5CV1ZMdlVJY1FJWVBHWS9OWHVY
            NHhkc1JkRE1XODlTT1c3S0tadm9DbTQKbC3L3dncTxqtiBTStdvZxU6yQXhp3g3A
            IvHSJZj+CBFgaOg4E6bOntg7/3h2VKC29Ng94HU7u63XU1600njmJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:lRGhXuq9dPf+ijl0CuYp82lGX2lqXTb2LWS2FBk+mjRat+jUYIVkhoUavV8/fKzqL+ACWMzBMF32DkCzTcoTeTdqDIfUFKXlk0wQ+nCjNeTY7T0C83NeeFk4iqQsm2YPhN4Ax2Q6HoNf4QbcbseMvxpSrRKzSU+DFLKhbbLlBiY=,iv:xqY3b3n4A4e9dGpHxrJrZJNUhNavriuMQCAwD4re32M=,tag:0arhorz5BezQnHYUo6VvSA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
