network:
  ethernets:
    ens18:
      match:
        macaddress: "bc:24:11:1a:56:46"
      addresses:
      - 192.168.40.248/24
      routes:
      - to: 0.0.0.0/0
        via: 192.168.40.1
      dhcp4: no
      dhcp6: no
      link-local: []
      nameservers:
        addresses:
        - 1.1.1.1
        - 1.0.0.1
        search: [secure.theurer.dev]
