PUID: ENC[AES256_GCM,data:QlGxdA==,iv:E20IeqDEVrbYhfhqSF2Uqw48zYWmc/8SI1vtHOv+7zM=,tag:2/rWYtzRXdL4PJfwZs/CkA==,type:str]
GUID: ENC[AES256_GCM,data:guMilA==,iv:0W6KTS4ZPzkuIwv+TQMrzaBsks1nVIf5SU1vD+6GgN0=,tag:NXnN/4qY4HlRNEt/A9Ky8w==,type:str]
TZ: ENC[AES256_GCM,data:loCp6sIeBZPohemefrPTe3NdXg==,iv:EYnDwGLU1nDz1ruvmUIM2Mw8rbZPyYpJMndFItQrbPQ=,tag:bAz2yoZMVn9cU71B0d9gGw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:uyQ7yE8vliLkLCT89Nu4ghqXkmSc,iv:PBFnerKmMUSIfqXfNWN8/g6RdPyJZNv3kxB0D3wpE2M=,tag:xRipZi4UAJnn3YnRqnO8wA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:KHek6LJl9RrOzh+l,iv:fT0ez62MWpQdllaDu0xEH1RaCTFR3ddb5NVl6tMPteY=,tag:+u1n1zzext1ua0xZ0/KMDQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:cH/ZagjjzDYs0w==,iv:jNDOYeFPoBkMQ0lTcC5Tr3F06J7YSXJcXmr79o98/aQ=,tag:9eFkEDOdUL57lFMlfDA7eQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSHBNTkptOGlCN3U3aTFo
            Q2QzOWJXMzZQTEVuMFJja1VvazZhZXdlbmtnCmNPQzRwL1VsV1ViSUNJRFdHOTNx
            bDRXSUJaT29FWFdoR2prRkwvMnQvVDgKLS0tIGxSTVNmMjlPQkJOTVVXOCtMOHFY
            cUdsa3hOdndlWWdOemR4dkU0N09UMGMKVqBIL5kIQElCTLnA/PrBGP9xtVF6h/+s
            zCWlalxA+i4Ua0+2I7boSpSLwJl7W3FS+Dd/orypR4e+ovX/8m6Y/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:CFEygL80VIbXS4Uz0/uP0e3Yb10vRkwTX/VLFA7BJGWVvplIvSpGzHh0RAV92WySRB7esW6Ke4fYmftE4wumk8IB0+uK+DYh6JjsJ0asIsSI/ePfzFp+ifd9IWcERKXkP37aO3CRb9iic/XJwV+O1QvUmTZGy9FL2KM5UKw+svg=,iv:plAz1XK7Yp3lwEXgn2i0is6ti7Fy0ckjh7jk0pQxcng=,tag:FjFajJje8jEUFu34NHmA5Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
