PUID: ENC[AES256_GCM,data:qSu14Q==,iv:ZNQyb470NqkHIvpQmH7rxlN/0RwmLBDaYEllhiPHMSE=,tag:gcvgBdPbig7KhIxnNvK/uQ==,type:str]
GUID: ENC[AES256_GCM,data:qt+Y7w==,iv:XQHr95OuhQxLSHoGFk6iE/0AqFfOnsHuYsrgMzyEWyY=,tag:kvtT+aXMxBbSIKb5J2sCKw==,type:str]
TZ: ENC[AES256_GCM,data:AHTOcXuXQEAJntNFv8NZRYa7nw==,iv:HAaF6/p0iv42Kxa0gjeSMpUIrIJMAM96wKTe/mrd7P8=,tag:UD2NiFxGZ/BUXg0N4Hrrrg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:HCzamYQewnqT9VRolFJdRH2cTK4b,iv:5+AIPeVcwG317ztZ7PaXBer/IGUHLNG0724joby5TQ4=,tag:dRDgMBMyrax4mCiIGnM7QQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:3SNTCHb+e7A4CJr7,iv:MYc9Ctr3NHuVzM83REkaXuXGGTeHllBrx8nMshm17iI=,tag:TCzwfXAi3Cm0vCd0f11RzQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:dLaAxlG4hqkusA==,iv:YwGMNiGZlOhrWV7PlySbDWRQODDWc0I2fbKRn4J0xZs=,tag:qpRkE4iYNiQfBmuXdEzwdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUG9NVmVDTWdaZkw4NWVr
            eW9pODRzMnVvaGRFcXhYUHMrTGlDSWxuT2hZCmRxOTlLTjMyU3JEaXB1Wm1YRGNz
            Ym5aK2VIcGxrbHMrNGVpUmc4VTk1RG8KLS0tIFhjaUQ4T2x6VzJXODZ2L3d1VXRK
            QUszNWhUUzRnTWhLWFVzUERHT2hjV0EK/Ox24vfuQCb8YCS237gem0Ncd89IDb4K
            a4nH4G4ttXBjNE9SJEFL5wFCZrc6Akc3WaJ0dIkKoTylunx2oDf2cQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:17Z"
    mac: ENC[AES256_GCM,data:uUE5gAkCJ6pV6XWGOdKnWdNwd0caQTGUwJPhdEf1S4DSsf+8ugoo61G1WfEg/HT98+XL+OiAAjSuQ/UkNU+hhlhhOVwfCcULw4UQXpzHRbmpMWLXHc8Rc7DlnurJhEaEgSVniYno949bZsQWBah4A1JVkps12vinasV+LkiNZMA=,iv:BcxzQQxgxvHyo1PSivZsGFO/Sr/9S3WBNTIvAqC/sA4=,tag:Gq7yFQ0qDhSrqaI5RWb4dQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
