PUID: ENC[AES256_GCM,data:ySWG8Q==,iv:Ig/qaolDC3xL1yp4nSUPCchnI8DBXGEnlz9M7G7gvwk=,tag:MhuvN3+m6BY8oqqQ/yVIdA==,type:str]
GUID: ENC[AES256_GCM,data:lrUWaw==,iv:pJwFnnXrxE5fTBRUALDe1Hp5PqsCHeGcNr42PP2Vtt4=,tag:Y6aOdl+v+q2bLcXOj5kW9Q==,type:str]
TZ: ENC[AES256_GCM,data:hE9Je8128fiFx5Bn9xDNBliUBw==,iv:g1kHuuoX5HN1QZA+sj9TrGXXkrYmVWnH9nqx+qmiBXw=,tag:1iHI3cAsFsr+ZKviA2fuoA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:DVmamfLZ612vBj+wrs98RQBqEQfY,iv:LcuzMNdUtnqbcj3pRVFsNvQI8YkBTIfF/04WZMJXUQw=,tag:HnfmYLYe8jd09jLDDtGQ+w==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:CgF+1Ozm0MAbrYzk,iv:XM1jWeRHnYzKXCRU8T9B9+fX5HPfLMAOcYaamK0XffA=,tag:b0sGictIfcJtbN9sdEQ0ww==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:rcIlXQ1CGob3Ww==,iv:3MpB/qvlLNHzUSQS+SkPsu9srEcCx3h9B5cZPJyQFkM=,tag:DLwOWvn6mt52w+iCsjMaSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5V1JEN1VQNlhXelNBTVRi
            dVBHTCtqMUV1Sk9FOFFkZXV5NXUwVEZrYVFjCjNDQnNDOHZvczRub0krUThTbldj
            UE9OWlRUZjdDeEZUdGd3dWxxbE51bEEKLS0tIExOMXBMcXdnMXNIQktBUjE3WGc2
            WVB0WVBkS2FhdE93cjdydmdFZzRpTkEKZBD3UM3Y5JJf896slUYTNaYbkh4ubTLL
            7EUBV+QEm3+mU9+QHoMHxubnONkmTDSYZfLymTr4qVUl61Ropj9heg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:AHFepvVgWd5aiynU0wZcLs5BfD/Uu4qAhUdLjurqLExs/RO9M1TEiIAIoKeb9sNJaeVEwFTdvksp3a7hO5bp6yuNQey1CCUsdaiPnAiWHjFOPOC1vATGxcloj2fu29vs4yfYyK3EYxDht/5r9bCnvjRQngNO9Y2W1EqBGL6OK+s=,iv:E/DoO6VRQzPPInFcwEngdBA7cZugEfgSyuIB0volujg=,tag:CinEBId7RG/lAVgqxW/lAA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
