PUID: ENC[AES256_GCM,data:oLJGbA==,iv:NHQnbTzFr1BCVxpAKnBXh40ZrS1KkJ4fGIksYPUc5gw=,tag:styHLg9dbcsVnEUb5k2IUA==,type:str]
GUID: ENC[AES256_GCM,data:KxQqOA==,iv:eWYDGnnAYvqaR42uIay+FOFVDDYdpptsFNUbWulovb8=,tag:JFri7KsvTGWtGFCrt/4eBg==,type:str]
TZ: ENC[AES256_GCM,data:NAXJL4GoIyRQ2zYCWnLIj3JuZA==,iv:+MO0c1AsWjJSInC0rWE1rKE0Cdmb1B9Or8oRIl0FxJo=,tag:QddfpRJOWhT+LISguNGQVQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:5LBDFLq9rhS1111/KnfrbT/e3RTs,iv:ZPCI62EzbOcM1s75pFU3w25NaLkpUrDeeqQUHPpCV0I=,tag:sYbxfIiKmWzCCTycPA3ffQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:plmV1T5vuxkJNseS,iv:xDRZvdq3JX7EYyA3zeGcbo/C2iZBRzM7Glx8RNfmgBc=,tag:hQETG48hvpF31+Eb+M8BLw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:Sck7jbfmeFq0Gw==,iv:eEJ+tXvhfD6j32yYnQ/OvZbx3jmcYfULG5+xlKioGNU=,tag:0MYu1J1YKZ58FSRTfhEBUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRXlKcnZwMkU1ZUVBbTVI
            K1ozZno0NEc0MnVZaFpYRHY4WEVDdWpKNlhzCnY2STFJK2oyN01KeHNWbXBldHRn
            ZkdkZnZKdFNQejBQL25qN0w4MWNXamcKLS0tIEprOWhQTmEvdGZ1T0R3dFlHN0JS
            bDdRa2VqbUR0TG5VOEdRcncrSWx2UzgKzY4oLkk1pqkwOtMKtW7+5fBgviyj5V7g
            iFlnAjBnujeQ5LWSkGt8vHJO+Sb7wBHfdl8wALYB1xphAdyGfJYskg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:FsVAfRsiuzLvzFSZHgWe8pb9ZoW/M/2ROi2/RLh1ehalFqva4A6W/H+vrmNKbpuDfgpsnRoYU8EZFbdf91/DSYGV0KZhtBb3PebbmofQSe6R5obyCvh6WlX2eVJX2eZmnFtvQ7HYyuWLiFmLnOdEo2a4HYmic6ycn6N0nvVQ3wU=,iv:YZxZc2CehdK+Glb7f0aO6lQg7vmYV4nVXYwAy6jiGBA=,tag:sXYdiIp3ZtcEBaRc/MP4Pw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
