PUID: ENC[AES256_GCM,data:D8sA5A==,iv:57VGIR1la/IyvbnigkDByZu4cMHVrGFRXDZZ+SdLafw=,tag:FkPzNQeeVazY1VDenPbosw==,type:str]
GUID: ENC[AES256_GCM,data:soHTxg==,iv:+7DEpRCJNybdU/43U5diDpMcOCtgAVvxzNeAQ8WBFzg=,tag:/nsmirRD9Vsi6psEhz0a2A==,type:str]
TZ: ENC[AES256_GCM,data:AOpK4/d61Rvy1p6t01YEljaROw==,iv:cXY/j1Nax6Cr0RiOEOVh4SD6+IKucJxUyAQbJ3Tmuic=,tag:upfNp0IomhRB/LGGWQSSBw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:53lJebrUdF7Ueu8eY2GzHfXBjrlT,iv:zggWNt9kXODFuNQtH6MTN+YFgXhkR59Y9lj37M/8J7U=,tag:KQ+s7HZ857946IwvYPazmA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:yLrTkNgypTodvIrb,iv:uobXuvctJBpTUw+EIs8qFWwuTLch/nsPS1InxHIThoE=,tag:1atgXEoqyahJOsEXiX4DFw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:FwlFQfbUjprexg==,iv:xnYuNHFSH7rs9E1Eh+/zWRXLWHiGTY9FXjdr26aBGaw=,tag:MNyDh5t1yxoePJsxrfqQ5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMXNGUUFUdUsyYlVZNWs5
            TVJGRXJTczdXS2RuN1dUb2VIN0xHTFQvdkZVCms1azBBMTVJZERaUXV6VjNmL242
            NEdIcUtPdCt6WWljWVVtNjgwNDZ5T28KLS0tIGRpdURpMFlLQzMxcUIwZk9MdlRx
            TTRCSHN0RytlRFZST1ZQYzI3MWwzWWcKksdiV9y7s6uC3AyIc+nN/2qRaiRZz9p4
            ahEq5JrSuiYA63FaWntvWi3dwE7ZO56NxMXZo/7g4/IomcxzUQ7YwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:PT18W0hniIgesFGn79Fkqy2rCJFI56uigLTF0N9qoDSsu8Bse8E8KiaUHZDVrVAHaq5OkdVqF3Y3LMJMVzOdAM+UeGgvhalTMwl04z7o45NEYQ/sMee3qUCsY9/mt3DShEIyYzaY0MZ4ZV8K+PmcYlAkdpFbP4yN4LpVRz/S6c4=,iv:8I9cFTYqP1L+/6bdBjHb8rGhS/yw4XT329OCn67iUIk=,tag:K5bo14RRlNpaBYkuw1C8Dg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
