PUID: ENC[AES256_GCM,data:R4xASw==,iv:YGDNK9A5jblXnHx7H/NnKh8iItNPgQ+KydIPxN3Engk=,tag:ftJW+BVGCqsGLTYhYc65Rg==,type:str]
GUID: ENC[AES256_GCM,data:iPe3Tw==,iv:3Py4R6sIZAuEtWDFtJ23rCjTI0VNxS5LjcJA3D/eU7M=,tag:LNIY1dLam5iUVwX4badUmg==,type:str]
TZ: ENC[AES256_GCM,data:xcfvp1Rl4LSUyRT5NSd9C+iw3g==,iv:5D2Aa0qIYMbNirZOla7EH3yjrUUnSEyJ5lIYjI5rogc=,tag:0hkH9IbXKda0wnHf39rHrA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:28gram4/0gqQt3yOYI8OZXGrib5h,iv:T3OZbnLyoOI476wIU3Re5QOo8HGZY3myu+AonYO+Pkc=,tag:XFK8KXq5eAQDccQzY+nHDw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:V60ZAVMFLlUtPlLH,iv:Xc676rvRJRpe3It0e6j4bpoEY6Vmj2lK2I/rSlNSyj8=,tag:dxi/olqBirAgic76YnakGA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:7xkhoQIb0rOIVw==,iv:3N36seheB9cEMUxVKqiOZwfF7nJFYA1TE0fcJKXNwRI=,tag:S8nRN2Urd1kTuRnK9Ng6hw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTXdhYXBZMVBMSStIWkVr
            dGNDYm1xZjNVVVp2YU9BNmQwMlAwU0QzcEVFClgrbE9QZE9LeVBaMUxYaG4vRE02
            eU04dmlUY0U5bUd3RStjaEZjTTFZd0EKLS0tIFVicEozTldDbHhwLzZ5ckNzSTJa
            K2E0eVd4YmhVWUpLSXJQdmdxK0ZDWkEKme60N9GcjUsch/zWlZ6g686Q2EERxmfy
            e+0GjC4JK+Ujq1mpVLYi1ih3OLauHQ/T3DT18sN79aM/OIjxS72BzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:2M3m8qzdUe+dccXtms5OYtFrLfGwWfuKrlpPDPxZjqniknxv8jvvdl6vlkD+awWumzUgHLwbqQrSpbuhp0wuUzTIspioa3cWtgGmGGZXtKBwAazLGUqjl6l4fof4xIcAvQn8C8bJnGjFc2XvD66UGhjUWpQbVJgNyNTUug92OoA=,iv:ACt3uWfNX2Fua+EbVP3VGqAW3oU1wyrUi8DcMrdAa9o=,tag:rSnSoTD7sV/tNVZGQNMOEw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
