PUID: ENC[AES256_GCM,data:v2eHGA==,iv:ZU1+iAe912eMclvaqj6sPFWsZARNNehccSVa3f7V7pQ=,tag:k8cBaKbCdXAmoobjRed0yg==,type:str]
GUID: ENC[AES256_GCM,data:R6LSrQ==,iv:lxsnDc9ton9LBvhvRFguZnnXfQm3O8YJrUhtNlx8IuA=,tag:2P+4qlnHO9qhZKcoZpyFcQ==,type:str]
TZ: ENC[AES256_GCM,data:HrOsUyveCKdc1YKZQlthExBXBw==,iv:8nqEVZmQ5VOu+R3ckpi9INzfAYEzEN+aFo5jqlHwZAo=,tag:CKLYyNeZ8m7ZKCQrbTMaUQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:XV+4VcdAnBLR97Um6GSO4vKAUS9I,iv:ETXn5+pZo0U4k+stX3VuLYCps6BXeAs7D6QP8dVs05Q=,tag:7NRSpKBX1u1cwjWqQLKxoQ==,type:str]
PIA_USERNAME: ENC[AES256_GCM,data:MKeGyxNXZN4=,iv:bpZzwnc7NHWjAXoriffP1ANKFbtjcBN2jisazNxpIxw=,tag:SYVCY6h54jikjK+9PNDF8A==,type:str]
PIA_PASSWORD: ENC[AES256_GCM,data:VEaJOWUtVlhH0z4vjF4o,iv:4ME1W9VCbMxVx0DDpUfOQ/D19XpZ+aW/yUFnnOaYELg=,tag:t6t4/4QPb9gERWbCOxVq9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhM0w2OC9xZUUreWRPVGNI
            Y3BYZnAzUmZaRmtjZTEvc3R6TytRSkNKeldrClkxTk1ORzF6NUU4NDlWZktsMW5R
            MUZGNkRkZW1xRTcxelV2UE5LMkd4Z2MKLS0tIHUvdGZRL0ZHaWpVYlFwbzJ0amVa
            czF1MndNaUpXL1hhdmJQQWtnK21uNkUKg7PBzzC7be4T4YdCPMxe9MYhvTObmctH
            3jnsnTliDhQ4XadSU1x3KqJa0tgWYHCUOMabsbFWsMRQDhy5Lnbutw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:18Z"
    mac: ENC[AES256_GCM,data:5y0kMtRFDTUjt1wbfJLCVglZ28nGmmYTXMImvSaGGmEKMsRI1jT2gnmV6xLolNISY6Q8cU0x1agu3QTYgElxcVd1nCVjfR6/y44XWjwODj8P/C1LpFmjE7VFLOWRiz5QRjQ0V9bqdG3IamY0JIMJloAgpI/sjoSjRlGaK4+CO0Y=,iv:bqzl5ZszFWlIitO6dMViBoZeLcScI/WTMqGqGBEtdt0=,tag:nAyFZgRExXtHaQyYk9y97w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
