PUID: ENC[AES256_GCM,data:wRkecA==,iv:ewIdFwn4/m2cJKfyDrdI99i38jt+IWNZJLEo/BNcdVk=,tag:aVv/R8FmP2HqVzuUmjIenQ==,type:str]
GUID: ENC[AES256_GCM,data:X3ojQw==,iv:F/P/UaS/nLB8c7RRPMWvnCQ50DpmEhkxRviiYX8l/No=,tag:Re/ZTpcPDm63+KXILP8Siw==,type:str]
TZ: ENC[AES256_GCM,data:GX3KAXCaH/k7QZr0qSqcYNM6tA==,iv:HStKezV4kNoYS9wJ18MhbmKc3nz2lMCz3wUH1xUpv0Q=,tag:VSxgeQMwLVT1+dSYxHHUxA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:p3YSXzFTRBHbcpnWMR4JCKnhGhMs,iv:vh2DktBEjRuWXUv1XtWvdJd+aT2QlmLa3zP1Y2JgFc4=,tag:t04W1v9pCwHgpJo+WNy9oA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:MnIP5+UGo2sj7jlc,iv:s55dTaVKzOBWKeoXiHiMI9WR8koX7Pmc7tZ9/35dWtQ=,tag:YiZzmubrTVGwR3tBBcnUcg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:w/LODSFRY2UkTw==,iv:/i/Hqc/fGr44CbuS3MjqJXT7e+phf8sN4/EPRRDW9vw=,tag:XXp9mJqjMbTZDpT34pPnyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeVE3ZzlkanBmamJYeERq
            ckpmdHdqSWUvQnIwWlBUY0MvbC9FRnB5ZWhJCkZnVzRHcXZFYU95Q284K2wzSVN1
            QTBKSWlkMTV6bVVsZWUzcW9XaVlBOFkKLS0tIDd3aXdUZE5ZMitFRi96UUVQMXdH
            VmtFOTUzcFN6MWZzOU83WlM1RUdRdTAK7+Uq5khvC2oeGgqGbXKPVHqgZ1unwbL3
            c+LmEEe+Xjs0u0jjTncAyrqU1d0tv6Umb74bzHgIm1FQUcHcGwKwlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:bBUBWLWX25+bSlig0ug8WASKzx8nVA0wgeMXBUh/VdVXwvjlCXIqAVj4kELCc3v8EWU08tRrz80NSNsNqRwbk2t0iEh2NCpy2OzzX5XO2dAOrm1nNn2MXAHuXt4Ze2NA3+s/Ec82ur0X18h1i6QrkfeNNPaTEVGuRGntMTGBw88=,iv:F5QmdMkAHLSrmYSj19+RIX6AZSZ/K6KjLkc1BwCyd9I=,tag:OmN4qP4YZORvuStqn11R5Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
