PUID: ENC[AES256_GCM,data:6ELwUw==,iv:ohjpNkNpU72aAdQxOXfS3zXCGThnLTScN9LjLgszCJw=,tag:CUuuuEVBDGANy1OXa1HX0Q==,type:str]
GUID: ENC[AES256_GCM,data:S7EF9Q==,iv:RM0jDCYZ7MbQcrTR6TJzotdSH9MOk+Ovo49KFy5gaHI=,tag:VApFkn/qCxSSISYgf8U1wg==,type:str]
TZ: ENC[AES256_GCM,data:RgKxhOl3m75KoSPWjFK+xwGOFw==,iv:6Ls4mBPY5FlRRZHBk1Utk8yF+QkEplri+aG6Uwt0onU=,tag:jOEAGlvBlVeBgdAKudkQXQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:gJC75090OWw+208yWIRnNhcgDGdU,iv:Ri2EkzNKlIrsV4Joev4B+O3/f/R6KfyX838IVxgAf2I=,tag:dymYS9kOQvnz5uAIax1IxA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:CmOZtMIrHU1hZzd3,iv:H4IhbkNW1Ars4PTh2LXGGL2hMm/8AZz/sEo0CT9GdqY=,tag:Fq6Hzrhbq1HkC0hhgH7q9g==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:uGmzyQzG5ZocEA==,iv:HiPvQ+1s6zWvSY9QHBVFAPWcNaG5apHn+rLsyx9EKS4=,tag:Q6HViLznbvNuxUTyQ7QcTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbEtaVkNYTGcxOGJXS0N4
            ay8zekZXYW9yQ3JnZy91d2owY1JYa0ZqSjBJCmhDN3ZGdTNHRnFKNWoxTlZwVCtK
            S3pqTHlqKzk1N09JTThQNE5Ma0wzaDgKLS0tIExHMHNsdUJDQ0Y4SDJCTEVHT3lY
            TGtVK1hrTHhOVHJ1SjFZWGNyc3pNcEUKYAqiQXIVMGG/56hka2eznwmRjnR6tKBb
            IyeyWErIasXqRh0uEQJVH6QnBEwHUNiEfHnu5opd39Ui/E3CdiXErg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:wkyLHcDon1YinVHu0HtsthfaOFn6UfE8FSgEpGIGcoE6wHcuxmywezVBfqhWDcjlkb/22u+Du2Y6p2zc8vnOPjor1qsiezoiphqs9DlZRxfrFdTBRSP4pq0/l84DXYnTGSbYTf4+a8TrzHajFBlZOUAgKbHi1kip+vxf2LwKdME=,iv:c0xm/Dh2nWwBUNBI1fWzhVnEdqYcga1Xff+1Y25Orr8=,tag:bORbWlf75XwxK/gXaa7r3A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
