PUID: ENC[AES256_GCM,data:lVJwqA==,iv:aaU+WXVuytpZtTDCvaUNKnEerlYfyPJoShIA6wzcOMY=,tag:c8vdulz9V2QYSZPIJj8a/Q==,type:str]
GUID: ENC[AES256_GCM,data:ojAJpw==,iv:+WLfd2dUG+j0GUjz3aOpYcGGlB6pZQOVI4BdFnDwU7Y=,tag:Wljd2ziPt7GO61DPCaxeRg==,type:str]
TZ: ENC[AES256_GCM,data:StqWJi1fvHvNT7KyMlKra7547w==,iv:aJe2heJ/QQz+5oUXsE/rf1GKAQn+WdkaiJ9NcdqtaX0=,tag:255uTtltTzZk2MwFwZG8Xw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:1ShNSbe47jk+qUZP3Y0FY3YkUi9B,iv:rbGOev9XdhcPP+uBX3CIRZcBhUWzAJ63O2pZOFqUTkY=,tag:Lxattf4WthlaDIuuQLPzKA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:B/4CiNEb++JH5kMn,iv:OHGBLSKk8sQvSUslGTodx+uOXnIXOQPntJgIMBB88Ig=,tag:xL0VzHnx0k+nP3W1x3T8Pw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:CSx8IBDFh/BlbQ==,iv:rBoJOz3/HLyLSpjAut2Kh4Sjp0/z4jojnQAzjF8XUtY=,tag:SYdPGKF+BwhFc9+vF6Hg3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVzBKb1RDUG54Z3R6ekhJ
            bHJIQ1pOL0xyOVFueWVVbHVJVEJDZnY0bXhjCnVSWUFuK211WlFyQUs1NTFZcTV6
            cW04Z251cTZ0VDNvK0JXV0dNTU1aTVEKLS0tIFBVMFNjUGVtUEFYRjBtaWMzT0tY
            STE5S2QzS0pxNEdma3FFL0poenBSQ1kKBq+7zWEXHq0LKoHk3mHnWG45Lz9lTjFH
            0oYsVueaFQKyJUlVAuaylQScb4yKjg0mNKuAvGt/M4P0jl6eJCRn3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T18:25:26Z"
    mac: ENC[AES256_GCM,data:NDKU4dt9h3xixvhNMS4CxH91mojY48WPxLTuPtKG0YRqnHE5GVzdLaM66VNwVzQS1j/98u7JZkVlyVBJYJsPE2p8508UBnFiKLLNS97YaQ2+/a9hd+7QZSQrHKNARx6J9yLK5nClm3TqmSwtt+gkXYjohA/qncZk0Uv9QFQMGps=,iv:9htG+3kciA4+042Hj3nS6b1R8zmfp5EB0Rmg5COcLN8=,tag:x/unrW5FMDb6ceRE1To9og==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
