PUID: ENC[AES256_GCM,data:ljJMdw==,iv:Nx9zVcpPE681fGqwEX3ZD2ABeIXj46cFHpoFr87+KM8=,tag:B4A82zXNQpvcdBi43/TX/A==,type:str]
GUID: ENC[AES256_GCM,data:uODvbQ==,iv:sxSnsgZFWA/E+fSVq328Nc12PSaVobJHIlvvckG4zS0=,tag:dA5/kz+Zpo50VprgXffwaA==,type:str]
TZ: ENC[AES256_GCM,data:FGNvpMMJcfDBSN0gNAtHAAUkGg==,iv:Jnwera7S8HTSoNfTziNKLv/H3X1GGpdA2QN8A/B3gNg=,tag:sBLjNNC1c44Ok7xwUE3UVw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:52NMSiV5Usmb4svJ0ZOZUZJHTcA8,iv:WZ6PZ/vOoUKEiarsdotsubvGascTCUnniinAQ5avAhA=,tag:XQ1bxNMpvU5412rZs1b4bg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:di9MQA1I7jqR3YW8,iv:Cr52yT/VA1k+A48h0Upt1n30vGi6i10TS7eOEXmvryM=,tag:1xM8veeaT2WEyOFvBHrD/g==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:23dwzIZ/+W8swg==,iv:2kQ9yLVTkigWVGTAgYz/mR8us11gcyutSMyZKIEh+N0=,tag:EUqUuDCRVFiwbsDSpafbew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNUpHeWZlNDhZY3FTR0ND
            VzdRZVdnUnplM3FNWm5tZTZuZ0dHc1ZmS2lJCjY5V1g3QzJ4WDRrclRPL1VCdHdV
            QUJmMXgwVkM4ZERqQ3B4RnRXNnpWN0UKLS0tIFJCa0E4QXowWGw3MWNGc1JKbllU
            K3RDR3JvNExvMnN3dzZMTUVkeU9jclUK5lexUNzxURLPEyZ2neiTQdspm9MuZGFd
            RzXOzbhq8V7VYMG9c4JSZNXt3Y5w4jVLNmGSp/hptI6ZXCfJH5ctUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:rF2AApTUcQk0yRYx7uj9vFKFiFfatwe6qF7e8nHgOmqQ6NCiiwN37/VH6jUFg3IgPgrLetuZH4shbUCC2c9XBdSMAKpj66z1jQPs5Kfl3TJgWzDKobRsTFxLAGfqnN2Qf/w6GQrbp7DLCK8yxeHvxPsZEUx3cLVE9bOtEs+lI80=,iv:CJ4zHiPYRCJQZGN/MNr9bc1bX12uZIrjZoU9rdqe5+s=,tag:RgsoRBEgweLWvGKsxHkzlA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
