PUID: ENC[AES256_GCM,data:Timzzw==,iv:hzMOhmyLQMd09evCyuMk+bKa62k/dAB0JEeGo6WojaM=,tag:hsFJRhbZdSEs64EbGqjJyw==,type:str]
GUID: ENC[AES256_GCM,data:rSVugg==,iv:ggehOP/hm061yxQgrD6Qfsf6YUQwIK3YKKxSP6JPzro=,tag:1iUWGmmwBqb0sGzlGiGnDA==,type:str]
TZ: ENC[AES256_GCM,data:KIcozS3AQ5KxZbf8ZSBiN1vRhQ==,iv:viRj+WqcQADzN7bpiem8OBlLWx/tu0NQwTLc4sh6XRg=,tag:hbKTnAr3JAjVS6KUHGC04g==,type:str]
BASE_PATH: ENC[AES256_GCM,data:YjwYpAgQQV0I8dQv+eGSzaPpO9u1,iv:lQHgPyzH9iIKS+F4m9qUZwffI8uczNS3oxaAWVF/3Z4=,tag:t1ewGIvY4Y28+UxKv0Y9lg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:KBbbccVoXkBQUiJ4,iv:leNGaL6cvB9UTayTQshhQHWb/iwHf7YTolg8w1JF6tQ=,tag:GwoQ3JGzjh9Zmo4tZC3qdw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:hdsq1AoRbjpOMQ==,iv:IU3lk1hputKcm3RbgBTbqMIMIpyyXeM2IiAPwht7U10=,tag:JI6N1ijfBJtySC01snh8YQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWTdVbnJIRnhnaW9WNHZr
            ZGY3QmkyRHZ2NE9uV3FhUWN2TE9TME9DeVJBCjBhZXpaNGszdS9RUnZ2eG84em93
            VUtBMmhZV3d2bWdaMktDL1FHS3QwZWcKLS0tIGdlTmZhSXdjb2ZFOWJXYVZPN2J3
            elpNOExHS2RNTTZsLzJOWEJTVWYvTFkKmE9l9TDxi1Oe5v+FoHE6LV8vZt76mvCz
            ceJibvYyQaL+XOFb/gtEvxvt+kRH+FjaFOiLXkvkkWKgNMnj4aXiLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:lOUg3iCd0FzxdBv0kBch4lR+1qEUzOY/sP0zjBOBffD48ZElqFMW35Nw0r++MHhH/NU75tEGnehWRBX/Ct+UkBGUpmSwR0cq97GnZspbrtmArMT9DdNyi6BQ/Vq80p76cneHgwP9uNfRkH4Ex7I1FtBhF3yuUlvjFFrhIaKA1Nk=,iv:0uHO0k9s2/Spt4F6ESoAWkQpcviKz1HU+6T6CVmMJdc=,tag:1Cf8xBHAMhQGVPzHFE7VMA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
