PUID: ENC[AES256_GCM,data:sPvZew==,iv:fYqezt2KldnqpJAx+uE9ensMu0toxTANIYqD0z14Fco=,tag:f4SieJpNhtLXOnOEUAXDzw==,type:str]
GUID: ENC[AES256_GCM,data:2IezdQ==,iv:yeMIgxhIu5MgTR2r7dEBUfRXrHKbl1k3lC+gOsVqqX8=,tag:rT5EESmWG0bQusCwM/m3Iw==,type:str]
TZ: ENC[AES256_GCM,data:tRSqUB5JOouR46AdbLN1czAr6g==,iv:ibdUU9RxFV+ONltZe9BHsznB6/0wT07gOwniiXZURow=,tag:MWmnW5qilY4kgY1M11tVUQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:qUZVjAiyv/bbPwZmSWYqGWoHDJ2a,iv:JYn3a5sp1qMz8o5EdyH53w6XxzwljO/0VLvW+HHGSos=,tag:zMimhSjVKx8A/+jSpL2kwg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:Ztk9dKL0i+3/jR4Q,iv:DGJc3uvyMLcc2wqx1k9YotAEcUMSQ0viCHbig8H0nS0=,tag:JktzqjTs9K8fpWCBsHnarg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:j6WTz+9BPv60sQ==,iv:oS09AKcPlpowZoh4lSTfh4bKsx2/sSyspGTh62Sqm9I=,tag:76lPly4VwlXkmPIqR0ycGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVjcvME42eGpOeDJVV1dY
            L3cvcVFyS3dNVHUySnRPY01RY0c4dEFGdzI4CjcyNDkwdEJlRkdVN25SWTc2SXRy
            WjRBekFEblY1MDZCWmdxVzlmdTRBbWMKLS0tIFM1OGhXMVJyN3ZBVm54Ym81bndZ
            ZERkUFpzckJYY3JJUzgzUG1tSDBkVjgKgYPcckgxRuWn63I5S59KnpNWNV+wKnYv
            5ippjwtPXnaANzg9DFU+xQWV4wFQ5MqdvXcIwVQhzsNZSw8nLho38w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T18:25:26Z"
    mac: ENC[AES256_GCM,data:KyNCAhMenGWSaBExHKUhlXfgm1UHpUjNjYM5D962845Z3zVVFHItxRQXbpXt/EOTO3mqYtJW1cUdh5LJ0zoB3GxQXMPrSSomc7rsQfPLo707MRdjAoTeCo5j5ynGhWhfY/NlSBuDzYt5mcKKIts7UcAqYIAPG6b+kqqA4z4w6U0=,iv:NX5fDFRwTFyDW2ix0d0kghvvnnc1T8RqiXSLmmWh8P4=,tag:f9wMkMnKejANO6U6SUPOGg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
