CF_API_KEY: ENC[AES256_GCM,data:cwZTuvbCfCuVxnR2yX/PYnLjH2MGPR97gIWSF6oI/uAEC2MR0Tl/qA==,iv:q7OQ8pUm9ZFdKpkmisWqIVufJ7dOdh6DtYMPk0QMGk0=,tag:oVMpiIzrqzlqKuT+Vw6OAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwN3Z0K256eE1CL09GWlJn
            UDNUQzVZbzVlemNRYk9FbWhmYmhWRElEUkZzCk1MWTdUS3BsYzVHTkR1REhidFZJ
            UmlLREw0ay8yOXJnMkVNRHRoT0JuMkEKLS0tIGF5YnJnOXlXRWRFalFCVC9XNXIr
            cHZoY3hqOUswUXNKV00rbWg0dGpWd1UKwCK4a5yeZNoamUV5mribL0nqFWkQbRhj
            iAWNj7O47QEAQR5/Te+Vz3FlKJoDES7dp25RefZnTJVcEMIPQvPbJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:06Z"
    mac: ENC[AES256_GCM,data:Zt+Cw0+hmWjC7AAS5obkC0+/dHzg5LAKieZK4/gDSi1qFv186s30SD9qwsr6hG7Toxdp5E+GzhcQTQFXy9QTFi4mF2lljhWiwpb327EuGIhgRA3DYsihfeWmXAAG+GIJIf7CoqdvbbVkDoPixYsERR7zRw4x3hCdRj1SDmdThOM=,iv:puobJ5EAVCuQF1PPDCx39aSjyShuJgRml0dx5KBaLWI=,tag:gFyVOAR6YqfKnwMmTII+Qg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
