CF_API_KEY: ENC[AES256_GCM,data:xJmOqmB/0YFUaEidVZ8CgmRJi9OFlytCglev8P9ypaczsnFX8KZjdw==,iv:rRMYsVaueCg+ISwdhROsebFZ26rBIzZA4efvPn9xSDo=,tag:jgDa+wRD6BTHr6ehcT5hfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOHN2TkJHcUdkM1g2TmxT
            Y25OTjBwQ3ZPS2FqUVdRZkhIc0Z5a2JPUkM4Cjk2YW9NZnIwaDloN3BXcWlPV1VF
            S1FjOFZVTjNRT1YrOGIyd3g3ZHp4MmcKLS0tIEZ0ZFlya0ZhaDhKc3dLcWcvOTh1
            Ri90Rm95NFd4MWtxZEk3ZVdoVmRVV3cKCVEzafxnL17rRaQZmjZ8j+nS/gAxRsTS
            LdLwEUos9OabS9IJ+2Dwnukpb93J794qcjD/wuce4PeQXpW5KVMp9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:4EEWr6rLyXppSwZEJg/IU1IdZplL7V3tDiINrr8suKOPPwnKsx4OyRGnuOYKWwe2UwiUyhAuQOl5yMnGW+aWwypDirRodebnUrpyxNehRdCEKR/bx4VDHspeD7GVorjRQisBaD97S83YQSJoCQu4WutEpxHgcxs/uMPdjaMJx/0=,iv:yAs2fOwcOgUawL0xgQevcvCYzbfmdQjCD5TFZ9L3Buk=,tag:P83Y8Z4LrJaKvN5z0of43w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
