CF_API_KEY: ENC[AES256_GCM,data:rVWoTc6e1hbJmhFpsButuFKFZa5OEfk1YoCszlrexvKOR77EqwkcMA==,iv:apNGpHnea6q+V6F6NIZPDX+hhp3NX86Dw3ThZOmG/F8=,tag:Hqc/jmOFiF3Gpmm6f8Vzyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOFdIdnQ0MDFKZ1A4Mllu
            NW5tZXVlUDA2NGtyYTMrOE5zYmFlc0ZSTUdBCjNwcGRSRm1Wbkh3WFRNd09RNHZz
            OUlBcDBrS2o1OTFRbzc0aHAzSE9vTkUKLS0tIHo5NVY3elRya1AwTzZYTkcvTVRZ
            ak1ZRWMzNnlPWUdqZ2VuOTNmOEF0RHcKY6uPsvVrNiDf+ugyC5DlTkXYBdqPSkF2
            zlDYlHWZ52HSoCb+smewoTwIFM9HMM35PYo6h7C/g4Y/GHmeAgCuAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:08Z"
    mac: ENC[AES256_GCM,data:03nNdBzpP9IbVNZr8QcPOvu+rdnZSFf5dvstL15Jxup6QqAD9h+ChUl5U3zlLQZlTibGqA36zjY/rk1htfoBcmWpzNUMzPDsgJM/W86RahAoZKYpVBPNsRGjpNL35Xe5ZSZTZ8Wlokqp7cee0u5EFhD4wllwnV1KzAHUGanuank=,iv:VjnsCwdtPNPzLQb/DPEcAoJS6g8i+PcCeF5Y7+AFzGE=,tag:qSy8jh3D77RF2mqVsIYF+g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
