PUID: ENC[AES256_GCM,data:afrGyg==,iv:oC08kuRr0F43r8Rzums5mhpG1y3d9MSlBHh1F6CgaYc=,tag:PSjXKwY6O5HAZXleV8sLHw==,type:str]
GUID: ENC[AES256_GCM,data:qYCRxw==,iv:PVEsPibKGrEhwdiQqrmIGLfWPdP7HgvM8XXJKhB93wM=,tag:h7zvRTzt/BwnUIsgI7FvoA==,type:str]
TZ: ENC[AES256_GCM,data:6Slgb1gobo97Wnr80nTpBa8e4w==,iv:5AtFniF6wQk+jfKSJhJaSliBv9GgjcJXKGL4a4cTWK8=,tag:ozgxa2UBvvUUck/EwsF5FA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:W/R3YSipYVTIfUYxpG+SMKnuQ8Xe,iv:hP40TeechiFQIkltJxB4E4OQFpant5ci9rFHDhfOH5g=,tag:EyeuqZvvFW+HS59gtyc92w==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:dek8WYxTYtXjDznv,iv:EuSMTwIizvDDDP18bMmulFHWEZyVuzyM0Dy/EWitXZ0=,tag:OT/4ex2Z0jkvkzOZGXwpcQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:88zR4A7SdQt6pw==,iv:Ho5F802kNFgu/UzlwjkgEB7C7SLt8HzEdlT11EZdeMQ=,tag:VcrVL8IVVGlyzFV6TR+/lg==,type:str]
PIA_USER: ENC[AES256_GCM,data:RoV2g+Bdlkw=,iv:aHRPe1bhu8ffCDbXyHQqQ0nJHiYMMfl8N/7YCzDt2hY=,tag:bePsuXqtMRiVZkNFFEHPzQ==,type:str]
PIA_PASS: ENC[AES256_GCM,data:VlNS182yLMIr7jKmz3jH,iv:bYSObo/nZ5bVyKqJIRUz65Jzj2Dm8jYCEnasZO9oG+Y=,tag:PQc/d3wJItezGjvgUkmuFg==,type:str]
QBIT_USER: ENC[AES256_GCM,data:FhZ5OiSccOM=,iv:z/4JNFI7ZcUTdD4zFhsen9dGh6ZTk9qBtk7ORF5N3MU=,tag:WZz35fiLsfXRzP6jMRjXKg==,type:str]
QBIT_PASS: ENC[AES256_GCM,data:XTYT/aqefVNm2A==,iv:fYK3g8sKemSINwMS8vwTFj1XC6UWcKKBUQIKCETm5mc=,tag:UyRdLZtEe2mFnqpdao4vdw==,type:str]
QBIT_IP: ENC[AES256_GCM,data:JP0g96KagEmTKCj19OUMiMs=,iv:V4uj7/2x3uzHpaYTl7qIEBCaJdpFX5vVVqvBdJBUI3A=,tag:oKhcpvhTsTq+TGPanHsfaQ==,type:str]
CBRE_USER: ENC[AES256_GCM,data:AxQcHAtAJJY=,iv:3Kmb9pZs9IBDAL8O4nFAuV6VtKWBAwtWqgRXW9I3C/U=,tag:4KuAL4qR4IYY8NbPxD6jcw==,type:str]
CBRE_PASS: ENC[AES256_GCM,data:zVDz0P+bscYRxA==,iv:4Jm8Xfo1yA7V4HAIc0WYQubaBcnXurFK5ZMJ/tmbX7U=,tag:P9htIT2W/SxA0uk4tfGQoA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaG9Rc2w3NS9EclBWcVhi
            ODhQd1BTaGhBd0ZTM1Y1RW5lQjJVYzBjRG1vClZKMjVhaWxzeXRHQUhSRXZPTzN4
            TmtPWGlFZXFSVFdDMXMzY083eGhsVzgKLS0tIFRqK3crSmxYdUx3Z0ljS08vaTJz
            eHQ1UStsVithTkRmTE01ajd1TVozWkkKE6MsY3zbjfSDX0PohHs1vWMd9QG1IvsI
            ULBTExikXUdKK9wQTcYTzMGRu/ybdUDW9Sh2sjreP3dvZwnYCrb5Yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:18Z"
    mac: ENC[AES256_GCM,data:G14wlM5c10v86K08BUvcjQXkY6PXU/JJXKenYCExuNzpjiE6W43bPFkwpNnSpu7Z25ywrfu0UAD+O1VAsY8z2r6S/JrO2mHpuKR9GYSmiKLe1E2fDmu/5qcbHB9MawX5WUiAjR35rw3GCRuP6RCNuh7fEQ3LZ1V/hpjJ7oEV/XU=,iv:bC9/BkjZZEkuu/Cn8qGUvucMav6gw2c2g2hJtDIIczU=,tag:RWstfBE9F+nT68tv1V8r8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
