PUID: ENC[AES256_GCM,data:edLDVA==,iv:RJ1kr6JgE06yGBqH1zCRwFfrUclhjKzRXKAIHeVYsNI=,tag:yCNse5CLnKnRtuEnAmG5iw==,type:str]
GUID: ENC[AES256_GCM,data:OWTDjQ==,iv:d3bHBs1oBInZ54kkxgtPBO5pYT6PyrvOhY+TruAw3J8=,tag:cc07x6BV9PFIO/MOIzGnZQ==,type:str]
TZ: ENC[AES256_GCM,data:L9+jC3VefvMJCbpnUQjHlISDFA==,iv:giprZl1CSvIyk9AnI6g098AkKhXc6Yn5NX2dgQvRm9k=,tag:iznPJ8Sn/dEe7PTmBMxPfA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:wttOlph5KhGuuhcnEjpUwQVxG9BQ,iv:6iqKT7av3u9TNxeC6SU6sfZgjz6oRkS5TX9k8z82tTk=,tag:Y7JveRiLPsrLmCmGDSlGUQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:Pga916nuWSAd05ad,iv:QrXhNeFruojPeV1BPW5HKxzBqCI0WTmcdntw2ZQH4kA=,tag:RAaSQ0YFuM+tm00BfMT0eA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:cST2Vd67Tqe7Eg==,iv:/CCzZ2MMWBbTIe+g5eFnd2WWHdMmH3VI0OpAq/1UjHU=,tag:BObxcFKUm2WFyCijsXPMZQ==,type:str]
PIA_USER: ENC[AES256_GCM,data:x1iYzdNtyyc=,iv:qiCUmJliNd5CKNuP1GXnpgmQnx2wThMSiWCr5afuxGg=,tag:sQU8A7sL9iR6WWKuQILUXg==,type:str]
PIA_PASS: ENC[AES256_GCM,data:FpoO6JRe2mzdAOZkSHfz,iv:okXSWmeMxY+L8dhChWqddk/TXmWTQS9+jGmvYBAQ9mY=,tag:Z9irAv/IEiRVwtHHHeub+A==,type:str]
QBIT_USER: ENC[AES256_GCM,data:x3ou/lQp6XY=,iv:Rn2MaoF6+xU93qquAW5ZTThyFdkPqzC7s7R7v1a4vm4=,tag:KfJYnVr3Yn5Z1SjxElZ82Q==,type:str]
QBIT_PASS: ENC[AES256_GCM,data:NcxE7hfKBLUTLw==,iv:XRDHZ1dygfteeWuASKC9HDjy8NZ3p9dKyJi++fbNeDM=,tag:i2sw2Egh7/pqcB1iqEAV8A==,type:str]
QBIT_IP: ENC[AES256_GCM,data:S8cGuCIvf5gn0kTP/iv7Mj4=,iv:r4hnk1VzhNyWkGI3G1Q25JPtGBVzPnobvvl2gfTRKP8=,tag:so941ZJjxrnsazDjCIn5lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNGR4Y1dWRjVjcC9nME9J
            UFd3NUlSUFRjWWRDN1hENEtmNjEydUd5TlVVCmRyMmdYSGhLR1B6cTVDSVR3TUxz
            ekJFeitmdlYvUVVKeFJNRmZabWxYSncKLS0tIFJ5WkZlaEVrREt5SVZiSFJ4aG9W
            cXhPM1JmTk4wbUVUYWU0TUtXdWROeWMKKKH2HHSa1su+NUncujzxiIppUhT6ExP+
            1s6ODbCcYw/EEsFWjp8qbyIBvK61UMcMPw22FnBnlEEerdoDrCr3Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:KyCO08gry9aIKPZED0IIK6CTkr2W9r3GDRdD847GyZ2C2LgLcpD29ifugyTIdzgjDfqZ+60gTswZL3jVJsPaadGwIqGaErAY+9ZSXyFvyPLAlrIBw11RGKEnC4F43QJNnte4dK7tD5UpAikVfAqIvfzvDi8ID2vBHmtuWv98WGM=,iv:09wxaxQU2Gy2FjQUJ2JnzgUJypEUZXvKIp258Ghuuok=,tag:JDJcniAwwFo2kPp8lr/uEw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
