PUID: ENC[AES256_GCM,data:dnCAUw==,iv:pFN63KyaIaa3pYZU0cZm36CRZzp7tXhH6lGcHCmtJy4=,tag:r3z4R3iIliwSJAHBNmoQmw==,type:str]
GUID: ENC[AES256_GCM,data:LMsmPg==,iv:cfVywOJ7jtrIbFqEyIcqJMP07Arv3tUdfNhdG7ixD3c=,tag:T8rUe5hvyakN2DtfV0v2uQ==,type:str]
TZ: ENC[AES256_GCM,data:IY36U9+tmcLmuTy+MLUTzhS3nw==,iv:N9ZJSASwfVRKZYJkKFi6qJlnaTWRhPIGxfQKRprJjz4=,tag:iV5nTfS9vuAO/4eSmxHnkQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:h8C2vPeQ74bF0APLId75ID5v1uht,iv:uENCyXp49BZ/bRl0f0D2SrtJbzukmKRlNqaS1lwpTfw=,tag:oY7/vj2l2D01YnWhdEEeOw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:nDvicHgqz+igm6zE,iv:/aGMgr0rq26YzJqtLtLquieD0AC+dlLdI6+okez8afI=,tag:VWnuuVOYzfYBUTn338+E+g==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:pxiiMz7sXUsjpA==,iv:CjEJxMaMn0MHofPxIuzOnpojfTgyH4XzZG1BIjsirSU=,tag:xZChoh8+I8hGVFM71sSJKg==,type:str]
PIA_USER: ENC[AES256_GCM,data:tGc/3MUxI64=,iv:cHKvMkH1SloDUlAj+pDNGCnZ54E6ZETN3k2iUPzizBc=,tag:3foQgFosheuAClKoVzmbUA==,type:str]
PIA_PASS: ENC[AES256_GCM,data:BFgdGk1Q6TsLpZHF6qcM,iv:F27uSRrsaZTvpu6P0teOGeW94h8Ja/egOWAVZTXDBu8=,tag:Bd72yOM60XP6LP29GwSFIA==,type:str]
QBIT_USER: ENC[AES256_GCM,data:waKKykHtuXA=,iv:8ckGan1/uhzYmV5s2yMcrLzq2H/Ijt16K3ipa8LnbAY=,tag:VIv/3Ux0JKM3+l9RzH3i1w==,type:str]
QBIT_PASS: ENC[AES256_GCM,data:Tl/PQCCLLrnXrQ==,iv:j4sRAhe26jNgzFMxfuPWIJdmU9LrxMZi1oe1WGxptMM=,tag:8Sy3rL/+5D1lyrpFxu2YTw==,type:str]
QBIT_IP: ENC[AES256_GCM,data:oFF/BZh+KZlSnB17yNrHVFY=,iv:bA8TCZVkJRc65ezTcCJWqhLegh+3GbP/hJiF4BSJ8SE=,tag:eluqZpXolu7NsttbeS1Czg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWEN0Ym94SnBMSnFQU3M3
            QzZGQUhmWXhwbkw3cTZpZFhpQkZCQTZ4U0ZjCnpwOEJBUW15NXAxYVc3WUVYVysr
            ZCtNVU1NbmVZQ0xxZTJ3UGVtT0g0R28KLS0tIGN1R1c1SGhzZVI0cWtIa0pXRDc5
            ZldKYjE3TTJHRURSekNLVzZ5a2xQY00KwjokXC5RCotPE/k46ocbVoJPTvJld7l6
            ahgLST1T0JY+2Wr6Oxv5WOhVGsWhlE8VOdSrIdxvZM6qNKSdVVutiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:FyasK7Wd+f3eHQ+eIBEQ3p+xN1njDqAGdaMEz6hmfRB3HiIORapfhda+EdU+xoKeQKGKCs2br/HRLnQGeKRO3E+Iz8EG3ZOt2ZQUwwtx8Cha2XPrvtbOHCSxSDBXDLZNxwNLY2SidDCURQun1l3l4AUFaP4hCv7KhTRyZlksMIQ=,iv:a+PnMYXioQxIEPiqLXuEqowA5zq71/QOTESGLH0+HGc=,tag:n7/LAXOz83q5slWGphVznQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
