CF_API_KEY: ENC[AES256_GCM,data:ZFj0heEaUDh4PMQHn1bPxyKkLrtuWv1guA/4ONAnd+BetKNv7lC+eA==,iv:/YJXftxeniEmzcLoowbX/O8TVuNsHcn+ex1S7ThfR5U=,tag:XpnX5sXXEfToD2McXPlJcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUDQ4Qm1wdDFPWlh6SHY3
            SW1UVTRINUplNjdwVUx1QzZTdUZCcy9FUUdvCnJNdVBiRmpuRllsTnRxT09UM2w4
            NnhlVXVnOWVGbWJJbDFRNWxTeVo5cDAKLS0tIGo4cXFZZDh3V3VsZk40Y3RFVVdr
            SHJHTk5PSk5DNUVtUEZYQzh1WnJES3MKIOflabNFVjkC4MQRdaq7o8lmFdrv6Qcg
            bzbiYAmMmVq1wN/t3qJTlnKgT1z/qT71loq7q8kbI3TKFTDr80EgGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:RZO6oSz/K4JFF/pyTntkOOS6N5qAtzEA3L7t7XUPpxHJ5A5IahrSTPVMSKsgu+YXi1Zv5RFPuUb5Xi6H/o/41QW6lPlXcOqx9URhT4u0bMqOgEURDOtwhgnTA7UNJohbT5NyvjAfXinGGKhcwfgY0e2svtNpMcOMxdjVGvW676U=,iv:sWfa7OjvpPjvXqraomNJ+VpoLAWJF8muNtXD2MmSYZY=,tag:SUc2E2WMjOOkx4Y6cm4I9Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
