CF_API_KEY: ENC[AES256_GCM,data:SmFnWLMRfolHdoJLYjBanHyOPLnv0cFGEL0p+tffLNxDMMANJsTk3w==,iv:m22uU/9YnV9GPGIRictGPwT5Nm17YBrxP/XUphInft0=,tag:on2frqyKZwnJsAPlfdqLTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWTNPZWU0S2JTNnZodDda
            Wi9NUGxwSkswSXFqdytVYWRvSVVhckE1bEdFClVCaGVNRFUzeEczbmVGcURXV2ZW
            L3pXamI4TVJkbjRwMHIvcTVCNnNaRTAKLS0tIFVNUUZDM2NDNW4vSDVwazRvNHZa
            VXM1YVdMemtncXM4c0tZdFV3MGljSGMKgyuXawJBNnMSnEtQ9mECUAX/mIb/eWNT
            W8Ur8CfV3DoO/OmT6NN1sRTPnDwXMTBr6+sKUI6oLwLRmcWw+NX/Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:1mpLYNvcsxO1Ntrz81iZKL738DXVbRqw9a7bGCVmnMxZTbhOU3Mp/rDVhcO9a6/MwFgoQ3chutH0zywWczj5Wh+WKSwfMtbAxKeRfdJlsSWgt1EYCsy/GIXCt6uggvKbtDAbpbA8DXaJcQsGkHekkhJSmluc4IPhPYuIJ42rbv4=,iv:p2T9L/56wp7dwYj8cRFnO2at61200mhDUNPe3tt3WKA=,tag:i7wtKPErzubcqM+o6Ovejw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
