PUID: ENC[AES256_GCM,data:lpSuSg==,iv:bYbMoynIILTCvcLjPkFtYHJC0hGWLjtrwwFWwInGvgw=,tag:d06e+PtCSFrcNeZCVd/qaQ==,type:str]
GUID: ENC[AES256_GCM,data:fpyVxQ==,iv:+RFM78a1wPI4Rm1DttEha8sdrGVgdFa95ZymqIieC3s=,tag:TW2WmEU7cSFLJmN9wSrqeQ==,type:str]
TZ: ENC[AES256_GCM,data:aE4vhqfgjpUKFVvL9NzCXunFSQ==,iv:FkaviaT99s1r47nqJkYq2fZjRG/uGt2bhfqnaxcbFQM=,tag:+l4G+ikcck/h2xOWjI3gGg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:/MVO+DISaeT3pursofDbZKGKvE6b,iv:L5cm0pFkXnEFAZ5XIOqCiHWvFWYN9o5gZWQKX2WSN4Y=,tag:ADa7Tp3YLgDUyE4/Ls9sZQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:+Q19RG0kb42KM5kA,iv:s+R/qu4ailygTxIHK5525vzapI9ekAs0StPDgVn7IVw=,tag:hfYQ1sGTIpmFKf0hN5sl0w==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:AjqEKJdfHCfaPg==,iv:VpaT7x17ExPY+52PxmbgwDRfPNnKpQ1uBy3k8ntco8Q=,tag:6zH0i4BEkf1U61DxZzQoVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcFBodGNTUzNzTFcxRHRs
            d3pWbVZXMWJ0VE16a0NNVHBNcDllV256YUhBCmhseFg4YWVlTXV5MW4xMGZaSmI0
            eTdZWThhK0E1aHpLalRXTmgzekYvUXcKLS0tIHA5RDZmcmJ1UFpQNDllUUJrTnQr
            ci96cmd5RjE4VlVpRDc1akh2S09hdVEKTk9ILFO/ypxu0r5ihDmJ9FbsFn7TIkTh
            1UHzqufSGorq8vkbjIiVz68XXu4YNFzWMRvv/g3aolZZjJ1yFS36bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:lb54h2B/vvej3QAD3Y0kv6do3COOHFmnbRHL9HDxv4jYVKXX7C3/lwtXrJkgtvmQ04KGV8xVGpxOtX196c8USBhjqo+ITcnJF2O+VorRdB5GTGxnaJtf+jhv0TFgWx4jVxT1N9dLpGW5H7OG+5SB+U3Hm71Nx+o617mn5Kop/zY=,iv:v3L5/C6HvJmzMjLSAvC8QQT1OIX8uEmBnnCrPbbUrjg=,tag:yRlEetuKLy1KobtGFQ2DFw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
