PUID: ENC[AES256_GCM,data:nsw8kQ==,iv:MXjZwusc3BHL3OImIYMOMwpl5GtvCcEARfclEBsfM6g=,tag:yxwrHK1lVqlVYzdOhsHxXg==,type:str]
GUID: ENC[AES256_GCM,data:P0zSCQ==,iv:tZn1ISR+BDjPsG1VywGjFC7D5EKXRJnIryxTotP10ZA=,tag:Vo5pIHS17MVQhM0yDBZl3Q==,type:str]
TZ: ENC[AES256_GCM,data:dsSbw6PZSpMj5ErI5e3JJNLS5A==,iv:27Erlq3rKHN6WLMd6sqA65VzJcI/9l+ho4ORptbNQ8I=,tag:UT2Edy01gL6FrFjYF2w7MA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:ODzozX95Ahikf+sInrqHYgW2sbt0,iv:l4D7SEWpJqQItsJpaO/y7rnZJFQwbJE9zb3SNQ2abeM=,tag:aXqie/TXX8Ej92/pK6DP+Q==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:swGBkaM/JyydpviP,iv:vB9LWblKxTUydF5pB9h03LQcw//Fp8Zt8M7wfhAOMAo=,tag:Gegr0Ts2ci1b/SU64YfKgQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:S62Sn9sEjOS06A==,iv:XajmhhE/3VNo/02Z3gK3t+fmDkLRpu30BQJxcpzaTnE=,tag:j2BdEXwA3dFSocLdrU5BQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwemtvN2xRQXpaemRraG1x
            OHZTSjZ5T3hxZlA2ZTQxVW1lanJUajdwdkhBCnF3bnhkV1dWSlNqWEZqdHdHWVlR
            ZTU5TE1zV2p1Mk15UTFiNjZ3Sm1vSVUKLS0tIFRxN2M1eDhCbi9GUEQrQk5LSnZW
            bmc5OFZFRlI2N2hJcjZkcXV5RDQ5OTgKv81lmBrWuJBXJby1GG/OmxkFfYXD7MiE
            hW6/ynipbNKUcS4sd45ZFWbh4xe0iUPWNRr0KE/MsIKk7Lf79prf5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:Q8hmojhl4i+2l6VlhDMWwkFPz47Y/nF7ejeaFkF2TKGiXC6942hWKul0Wgs61F1igECZuqP02LQI2eYDfR7ONJ/MsQFRA2BtsoTSr8JXTXfq7NRo+pOONaX/V5wqPZgDjPkOJQWIKgpehLlgP4KzeVezRyk5Tpx1yWwt1HOyVug=,iv:yDUSI88ywaD2FJRzb2gLbld9kHOgbk8BzQ2KJqCfzeg=,tag:T23o1M2e5+xSG2elGzltTg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
