PUID: ENC[AES256_GCM,data:6e4KXA==,iv:RLEmd4Kv4pf7VG8/EwtpLxKgVgI6idQr2UBECTx/KwE=,tag:PgJFo618/xADt2juO6hacw==,type:str]
GUID: ENC[AES256_GCM,data:MwpoCQ==,iv:6tljW8oCC21e3+/ExLQPFyo4DWpP9Y8ViMma7wgVXKQ=,tag:Lyjh1CvgoYwSdxOv7uwN0A==,type:str]
TZ: ENC[AES256_GCM,data:GNMBOWpvhGk+tAwugCPMfpryJA==,iv:AnHeaQHso1xc1SNzjveU/OgLPGu63ArCp8og1y0r2A4=,tag:WJOkrKj39LIdPuukRl54Fg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:giOrXuv5oouQocEQODvGkmcSl1TI,iv:9f5MB7f07ndT/ShLyl3cWkGTATPUt60q/xULjB20Zp4=,tag:uxTQwpddwASbxe4RXv/l5A==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:jDLwWzRp9EMZkngw,iv:srUjMGtSrVOSADWBljFOxIOE1I1VQ+tfd6dOzmJdH5M=,tag:Jk2NbAuC9CdnzgpDbOZwAw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:3q1ehrdmCOZixA==,iv:Lq1ERnAXHOeeaw9shUdZSby90V1Ajf54ixvVhPSjtv0=,tag:RfwS6Kxs0HzW49OA/43Bzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibHRsMVBveVBZREdkU3FE
            Ris3VXRjaGFqZ09HMWdmU2dJNkNvOFZQQVNJCmt2dTE1YVRicXRoZUpCakJwQmJm
            bkpScmcrekU3dEhITm43MWpyNnJXZnMKLS0tIElzd3B3Q28rNVB5a0FqNnpxOFlT
            NnNxMGRvTGVscTY0bVFPMFF1d1E5bkkKI7sFdba2gW+xV9sMd9EQRARKjCUWgsM+
            kLpGy4kPcO4YCBHNE8oCOpdqWhi7xNbevi2mE7IYo7p7Dh0ykGW5aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:xepuo1SN+J2+pN816MMvxGcQMRpLvA3dKCRJCloPfeDpM+p+BLIaZQwf8mgC0waDtUnyN/g9WV8gKUh+CK/RcVC3jUf8XPB000MaMjgf4LMXH6aORC5UlIB1JBxHtYMbJLv5MI+/k6fqIFYNFngGwPa2Jo2pCaVxH9za3XRztGw=,iv:H/pW1p1IY6OFxAO+tnh9GLoUovPs7t/YeFQGQADvztM=,tag:jMLptbD66snG7Qgur5no7Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
