PUID: ENC[AES256_GCM,data:AMLCpQ==,iv:9OIueVmF3G2fYOdrimF12ZtI2C3lDnUB49D+mu6fbew=,tag:jbvsGE9USotqk1/fqQmJqA==,type:str]
GUID: ENC[AES256_GCM,data:M/w1wA==,iv:jQOtvrn9S9Gmn1BCNoupV7MLfC8D5wmemOfk0qatYBs=,tag:wjvnLPoIhi5CFnBuTk7k3Q==,type:str]
TZ: ENC[AES256_GCM,data:l4SVURplf8QAdoeoWjuKKTG45Q==,iv:dwyt/IqeeX68PV0LoLnbkwx4KGid3vqoXvBInyICRqo=,tag:Sr5yBGBeihxX5JBROEJClQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:3HVZgkjE2TknSFAQ+6cz+8XYuS4c,iv:suapcaaxmZK6InThCXJNKUdQmyRlZ29bjRuj7vD1Vnk=,tag:WhU6CNV55V5HswhrRvjo/A==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:dzZJuj9kCYu6WmOg,iv:DknBnnkt6ALbZMiDG5EtOLJ53egkd8HchOluE/EmJVA=,tag:xyy0mFPyFRZo/d3sLkiOcw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:/xvhIBDILaIpSA==,iv:c871dSdzZytHJv3II0BdySGAX7E99ontrsUdXKkJJHQ=,tag:aQd4KXyta/Kqwei4m4KQHA==,type:str]
PIA_USER: ENC[AES256_GCM,data:XQaVZeyTtMQ=,iv:UsnVYA7+p9WkljCJ1PxKT54BwwrvR0HCMYtIoT5A9Z4=,tag:RTOI2tZnJZ7H4eWSyf0DlQ==,type:str]
PIA_PASS: ENC[AES256_GCM,data:1zTBaGCZQYEOtKpA33ro,iv:QDc+GVZCHkS/emL8KpM1W1CRknfMrEJ9l0GlpLJ34yw=,tag:CuZxsdSLxrblTN5VtV7hbg==,type:str]
TRAN_USER: ENC[AES256_GCM,data:PiF9UP9/Ofk=,iv:suZNJ8bLbPleLjctzOGGya/ihyDDqYOhxItIeFy9dfw=,tag:fTIRB+kxZoQoYTDoWNaTBw==,type:str]
TRAN_PASS: ENC[AES256_GCM,data:hXDvqPpjLAvKdw==,iv:XrDYcuaUVNt/2msPlAStRK2Za9MhGD6F72GRfW2947s=,tag:Ajqnzy9/rKnd1ExRuEcoIA==,type:str]
HOST_IP: ENC[AES256_GCM,data:UWzqCJE2OSgjwbZOzZaYOmA=,iv:wHQJ26Qo3hl4zeKd9DzFBBB9dZvL+BRn60z3Cu+8u7Q=,tag:m0w9/zLZbKHl3foMwV9ssQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeHVBT09uR3NRR3VETmlp
            QWRNVHBqT1pDODFmdHhKRkdJZ0Y2U213a2tRCjJTaFdCVGtWNEFQem5LY1lqeDY1
            Uzd6QnlLeWVEbklSL1hYaldHeFRUcHMKLS0tIDJyK2trOTZkQnJiZzh1MGlqRjEw
            WEprRzJkUVppbzk3bUdNOHpVVjA5L3cKeMwhRlUrSTDOM/zqqYdTOVpZxLQYnvDk
            nqPJqt+OiykeAJu5P9eZHVIv/ehT2MGlSeJoP9FAtCVXHFlqNSSR6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:18Z"
    mac: ENC[AES256_GCM,data:iEiWuIKL2xagwnoWwg+uA9fAQjWD43a4qPY8ZdbXYLGQQf8xzIrgISy0hi28alkay3X9t3d8XbwPvtPK86fbrPTI7HXDGSwT2LpoozdRzRoy59a6cNVZO8ilDIQ2/5HPcDMO48Rhj74DFlQvgK8ih6NEs2LhWtyrVMm3w+B7LTE=,iv:SUzhc7wuszhEA7R0AU24NLlWSRqg1VmfvVxXTjckn40=,tag:AniZhPDEW6uvIi7OGzRJOg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
