PUID: ENC[AES256_GCM,data:5NgHRA==,iv:HVvEmu9Jeg3bHn5b5FBcRXJVwWXgDm3GfoMlc2z7NRM=,tag:lG5XQEpRnkMkcfvzA8S4DA==,type:str]
GUID: ENC[AES256_GCM,data:AoqhWA==,iv:3W+pIO+tFhe8keBDJ/zJZuunNW9eua9hDPL8v3JchEk=,tag:uMPA6btT8WPhbmEYa/u29A==,type:str]
TZ: ENC[AES256_GCM,data:PF7+3tysGoUM5TH6Gzam/9wizw==,iv:rnU5cuRGhbeX0hx3GElAOTangZfkZgv7pOvW3JQ8+m8=,tag:zZTSJ8uighJBvc4r2KcNGA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:XUIRUvfpf0BZuVKjIjICFsrMsb+c,iv:KyDz8SMLB2RTtEzaEawZhGr2t8Pmw/cpUAsYYdrh/pU=,tag:Pg9FIT4BLW8YgIz8Idr1Qg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:dU/AAx9OtAj+IQ6U,iv:deSCRpl4TiaKrV7KwplIMism+m6xmB+pQcs858pD8b0=,tag:i4l49L+onnsUGyBfLlDELg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:4qmI9KkesSKxwA==,iv:TzwS1xcZl2CmBc082wRsgAml1EIgjoRdzvKUrKUxKRo=,tag:OHh2hyizA0m7+C/IEKkNug==,type:str]
PIA_USER: ENC[AES256_GCM,data:n0oL0aLfGkk=,iv:DOwozugapGf9fnxj3fOW4/s7k9fO4ACzRE1KNMAjAOw=,tag:hrybzFpjiGOb2vEJzspbeA==,type:str]
PIA_PASS: ENC[AES256_GCM,data:X5ZQkM8rkSR4UHhBRGO3,iv:yHWakltaDCm+7BqMVtRxBK/baiXA1qG0ijDNZ+2h3es=,tag:J7lVAwdpLNTnAxp9Y1buPg==,type:str]
TRAN_USER: ENC[AES256_GCM,data:gZn0RUZcM4M=,iv:Iu/PX44CdMCfkDUbd8afcJxX/iRR0YW8iCnqF8yBuGw=,tag:vpx9tfNTWh+KVYvd1QVZWw==,type:str]
TRAN_PASS: ENC[AES256_GCM,data:tMUdDT4TaeM5sw==,iv:bvlUoLPZjDcJ3vr+WDysvxL3M8dHbca77somC3P90i0=,tag:e6h/5NsKU73zk9SmryhOVw==,type:str]
HOST_IP: ENC[AES256_GCM,data:CMr9Gw+ioxJtVaR4+1pZT7E=,iv:3ciqR2+m5ZIr+Q8SNLAdjVtkPnJzzF/m/wwP/Z2LucA=,tag:7EdsRQpvrBYeEueNl2uiXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UDRSU0xCYlRDM3JMRUpE
            OGd5Nk1SNGpjcE85ZXh6bTBybzdxamUvamk4CnNWZjgvMlVBUDE1Q2ZOSXNnRlM3
            Y0pFR3h3aFBMZVRXQWZOQUpDTFBhQ3MKLS0tIFk5azFuSkxmQnZNOGRUYXdmTUdS
            WUZONkgrdW1UTm14My9YYlhBTHdWM3MKKIbjCcotUrezmBduh9n5NKKVmim6t1OG
            VH/OoP48kdoThrGExubMswdknqbMON5dUOw/fsWxUZ3cM//weGVIUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:Vto8H5wnRD1ZN7dYkWqICIEsUEjhF81GaokllUQBmlfUVmGKuJeQl8Vmj9G5d5L5h6iS6fN3j456BZRzDhufJn6vTj1rjd7oKxuGN9rDT3MFzT8yJR2004XXFQRvmR453oMTpFSb0+wH1+mxeEMZQJoWNCO7i0dMAoOF4hXXrPk=,iv:lrvzjP8MEY04O4CdQHllMKEpSyt/yL7EKB31oN96sYE=,tag:+9LKINk+WHAmMaqVltrDcg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
