PUID: ENC[AES256_GCM,data:g9W+6w==,iv:uT4IllvEBv2PJKdgfEIX4bsf8Z6mUDmvbrTRq23LmTU=,tag:NKj0l5Klo7/ASeQlSWghpg==,type:str]
GUID: ENC[AES256_GCM,data:zkmxIg==,iv:tc8qTSWHR+OAYus7MCGb/UqSoVg97j7j1ewN0DPvT/s=,tag:Anh90k6SmsBDGRVaxuztBw==,type:str]
TZ: ENC[AES256_GCM,data:jwORdt7L6DCRGOgt1OiJ5sz1GQ==,iv:2+t4UHeL0feIvZg/UlOQqPmSzcP3D+SF3SLpW+C3KNY=,tag:8SiHOtR5RAUnwQ+PBd3fyw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:o4wgO8LfYZrTLnfDZNcP921cdirD,iv:wGfNzO1PV7QYinGVINIgmaisc8135pgXpAD66LXpO9Q=,tag:l4ydXJPIFr4HFquOIoSMow==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:2PZc8G6J/Opuu2mc,iv:nnvCX22lpuHso4rihrNaByNrFiyShVX+eE9lc1iPkZs=,tag:Va4UmwFnn8z4qwr2VllAag==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:mNbhRCIFDWQW2A==,iv:ZM8W88gfmn4vUDMg3frzWdb05ze2DCdT2Zo4TAQNxTM=,tag:tQbvfMv7BWutDheweYsx1g==,type:str]
PIA_USER: ENC[AES256_GCM,data:U0YOIjd3ojY=,iv:RsgVRYHIXUns7oM9QrO5m4i1a0YMsAtNelrHtkPgjH4=,tag:PuQfnvwRUqYteuiQtJKJdQ==,type:str]
PIA_PASS: ENC[AES256_GCM,data:mYxr5f+kr7GS8V6K6pHw,iv:fYe6p5wVTxSm9rO7P3eOJFKbJXRDG+W9CZx1alpcAyw=,tag:T01unhxn0AZl2V7eGZXSsA==,type:str]
TRAN_USER: ENC[AES256_GCM,data:NyzVdcCTrN0=,iv:s2zU4x5rwZ6RZyJwyVNY26TBXQBFgoXqfyb0FYeuJhQ=,tag:wRLNNkhznLxa45DLyBz4tA==,type:str]
TRAN_PASS: ENC[AES256_GCM,data:mjW0Q3UFvvA3YQ==,iv:ICD+U+5HcOx+p+ZKS10BRro9+LoAzkxmalxMF16QLxI=,tag:aXYUOq31Ankpbuuyq38VEw==,type:str]
HOST_IP: ENC[AES256_GCM,data:ahZB2CEuv2ajKoBFKGU7TY8=,iv:0PazZWMwcLvZUAFK8psl0ij8+Jwaqr2h9liBkzFcoQU=,tag:qLiWQOPQOIFj01+JdH0dZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbVRwazhmRVFJUXUzTTlu
            RTNLZ1ZXVHNBdHJ2bldBK2E5R21JV1FHVlM0CjUzbWE5K3BjTFNSMVUySVBHdXB3
            TnZRZzNBUmozNDJYejBEZ3pmMXpIYlUKLS0tIFJXN1pna01TZUoxUzloOUxQOXR5
            SHhTSEtpMTdPeVkyVnZVd0NUV1pqRXcKWmwrkt/Pia4EMkwC2GWPbVc9aI1p2ch1
            lLyxQH7R+Q1/YGrtWwnxVaiDpT9lEUk64KuQlYO6sN4f9bZnmHC7DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T18:25:26Z"
    mac: ENC[AES256_GCM,data:kbxsetWn/jzYPltfMOSz2SejJkT7kSfwJldBOXkdjiky8brzt2YTzAyc40SrGiMO/zNLBRJdCvdSM/JPeUvlesHMaDq+to0WSatY+GgJPYeJ9Y1wDHAjqtLfEijwcBPAv6UFBtn63ks9M5rdWaauCim2nGhgPYROnfn3E/9hbUk=,iv:UQoqjZMeN+DWodxSrMxu1e6xIMhHF1HV5+kZQ40k7xo=,tag:wzkJh5lvgrdryy3L7Kc4hw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
