PUID: ENC[AES256_GCM,data:/YqQrA==,iv:7QwikOhnu7BnKSAPCp6spvpdYSJX6IVw2WiZ+l+jc48=,tag:Vad7bppAWR+kAUD4aAiCJw==,type:str]
GUID: ENC[AES256_GCM,data:lQ97tw==,iv:vl24K01qb1jfA3nSXIbdU1hlkvZ4MS0yZbshRyjS0io=,tag:qzXo0iwn3YmyVeb5k3eqcA==,type:str]
TZ: ENC[AES256_GCM,data:+eyMMNsL6swh9JwiKSSJoL7e8g==,iv:xaX4OKkGI4zmdJwfwADN0ajwsyX+zrg00U6RhUSWCJA=,tag:cZ8l7UQhd9tBaWQPgSgxiA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:FXIlgZeR7fSAaRcdNA3wRtCoG1Oj,iv:DTOwiUtYNiQxWvjV04Muk+DgRxaZaJoOJljFQdzFzEI=,tag:Cxc0MIvg4JM++qVyJlM8jw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:kybyQNCofvDcGKQz,iv:OQ+ZCBFQD76/R34nVChv9Zb9iRHz7i1tYVseKc5Hp9c=,tag:XsailSSsQb/F5XWyEgXq6A==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:qwvjT4o0NndU3w==,iv:JvCOhrsmUGV53aaZIo9UyV31In69dMGX4oWUUI2ObPQ=,tag:9d9L0/CaNWCAy/nVW1jv+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUlJMQXladEkxWUdQTG00
            Z2c2WkRjWDhiMTlQbTllSjhJWlRDL1BuK2tNCmMybS9tbVlNdWVBRXJHcWxnN3hV
            bzQ5NXBIcGNvYUFod2wrSEVRZUVBWU0KLS0tIFQ0UVN1bDB5a2JrV0hxM2hDd0t6
            Q0ZEVk5CTEF3eWxQd0pHVFdUdFpPY2cKcYiwWOuWEHi353UqBHQudhx2Xyc99YDg
            cPgw/vlJnRh+Ee6gqX9ZvVyBdO/hTK5xPZGkeb0n7jbxq628/+boRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:rvHmMjMArN6yCu/1xw7peMonLWt7YVMMLHlkkqXH9CvwVjZHdIFj9mlq/716tUeoVEzCulQfNfpznskLN3YQfhEJ6r9ooA3EL6FhwBAV7PDdulJPYBXLeyYJxdB7RofbCD+WE8DRxDfc7IQRoe0JFSaWyssYaddDdUd3WbYWopU=,iv:1prk/Wvg8pQcoKiys64l8V3H+qOaygC4UCRsWpfmtSc=,tag:mG2NsG1yg8EMgDlrCzEavw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
