PUID: ENC[AES256_GCM,data:vc2teQ==,iv:aY576jqeTgGv+PeaPun34zCSVKr3orWbQW8JQMu7SsQ=,tag:3QJbbbPn706DdrdZsvrnPg==,type:str]
GUID: ENC[AES256_GCM,data:3nABig==,iv:Kqk+4pxhtUOPpb5I6Qv/hsZtnsxq+EJJvE77P3IXxY8=,tag:DXvttEqjS87kFC5vRBdUKg==,type:str]
TZ: ENC[AES256_GCM,data:lM07zNYB8tG5ZIXeJTvNtVuVlw==,iv:HXRy+27RGhsOpkce0204g3+e6UjEhoaOdDoVGFNgyI8=,tag:2UnXFkscl0yGJZRGR+bXVg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:4q4oYlsj9aR09VPM94xySRCEx586,iv:k7Y2GL7EVWlj+YBNz3Vzmj0uGvixiqZ1LPlxTsUSvq0=,tag:zn4+YveoLB1Va0weS+zvBw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:MxAZaIH10tza5abf,iv:7MYc1+ImU6ZWCTLg2QuECK8BYesJoSLf/rjFkWE7OIY=,tag:cPZ/zWwKpO9yHd7uyfbRNw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:xXD6Q6Mz7l/ipg==,iv:FdABjCI/QPEkSTengVLv3Mn+7evoocW36LFq/IDG9IA=,tag:L0fLyf52NlQtSPDvrH0Ikg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTUdZLzNXRHMxdEJXOE5V
            SzFUc0ozbEcrNWtkTWtxNnVtY1FYajcxOFhVCmV3V1QxUkx5S0dTZkNUV1NYdWlP
            NjVWK1RESi9sdjAxUlF4YjhvRGp4STgKLS0tIHJHUnJ6OUpEb1M4YXpHVHpIZU5z
            YjdIR3I3bnFiekZXc28yOW5pRDNkN3MKiNZewlrJZ8cevFymsn01AJhGpB2NcinX
            UlJVY46bEjVmxXDgvwPqrDnMrS21Z/zCBofYtVhWgNxiMF4feEJ0Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:EuNQsEHDF1NcfDhOE8PJe0BdWrUvZqDlznVlbyQ9rO5RUaCwz3adDchvHFtepzmSjQb1fKvSMUJlC61SKJvfPSykYPCP2xFDfYdGqECPvoLxv7L9WgNoNKAq7lrJaBraedmLbfjX1laLUdgHNfASssLX2+63er3moSKkgO2reow=,iv:/zbGsxvuBEn3qxTt6nPvM2FTsKFUG6jTMcOk6OFgxpk=,tag:JCv7uPyO/KooVy5piSCpgw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
