PUID: ENC[AES256_GCM,data:OGIOWA==,iv:WtDjkoAGUgo7jW8IuG+H1Z7dPrHsW7u37sQ8OgipDRs=,tag:kPZ5+agDeG4KaaDMHMdrkA==,type:str]
GUID: ENC[AES256_GCM,data:c6btlQ==,iv:C0quA1wRIiYq5GhNd0e2TmtE3WWoEuA+4GnWLVD7C0s=,tag:RMSSipAl+YiwsG1LRlJWQg==,type:str]
TZ: ENC[AES256_GCM,data:kTRP5bzDKwC4QeTv5YA45/WQnA==,iv:cijoNr7kwCQPFwFeu55XPcR+rrPkvJagSxwMeF+5lLM=,tag:BBPZowUJrtHXj1HWlb+JUg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:dQEXI9O3BXJvr7JQoNpwVIoGk2PH,iv:1+EG333fzH7vxHORXL6UbHrFJD8hBhMiX1Cs97HlPKI=,tag:eSER495VtlSTipAy6xSjwQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:IietZTM1RqVIV2Ps,iv:blXQuCQ6/Uqr8J3cGXoZZELyZgWf6px5YBnIjxjeYxo=,tag:SijMPMMMVM91z05P9mAADQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:dhQO4apo8KUBdA==,iv:/lRFu2JXLPhuVPyG9vMuOjVDThQBF1I6BnEaahDnNME=,tag:SlPr46pBizhDK2wINoh9Yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYUREU2RyZFFIMlZtRjBQ
            c0JxVEk1bGZ5Z2F6bzdLQmtvR0RwVGdSMmxJCnUwYUcwNnpaZE1OUnA4ZU9aKzlT
            OXhpNEJ4bDlQUkhuTDdaclMzT1ZVdnMKLS0tIFZtRTY3cnE1eFI2SksyNjE5UDRa
            MmRXRTBJSHk2SXBBUGg5VytWR1VaUlkK5+HcaBdp1xMitl65zd+ppJuq35x3aywK
            Cve7aYC14KEtbRjfWjbpzYz5O0mbIxJ1EMh2tyXdI+9oEipX2augig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:v18VxMZZUlXv8OnF/8IUGd155cvFStPy7Ougf+aR7wJb8KiM2wArd7AZBkmZnyPelCXbo26wCrnD4MX39J81I+oGk1hDJxP2j6LYOIr1XYQPa/s4o0nGoDFRP3e7SRRLA3m1/unhSIWiBu3FErK6r0iaWo2HwjFo3MIr9ikyJRg=,iv:/rPW8L+pXimR/P4SQzw1THVzsEQTKCUkgM8OQd0uCuM=,tag:2ED1V0K0+nv791+KQu762Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
