PUID: ENC[AES256_GCM,data:NfFM5g==,iv:1slmgOKoEq9nGp8AAlzumfXxiN9Al7ELmJf9F7I+HNU=,tag:nUWd8uXJO3QEP+J/75+YRw==,type:str]
GUID: ENC[AES256_GCM,data:hxjVog==,iv:e+r/AzsvoZtsl6FlrZTXncAMIGhF+5GNb2m7PdSWV8w=,tag:eePwDDrWjziB09GAeM6IAQ==,type:str]
TZ: ENC[AES256_GCM,data:dvQTMMUmUWj3Sgku3sLVldMwXQ==,iv:SC/dkhw2WpaxH0n/VmdpehZvIpMb3RUEiT6WsHclDn8=,tag:A4Ec9EU+AeXP5KuEplynDQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:Jv7XVfu3IRGWsQCi6BjO9mfgaFT+,iv:zd/QC9/zSwX+f3NMig4SHAdCqtsPr2v1rLQ35Kjxgp0=,tag:qjjMGxZfXqdMnwIQDia13w==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:5HPVMokQgN653qgL,iv:EB6AojCDNOD93LOzGegnaUWm4s+rCVEqNc9cSQ7Aj44=,tag:hGuO4ovCrpWBgybKL3qXmA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:DN7TTRI4m+Palg==,iv:2UWWzP/Qh6VuZRadiDOwIF1polsBVsSxL1ipq8If2kY=,tag:i5OrBVQJAbSOK5AXuegnpw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQnVzMVpGZjhUdUhJcTJx
            M2pJWURMY0JWQjkvcUE4QkxoYnAvZWxNYkdNClAvamhaTlBnZU4ybXFhQ0RYajZh
            M3lJcGZ4SGp1cmUyYTJpdDhZeHdiYjAKLS0tIGZKQzhvR0pHeFhSU3N2ZzhrcFlS
            UGNLeFNxb2d0TnorbjdhU1ZGWWZuRGMKIehOt9tcEx0zjPfOaly+7HuETsWiYKLP
            9OM14Z4Ka+7VVTXOLfCk4EbpxawcNbLjPx0hVHg4xENbRWWLpXNl8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:17Z"
    mac: ENC[AES256_GCM,data:dY/L7oNYI/iF7GA6kivd3slnrDbte1hMdnKwDGSzRXSdJIRv8qlKDUytEXhnh/8LywYNxCKtR3M8VT5MDskbIO+pAzvUrvalczJWh7t139RKWIEzaqFZnW0o5aL+y8xCtXpmwcfUsrgkqm6uN+N9wLpAifsNS5Lvqt6J7L7lbt4=,iv:eCxu/o5paEKP+mtOE4+A7Wsmt6J5Tzy07yvIacdthwo=,tag:MmoaAprHDf3q0U52KPqyAQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
