PUID: ENC[AES256_GCM,data:d0Wqzg==,iv:ATKnX5tdJqruMak5ZrMqTBbR/y/buhIhwCXbwCtWJB0=,tag:UbhBccvV5iR4Y3giCk5B5g==,type:str]
GUID: ENC[AES256_GCM,data:LB0iVg==,iv:OfZNAXnO/DLoK4hkhbxWzPWbzWu5YFIoD1gIcGB5Re0=,tag:CTnLzu9it4NSR6zVbuBKRg==,type:str]
TZ: ENC[AES256_GCM,data:zutuSNL8ANhYdKUUiaNyJccvzg==,iv:/pFU0ZqlER4oeFowjqdrwjg4Sr/WQxinGoif7ckmdDI=,tag:V2ZRnmaTQFMililMe86pTA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:QTiT4hAsGpmSh8b+O8EIjZ4vFiTW,iv:2lZNdNRLXahO6nAAiicWFuBI+jf3nOQq2eBXLA2z61U=,tag:o8JYWJ55zaKZcbEWbF1mjQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:9u/EFSGWEst6aLtK,iv:VlhVlBXH45CL9C7swYG/s4uV1jHWym9pkUxhHmoPgWg=,tag:ogivDMm8GWeEDBCphzbC3w==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:oGAGEOrm6meFPg==,iv:h9m4//0dt/DU5hrdflVybmKltiJYiOAEyH1sjiEafzA=,tag:d8QDNYMimxmPRnqAkiYWfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyN3g1b3BlcVptcnk4T0t4
            dzAwTFA1RkluN01kMjJXdTY4bHlqYk1ZWVZzCjhjZE9kcDNDaG5FTFBaWGtvcXRv
            eHh4NTczSW9GajRzMjIrV0wzQjdUdEkKLS0tIHF3Uk51dEFIV2ZYckdGU3BEZ0do
            MGxHVzNjMGRwUlpKbU5NUDZ2RDY2YWsKRNglVFLUmLScY1x2wXFnvzGfyKGpjt/W
            qAOLNAG+yKzTjvpB1kzYPu8rVRJXqZ5sqh4Y1UWFbwdAJjAjHXhs0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:kPsP1wLKSFXcvN5T12rkvHaHR5yAlZg/nCA5V5/VlCU9JUH7ioJ38KCu6yE/sKRenIJda77d9Y0DqLuYHuQD7Y3S+w1OXDfL3gQ3hpMqhMLUW5gAGwLwJIIJDfR8hf9wETcPOnXLv6OWa5/FaoamhZ6KHphlahj6IWV7ZlXnJmA=,iv:AaIFP2KDudR4E8q3lsaOlLrDCINoL2ORGllmrj1yXG4=,tag:mRx6feKsP2zzE4BsQ5hVDw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
