PUID: ENC[AES256_GCM,data:6Udtag==,iv:7gSjuWQ2U415LKp4jwg0O8Oe5rE1VrU6CFHUeieSv58=,tag:BqhUthFySYrrXxdnTekEjg==,type:str]
GUID: ENC[AES256_GCM,data:8Caz8Q==,iv:GCYs7GteX2aNfaRlwVPa+KLgCHK/dtIY2yLqYH01/ZU=,tag:7iIc/78JPSbgaxImDG+XxQ==,type:str]
TZ: ENC[AES256_GCM,data:pywPTz0SsEhlIEWvuT4pkmju+g==,iv:yT0hQZ9C9Y5mwBw82NJ6QA1c6WncVsO7ntS70FdJzz4=,tag:xqlyAY9/N3FSQsfb3k6OWg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:SqqNXH05HCsPQFKuwTYpCRYK4a1q,iv:U3SAIgCH5XHxfGb8xuf4Gu+F4O3FcVj6oRSpC43B8MY=,tag:VL5iYscMpNBCuY9gU5aLhA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:+LGVwpsY9A2VgCq8,iv:m1lTrmlUVrDNGulWDhd0/V3OwUA+ujpHTWCiFDXus58=,tag:zFsvAQvLXIXfxRONb44Q7g==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:TBgre/y04I4erQ==,iv:Wv55qKtWqQVQznNxsqKpCBXmT1rM6/wpI9o5CKT1Ln4=,tag:XlJ5fT5wS1AA4FPRAr7Fag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSVoxdG1yY0I0MUhzUFFu
            UlNIT1Z4dGg5Ujk0eDd0ZVZGMGR5T0dld0RRCkpadnFva0FFb2VVMHNzTk4xd0Er
            NEhxcnN2SUJQSVVyTVJ4WXpzTWRpUUEKLS0tIEFXS0ZVWHgwQUQxUVVCc2lzVTE5
            SzRwemhFT00rSERMZTNHQ0hiaXZwQjgKzh4HKpnEgHz2ZeLjuWhTuqifipVML24g
            nZtYF5D9gPxvHpHo6WVw7wI6FT/JHSGZmf6XJvL8W2aO4oXIHVgLIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:zyaoRd9P10wcJHtczTeZaLPdb6AGmzFv6/QY6wcp3qnVHfbzm03fTNBStdY5fpMgrZGdqDzJMZYfeRg4ZrvVoiKgTN+EP1dt26107yXNZhUpcw6KGomRRigzszjApEpMudljTHjH4DnCUDrMF5XCaP7QMHk/v40KJHecUuvc3Bs=,iv:au8b28xACHzOQNJMzpwCtMoYlSm95tnEbIz5eELV3RI=,tag:/G0bFwRwE4DhjfsOhTgc/Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
