PUID: ENC[AES256_GCM,data:TlwLgg==,iv:UQnNMq+8eZFpDIF+SYik1X0CRBPvPc9fj9dOllPiC0s=,tag:B8QFqKij/Jd2WuuCYyKS9Q==,type:str]
GUID: ENC[AES256_GCM,data:vSGq/g==,iv:vk0j5PvpYOa+PLspLB/zloMDHulKTYPhWiC/MuNrjvw=,tag:bYfO6U4Q+coExobuX8dG8A==,type:str]
TZ: ENC[AES256_GCM,data:hapNAnX1bSfpkAuYXUD1HQw3mw==,iv:JUzc8wkBMWK36/pECSliNlUnoE/yLGTjMxzWbuzmik0=,tag:QS0RmEZfb1VW6m0QBj/v9Q==,type:str]
BASE_PATH: ENC[AES256_GCM,data:oBTnmxS8G4RUSdqB6O+N3fc60rjK,iv:nxHiI5vqxif5myhTOwccrmN4pVd1jXxlhuufi53Nzjc=,tag:Pu0PcsBVcS7efkBnQhQnIA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:M/rjdpPzJg28ix5N,iv:A/nTa1qQzIYq1+IS+cIDbWaqnno0w9Wpsp/EpoXsHAg=,tag:3PMVr1gOyMTHBAPsTHPGTw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:6hL5+fg7ZZKRXQ==,iv:q98hnXG7FbEiN+a/S30R6sUQ373ONmkm3lqqq/2M7KY=,tag:4pY9N7Af6QHLFWRwx6vYEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMjFkaHZvdlR2ZlVDZjhq
            K1YxNUUzMVRRSE9mMGRKdDBVTFBpUGtHdDJnCjRha2cxYXJEWVlRKzNmSW9rdGpT
            dUYzUy95U3doZnNnUXFiYUJVcVkxOXMKLS0tIGZKYzRidW5CLzYzelFhSjQzSjZr
            YVM1UkZSYTdpa3IvanY4aUwwNnZ3dUEKAYqgJeRYFqtoA7yFlDcB2UCgCql1reB6
            Oox9zWgiESa4riVRivfFQ6vtqhr2sE+jpiT+qLRakT80bAcJcRgepA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T18:25:26Z"
    mac: ENC[AES256_GCM,data:JlIbGZbEGCA3qKxydtUFxODbeigi6bQ1ogd2t0veaBh1bLyYtrcUpNa9JVUKEUFMShuBYJWjraXDm3ePnXebQ0YYN7Ii5o4BNV82GDfQIr73tUKdV4CQlJcHIaSXtZc+OIrdG3W+FqFeeGe78ah2337SDw9gRppJ3wleaEr52eA=,iv:VzlLJUQQOiERx6nAnOu2jgEtHdpatRGMgdRCoiz/NC0=,tag:F0+igthAQbCiNJqTZTwVwQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
