PUID: ENC[AES256_GCM,data:1bGD7A==,iv:m97C8hFm+fAvpGSCInuh4KcYuCwzRU8zwy8PPGK+BcA=,tag:74uTkexZcBxOQlVAHnLNrQ==,type:str]
GUID: ENC[AES256_GCM,data:TNrAXA==,iv:fymqwfoNTV0Ohdq9hvZ6Z5zC6J/ZFxyDAc1DyE0DbWo=,tag:DPAqDEFN+SS4E+eJZv4NBQ==,type:str]
TZ: ENC[AES256_GCM,data:4f0s/KpoR27HtV8GniBTcsNQeQ==,iv:BOcL9Tfo4e/UWMCcLLW6G1tOyt0vxuijvg8m5lcPOnM=,tag:fo1yMnlhxDEteu73DlUF0w==,type:str]
BASE_PATH: ENC[AES256_GCM,data:giqnpndqewhd6ZmgboWbE5+31ePA,iv:e5Fud7DCdjtTyv6PbdADvL5hFvBeeR/48Hrmk/1sD/Q=,tag:fCHSbVxNpt+O0SD1v2JU8Q==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:Kbt1AXEZwVNxKdtf,iv:DaTuyJCQIWLuj8990cG227eQC2juv+4ceZEmiCBN+n4=,tag:2sR9n7dvVBr6kEv+LGoJQg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:xlcLA/gOr8zHUA==,iv:0q6p5K83Vkltn3hhjCRjEBCTL3oV4RpSNqkuHrL28ro=,tag:1/46J7KU/CFt8lTwENmY2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxK3NET0JoWHhtTlAzaWl5
            SEZKV2ZOOXNOKzFTc0t1aWlVU3d0NnBMZWtJCnJTOFFxQ2VOMTZDODlnU0ppQTRE
            MVkrdjFqcG9hejBmb2tkMHNiNFRZY2MKLS0tIEZ6UEtYTWk2Q2tqclA2YUw3a3Fs
            aUNKcFRjUThDTDhEY2NCTUlRRUtXV00K8P92QX+TOBK5bk0GAUA5ZaCU/MZ4xuni
            wea5KEGnRgcu7ujrCk8ug5iTxZmk/PGnW21vX0YNwi51sa2qisIiHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:o8Rt63xr8KLkOWIHqRiqwOX7uCuvHjHPy99HobWbCvOKinNEyd+hUi4RVcproICbBFXx2ef9pr2gDi1R60ddCpnNkQdF6RNipEUPfEgNsIjo+FTTKBnfGGEJlz+05ttIfUK90539It7N72vJKAWkeiImb5k67mZsn8DPrV8fZIQ=,iv:S9nVXl21dlaD7itSd/B3sy0dF7gXsNVmZk4Cisp9Oks=,tag:YrIOeyBod2YLBdTe4r8Q4A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
