PUID: ENC[AES256_GCM,data:M2Ah7A==,iv:BOPoGJx+KhGWN6BAaRaZfBsDBvw8LgTqJ5Vpqs2+/3M=,tag:dgvUHs8yboq6nutIz6kNDw==,type:str]
GUID: ENC[AES256_GCM,data:aujQfw==,iv:Q1h86y0LkQxm4MKQHtmp/kUkx1axgKw42ShBY6JUgOg=,tag:1Ksb+4RWhJ5jeP0EltEIlg==,type:str]
TZ: ENC[AES256_GCM,data:yMxRigAjFmYHCMORRYcER7Y/wg==,iv:tcXGM35gXyoxsifj8vqfajAsLgfq4vtWUc15SlUGXRk=,tag:+bYr/4eB0FYVl7crfG+s3A==,type:str]
BASE_PATH: ENC[AES256_GCM,data:wm6Mdqx8ta3mhe7jDv6CFTOJciT/,iv:JDbsB8+xttkdjUBFFC1flDyvRW86d/T22i7G86za64Q=,tag:041vwPzAuyLrpOFsbz9iFA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:RBNFzOBBh9RUAkyp,iv:WgvF9CuWJGR0WyH7HGaO2JbBLGn1x+XSSrezKYyPi0M=,tag:BkE5K+wmj6K1bdY6stm69A==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:OZDS9FZfUlMQjQ==,iv:HA5AMB+fKLb8uXG4Nb5TL+e4IJ5uMG0qyXcEPIHIW28=,tag:utEcwOSlRke0UAicRaIGdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRlowRlgvZEJtc1lDeFFF
            aS9PM2JXQU4xVzVBN0xxWFNRN21ZV2JYdjA4ClE1dWpLclIyc3NZVTN3TkdsNWcx
            cjl5L3lGT29NYUgzcmtsZWZiUzhHZDgKLS0tIFU5Smc3NHhvWUJ0RDZTeThyUG1q
            WW83djUwOXNGYVdUNndSUDBVRkVLeU0KxPJMm3juUYpsdwK1rMtdQdRuLGq1Asrk
            Sum/3I1IthcxBA2I9uqwvCWItxOUrZWBGpMYSm2nUe6AZlWFoAOJpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:hKD74g0ArruJIb4LWW2nW7jKLYaYbxMncFhoUewU7OhC3d+ZSsa1RsyFdKwiiUL58TJheMEdeOfiRx0+44iI0IFZXKA766q0GoUwNftOcJFmB2BVBvEZR2xHWY/muXQSopYG+8KW1OomfZyqfNkzOesp+mm7B27TA5jFWGkWOOE=,iv:YNX25SKrUiFrUIbB1wCwBEy/ajSE64MNjE3vHLgHXVo=,tag:CxSMOyGW4EeFxJtU2OYdsQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
