PUID: ENC[AES256_GCM,data:4iGlYg==,iv:hlQrjrxrRGfSjgFvbB0QtXyJXyejTGrsNAkdi0SU9go=,tag:Uj+MGzyeRjLyuipkl29Uqg==,type:str]
GUID: ENC[AES256_GCM,data:JFUd8g==,iv:b/VTi0JxgatQVEUMP1z1zGR+iILcZX2gqZQ0HuAoHZQ=,tag:4LlnkrcoF9jrM3J6ZKpl/w==,type:str]
TZ: ENC[AES256_GCM,data:oK7GgTiR8ePeS8el9j/d7CcGSg==,iv:ggd/P8MiFk9vsawtfy6OZeDHcUqoGFonOGNNecE6/5E=,tag:ZU2IMM0Wmyw4JoqxIJ7Fvg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:I27JSthLIdXk+x0iTPrrHUmiwf8w,iv:tULFOwJbaj0t03u3lJaTzmxLq1IOmDg/aTYGLUpPYVU=,tag:4MzI2xVw4OCcDAMJrEzOsQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:KK2j/cFb708Nea3Q,iv:ty6N3NrIA2SL7vr6mTllIWnZ1rfB+XZlukCtyEF4e04=,tag:HIVzl2XBCTvxLUvnEudEow==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:NhuCmgfMFDgkTg==,iv:M0KT6LCVLk7DI67wR/j66K6YcHwVPJnSC1+jm9s0n3k=,tag:dG8J6YI7irwUIpVbGFIpKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmanpjL0tRUmZkVGxhMVVw
            aU9kMnR3NDJRR2p5SjlRQW5MUk16b0pNa2hJCmc4bzlzNW5nMEx0dUkxVUhYNER4
            WElwSGZvb3NEQnowbmN5YnIzQjJ6ZEEKLS0tIE5QV2dLZS8yaHNZMEl2RzlFWCtD
            QTA3aFpvajJxYkgvUTQ3ajFBckNLVHcKaDocbyZ54BA4McbP2J6chBNRRxyOSUyY
            rSakCarc5buzvKUI+wnesH0o07v/sy/Z101Gt6D6sgXPqnOqow+Vuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:HXN+ENfj8NbB34/ic5GvS/vaAIBhabuTdKBbxOikAGQgIXU4LZippFTTzJWamNhYFf6ZQMhx74YDacLKkRzfyUA2xrbdl1ptIE80INrQHCvz6oL7W12/9HiPm3RO37p04+wP1BDLwDqxRoAxyFQQyH8F/UxgDy0ok+1k7R2IJmc=,iv:8yYDSWvEV9Wr92bU3uvQzm4usiDIwyqx72syBWLtDRQ=,tag:3Rd0BM9ru/JZZwkZQ6IlnA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
