PUID: ENC[AES256_GCM,data:0st74A==,iv:Vl/FgloFP9Z1806WpPZVs6WqSwzTbTbsM22x9g/O5eI=,tag:EMMw9NmXjcf/VocSSNQ8Cg==,type:str]
GUID: ENC[AES256_GCM,data:21ICsg==,iv:wYBmdqZIgBHyrCWfC7FNM5bS5bey7z8Wt9j1M4/flhI=,tag:RnfjFa+0Sw1ItL2V+Maldw==,type:str]
TZ: ENC[AES256_GCM,data:gKHmnFdwBDckKpMGIwEFjp+VVg==,iv:KNGYqRlKOYGkwdPMHL0xkgQVKRHTd821721xlMKTkSc=,tag:gIukmpvuS29qZeQ4JDjawg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:C5GZSQKC8iTr5OU6Eb2iJniLqoYg,iv:frq8E+AD67yRSB51qGGdicaxpEyT5BHBpVZvUSAmE5g=,tag:EEufETrfaXiD5nQlcYPUnQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:MtwAMJukcBej9PBM,iv:Gquo9RH+Adc7MSNY3jj/EH6ftbeNEEszn9AtHFLHMO8=,tag:IqCRVZsMqZ2Ux2AzR4YrHg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:ZWzjR+zAeVCR6A==,iv:F3PbgrEXIyFJzGU2BPY2szxxLTE5S5jdk41nlgHeTSE=,tag:Gnq0/WdchXD9NjuM65Ia+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoL3hDL2RnajF5SGwyc2Nv
            RXA0dWFHemx1ZUU3dEF5TXpOM3pCY0t0NzF3CkxGN1U1c2tYdVhvYkptS3FpdXpP
            d2RCVFBLTWVCNTB3K3BLQzNucW41M0UKLS0tIFpBVWFQS3g0K1MyWlRaKzV0T1Za
            ZWNLaEw4bjNKZHpUZmN4eWRCcEVBUTgK4JetJU5furNiX03wsxnXprxdizEitbCN
            DAyk0KOqOWDljf1s4Jyho71eEtro2GlAcCXztiAizMUYFRsN+wTpXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:zlbp6rSwu0tDUDMb+mSRNs8UCmvMO2Dgyu9swBcgyQhNeb0oQ71Y7AA5TfZpkgMcNu4n0k3BYtwIgnGXuVKw2QOVOPmnqBG5+K94f+jQxUFUpXqPb7R7aNaijAziwxm3ND5uOK1PaBIKuvRTSmNYwcmDm9MBsLImcYjJgYHY+Ag=,iv:KJhMFxqGcnEO7Ce2XZaCAP1po9QvxwBLbuq3H1OCkX4=,tag:Pr/Y0ipXOWCa4yWQNKGCYQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
