PUID: ENC[AES256_GCM,data:tfp2Zg==,iv:P8+N6vk0NiaN0SPZyv5kkGoQKQHxOHBXpcGwVBzlNPM=,tag:4LZE2K9HC70H9uIhJT0SuQ==,type:str]
GUID: ENC[AES256_GCM,data:ZgIxpA==,iv:gPAe4JFhR1lbaAflfriBXqNpHcVVEFDskUapNCHAHuM=,tag:qGEoSLUPCIz2yIIil4DOdA==,type:str]
TZ: ENC[AES256_GCM,data:Dbo7NZOYzQgbdoZ3CU0cNFyafQ==,iv:cjfNwkuDxwH3VFW1wFeON476jTfcOD4+kX9EAOMvm+U=,tag:tGGzMJzU3E/xy6hMJqSEPA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:FZUl44C8v3dCsmu9ax9OsJ9rkXjA,iv:76Juh5Vj+U9M/n5k+PJ8w07JYCd6RA7fKb0DUmfwUAE=,tag:ybzStHLcm5DrZcWIxMMmwg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:8P2PRFETR2GoRZid,iv:Y+JOnH4W82t5QBdPwgIHoK1eGoSZMHkqyPACacVb/8E=,tag:bHi/BMCT/HJb4W357tZQ/w==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:kPx6piPf+0Z9aQ==,iv:GlOA3Y/TYnRS3VBMIvuJ2cAFxl3MokNfKzggcxoMPTs=,tag:23Y88sSxOTBACXb+ok1NpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVCtxbm84NjFIdFhaK0Fs
            MlYwdFUyMzlVZWJtMmx5TnRMazdSVnlJZ1RvCk9jNzVLU01CNVFGaUUrOGxkYlVl
            R1hGNnh1N0tDVGIvYkJrMHFhTVhXMWcKLS0tIDZUZkEzZ09iTjlldXk4MUx4Z25R
            Z3QrL3JnT0lYL0JRUUJKYWkwZEtJVFUK5zewARdOSiDUOudQSIjqTBA9Vcj2dETr
            bL0tvBYn/OI1pOthdC1RxtfoiKcem4uqV6qiOk+vaIAWZk+67GcLWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:ZPOjmccXZQZvCiDAfCk3ThNW3JuZ0vl++TSwH9Ko4VtIiLcXpWxyNXpOhbo+Hs/zIGkQgoxZqEv1IRwQr4WZ0Bg8fy7QnFz/ryH19jLs7/JzvwMhFUunm10PXGSXsTfkpQYW6LZw6WPdQO+H653DSM6B4XPI0O4ITv44PsJLY4I=,iv:RKU8uuyNs9quJIfJymC5DrxGZl1DaJ8yiaOQT8KTnIo=,tag:X2DejAUCjoLyI0vH9qivBA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
