PUID: ENC[AES256_GCM,data:vvfKgQ==,iv:eHsYc5n4oBk71/norgVR4GCYAN5Lu0bbhEZSPu+P/Ok=,tag:L2L+Ir2utCMsE4N1QVmhdg==,type:str]
GUID: ENC[AES256_GCM,data:RIL2Vg==,iv:dMlk4MpREcdkdDMxYDdrbvU+zn+fq9dyuW0tZHUDonY=,tag:NaeDbsxPF08KjsplxJuDKw==,type:str]
TZ: ENC[AES256_GCM,data:sk15i/kd7AqkOe7+mSegneYvQA==,iv:h3V2ZizOwMNWo62x6AWK08Z/bY2/hjP6aCNcofHrNfE=,tag:d+xFlAVdN49jNHmfbcbWug==,type:str]
BASE_PATH: ENC[AES256_GCM,data:d0Pso3Sa5M7a7CCaN85MAjmKsNtN,iv:zWhjfWGh8+GTQccwg95arpuY1xgsx3Ke1PR2Sa66Dgg=,tag:zDZnPGlBuKNOWDbTcCbkIQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:iigMwKSbIx0C2aJC,iv:s9nGgLaSAtYnbwvePQO8eJEGAMJXDmteIM9nelQldOg=,tag:aRCl/wAtL9/LRNaHrmx2bg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:UyRJknFxVJFNMw==,iv:0dlM1hSqpG3vfVSTBm/MxPfRNckSB9Vz5AOjVd1uOYQ=,tag:FhwW9v87likR3AaHARSwsQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOXRDVXAzUGUvKzg2STJh
            ZGpmT04zRzVLM0gyRndaclhhcUFBQ0F2R3ljCklrRCtjVUN0NWc4Z2hQUnF0OVI1
            ZmdiRVcxR3RzYVZXLzJzU3dXK09TczAKLS0tIE5kdnE5S3poRjJwNzRIWEFDOWMx
            c0dJcFVvdGs5eE1KYlNvN3UyL0VSTEkKNbbtiJHzaSfYpPdF7o4YrO1FZ/UlJldM
            euxfKcWML4CLHURvXKfGm4HXRmu5nsp99W7GmClyVYF1isgsOvubOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:17Z"
    mac: ENC[AES256_GCM,data:stI/mJ/sB9BBQw60Tuqp4ao6yLD8C3txiOTDAE8xV5a52rK5ARH/u2tfjMyZuHfpZE3++Dm/SWw5N8N1easTp/2ei7grk4g9A8RCwNfOSSdxDG2THA1QI8VKIb+jOXGP5QTD5G+myKwk2PPlNURYnupShZPihd76itd69Zeu0yQ=,iv:PAJK7s7lqI14L+pbc74Ta6O4Vn3QLvUj+iSgPwLM7Rs=,tag:30TJBBNeJ26bBkt4YThjig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
