PUID: ENC[AES256_GCM,data:wYTXHQ==,iv:fF8VSgqL1YYQyXA0x4iveKKSFDgsO6T7/ttVb5XaevE=,tag:24f4u6EzXLTDo0qV3CLU0g==,type:str]
GUID: ENC[AES256_GCM,data:FkEOQA==,iv:VGi37TLV98NrucOIRhp6xd3/iLk4uvV+gXqNKWo+tHM=,tag:MPVL5Mw6DtOyuEHX6bp+fg==,type:str]
TZ: ENC[AES256_GCM,data:xGHkmddqt2Xoo71LiusHzKBtsw==,iv:HxjBSrXJs/7TcnEgpTgn/TSh4UlowXPo7f+OSFowpTU=,tag:jU2stbsSZ1YL/IgDJ1UMKg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:woIpsUpOa+5gxHyIO0H/r8EFyGRh,iv:YB4uAoGy26Fd6JJEjNCUR+4PramaWYQZD15YOoLmFGU=,tag:pT1na1Q7tC4VUSp25HQ5zQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:ebsBScgHwTdScvvJ,iv:B6/Q9TKhdBZQgACQID6MGNQKgGJq7kdVaUvT5gJt6Ww=,tag:zlvecWFkoC/idSVQsI5EKg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:/6t4WCVcXdryLA==,iv:QQeM9YsjZ9pcYOQOIFn1Nk+hGrDAIjAxOTiO5X6CGIo=,tag:T10HDYJtbRq4KjZph4A6+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWVdnNXhwVDZ6V3h6UWpD
            MW9FT05lNVlnVGdORTlRZ2hwUVNzMDBnOGlvCi83blFXc1FBS3hhdXdVYm1XMEJD
            L0FBQUhOMWxJa1J3U3YzY09TSW5MS2sKLS0tIHY1UWU0ZlJjZ1EwU2lrWVZYL3NI
            WHpuRnhscUZrRmtsMDVMTXNqZHFKUE0KnulEB89WicQ88GNMNs6SeJpT0CnyWrQY
            iDDeh0TW7U6whZkakZ8xLkbmtWT71SuWWsfk82U7bf0m3Vxnabx/9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T18:25:26Z"
    mac: ENC[AES256_GCM,data:ggET47Lge/ER26mb9+HwZRygbUyUDcyPHFEIAFXU/IHmapcX2cc5ip+ghFmff9ONDHnud67Mf/3j+zc390J6kYLEqgtwiGTgrmxJZKEdj+KKD2CRe0njtKdB6+sZQi1cSvH3+jJUv2Uh2ilviHXdriZV896Nu7f/3JxU8yvz/Fk=,iv:eSG53A6WBkm8MogphP63+XKa5SKQfipih9ynFGETrGk=,tag:k6AmT+5t4WAqKLjTC5QF7g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
