PUID: ENC[AES256_GCM,data:3b112g==,iv:YdH1izk0YgPZiRWITBX7e0c3UeXd2Gx33ltZJxymlf8=,tag:latlCQTJgD1JxMvIWd33Vw==,type:str]
GUID: ENC[AES256_GCM,data:cAs+Pg==,iv:0KSRuWvsxTslrEBwXYTHQN9sBg8MncdGB9oW6vHPwtM=,tag:jJ3wE1V3pggtNb6msVOFsw==,type:str]
TZ: ENC[AES256_GCM,data:NvxH16cPv1eErYjFyyXOxJgEpg==,iv:gf3Rb5hoWIa4D6YhgNe2aJCSPvxH51eZ/4STCCPxdqU=,tag:tRuKY9NbJZnM9CeWGHDsBw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:fivwstF/nVdkoTvMpIttSyEccSQK,iv:r43hUy6ed7//osOsChPWJqhnPUGettpj0VnrzqlJOPE=,tag:ylurdCIYmPtmaGP4ZEzDdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmOFhVenJPakNVT2NKQ2VD
            MnJ4NjkvRzVSeVQ4WGZrYkhaTkg5NzJwNUNjCmhVZFVUamQ3L1JWSllaODN5S0Fi
            Uk1oa0tWVm5yUHkxaWNDK3NqRmN6WVEKLS0tIGlXM20yREJ5dTRyc0lIbHJ2UHpY
            ekY2Y1hXakVQTnowMEgzd04wWHpsQm8Kn0/BRiWBDsKt0Htpiy6bqdecKJxEH6a7
            Ew8Qy/CSsgMNqm0pFCoBIc7atmIqPX+bEFKLMe5iE5ZFjzGI+r1xzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:qEOovnD7G0pDdQpExHaxw21fkrpJyytX8qNArpxn3AZkL0v0RPz8q7PqAP9nSbMWfE3NAdMWKQNXq4ixF1/zYhE0a0CAhNEtAb400FTnrhdD5Q+eBeKVS4lJZPpTXFWGnd0hDf+GNL5Tt7VnlrMYf+8tacDVJOiOx8nByDE4SWs=,iv:fVO33kGOVxzWVfGBi4pmfoNHEG4I3k/gtYGdGVZtFtk=,tag:xX4nKatOk+ltyt1nLXDcpA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
