PUID: ENC[AES256_GCM,data:x+ZE3Q==,iv:BnwbLGMRRJf8+fnWn6kS4uT3Tme/tEaPvB+1u2muH3k=,tag:hHXz3ftNLcOyB8tEaqOl0g==,type:str]
GUID: ENC[AES256_GCM,data:ArIk2w==,iv:6/y3gF6pozbvLXGqT18WMuF3EPQ8XwDNPUJfSJtasU0=,tag:SngtbI8/Mp1oEidJ3kf8Ww==,type:str]
TZ: ENC[AES256_GCM,data:8YG2+cH9Mu/LB+XeKhqNTL1/jA==,iv:wcs4qYr9HBnrnB9bk8U581qXnc19oVnT/CSuqFMl5NI=,tag:VjN3h0DTB2R0Us4SfLKuGw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:3aUTL2008cxvrvFir3klsFSeuvlm,iv:haXVQgw1KqlDIZBao+DW8fjHcFZe0Cw4pA0pAkcRuFY=,tag:RT/g3e98etmo9c0ALnbTmQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:ZEPSBatuVxyu31SN,iv:JAc/6NEYmrgEhFnRsjDahVpJay1zMGHxQqFeCaBSd9Y=,tag:kA+/CbVLZN8XCSRHZV0nSA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:FBwVSWLW5hK8Cw==,iv:6/cyeVDbK2lXv6ajEFN5cL+RNLcdkwhxAmfj6BlYKx0=,tag:UwloO8ZQKOhRynojdnIT2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeFh5ZEtxT2R3TzdGaTZQ
            eHlIYnlQUDF2M1k3aDNVa3VUd3hYM0QzM2pvCnc2QnpRb1JUdy9iK1VlbWhOL2Ix
            SDQvU1VlaS9iS1YzSXN1TS9rK1U2TzgKLS0tIFJWVGZobVRDSFVnQm0rVFhEVWp0
            QzBEM01YcGpTVXhjU2dPY3B2RURQOTQKilR4jWvjgg/eoMP215AIn58egqsAW6ui
            OdNJQM+M6JGu31wpOJh3HOEhU6d5idRwHEoaHPel/41eBAEAlcyQAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:2PVQFfQssTAxho1Ki6GlH1T81tl+dBi1hflO4RBv/OasBiKW+jYgC7ukHuaqu8fcx9F5hyTUaK6stf8G5jAiyFEYe942ifWeKqlKgX4ytyfnt2K5+C6/HMvmXNPopPNcicIt91F8f/GwLBX+44cjBHhibwwXXE/9NBXYBiE/Z60=,iv:rcuTLVSZCMa8kJGv70I08RcQ6wv9H0nTemIAvdoLoyA=,tag:ILwMZ/KAR9mJmCsr7IP4VQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
