PUID: ENC[AES256_GCM,data:KfEJNA==,iv:D7677dc1E/jCiZeRMszMAmfZ+jKe0W2dK5Oc0VPOY68=,tag:uHRfLHjdDYe+TZXT3j+bdQ==,type:str]
GUID: ENC[AES256_GCM,data:LOffgA==,iv:pNm0JH82B8qKIpDh+aGtrRGE9XL1RMA2WY4TxAzWeRo=,tag:UUDUb7R0hjEX1ofy7PpP8w==,type:str]
TZ: ENC[AES256_GCM,data:8EIEZLnpqv9Sdy9dMzAat4whUg==,iv:D8OUSGaAVJfb/8nCghum+Ap5mYeZtzDPtxAaxb/MDs8=,tag:IVT31vPG1UQLBPaBTKUEIQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:eW4VLuAwDkLSwgTTGPZGVeferNr5,iv:5bOXPt6SjhdhOrULkSZqyqeYgdwGtFNWFi0uwMeHlQo=,tag:wudV0H5rNtwCHnMOm6rhNA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:l2qavas35XliVn8R,iv:BPZ5lwMKIkyS0rPiwPb0J5yAsJMj+vX2OTaoFglP9+Q=,tag:Hp48UhSLLXQJbwGLoGxvwg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:Y7rB4diy3NMvGw==,iv:Py6nuq5+xeYiO7JzngxIck4wLFqL5voBLO1OSU+nmN8=,tag:oaf/cvrMa40esTucRvD1Mw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYnhvR1FKL0s4OWNOODdp
            SEUzSmREVitmYkwrUmtQcDM2aExXcGc5T3d3CkpvZ3VKQzR0MHNrSFR2dkdTNlZ0
            WkhWT3NFaHRDZFlDbUFWcUs5dFNUQ1UKLS0tIFBRUm9ENmJWdmZjd3NpM1RtMUE5
            NDF6TzR0NU80SWFVWmdzaHhkUVY0N2MKvjPOUUdTVtGY1dVrBoW/99TgLR/GRvhv
            xrEhklgyMIhn3TXsbI7IV/+zKF0j0tQ75pIhM2n8hPcPgdidW2s4TA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:17Z"
    mac: ENC[AES256_GCM,data:FeCbFiPr5vZmZntcEc6gxOv9yPgn/N34XER7n9ZX1Olnmt66v+FPpLHPONVSq2VA8JDd6VLQmWOYtX8y/JPSjMvMu7Y1qv2tOEHdfrIEprvNu4Ho5jJLRIakZN5HI/OS4S/uovWkkPFAVo61Ay6kFqgGohDgBIl5/+ULATGYgAA=,iv:3TeJJt2EfrO4rXRbG9iF/6ELDONs4PZEAIo/TmNmKIs=,tag:RYEyBeXd70NTn1HlIOjZrA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
