PUID: ENC[AES256_GCM,data:Wf070g==,iv:XUt1R9u9GSKmmL5BR6yb7Hr8Y4x4xyQmM6sbyvsUVCo=,tag:u8p2qsr410W/+EekeRgNpw==,type:str]
GUID: ENC[AES256_GCM,data:PdzmbA==,iv:h4uYCCYSI2SD+oGir454G3nuKD2AOzB1JxUST1/MzUM=,tag:8+mI/63wL/m+LTFgw7n2qA==,type:str]
TZ: ENC[AES256_GCM,data:OkqWkAZ/x73dX7/szhwmato0uw==,iv:nq4UwY8KDdbIMVQmdqR7qrI2h2n5Z8MTlW0QtziBSO8=,tag:ZGRE6NwF16LkJ7eXntsKVg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:qan9L6Tz0RpbBj7AKLH6mcm763lC,iv:eDmM1H1KBeweJfGcT8qoUMzjDXA6ZKl1uMH3siqjjsw=,tag:tkrwRwf45v/TpFfd7Tn4Tw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:iS3nYG+34K/iiYpd,iv:bdDKPxlEWXApoMoldcI9gOcvklEaHjoWlIb9NH5BaWU=,tag:84GR9Sv4ZvDDW9WF8F63dg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:QJ6FxEfQNbuEcQ==,iv:SspSS2Evc+WnaB3mar2ho65mlMfS6HurUKJkNY9HxWE=,tag:inYrOVGo0m6rC3xJxddB5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5U3NHdVdaWmtpQ3FzNTF5
            aXVNdEdjTnZrVzdwQnYxSk00ck8yL1MwZHcwCng3Q1V3bnNyZWJHTGJITFVZbHlC
            OU4zeW9Xem9WSm5JU2VKSU5xZTRDNGsKLS0tIG1XQ3FzbDNTTXdJRXBXVmJqWldP
            dWpncFVPc2c0QXk3ZmJtbXNVSE5ONE0Kt91iAYGiapsad08SPGj5y3UVhNYvYrLz
            JNnl8tj+ovnodpZUt4V8tPRR4ZuajftqoAdVW52HdaGrIqFEbvtTzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:DT1Vo7YKJhdBA9+IUgYpUWm7UPDPuFc1uTvpVIBoPgoihU4o0JeJrdUWtDuokcYsC2UVnVP8P0g2q6FzL/VZbE1CjuEugUD5CZxnhCFdBN2xdSaYghcNFDsIPb8A1uVjCQJAMeDYdLpA4hdQr4SnerCxcSzt+OAwYcXLRpFji0Q=,iv:U7UDNFRgsGjMeT/5Gk6oPU34U7jOsYaDokbhd4P7ets=,tag:xaVz7Oc//pJIjJ0iNv2JAQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
