PUID: ENC[AES256_GCM,data:LTGEUg==,iv:oRtyGa4jOeyllvUV2YfR29ktXlUxwd6wsYRzF/mT7Wg=,tag:fFeo4aNA6T3I7477sKwamQ==,type:str]
GUID: ENC[AES256_GCM,data:EmED3Q==,iv:gajy3ksFAmo0RXvNXnm9LzK5O4LbCQ9j0VdjKpy9OvI=,tag:DE7czpxaU3EwnBw+08q2gw==,type:str]
TZ: ENC[AES256_GCM,data:gh22wdBc6+IkxUScWqY7c2xiAw==,iv:FERj9Thy65xD3hzB1bsUSPpnDH6VwGyE1H/TLXKUD68=,tag:9WGLDGY6LWIJJ6IXDkyk2Q==,type:str]
BASE_PATH: ENC[AES256_GCM,data:Te7kVKVIFXVKE/UUBAXqnPXO7Dmx,iv:X3B5SM6/ekbayXH3HdCS4ePBBsRibjjUiLI2xps3RL4=,tag:G9Q0Db30pdXYGeCTA+6dbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YUlTR2VScGIwZlRvOC9K
            Qy9GRDVjRzZXTDF0Qll3YlFVSnZEVEg2RTFBCkYrWDZ4UkRTT3BiZEd0d1hhZ0R0
            WUd5dytYWGFoV3lHZlg0bWFmWUZ4QVkKLS0tIDhLd3EwYW92RVJBbWhLdzJIZ3RV
            bG9zUlNrMTQrVVZMNFcrakY2Q0xnbGsKMCou5TIcDhlOvLxuH2Z0ZRnUWJGgq+9/
            Ho2chpgDndK0p/43xZahYk/k8hqkUt+YyQS9s/DlmYadWGtO0Vc1mQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:18Z"
    mac: ENC[AES256_GCM,data:edrHHyOc/CwuJTRk4zINvpRXoLaiHqXPESeieZyqgMYPXrR8QEJTS7gsicajRhUX5II9vzaJ8QDPVLpmRnB0VbfyMRtMj8mlbUB2Nq4QIWCEWOKJ8FVDdw27BYIWH9RVvIENxxdUIoSFqT4NqXPNBaGQcFkOKMUU0sAy0e/P4lc=,iv:HdJhlgcrCdLkPtC/VcuXSSa5LMUm3psN5yTYykHAfko=,tag:ua+tmsDZyAuYvFCB9WEA1A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
