PUID: ENC[AES256_GCM,data:EsaCfA==,iv:KgycTsTXcfL4z0tet4cvbq2MroBvQPjGYDUNNYsgv2k=,tag:pfelpQBZ7Nozh1OJ9gZFDw==,type:str]
GUID: ENC[AES256_GCM,data:e55oSw==,iv:p7vxNjtqEDuJ79Zf08tsVQU7x1T6q36n4NGZETfdRoA=,tag:OK608nwKkW6KAH1lJpqAkg==,type:str]
TZ: ENC[AES256_GCM,data:JUuwjkFzMK6epr1THjrFRlLlsA==,iv:o9GJIf8ULGE4C8+TCazsraMc7/xM7dhwP9fg5WIoxnc=,tag:6DE+VqHmCNvu+ZZ1qd/W2Q==,type:str]
BASE_PATH: ENC[AES256_GCM,data:WTydkQU+6BDzd1/P9m6lUT1f7GEO,iv:EtcOktWqrHJsyhOuGtEwNTDHjg6OiFI6lqt7etSmuS0=,tag:OdlxNfr7E2EPZmD6ri4CNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDS1I0WHQ4TmFoNWpvbmUw
            VWlILyt5NXZ2WmhhV1F0NUVnajlkZkxLcW40CmJCMkZmaFRsMnFsN2pwWG5GY2xB
            MFh4ZUVRNGpFZHNPakxDS1VYTzVISVEKLS0tIElIK1VxZ256RlhaQVhSVW9RNnl3
            dlJ4KzR1Y0d3Z3g2ZCtmTURRSTVNYlUKR1v2zYL4gxXJsfR6ZM39NZ0aEcN5YyS5
            mVDS8pFmIARHiSBeQrBjWEvHtoKOrFxn4D6ywmZerJP6avrrrHlprQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T18:25:26Z"
    mac: ENC[AES256_GCM,data:Wdg26Qp/rFnGRHePXJnNx0dPmy7Uo4wRe1DghW5ctEDnybT9i42a0HV4m+ae5sc0dUoiC+MecS/7qsupSKt04ZRUx45lPQ6NBrgiHXuvKncyeBVYR5hpOcKT1fvfFpzzK2POZdfBHo1A5gWsgRvIG+qdFRjeQOKqyYT0kJqWZQw=,iv:CBHIoyWQ8bKmfh5DZhHC06VVD2EKa/dUBJ8iIuSbOy4=,tag:4Zc2jvmYLcN2i5nT+K94QQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
