services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: tailscale-nexus
    network_mode: host
    environment:
      - TS_AUTH_ONCE=true
      - TS_API_CLIENT_ID=${TS_AUTH_ID}
      - TS_API_CLIENT_SECRET=${TS_AUTH_SECRET}
      - TS_EPHEMERAL=true
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ROUTES=192.168.1.0/24,192.168.10.0/24,192.168.20.0/24,192.168.30.0/24,192.168.40.0/24,10.25.25.0/24
      - TS_EXTRA_ARGS=--advertise-exit-node --accept-dns=false --snat-subnet-routes=false --accept-routes=false
    restart: unless-stopped
    volumes:
      - ${BASE_PATH}/tailscale/config:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW