PUID: ENC[AES256_GCM,data:RuHpCA==,iv:fkIp+oebD+yECDmjDzSLinv4P5SNKDDq3DM+ulV6dCI=,tag:e2c+0SGMUlNLzknZkA1rVw==,type:str]
GUID: ENC[AES256_GCM,data:miv6TA==,iv:7e0v6jCOo9mKqnrPHtt6FK8VLcPf/S+R9LTeboMlZ1k=,tag:e0mmdLdcyn4GpEPOvU9B2w==,type:str]
TZ: ENC[AES256_GCM,data:QDdkRh1LQLV7aj5ItpOgrMBa5A==,iv:3ovTlInQ0GihAKkoxpaCz96+Jg2x2vWQwf4HJaCE1tM=,tag:sLSC5MwJN1pO+gqrFtet+g==,type:str]
BASE_PATH: ENC[AES256_GCM,data:5qJjtxqAHrwH0zYJl0fLLH/Bj9RE,iv:yhupFshgS9KjNJf/Sa1mfkBStxl3lty7fIyt5wQ5WZk=,tag:l7WxOgDLNUQ+ACkQ83o4kg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:eC3praNmPdK7sF71,iv:tLledU/2TU/jQQRFTgloYkfu2Y5F1JqeOT9w4a1WE0o=,tag:5B/0dgM9dZMAmSmE4YKHQg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:o8x2ZQV89hb4Vg==,iv:6QCRgFYt9ZAeEksK971nVF1j86mXnX5JL3+BAhBeS7c=,tag:zODsMJANosztEacNmvORpw==,type:str]
TS_AUTH_ID: ENC[AES256_GCM,data:s+yMDw+NpHA1BBAl4eo3JHg=,iv:mk4x0eiNihgrAzWYRDD/zMfP4clverOzPDzsFXJwOOw=,tag:kdYHnekz9ehhu7UODt+Nhg==,type:str]
TS_AUTH_SECRET: ENC[AES256_GCM,data:fvnuCO2iDBG83aWIijasXc2mQxmZGgH7mOCQvP79xaNVubseJxOJFnJjocNwISBoBl5P+KpvbC7afVUCC2+djg==,iv:WgbjbtbNo/BIoh26x6iM+XbeouZnfnVodVFgdP3uvRM=,tag:5oXupiLYw74jhRUxxwyAAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTHFTbmhTVDBhUFRlMmNr
            THB4bnMvZjdOWXVTeEZrNXM3YUxIalN5VFQ0ClZucjJuSzhKSnYwWlZIL0ViczJ3
            dG5uOFd0cCs3aHo3bmQyYm8vbTIvWkkKLS0tIG5LSzRUd1E4L3ZlK1NHdW9qRXQr
            Tm9iUU9ETUVIdHcvakl3NWdRWmtlVHMKEFS6XG3fAzuQoPsOxoAbgcThTX5V6dFz
            Yue7Cmhs77Udl2ACE83vBouIx1KR2s3W8ZOS/FwE2Zvu8hbtxjM0BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:wx0NF6ALhOf/EyOXClTYEpy2dcloVnN70rIRT6FrBqjOg6JrwVIj4vuPsUihXYZ5ep/2J3LOz6YgFHf3N82sf5Uje7t1X+CM+XhKTfnvJPN7uqk+EP4T23tw3ATus9ijItg+ZNxyyC8irJYvHkhIyWLdjIf26/3ZKPjAVqu7d3U=,iv:EH+HB4ifNuZsPQcD/FkgyEEhRr62XA4nzbvgWeo74w8=,tag:6QX2e36ZdFfwH9i7xagU0A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
