PUID: ENC[AES256_GCM,data:8FwA8w==,iv:j4Pu1yDV97ivFqkjv+aQ+odxSxR+OVLSunaNM49wOm8=,tag:kRcvaCimDl/vA4AcBNtI4Q==,type:str]
GUID: ENC[AES256_GCM,data:KPMu+Q==,iv:RkQ1fN4y9wMFnVWeRKvdutrOma0VW6Tea5zsA6sa3co=,tag://Blvt7INkHwmHcg1KypIg==,type:str]
TZ: ENC[AES256_GCM,data:YGWq3uxXbay3hWbEPz8ZPVuaHQ==,iv:fqRlqQ0JZ3ArszG9+pPD+LmsmdqO9TwlFlB7goXr0oU=,tag:npupHUk97EIWYMaG3H5TUg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:j9JidKHoR9Vej7SdoP4umy39TxoD,iv:kbFg97GLXLd0u1Fbv17lGlfrZmFD/hT+3rcSnWJXsYQ=,tag:l97euxRoqwZb9dpA1v8fnw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:F0Nby/tT5qmSZqCL,iv:X/gChtg/tPQhylQNwFGzUrRcJKtjO0t784tAyPtFFpQ=,tag:/niejH72IzIUXGIj6VM0Sw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:YcqFM1Zmc/xF5g==,iv:iU6uuSs620c71gkiRgbOVOlzJn6AoBSEVv0z9PMDO9E=,tag:vLtCvEtREZ/KmyS92zo1Qw==,type:str]
TS_AUTH_ID: ENC[AES256_GCM,data:L27aSspdsxN3uU84Gux3oZg=,iv:Cjy/Gq9DASlkfJips8uQatRnSRC0Wi/EIlXrNONVPCg=,tag:wDWw1PgnvrHAx+PfrNE/qA==,type:str]
TS_AUTH_SECRET: ENC[AES256_GCM,data:HgOwfvGGZE3pORB6t3kz/+d9XZnIx+zldltorsP02eDfazgR/4w6HRWlRzPm4Nbsj5BwlpyypR8IK6mCObi5IA==,iv:4BQ7AhBDhFEZ20nu7aJAwG8jEkhKnQfUqsDK+Veeo7w=,tag:fO5wjHSVxrZHG6Fh7bzdtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Vm45U0k4ZUdmajNWZVRT
            L2hoTnZWQkVQaVdtUGdjeGhGcEdySGIyV3lzCnR0QzBhSjh0RndXZzFvaDJ2NStY
            RUlXSHBMMlJHSGJmSFRQQTRBVlpNWEEKLS0tIFB2TDYxbUk0Uk9ZYmxUb2V6UjVD
            bFZHM3RwVUE4TjR4UW9sblJaRzVKdTgKMH39lV9HI2s10ukQjDwnoBnYJv0KtAaG
            yU0lRLeFV7ia/m0uVSeWFZ2O+cR2tP/pzddtN6BK/o7bLerXkdZwbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T18:25:26Z"
    mac: ENC[AES256_GCM,data:N8xMuP4Bs6OnUC82ccDh5NDM/+XwQbfOdkuHQ7sdLmhSXVkiSvATMIWIbshn5zBN2JtpOUYvkRPYgieHxYHf8DabEjta7/y5grcc4yyUYnbtcdHgBnaXWGuQAYkZ6ugYIkpzoJPlGY5TxVWpCUeLHSGpfCTfUWRoemfiviNJecc=,iv:q5eB4CSGyo0Ls/37sEZOE2H+t/FnTJ08JAXUnQAmeKs=,tag:19toNFv3AXIIjdkls6OfcQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
