PUID: ENC[AES256_GCM,data:r4CFhw==,iv:1xlIaIi+PxrU9oxk5wimUHy0iAl/AzUxMtBwEXlr+0w=,tag:EpGTrcHIgWbt/aGjZmIbCw==,type:str]
GUID: ENC[AES256_GCM,data:4fgHqQ==,iv:Q4sj8j1QdtvoWEbTBoA4NyDvL+HsU6Zqjc07g7zhSrY=,tag:w2tB4TWWzgMZ9ThUy+2s0w==,type:str]
TZ: ENC[AES256_GCM,data:GC7H1IEgGDn2bdGLOWXFqrVVYQ==,iv:s0AnryqF5PvkxnwtmyP8J9MGAkBFzJscLwVrrRDsWAI=,tag:GK2jGSwL0g7eWss+E2TxIQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:VYv8ftxWMwyl4lMDelctrxvr0eNF,iv:4APEC7f5IX7ekr78ST31mWfANAmtCPAKYMjXDjP/fW4=,tag:BA3scKiuRGJt5HlSDWYrJw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:98HDMsMPn6/vz0+5,iv:3GP4hHCnjWzg/DFElXeeVS+93UHCDxAtFUaBRgQ165k=,tag:qSVIj/ROzICykwqareCAmQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:ln2wyd7d+6Apqg==,iv:YZt7eL3qRab8DS9haA9uvnKH/amrpif0Xl7OtXjsWwI=,tag:ExvZUDLAXNfEIGJTnvLcgg==,type:str]
TS_AUTH_ID: ENC[AES256_GCM,data:0zih+EWAl8zKjeH15/582xE=,iv:QipW7IaVm2GxHUzLtvw3xqrC2vkt99y8mrwxCKBd5Q8=,tag:1nEyWM5dUm8N24uPi1WVZg==,type:str]
TS_AUTH_SECRET: ENC[AES256_GCM,data:OIVmyAipZc38sbrKpF9m6+C0cViaeQZ+PJ4LhDyRds3vm7Tlzw1Q93yrPyAdEunkx8uYpAu99Um8JdL19UBCpQ==,iv:kUw6WHii9T8Pq3V9MnSVuVpv6vHt+eDfU4eTJGCz3W8=,tag:4BIl+DYzU1J/iK/Q6oqxYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcUxieTJlSlBlb2hIcEFp
            b0tKSlFZVjM5aW5JdFA0dFU5YlFIYUxnR253CkduUEpYeHE5azhoQnJjbXNtTXM2
            djU4dzVqdTBWS3dQczhkbWdlU1lvaFUKLS0tIDRzNTVYTVZqMUtSWUVzdWJHTzVY
            VlRDTUNRTFZuWGhzbjc0VXRyQXBDb1UKXmsXXNYrZvPuRm8viZyZpCLrrIzlUM0j
            hZ/3zAvWNd9I9nEQldWDJQjXF1ReAfQVDyydo6cEZNFkMTnPjPlHIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:Yfm6U1cT5662j6v1yb+EbFW1r4oXdVVaJkWz7+FbfP5euNbjkuWsoaR2W+OXmsXe/Q7zZ+WhhHNmeC5EE9RdwiWvwyERY6nZPj124uwdSa5MZyhscYXkIBe7TB1bEgZgrceKHe8pSoIeDcELUDp4xZuYG6Bc1lT6+QNhUiYIF3c=,iv:0924HVIhXGK/U5wLsuWir67wBuNhMmvgt908Cpqmusc=,tag:QAER3H2dGym1Sf8Ap78e6w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
