PUID: ENC[AES256_GCM,data:7PiTkA==,iv:cH3AnECLaE5hQwHtp+vHgW8pA7N+6lH5/itYcUDwg8o=,tag:9QkSfeDjZZ3UGOxLSaDZLg==,type:str]
GUID: ENC[AES256_GCM,data:3i0hYQ==,iv:UU+qgz8mc2AlGsDaq6XyUuGidnsGSxYmGdQ+PgpzUe8=,tag:YX8pphLpwvCv5K5EnPHoYw==,type:str]
TZ: ENC[AES256_GCM,data:agfvnBMy6tQESIaa0t19104VKg==,iv:Zu8XtOdFfm5eonqQwq5ZCgm3778sCUYqcd3v7l0el28=,tag:SYQMtWtDYKyjLcvFIC98XQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:4/YgytOLK3b9tnlojVnKdu4VXP95,iv:ZXM4F3rMyFv2zSpa1LAsmKSAMloE5oj8XxMZ7slswzk=,tag:jxHJgBLE4Wm8g0fTFOxjBQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:nor7bU20CPatkeJu,iv:SKBpzdn+TBAJ3HE0AcuDCldZzh8Xga7J8kTYzGzIc28=,tag:rnl3I/fNtOF8nN/Wz2ZOng==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:9unIjjcstrrQYA==,iv:iqmeekdWxS2VSuP/W9SXlrvMvCS/71uyp1Wn11E939k=,tag:6uqpKchwu0k4PmleHLA48g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybjBOOEhnTWh0eEhLbjhH
            MVVHdmFJY0FkdERZNVdTTnlTL21hSHR0Z1NnClpKaHMxUGdoZGRIS2V6UHkzL2Ny
            Y2lqdDhMV1VOWVFMNnY5VnNqZWM0ZDgKLS0tIHgxcUI4dFZaZ1I0VWU4T1dWbXVY
            RVJiMVh3VnphMXRpR0JZbWtIM0hNNkUK3BTz82sMK2h1J05DB/c3iuErWDPvGuiR
            V/xLeTMSrDjdeBkc2d0GzxN1HG3qRpGea56L3zDT4iRiJ/qgnukHhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:QGED1shR8lH15/ED/nXrk0cyZxrNzBaGu7TE7MFzKit5yK6KEoUNysc4LdCVPE9QTfS1h5W7io/b0+mXEFG+TAE5NovffE9ltruB4KdEOJ/unFAtgKlOhKop7Q1WHT3pbRLH7k+3YyRD3stImE+Nu6fEgcbwm4AFCu2UADbPN8c=,iv:Dzu2N1y6mZ8ixQtlM2VeC84YjR6qWmcC8f2WFKVWXCI=,tag:mOTKOwN95/eWukTsNFcaug==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
