PUID: ENC[AES256_GCM,data:ZalI4g==,iv:/3vsg1Ovh/AQ1Wq5jkUMwFk0XvBkw7Qqbb+3iFw9CRA=,tag:9Er0hJPCOPOJ1U7FBosP2g==,type:str]
GUID: ENC[AES256_GCM,data:MJfiHw==,iv:ArT30SRKP6lJOPAhuxbxLp/PzYGTPozxKW/iwyDHd3I=,tag:UVhktLcjUinnGtbs6nC4fg==,type:str]
TZ: ENC[AES256_GCM,data:KgMAbfH2TzJ1CIVwVhM34xqOeg==,iv:TmwPUSrhVTlk6RLGDtNAPh4ZGVqZ8+IaKblkzThBccM=,tag:Z1S8P3tbukLh7yo/T1dAZA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:mn1UYQqa5v7i/K03ujbwQBCxJTcz,iv:fWXbg3wiv3crejM5Z2qF2PdS7pmbWlt36B6QWR8/THQ=,tag:dz1PxizJZkZAw9JvMfqrdw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:tzdZUp3CSX1ZnyZL,iv:/V+iPR0osClXao9oG2ESHv1IcQM/TGhNd642OdpMOEo=,tag:+usOr9FT18w20b3mhIMhpg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:U0/1AlODrRf72A==,iv:+5sV3PjqZiRVpCe6M53Fn1FEZxnkva1c3WydbcfdnVQ=,tag:3CFtAWEhVlc7j4z6uIl3Qg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcG51VnJxbGcvK3NpT2pS
            ZUt2SStHYlNoN1dTUUtBd1Y4ZmxITDZLL213CjYrT1lnZGFBaUZPakJpdGsreFZv
            NmhXOVpGeXlHbnpYUzQ3ckVnR3ZpQzQKLS0tIFlJVXhMcExGRkQ0OVJjemg2WFpy
            UEdUZTZYaEhiY1Z2RUlMNjZydEtuTHcKLTn23gnXJxr3GWXQLxbQiflFAm9p9uyE
            sZn8kUN+eM3HmuTSwzv5BlM6TNXW5ZjG7QnmOIlXipQG+2Py3TDT4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:gfcX7MMuupgj0VeqIZazZYiLy2jM4Nb4AsbvQicxiWguJFPx1LYG3Y6Wp+xg4pgB1IsCwZs6TMWs6ZQp09OBRelmS3EbK0R8ir1j5EdziLgeBi0XbszBP4JY+7Ubazrz7jk9lymtfz0ArhJi/Gov5kPIjyUuSwTGGB8OFNvGVS4=,iv:n6HOm3a3FqazvBQkKd458avMV8bU7moeskTpN4RnFNI=,tag:+Cl+ob+SxpplAjZ0/FoTfw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
