PUID: ENC[AES256_GCM,data:kdWuFw==,iv:ZHMPngTjiB9NL4Wo/XQxO6lQaQPVGWt035+H2U3U6IY=,tag:FL8T/DuQ5Q/c1Lrhv+6E7Q==,type:str]
GUID: ENC[AES256_GCM,data:xGiGtw==,iv:Vx7c2JIiMRGrg2mCd0G3JbUjjLoqN55XuchLFAt6huk=,tag:FldTiiciALZZnSnN/7rGBw==,type:str]
TZ: ENC[AES256_GCM,data:VMGnprvC5rgjxWFuAiPCACr9xA==,iv:4UrHr8Rm3WERS1LSireq+uYfHJZBJWadJVzGO5cUS1k=,tag:9xyT5K4FPoMCNASBVMX6Fw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:sM+fs5GS7Mgv0BhFJlrVV7t6xQak,iv:DvI3J/E6XJlgo4nSxl/+P3wrT/NNMTf+LCN4EgQyoc8=,tag:PPQu3ttDWkbbh2ViMoO7Cw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:B8G9YasaXH0JwCVT,iv:Pw46GgwNf3S0/iRO7mB+Kwwnpf970h2M4xWTT1IxsG4=,tag:XRlVkOZwt/zoK39h39+r1Q==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:U8vNJnK1P9rRVA==,iv:yYxBHkXPzEAXUC7CrGV6nSgVV0E5lrcBMBfQ91aExkg=,tag:cIOv932sQcMkNWwuESdorw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMU1YU21MYmhrZzJlM0x2
            S25mZ3pTQXl0eWhiRGdWYnRCbHRJU3VNWW5rCloyVlpsYVpKT01MRVV2bWM1VEJa
            UHd6SGFSOFppV3NiWUNGVk9oZXZqa2MKLS0tIFBDR2RzT0lhYTZXQ09ORVF6V3g0
            NWt5YnJtb09nMHZlY0lMMVVPa0h0WmsK0LmdHTW2Fi7ZIVCQtDNDG1RyHN6RCyNt
            TPw1ssX/ULGH8Kef6bo4nW3REfVOEoV6vnpxECuJ9K403k7L1QxbRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:NbXsUGG2+vKTOMFikoUjyYlxKgMn0GhZUY6zyD+goy0FwbgyU6ndEZQuX94f8AUICLNvw0suFFfXI3eGr9qJINOy36pMTPSzfA9Hldh6c8vKey0VKIPIQC5q5JTL8/sg3Yb500iO9UiYnAtEPIJGX6lKKZMnInQ1yHbwpObXjLg=,iv:OptyhfIswu5DEXxFBsnwNtdYVXJKHjpHts4yD3Zpecs=,tag:wOvmadWZQINNE4UplAqC1A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
