PUID: ENC[AES256_GCM,data:qVQcxg==,iv:ZAqag1H6bZ83yhwipxMXv4DZYPzUDnJwbkccp6FAo4c=,tag:dnZ8IH82wZn7LttJ95FoNQ==,type:str]
GUID: ENC[AES256_GCM,data:wEACnQ==,iv:UzLL1zzHpuSWadjD7xMYFggyTGc1zW4kJ7jqsKTkRAg=,tag:d0ENFZrAwcfiSAsyZD74oA==,type:str]
TZ: ENC[AES256_GCM,data:W3U416YaSstNgma8YlNmYli/gA==,iv:fLJbJRm5aNL9tbRQFKv8pH9g/Fg73pDu9zAtXv2NQr4=,tag:zkE1S3+ZevWxfjB7YllYfg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:tTOVm5o0csdk920HXh/KtRpI4Nct,iv:4+9VBZ1/MKrmhHwf6tcUw6Og4ryioL9Rn1ql2+aqSkQ=,tag:GBXP036yc4u8ZQSQD0xhxg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:/9LNCIjoRybm30aX,iv:ixfpr3lAereojr/k6pucDWR1Kf/72N1G1J/d2up57vQ=,tag:YpmTNsOhL24P+MZr9QI8gg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:He4+x+CXpMEq7Q==,iv:DwmqIYZkskL6ws2PtNKHI2dM78fXZM3yyNTA4KGktZE=,tag:ogRj7Anxtq7Xw596q2hd0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQnRUbUdkRUVSaXl3RklW
            U0tpMVM4bEJKc2V1MTJRY2Z6MDdjSFZuT0hVCnpXZk1CMnRoYkw2QkExcHE2eW1Z
            R1Q0VVFVMDE5bUVQSHo1WHJSWFh6cmMKLS0tIHNRQjlveitwbTE3T1FkbWxOZnoy
            NG4rZ0t6YWFXYlJLVFpIWkRhV0o2c3MK3q09S066bkj3OE5jXuFPNWtOKXEz5+5h
            73CYz8cuPAglKYjPLAqKVCQ19H0s9hsARtGub6OUK3Y/EesEQI42Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:bXGC5w75lOVpr66H22kpuEvIJSkZqczN6TMgCj6bG3yiX5WqYAshj79PCv6vaHV24m8LlnhSY83iTcSwo92eR2wlskNUAkfgud3SCKACZzRGx+oA1+YzSCghbgz15DT88QcmqLplAyUakcZ6mX+H57AisTNEBGkA9fpaSseQ92U=,iv:9GE9sQlwH5zSAnf5gZsgFgQGzfbtEWbCqg/OJTAYz7w=,tag:PGUH8eZqNJsckdxSxNAqFQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
