PUID: ENC[AES256_GCM,data:onolBw==,iv:PcvrSW9vmwQLYvvvZMqKah8him6oRnTw7wrHrJxwaaI=,tag:zKk0yRbsPhlyyA4IlKL9lQ==,type:str]
GUID: ENC[AES256_GCM,data:L4SOzA==,iv:O+6rZOslEzrRrttPWY+jmiPo3m4fRlbbEk4qj77ljhM=,tag:x8KCigAek2D/2AYUurWKoQ==,type:str]
TZ: ENC[AES256_GCM,data:bC3OWSO+Hm1carleDQUVemTc1Q==,iv:Y10I8/HGDJ/m82VA616Z3A4apZ5g6yfb2IFkwlfeOgE=,tag:eASkA4+eH6q/+lWAOgThxw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:VGh7IMEnhpmEVqIqNjpflZQuQrGp,iv:/KwKe2C+XnCq7MN0ivyd6geuSWwBflx2KaPAnhsglGU=,tag:iTHlCizkZHfEiAhIJEJzgQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:jp3SdqBUTvE1j/ED,iv:plIPpUyC5mI+n3NaeRcBO7IkqdAFATF0Vu/CCODeupE=,tag:w2CJT6PhNW8DW99y+EzU4g==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:7WfQCSDhvKLBnQ==,iv:HYLag6O7J4NgxwTk/yBKHfrT08JxIu/3ZzJpTztXedo=,tag:ZMSmZmMGP4wOzqsEvWvXvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQekRicmxhN1hBTERVblZ1
            NjVwakZLaklDSlUyV2l0ZC9qdGVJTC9pSFNJCnBRTlVxd0szK0YyQ3BtSWEwbHpN
            Q2dJckNUREJiUkEzNlNwSlUrY043VDQKLS0tIHhybHlxY21QMnd2UFV2N0Nwb3M2
            RExNRm1DVHpJZkpwMk4vRENZdmR3UU0K3fCwlxi1IEmaHyBn06k0urlVKT4LDxaQ
            QKvNaW+yN4wTfeypfGAZQTNiLZab/TTd0lzt0NgfLHB3lmDy9hR5FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:tTQI/YW5CxL06AgxNyZy7AZHZfMI/YhnM26R7rdzA9//ABWv+MhlsBhrGHXKkTN2C1e+pfCy7YCfJb/JUFLtGUElst7hZ5ZHL84V4Is2zTvVhSQwxSmQwDaxudsDXBsdWks0M0x1N+QnNXMm0M9uw44mRDPP9TRFN+TbvZm98JY=,iv:XTA2ztR4lUx+p5I/+OCKh/RAUBNM7+9jBJlv1eK+r2Q=,tag:kfTtE4Df5sAhn0EPoynfMA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
