PUID: ENC[AES256_GCM,data:vHHlnA==,iv:mvUi/bby2E6dk2/YfpeaVZMta6hWsUWQjpJ86lLdcpk=,tag:Jz4sj49eJ0PAkMzjjsmAyQ==,type:str]
GUID: ENC[AES256_GCM,data:7g4e0g==,iv:SPOwqH0yO4xcFze+pZZYBTqq3V8JgRIumpmdvTxyXkY=,tag:8aqrCd4FJwF2L/BOeTjTNg==,type:str]
TZ: ENC[AES256_GCM,data:uBhduDexScBSMq/plH84J0PgGA==,iv:+rr8eBrO1xfjASxliBzWDnXJOKkOOOS9lY3o1gQ8hWg=,tag:RHqaRooFROSJC3Py6qnQTg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:c7mh12hwK5uUpFcQ8nW9Tn9MTqZh,iv:EIpV74hfU6TsuG60tCPvfa0WORedEMm4vMorBLq4Ib4=,tag:UfeCj1kcaY2+EtQnd16w1g==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:EsqoR6ArrUiiFikn,iv:yFuAwt1VZ0UJn+H/ndPOHVXaRAoz4XVatzSaDaVT7CM=,tag:AiyRBnkk/xFnepEZ03VpSw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:ou3eWaVoOKjVCA==,iv:KJOPGs61/CyKWkpu483HK/VSvpxyADtLAbuvelYB58s=,tag:TyG45j9N3JCeTPLJJyB3Ow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Vy9hVkFQVGVseExNYjMz
            akp1c3pPQXRWbjFDN1hVem1obU5ZZi9pQ0Y0CnVTM0MvOG0vM2ZDS3drNjFzM201
            VlZra1Z1VS9mZHFTcGh2TVdweVI5dnMKLS0tIC9PRy9wSit5SVR1TlR1V3drOEN5
            a2daNXVSMlBUc2t2dW8xQXlYS08rTGMKdOcR4u3S7GyG6vczxkbhyEK6Im/I5+Ck
            07746cA2KybXCQ3NJB3gQio3e5D77J6S0IiI7gHcS2w88kQ9Yec7yQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:17Z"
    mac: ENC[AES256_GCM,data:CMjeSQ+7ZJzPnM0LzOxKbw6H5mIEMWxaTDorGK/mm8lp64a4FoY+M/oHkZD1mQfnoaGIrXDdzDZst+AyrwFyqd0ybVgACN4sUJyQ3xnw2JiMkAwyrzID5Sou6HOoYn7CJVt2OI2dYctEl13ueRryrwhha+aHWFHx8b/4j6gUtEY=,iv:XSuOmdGXcC+xwndkv96a5r59V4885oDKRRiMV0czUsg=,tag:70gToMLn1LPS5fOAD5Xxqw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
