PUID: ENC[AES256_GCM,data:P0NHMQ==,iv:qBQlYUi6+9mBQAryrFx5nH6LkukwxNNqAIBOVrFeP6s=,tag:Au47Y/aOXLPKAtVI+CYmYQ==,type:str]
GUID: ENC[AES256_GCM,data:1JOfWw==,iv:9AuNZpbVUgxkXFzokMhtJnA2HDK+0szeRujSiYQSFCg=,tag:i8KBfhNEEg/Ix0kTED0QFg==,type:str]
TZ: ENC[AES256_GCM,data:d696OmG7TFvyRvwfdXebWXaweQ==,iv:gGNaw25xHGq2/vVFbFY9daSg76fYh9eSgw1o+H+X4uk=,tag:3IuHk0j+Vc0+MSSnwK48vw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:yYNvn7KNXiuz5xkLNmNhUSDOs4Ek,iv:Cq++7lt5+jivgRYFbvTTRR2GkBfx+GYdiNGhD7F615s=,tag:xJldR2VWm87AzHlECHnDxQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:K6zNvUJKG2ytFLYD,iv:eYDmCHfjhORYz2buIr9bk3WayDI5Y2mn+kbgctoLfKo=,tag:rgPcCszKhms9Agvf6+m1JA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:rJXqo0OcQC28Mw==,iv:qLW3oiYdIxEENfB7e0d6V2qpuf8PdPbvR42sS0o8EIg=,tag:dALTzofvxAUMzNDpMfE4Jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOVRCK2VhMk1QN1I5S211
            dGVHU3ZVUzRuMGh0MlBQTURxSzF2VmR6SWtFClc5cWE1a0UzREcyZDFzYTFxbElI
            M2hHWEY3ZmNzRzEzcTQ3VnZQVEVZd1EKLS0tIHFRMHFEMHh3RVVNMHQwVWNkT0ZS
            T3d3RHZxNFd4d3NZeWE0cElOV2hGSDQKqy/uygESzcMK5cL2ZnR4oIKwpZPiJm9N
            8Y4lF4kRWxb0DXx+EzBA7ChqTshBYGtCeVt73Y01s2tWUNhANiofIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:TioPiWte8grBP5Jg5PMNfHRrvoBj6KbgWT9657BUBXeap0IFeierCI6Vu7xw+ToJ8TbnDAP9Urubo6zBtPjFXdpsPospaqsgxdxkC8C+fYcQq7jmc2Oc8uzOysTWKFSmLV1/wdYPXajdmH9zgRv4XbpuxYMSAHA5OusRaJ5wA+s=,iv:TJqpzB9CulXtrlORANKa6LKYsg19BTFq4e+v5F8BwiY=,tag:7gNLlbZUbp6IgQrfhsMsOA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
