PUID: ENC[AES256_GCM,data:Sugulg==,iv:KhOmq0pNAXayBk1x1RtUROg7o2e6ezWgqDuCL00DNBo=,tag:fw8pvkOc009CghK5YM5eEg==,type:str]
GUID: ENC[AES256_GCM,data:TADr2w==,iv:gazV0hGte8BQTEjRGsuTjTSvdPb0Lewe80ygkJJ2cIk=,tag:b/H69uIAtKQFnBJNp2SDEQ==,type:str]
TZ: ENC[AES256_GCM,data:H/B+rqG959nSinmBqKFqEPhAFw==,iv:u7qVpSAoak4CO9ItPRSpXttjvGoSWX3a9UeDFFvpw48=,tag:98u6N0rVmjVd6f9NadYZhQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:YPpK1x5MhmyTrrleBQFVviq4qi/M,iv:x2iT6jBrEiWTtIgx+O3l2Mx5E0JjGMUNIQSwEEknxVE=,tag:9K74PBtHKVl8y5JVGna2Sw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:uIaAXWOy5RA1Y1tD,iv:uWtFo/WpQ8i/TNXxANCGMipY6vI7AvtFoz8ze5+VPNI=,tag:VA9g2Cr+nVFQOOKfcYw+rg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:982nyZ9iIBl51A==,iv:+WkdNxJrANaHMLu5A6yPYJg5JWFaVZq3wJYOnKpMRbw=,tag:Ulp6fHoGQJ7FBdJaVJj8mA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRkg1MDJHL3lTMkJTalBn
            RkwvWGtwRTNiSGRmL1pFb3I5akIvK0cwQ0JzClNVOEI1M2dRLy9WTTRPMlhkYkFZ
            aUtDbm1RSnNCMHpaaCtDU1hUeWo1TXMKLS0tIFdzMHo1MXp6OGxNSVNScnU5K3Jw
            dnB2YjFBLzZId29xQjlIRnJ6aVZlSnMKyCCGmZ9OipRDe3cghQ41xFO66YPoMqIt
            1SyZrMEwACKB1vK9ogTCw+CgjdR6z0yPs4TP1m5E/hAVWjEFfLGrOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:EIHYn4VVnBbYFTmVoLBetlLuBMm1HA/XfvCizc1rCAKGTOU56i6lHtiYQgSWGy8THopHjTN/VtwD8FhyMXoao6fQuOc1VWxfcCWiZFzBNeC8I5gQKn8HbSXUgyL8RGpdVT2z+0tOI7PkGNB+pr4Dgf5iCjHgdfEsPcINTGYVr/o=,iv:d6p/63CT8JtcfDEIdB5DKxf5Uyqnl8mPov+Q6ncGbzE=,tag:v3BLKwG9Epqt/YLr+h9EcA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
