PUID: ENC[AES256_GCM,data:ucDCZA==,iv:ywkUj8XLWoUttkNIsuk14aquVgvDZDAP8viA+ZBvToo=,tag:+zjWaWbkJMVPrurKZEv2Jw==,type:str]
GUID: ENC[AES256_GCM,data:TQGMlg==,iv:aUIMPQWXSz1Zn1870WMox5Ny8eD4tAqL+ysHDnrOOro=,tag:m7BRF+Z8COAC6do/NWgdMQ==,type:str]
TZ: ENC[AES256_GCM,data:QwMDr3V7+WwVm0asgss8bP8tJA==,iv:r6Z76+Bq7Y+b33BmRUHKvbH6pQEz2RNnIMzKVztFUhs=,tag:rsQicCpp/U+4vVjdyDQSQA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:f2ND2cv8MSIjnmZfag8GoVfWJBdR,iv:kuGAKn8ykee7Ad8X+gmIm6o0dkMdT7mjVnwoAJ44T0E=,tag:dVPiC46prEfb5at6OajIFQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:pIo9igICuF65+zHS,iv:cUal1VM8eHOSQ8mrxRp+d/6YkOwpfsWTnurnKeqybV0=,tag:ommyqtOPcnDfvmxoWhcN0g==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:TifoXH1xlDQjfQ==,iv:Q2hbdvd/nrZdWYspJJHAUhIJ0QA+Dja361XaONwyRI4=,tag:M1mcKDQi1hIk8oYJrOgfXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMTdSbmpndXJuRGtFNjV2
            VGU2QU5uSWJ1NUk4dnBOZXR0a1Bwb2tCNEI4CjR6Qi9yTnYzdnJlaThiRUs4RHln
            bGlOa2g2RzVLSGpaWVEzNUJuODFrMXcKLS0tIFpWYnVPZno2c05BQWx3WDZZaGZr
            cjU0WHJvbmZQclBnUnB5eHhJLzBPR2sKa8vUytFtDdzDE/kKA/0hWoDvuENZNgUG
            71FaUCLS+ScObSlEuCNcqSt9q2JTo+ShPMppareNnzvEsXGTVV8yDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:M/bFens6cuoQlFD5VObO1vtJAk/0B4Z20rHe/K3Lp/6KkvVYXWll24rdesGUPIpmReHWZwWlVOHRR/GqkJsHYku2mDdLCx691WKsqzwaGUqhm5M5vzNzrkHklreZAfQQ6KwW3SB6SX9iF3kImWrcbOmnPPS5qVNbrOGxX76aC7M=,iv:GtiiYqu9uTKqqqI5vWvEAxuph7ETS47Rzo+AN1vWN/8=,tag:cx4UuVBc5yRIyw/cqdraTA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
