PUID: ENC[AES256_GCM,data:uR2oyA==,iv:eDaVc/LIKU66dS7zdcpMvzh7H8OLHjvOKlm6oftWGiE=,tag:SwpmjD0iP/j76c/orX1J6w==,type:str]
GUID: ENC[AES256_GCM,data:oc+rKA==,iv:w7S8wqZLsrFpJaX3zFzy0VRzQLyMyyDT/Ylfhk61Ogs=,tag:kL4Bo8V0JMyVD37ubpV3nQ==,type:str]
TZ: ENC[AES256_GCM,data:FwbE/2rq6CnjOL4lib4ABlkcdw==,iv:h12d5t4f6+4rpwlUBVZvyK/brsbHPpLonF+Iya5r7Dw=,tag:NbHS+vTDHmlB7FpQ/Zb1DQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:ZquEgE7D5GJzLyK7uH1k2dCz9/OP,iv:Bi7tLRoxOBfPwQ1TTCHxxmPpaEafD5V2tqx88kGwZHo=,tag:9Y8/FUVEc2ZT39EVXqsDUg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:WJr0YmE2Gpp/BaQ/,iv:4Rav8EwQiycNRhELh55s/8KStGyYicyqrQCxHMY3fn0=,tag:Rk/THM5ObllwGt/nxI6vgA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:ivgsj2bb+//tNg==,iv:XKkz8/DxMwlNWTPNz4bvbASFN4JUkYuXwOlR7SrSEWo=,tag:B+UHHpzaB4INiLn2SoD+BA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzT2JZNFMvYmp1YlZ6RnNR
            UVZpUGszWVVPRndZa29xK3NwT3FmODUwZWtZCmtHS09wWHBaVm5Zbld3ZmFEV0ZS
            b1hxeVZYRXVkYXdvUmlvdFlqalBKZEEKLS0tIGJQT2xWLzZOOUNlQTdqV3ZXNlJJ
            WFJPQXJ0RHhDRUd3Tm5NbzJYcG1kYzgKS7qekRblHb9OMmAOVA6gbcsFg3G4mkj9
            RJGpXaqVXTpBv/+DQf6HNN9tbMMiASLVxd1Xd1N7yqIb8MRNQgQiZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:rO+50jX2paVv+r32UFQakGQxEhCu7V2TLLYvjXn5CjMljY4pTwougwB5zvMa50KjBh/gOcGrO487068Bkv9iDpi7QH2MbRRdK+Uqs3j1FnXJbKkqy7ZrccDQp8Ed5qI3L0y1rF/267qSd9K4YwALEnL01GPfRYkquDhK1qO7ykw=,iv:5Cj4OXMEfWk978V9gyb0ir62svkZmu0GMAhesiQg7Nk=,tag:h9qhewE5geMlNQdYpkTQYA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
