PUID: ENC[AES256_GCM,data:At90Rw==,iv:t+zG0C8dXVJFOq/VLTpd6KHxFudycSr6thjiSXuNCqc=,tag:UOpxMWaC/zr//jzphUDW5A==,type:str]
GUID: ENC[AES256_GCM,data:7avzSg==,iv:q8eNiGOHswNlEZOAKnE8JpeL1snVn2Mx35dtywITwCo=,tag:XzrUxzlD4lZIfEoR+AvNSA==,type:str]
TZ: ENC[AES256_GCM,data:rRxl77+zt8wvF6TotMMGXf7Fug==,iv:+Al0O2G0G9NMOXT2cxeiVMKP3ucjPRidOPcGw9XKLW0=,tag:kMvDiu5SJ+uwtJvHynZmig==,type:str]
BASE_PATH: ENC[AES256_GCM,data:qrGYTU6qD5jg1yjXyfqR7tbuAx/8,iv:gr8JRZ2QTEZwQOzR8NbSFH9/Z3DT9CZhD209PZQCon4=,tag:Phr7gwQO+8MC0Xd8fsAXyg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:/Xg558vqlC4ksze6,iv:r2AdY2N8n047/IUFfMckywQapK7BDQFciADgSmU2ONk=,tag:dRvAPXuMG4QkOdWqeNMbwA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:cF5ZI1jHUJIEOg==,iv:2lbsB3rQUlbAirRyrnGNaPXiI81EMZaDW7H0rXmlYJA=,tag:a9/KRzah4D8ER/H8iF/vVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcmdvZGVMWGNDR1E0SFY4
            b3VrK3VTaFI5L3hHeXRJWGV0QTBzWUkzWkFRCndhM1BEa2x3b2tUb2lRMXY0clhm
            OVdLYTlDcjdza0dselV0ZXJmSDlUblUKLS0tIFZ1Nm8xc0Y4VTdYNDNzTDVzN3Qr
            ZTZWL3ptS2tnOFJUUDRGS2hMek9TS1EKJxCrseJ4FmKMNNWqJQxiOItYw+XxBP6x
            3eMWUl1FOJXGjE10j7n01mQAN4zrwFAIFcj30YYENCIUsTvMdi+oKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:08Z"
    mac: ENC[AES256_GCM,data:kcSEssI3Fl+9cjH0MFapnDwG9t07GDpxgn6iM/oejSt2xvsqs2E9cOaRZqT0Ry9f7Qi+qAYNxzcgo5A/NiZFe5Np7opSBBhwycmD7p1saIEPFlqQN5n3glSiA2PFtIHMPP7USh5fmeHda4h62nMt8B2OudLpDGPQCFUfDVTuAfY=,iv:01GnlFEF3kiymK6wpx9/adF4CcMCur475aoXmCFGgCg=,tag:Skr2o6TzQBuNpD0TBBnrgg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
