PUID: ENC[AES256_GCM,data:+KM00g==,iv:z/MlaiJyCVMBFjloanwzYFvBtHcsKGmCB5H8DzfpBFc=,tag:UGTA87AhPpB5+Obb+pnvLA==,type:str]
GUID: ENC[AES256_GCM,data:b4np4Q==,iv:4kYsabTZvFa72tf15Aqxpjf/ReUm/1WxzbgKZx3PIi8=,tag:4KON5IWZCl6VkR0vOsFzaQ==,type:str]
TZ: ENC[AES256_GCM,data:fRaEQHBFCvSsVdBFdAdgbIV8og==,iv:O2udvhb9AGz+nvj222u4GtNwdnNb6x5UBf9h099TF+Q=,tag:AaYQMjy/RTwskgCbvKcCEw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:ccWF1aBKxPA7eVpRZNcQppU2v70/,iv:oyt7NdPeGOZblOtTgj6UBW1KCURv8sCAaGOUrtZ+E+k=,tag:f8+MxvsttT48f2SDzpH3hA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:yliRAv4KO5uA9sNv,iv:io0uiZpsNTv1DdpGV63ufkttFcWw7HsKRj8o1rvmCeY=,tag:r3eBV7qo8jvgjI5W5mVeHQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:mY6Krc39n+pUZA==,iv:ph4ejQARc0ChnTELFB+cL4DeQ+3U0d1R21eZ+olwtiw=,tag:HeW+lS90TfM5uFBJfNsXgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaFpnYnBwMEEwRDI0V0JC
            YmlCN25wYmhidTJTT2E2ZHRBMVFLa3JtVGxRCnVHcnIvZGRETnlXR2x0YTNEMXBx
            VlZqZ3RWZVNFNE5QOGQrZkgvV3Z0amMKLS0tIFZhQzA4Z2dmMlg2dEwrNU13QytF
            Tm5ON0FxL1p4S3NNTnJmY3h4dUxzemMK8fnyxfCV374+efo8bm+yo5tDtN/n7m6Y
            wzpKSgP2gJ+Ksz+JP7QYHapPNdfp90C/ekV7aEA3vz7RJrVI4lrkAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:06Z"
    mac: ENC[AES256_GCM,data:8+gcTVD0Rz6QwfVkUb3UMbovomBK19aZ9T53mK6AWLO1JtJA9ly4lhbRVPDN6HiNySB7mlaQZG1uxVSlew2cq/rN4tByzgzjh/gddS1jyMRT/3ztInFc+zHqt6YG8rQaGIZNENgZbYzOq0JV7IsGBlxptaeOcaWAI9TeIXR49vQ=,iv:Ib5Xg984QsqrcrYRszd4ISWj8RaR0JefBFxA3oNBY0U=,tag:LtjNh2z0ddIg87S9K8CNDg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
