PUID: ENC[AES256_GCM,data:vdlkRA==,iv:iN8Tyt9bUcsgPm3XQXa667UzwrWeFkvanfu4JSvQHtc=,tag:gKzaEn0y05WvsEhQkxYk1Q==,type:str]
GUID: ENC[AES256_GCM,data:pGYk/Q==,iv:1cdn0mYnmPSv9uHu7Tgt5JS/I3f6PP8uSkj53XUG2hY=,tag:pegPcgNPF20aA+6z1VmZRA==,type:str]
TZ: ENC[AES256_GCM,data:Hd5vbxbToj5lZ0UrUHJDcYmwbA==,iv:iXPq484hqQ4ZNfyVllpWvxFWaWTIIcHkefmw3jM/qgE=,tag:aRsad7hCheA8g5xZ9SNPAA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:HRhOWPmx6VTJna/+1i/5vUzVkzjD,iv:knWtPrr/+5Il5GqkxsqLdCx/Y3bz6EHJpclg+ICCG0g=,tag:Hw2Z0B8UAdiLoMqtjChkdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYkFZeFRPN3ZQWlI4c1Nv
            Q1g0Y2pHZkpVUUxyVUtrRUZFZWgxWEg1eEQwCkZjN2hsSlJQek5jUmZib21kalNw
            eXlQUjVXcmkwMWVZRGxMaXM5b1dxWG8KLS0tIEtwdHR4cEl2QVFiUDNWbnFwR0Rq
            QmUvT0xLOXJDeDZPdjFid1lnbExMa28KYHRQZYF4TMN/lwPJ1l5h4N6vHbhEfCA8
            4WH+AVmg2laDlZMgEDUrkceevjSyRiI5c309MWT/ctNAGPbP/r37yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:bVpp7Mi3XwqIYK0LtvZp/Pqjg1EGeqeXY+25P69M8m4CQxpzRsOlz+qhrAQ+Y6D5gmo4KrRilJjArd0HQbboA6Kf+on5t12I413LDNCI4L70NRPyjoWtM/384rbTWq8Yhsgi/mPosTd2MadInOCFcynEsUbXlDlrdw2OnVF+wK8=,iv:GGVqCgAIkj9TH+wDDFIPpjF7IhyNvqXDpD0zpniWZHY=,tag:j6hHslzycsBAMbZpIaNdsQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
