PUID: ENC[AES256_GCM,data:USCqQQ==,iv:p8SzvexCqq3UI/HB1AKoIW8i5J8y4L8NehZPpOpapUg=,tag:u2J6GTyEygN16IEp5lPk1Q==,type:str]
GUID: ENC[AES256_GCM,data:Xy/qfQ==,iv:FIg6VOhkBlTV7Ye7FsG3kkEy1ZuUQYAjvFMdRdLNq+0=,tag:1+AEZA4INXyCU29pOY3jeg==,type:str]
TZ: ENC[AES256_GCM,data:9sVLmKl+KHDNbMa+6TZtmTuMLw==,iv:Uvlt/eqOO8PRl9jsokcC04SVjgXynfXDX86emunEE6Q=,tag:I+3429cnMMX3pOIOItlzqQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:+yKRX8f19b0Bkkkitzy/qukIJ4pK,iv:ZVyW+25kxqee2asMV7zK4eJQSVIkMvg7qJzC2l7zHEg=,tag:ecQ306tBZ4ajJTxNQx7/Kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RmZPMHo3cmJobHpCdzBU
            MEE1YWpieVczVlVMb3dtc0dGWUVpNVZQUjI0Cm95RWdzK08wd01oMW04MkNWMFRG
            eUlCREg3R1JySGxKRE5PVzlVNndoYXcKLS0tIGNiZFNMRi85Nndreml5UkpkZlRG
            RS9GeFk1MEpVUS9SeHFhamd1TUUwdTAK7Wd+qxY6vJNuGfuso9r/B2v2sjqXV5dw
            MyDFGixgX8Qj351J8K0NVR++7r0kxAyJjAjbypQaYVMHA+5L3x1j0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:lO6kqUauRu6e/7afCJyziZRsP+sUXeN0v8l8GE3IwKTzT1nqaPMuFQVuD9fbRMMkaaLAHhbEsv1bF6oqm7gz5PwWipwgZ5z+3kJvcdnGd8AW6oLghWUZWi8Qkt81yq+snI46lhYOiH8qHq0zPfnw3U6jxsdE5JIFnpGGsFdVS9E=,iv:hwdt6d8f/k894niGCutNKjS5DX0WcZ01cZ4cv+GljXY=,tag:cM46FxuMcS+DgwcJCfJ44Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
