PUID: ENC[AES256_GCM,data:uzN7fQ==,iv:td0hmDGKg1ewR+c+yDLbkbo2By6z2UrwCH3mCafA5II=,tag:DGWRIXmfSTQTp2KYaW1JPA==,type:str]
GUID: ENC[AES256_GCM,data:G1JFog==,iv:kbj7AUH6+qmgmKEf/Hewm/ugOTo/d5kmzsUnaPKEo+Y=,tag:/m7NoOM9vvNbkzZ9JZbSww==,type:str]
TZ: ENC[AES256_GCM,data:aFqvQ9URhnVcQFq50MA7ZvBOWQ==,iv:2eGZcwx2rikwRssrxRBT4a7b30nUdAdx2fo+fEfMjz8=,tag:rwaZ725gm7P8JtmcPcWKKQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:J6cSsOhaDlKzxwZvg+/XB6WdZml1,iv:fyIN6BCijVKK+eLL7iLng460zZejQ1Bgfa9ZDNcUbAo=,tag:mqBOLuOCyjuNoo6Cbv4CPg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:LFvm4RpgIAbU6HRA,iv:6pOSlC8giLkORnyyHKU0crni9+qUipX69evqYv9bVQY=,tag:jzqm+HGuZee/COqIU8jQGQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:hY8FtzNtEG9fDw==,iv:F/FRVFnJLjDndW3xXWeOiLbXl9qrk9iwMWcGMp7HmqU=,tag:p6obCKUocxdIHZdWRsq8Rw==,type:str]
PIA_USER: ENC[AES256_GCM,data:qbzzjHqtruE=,iv:jW4qOJf5pL46DFjv2aRiY72OmT9TI95wSveCJnsEcmY=,tag:cIor+/wHq3EKS0nhTSRIvw==,type:str]
PIA_PASS: ENC[AES256_GCM,data:iilySFgHWlbzH7JGllBn,iv:IY+cCWWom4/vmKh5oKib7wK4hO592dScLRAGV+lRgJ0=,tag:kF+O0QNL8/HE8eDnZMnMDQ==,type:str]
DEL_USER: ENC[AES256_GCM,data:af0N+p2JPuw=,iv:yFSJr3Tl/+v+FQ/ZFG/BDBZ6eT+UDQ0C18uDb8BBr/I=,tag:IXxKFyPzWz+gVXzBWSliiQ==,type:str]
DEL_PASS: ENC[AES256_GCM,data:TK0jtkZctD/zAg==,iv:LDO9IZXTqvEEvcUpFfotwKCHEwMTpnOKNjBqmNUcoa8=,tag:BTMVdu4/xvSaUqh4Oer2qQ==,type:str]
HOST_IP: ENC[AES256_GCM,data:Af27NgWqMvm2eeEBpjViit4=,iv:nQX4QwLf+CbRHBgJmHc/GteVc2n385eq439cSx+iayA=,tag:MTIVX+j2C2lbVleYFy9kJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNUMzVkxEdUNINzlyMmpX
            V3VtU094eVkxUnA1Y1pUL2Radytjb2E5MjJZClBMYnl5Q3pFbnYzNFlySE1vVWZI
            STl0eG12US9Pd3hmNmhjbkZqejFLUHMKLS0tIHdka2FOOExRNmJnY1Z1eU5rZitV
            QTI4SHFzWG1rbnRYeEt6aEpnOXBqcG8KCoowytwT+tQISLEk/MI+GbaRUCLZ0MJZ
            3d4UMEyMeiwfxE9YbtUT+xXWNsc4he8O2x5YjjsSgBVfM/DLOA05Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:11ahoPskl15j2dSHN1QBhXF142wXuUz8TD0Wm8Qw2Oyk52J7GQn93VepYnb0flMQxPbohXA2wEnYrTi9vXXTwmKv2t6fBLG9z12NvVYgFiAPy2fTEjbkYcUwiGN9h9JpCVOy0Y8esQe3w+yHxupLBy6NRqJ/8pb8iDYU600zsfE=,iv:9FWgNr5Imoz2VoYC9h8SDAhYtAkwWzBk7u9kt8DA/gA=,tag:im7YXYBwR+SQZnR574Y7iA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
