PUID: ENC[AES256_GCM,data:L+n46A==,iv:8IbfnEIcn4YCyI+nuX6BF3DJIYteIWF1TobejeiAxX0=,tag:JRdlr17QipJHAF8sjNRdlQ==,type:str]
GUID: ENC[AES256_GCM,data:Nvecgw==,iv:va6U/nHjvF4dHDoKxqVwDv/uIjfnrGNnpWjXOmwUoEs=,tag:1G0ec8hilXbtvaKYolICww==,type:str]
TZ: ENC[AES256_GCM,data:wT7xKeV6YpctZkFwFSd4esmdpA==,iv:xfHJXkpwj5tU+gSyuRaDqEnigQVFZsi2ylsJ/CGj7pk=,tag:DtNCWyvWV3UjVuj5hPGkXQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:5ykK7Yv/FuZAeZG/ZvaGYVncT8BK,iv:lZfk1mJ2o1W4Y7pZ7TidJ6A59AwfDmeZAjcCVS4bsRw=,tag:bn+hQqC545P8yJp4TgAwWw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:RCi4Ze2zPsblUU3s,iv:jrTjaKIfztQ7Q+hBM+0k/kvby+RT9/ErJvlxabYukXk=,tag:I+vKcNG7h3WdAvbfYIO5rw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:P/KPdHUf1EaAlA==,iv:TUazzgBdjwZU7GUOl0f2M1D6PckLhrBOKmKfKogNcXY=,tag:TIhEDrWGiusJuU60HDH2gg==,type:str]
PIA_USER: ENC[AES256_GCM,data:KIdFKNK2a2A=,iv:lGyONl32PYRzsln73i+Vzo4a4fXbYQvpP18PKMhVrGM=,tag:XLXdcwslrOXehWWulbRZ6w==,type:str]
PIA_PASS: ENC[AES256_GCM,data:uyAZk1MGoXsSOnDR47PL,iv:Wd70hSiZWV6Dc/b1oLpZfKXxfn2AS6GkHnPtjvfzwds=,tag:KIXPu+rbwLV0Y2XZ9axiCA==,type:str]
DEL_USER: ENC[AES256_GCM,data:umvaVXS5/Iw=,iv:rJkyWDWj5AuU4KAgfPjdkPRnFT0wzERnOpmI0hnGt8E=,tag:psIQULxlNgqVvGFM+Muolw==,type:str]
DEL_PASS: ENC[AES256_GCM,data:ScWvASuDfYzRbA==,iv:HeMRe3gvmVo++lDUqjolsYMtEWW4dxkKWQ7P7fHQej8=,tag:jf/vahXRdqTQ3uRvlAlYDw==,type:str]
HOST_IP: ENC[AES256_GCM,data:WSckwd8jjYWBuAFQLTvOGFI=,iv:NOeDQlnN1Bn0dGNiGqCZ4JZ7A+zKPkteFxhtX92c4JY=,tag:pluKAeO0PjXB0tqQiG+V0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMFRpVU01YlMzTHdaY0w1
            VVcvd1kwRWlTMmZ5TXFYcUt2ZThNVzNPd0R3CkJkWDRjOGtqZ05XeDI4WlBZaWxJ
            UXRMTzBVZSswaUYrbCt2R2VweUhBRG8KLS0tIE96UXdrWnBnOWFRRnRUUzRpdHZ6
            S3BCUEUwblA5M2ZuNXhRU21UT056NDgKHD7Dwxuer3TgJKg9yI1728whQ7MignwR
            jkKyhDCfmOxEYS4CA22lTZesmq80GNakRtChUZDDqwlXlA5B8+4I/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:3mPy2EcKZbvqVFHxTW2orkWF1KIddtlfzgVu6QIp3mm7Ytc1aHh2NaedTSiBtXD/DBBRBBrSZo8VWZyPO3+mJ0FLQBzZzoOOsRQ0tMjsByaPxGuj4dRM62fucqQ0L86w5fs28+m41bm48XtFUG0GbH+y59ROUsnrWYzJT5PKiG0=,iv:xzfkPKV2qgxR8X7+FvK/3ffONk8/WdZh8Lqq595IV3o=,tag:+m4QownwzVacjuFMmPQqJA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
