PUID: ENC[AES256_GCM,data:t5QNLw==,iv:HCxH47g4FdKg9oDDk+RhVt+HciSPvJj0BTePM+uix7Y=,tag:cQwD4OWnJT7AatyNcKqFFg==,type:str]
GUID: ENC[AES256_GCM,data:XuiySg==,iv:I+jT2aPzNIESnK82b0Hnp0Y9Kqzx5F6Ahpx2aW6dyy8=,tag:LUgYQT9BgGM+aNJxCuqoLw==,type:str]
TZ: ENC[AES256_GCM,data:ecfiJrrjEHhjGKF0Xp5sSHreXw==,iv:mLHe7JDtwtcyFoCgDmCX2KYRfku2e5ssIBU+KpdZOjw=,tag:NisodX0kiIhsUu8o05NdHA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:a3h+y7DIYcZgtuwfdRPINqSAwOkK,iv:ir+EP09WMQpK8wMRK5Y6clSNCqM6Fl5/CKWtpofTdI0=,tag:vrLyui+VyDGbp0MSihoS8w==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:jAMXUYo8VupUeqkC,iv:E9bhiSty6LRH7Py0ZX4kn8eHTQlol8CmfXcsULEg5pQ=,tag:H1akJu3U84K1sD6lCxe0QQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:KbWAOsGvkxxOlw==,iv:zndviomc/oOlQKATXPYdpkkvd2EeAC6tBH0WZ3NNVUA=,tag:ldmyac/GczfofzrJmmybuw==,type:str]
PIA_USER: ENC[AES256_GCM,data:fNG9Zs/A4OQ=,iv:QAyXS2IWAe3Rf2qWRHr7MkpO0bv2KQRV/v+Q9o09y0c=,tag:TJfot09IysXt3RzrDaXYaA==,type:str]
PIA_PASS: ENC[AES256_GCM,data:aVjGB122g0inx7r6fd2/,iv:0K/x1l965UGiIi4Xm+FRqiEQDrogMt30wjdwCgbtZ/w=,tag:40IZuF+5uTfINpVWmQG82w==,type:str]
DEL_USER: ENC[AES256_GCM,data:+Vg4lLRIBz4=,iv:gp3bMyotRW+XgAlovnM7NprEFTmTN6/0pjJ40PjEBCI=,tag:gkIkmmQUTJuWx9S7Fntmog==,type:str]
DEL_PASS: ENC[AES256_GCM,data:Dk9Z52sWLcmqMg==,iv:5uuEQRM45SyivduO/svB4WH2lTXOFsv9e4Xl+xzvYCA=,tag:EOAQRVbDX05uu7wVMMJHWA==,type:str]
HOST_IP: ENC[AES256_GCM,data:7cY8PC4OvVqlPsGa/hEt9lI=,iv:EpD4P7DoB+uBlUridWH2go+sSS4anhxsLHUlm88z/5Y=,tag:LceQ4mmxwcFlIinYOLALkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydVpSZytQYTN2NzgrVVlm
            TWhxT255Tm9hV3pxVExCWFB6RWpCRUFSQUN3ClYrMlR3SHJzaWtpS2RWSllhVXpS
            ZytuNjdZVTFKU2ZBU1ZRSHVYQzhhcVkKLS0tIGdFMlgzUjN2NDAvVW0zdkF3RVg3
            QWMxbGVtdllEeGhYL0ZwSUk4cnFIU28KcwK2Ku0w+Fknrm6t3e0I4C0HmLsTHPm4
            FR3+UNxm4hiJYskSONgZWXpL3QmPPYwjBRgkEYICVMJPJOJS0XS50g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:1ibqB6m6Tam+XVeF49h3NTLF4AI2YshNWLg8sakCYylVjg749bhYVNHUMETMHLUyhqoJgDPAAae0bWY1Lai/feHjKKktZh0UxnfMEyK0Fj7lh0F7RVyttb4LKAcPqq0ICU6Ylixcl1U1KLry343x0JzSPbJP++g0ow0aNbJ0c2I=,iv:gf5ml1f5MPy/48nN1t57gDY08iPZQ5GvMOh8hb4O64k=,tag:FG9TSoPgdgbP4C2vlDPNpg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
