raw_uci: ENC[AES256_GCM,data:LxJNLzQd5J3nMya/8o532Wmtq6P720wG0dNWMLSOyXGMLoOTaJaXBkH8p31WntYUIOX4MXUKAkhu2eShvWl0Lh9ITib8Fb7HV3YU6+CQxp6cwIL3Xf+bGe9kiYh3FouRK1InLRtgtuD7PoWo75fSVXWGfL3amjy1fcOpeya+5C1Iz+zX+M+5ct1JPzIfaZgMR/2hD2LJVXmQbcil0ebxtqg+9WD2a2frG4UH0+OnZ1FM16aIhWUpiHXX2rfGn9eNtaZF0R+VOFz1eGEr7CmDmFKLEim9PEhkHPz8AGpQDcMFQmAta8PJMM7LDbiQJTAJ5xJkpOWI5H9bt3swbjnHjGIAsmKlALW7JnBx0LHqAqgXQEOKvmPEe2Bi8JTSKgcBLjQnl5cljp0RWRKEs7cuN8YYe5qB9CRvctjIkCEjvwc6DjvpQWVR2HJR5d0cW0kc1+d7F2DPh2CL7LPzKLxEv/YTZ2CaVz+5Ln0Q5JQQ7+OT4e6jyXCMqPMA6AP2S5kU6Bb4BmXDIdE5bzwKvBNZYrWcsVJR9sZimtwikTElCyi1/BBDnN0b828iJN5dFFyILJGfVs0QgpGIvhaM2246So8RxODH74ZF91obtc3SOb5gLyEVY1/Zu3Si3Wdvoxf0re85qX+EDs/EzDMEZOui6jyxhwC18pkpkKhYcQK6Q6f8T9eeWagjyS6nQN+skv/bfpC3X7SF3g6YfIz5fwQP4hn0Pw/sCi4EHuZGuyXIrXY/maERWctyVqJwiqRWt+yOlkuprmKmSlGhG9gsa4c2znqn/h0q/Uuk2SnbFff0gwTuSROdyXjfTEwfpPzPGyGoi7jyKA0UiZdGrI5R8BuhuLZp+FnElZncffrtq08k97gVPx4v0gOA4mxs8xIVAwE047YVOWENQgydgaGf+LS2rBC3dg8b8jke4LC0+zooCjbvZRUdbCSc9IzzI/VvJUYFqXsKgok1/euIQH+lAHL4BrgW/gCLzhYL,iv:eupNUFxCf/sRcW7AhePoEMxZfveJEmbaAYT/z0uWypk=,tag:ZGiJZt3RlRgG6o/I9uQ4Pw==,type:str]
module: ENC[AES256_GCM,data:JP/+X+o/Jnk=,iv:KM9v7gbDmN8KwM0wAgqMEgaM7nwvrmXgyiUgub91nuU=,tag:WuqEaZjBP4JaRjyq8OpBNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZllOZGdLQW5pNHY0dms4
            ekZUOVgyTWZZQ0VsYktvQUJzUGEvM3ZvekVBCnJPcURGOFV6bW4vQkRKZ1ZxVmM4
            eHNGTHFzNTh5RCs4YVBSSEd2c2FJV2sKLS0tIGZyL21KV2djUC80c3RiZm1KOFlT
            V1QrZTIvU1lsY21jVHpCMUgxQjVtTnMKcLvUx6++CGWrY+wotnlqAR/rgz4kc26g
            a/9lvZDrX4ULLrMrh9JkbHv/NSD/qLjNVEeEHJavYorG6XVCT4QAyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T19:03:03Z"
    mac: ENC[AES256_GCM,data:hCaft1lD2HlV6aPvjrBF17CZUDzzmeB1/ERMtMArkOSh1aQwu6YcUQ+l3JLcsYCsVLwS9fVnEoLDemQebckATZPp07bdAAh82U5E7HzG6QUC+JDYDb8E11PPsa/wQI7Levpv6DPnmSrABXzOpxCq5Ax9OZkYWU7yG6f4WDEIs5M=,iv:2gr+kbN4O2tLYTwpesIw3x1tmKaGfrqtzoolf/VE0CY=,tag:auRZv0XIRVBiOOao8kA82A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
