raw_uci: ENC[AES256_GCM,data:hYlkszdmIJU2JZLicPNlNvxr7UkQHxOw+CGDRH4ThoJgn1VW5jM8oBwWez4s4ocwYxYd6sN7Q8k9DvpnB1NW4bgfM/Agh3Es/rZtLHQmWqtr3UwuIccSdY3X5a1a/2NIcZ6VKPgTF0H/1ehkEyx8LzWLsPSSm91ecft6dI0OeclYuRLjbvV1W9KETpVPDuKCkvKKckDZoIK6W4LUL+liWTaa+6lfi7fu5b3X+1eU4TYHy5HyBZ7Rknsumj7yzRDFnFMaw7ACNTagYXGxskP1+GdEfXWIp59kv953fTMLxEJoyXbxThy2F6bCxX4mSGWEbLuWMB2U7nF2eORS+aE2MeKSfr0v1Nt1qqRr+D68HpbDzdDVHuCXMXPbpS8YBN4W2F1PSTM/CXo5qy1E0n6FaH/rTiEzieUx5I4uclND/w3hNI9rPAXuFCx3FdvhCCvUM2NpodIM6BKvB4CFo/nfHMdU3mqZ4nA0YGTJ3KU4dryiS8D/T+YwZjeNe875ouQz2DHJLeeUIQut2jdHct5hoM32D23Fu41N2pdSLqdQjmm8ZvZfn9xt3kfBxR4oUV5u5iaqzX6aFoUIxUO2ptUgScBbd1rKYxM4MMT9tdn6waEleqP98zed+VsTJ/PhNCs7TXZSjJ36RQa2njzQx4qypUYPU8yqTll0zaTrZw4voSZnxszZW7DLvHedM8Ey0ALfatzj9t/S/NRroIERLD+U/qlRApYVOXfHuEg8fl/UTYZrQJ8RBAIQnMyQrzRaVmmujmJ5H1iYbdsmHGmgcRZCmPAk5KkbHw1my+E7OoObksQM96q0EGtj06trZIcnufKrQ3tYrlk2xdjREWF+bWMX4JmJ5NLQj0wZ0DAVtiZzOk3tncg+Q2oqC6FMzn70QKhXm8aScsLO7kBHGNm+HBXlveljKfDjKh/LNZ+7f6ueaYJfyobGYGc3jvmv1ZWL90SrV+qnvxd98eRCMnkZvrF7DP5r5ewISRsR8xpJK2cdRD4yokD2yIXeLDCQRm3HFQ==,iv:JPgp3AkCa94zREMbJNzXZBmTrVEvYedh3bKxS5NbClk=,tag:8I3p6GMyiJDvk8Sw2SqjlQ==,type:str]
module: ENC[AES256_GCM,data:oBi2wDbLsNQ=,iv:qxivSSkN9/xCTfK8hsFKYAUO+lHwYyjWg53aEkP9oOw=,tag:dmPppx8P9PwEGj9aF4DS7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMXdUQlE5MXNXVU5pWXIv
            Y0huQmZCTUVxekVURS9KQTNDbWJ2WGIyOWpjCnRwTG12OGNSTGt6Ums1YURLSmxw
            V2JWS3pMQVZjRWV1eUd0VmRic200RHcKLS0tIGhleThVY3pzVStmNEdMMk9yOEtZ
            cFVsMUVWaHovNTlYQURVbUxnc3FydGMKQdXKDZmF5NyTkrd6JPumSAPDGbvL1CQT
            cYNrfNR9D9VdFqLkKPZnWPG4fHDwM2vuhdezX/WXSbMveexLW8DN3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T19:03:55Z"
    mac: ENC[AES256_GCM,data:9T+2FJBXZ4NU0ZuBbGYSg7GOuHMytGw43RVdjEXnD3jF4hnVfAtXq9LQmVlAoibKwDLRcSJOlFhIdGLbzaKPwXtEmtVXyzX4a7U/ZcrtU8kAcMnmpHSePR9iPuyQFmfLeyKsaoXjncAHZ7BZFhCSEkXPCTOJCVwJdlvMPlfe17c=,iv:V6aiegyvUJCJgwp43JYwFYjTqYWIXHI4Em5vpPcl4ZI=,tag:oAdQbpEySHVOF92/PrCxTQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
