PUID: ENC[AES256_GCM,data:RK47vg==,iv:BsS1nDe/i3Icxaqm9ejMv2cG16u2iVY8Q8Ma+FUQ0Mo=,tag:MtD9xtLEMRhkgU2Gz/6afg==,type:str]
GUID: ENC[AES256_GCM,data:daW4Og==,iv:BrU/3xOjDKdki94R4kRUQzLJUZRy2aE3a4VqF3a9qjk=,tag:JpLrAs7Klq24APCcnwCvZw==,type:str]
TZ: ENC[AES256_GCM,data:PkfGcYcY6TiVwEICptsyc/dVnA==,iv:YcSnwXneiAEbnIikOpKkzY8ubXYxzeoM29L2VN89zc0=,tag:oxJ+/Y/SM4OxZ+YuOl/Ngg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:Ft1/+cuI9dVOTl2yHtKalh66sXZo,iv:tkU1FcrQwvOjXymYJRoSF9WEADGMc/nUU9hl9ylaL8Y=,tag:SBMqm6HKfBq8iquzWXUP9w==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:cSMu/Ob7fJaRg7+K,iv:ndAVOhssCA95urJKue3LTMUMyJTWI2PrbKo86RGigic=,tag:495G+uMQmLpL6XEkO2C/8Q==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:ulkC/avjc52qdg==,iv:rg+8WK7gW2FptgsoMKLaBvtB0lWbd6YN+6geGre7PIg=,tag:NoUa24k+1bK6rVJPiemg9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UmFwRmlCenEyaFh3Nml1
            eUJSS1ExUU1QNzEvN1ZOUGdRd0RxbXdWZTEwCmt5R2dTeGhXQWdXV0RzaW5GMTNF
            ZXNsV2IxUWZrSU84blp3TWRxbVBRSEUKLS0tIExMaURaM3IyYVprMmwybS81RGpR
            QmhJNVRVYUQ0SkN5WEZ2dGorYnUxNjAK3q233CgHHuvItCUcApiBfkBSqG5JNpEv
            mUkB2f89dXbAu1LGMleOSYLZBPC3eoyrr1t8REF8rxODuO3XD8gdRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:jl7vFypgiQPzdgTSVJgOBLv+63YdAUsas8V1v5+ImrZx/gmHSNzghA7FApHt8bzyNOz33tZ/b5zssb3QIQWSj94qlyGJbyU7Ra2jtUwPb/Anl/fqOvaEkGhhE/OqSUV4wF9CLthN9thsXn1qSOXotSA1ZdfzZj0qr+8fSD55P+0=,iv:AFUVy518t1eZNTSbIXdEDV6byPgj46nOc4thTzEXY2E=,tag:vMRLTG4MIytcs72curQHDA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
