PUID: ENC[AES256_GCM,data:18KTOw==,iv:qqENlaaMxeSR1lvfV7LqQGZ7um7aQ7nhjCq7BImiKjg=,tag:ReGE9s9DvhMILgPZaTGnZA==,type:str]
GUID: ENC[AES256_GCM,data:tRpcPg==,iv:ViZms4aR9LbkSfErhWCTNnLYef5hm6jsJRkkHxxw0xk=,tag:B0AxqmZy9enqeYsN6FG8Bg==,type:str]
TZ: ENC[AES256_GCM,data:/kpC4PZzn68YF2WmJskiGmae3Q==,iv:NReqm7SEa2z0BlGW6Whbi8XP2Eawbg+NLZjD1Wca/ls=,tag:c8f3KG64GWXvOSM3cm1njg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:svHsHrwYKdhBWLZMjCJwhxJBntlV,iv:bBq6eg9PE4YhbS+fasgRbwW6Z7Qu/oKTUtx8S+rpgbg=,tag:IpSSw0N0cdhgr2UOYVkJiQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:hyFfo2VhDqN8OdOO,iv:WaKZNIhGcRsa6JVWGv4/paq2X3qaWuWkiOkTHd/B/pA=,tag:QKiB9oovII8uUYM4oOg0Ng==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:vcPbkzqLw/fOpw==,iv:WG8gL6BwDaZ9FKTXEOdYIaT2YM7tRlbaO9hHF6yQR8I=,tag:UtzVELlDvlFxto/qzzH+ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicjFJUmJEVWhPK045WmpG
            cWl5VU4weXdLU0JNK21qSDZIN0ppQXpFY1RNCm9LRFY3Wld5am45dWFNUVBNN3dq
            UVlMSTJqS2l0OVFadzNQQjBMbFVNU1kKLS0tIGszaU5RUlFTQnVDaW9OY1d0NVFy
            SWJVdWtEOWFnVnRRdko4MjZaMUN0dmMKSbbh46HRq9n6DVzfH732vAP1UqIa1PmP
            6/wb8TmBqMBoclXzm+BzEZXt3qkC4rvU9mqGdIx5/UOB6UTIr3Zh3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:GXV7TXCe3WNczBHZezZby14BgO2UEI+IRczEtGni9VO2OXom/Pq9egiJZEzlnHs4Oxs90JEgajv/I9sh5VfiuKHHpdDEw6+WSJ+TGHWGET6RasC1bZ7Qrad+dP39qwZd1tLwSUw9opwlajZAPhjnHQfspNdTehzHUrCnK2DtV8M=,iv:Nvqb370U5ntQCsKyLrhkf7xXLl/DcHlDiY4qoEol/Ps=,tag:iUgTUW7d7tXP+oMHsV8eiA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
