PUID: ENC[AES256_GCM,data:EIEyng==,iv:Weu3EhUiuk7bMb0y8XaRWX6JNhUCF1FEI5mWO4iuV/o=,tag:W3u2nSdVMzy8edu35ZGfdQ==,type:str]
GUID: ENC[AES256_GCM,data:0ruwOA==,iv:FSZP9fOLYA9fzIit3AXfOZ9zpL/cC4pZ3u5m4+rJu/E=,tag:NDAdJUCVjIlr9p78OmAs8g==,type:str]
TZ: ENC[AES256_GCM,data:H4CQE29uvVBTYqfiNf/r5l5DUw==,iv:q2MQLnrwDjbu1ZGBdNfvvtAIAaBnWS4Hkd+nkiQ0Jdc=,tag:+7TeynA/CaUfTeBkTC6S7g==,type:str]
BASE_PATH: ENC[AES256_GCM,data:F6r8U/miVvkmV5BGKrv7BRWTT2F9,iv:53Wp/d+uVaRZcgEtxVbeOfUU8p/BOpCkoQ6yB53Ex1g=,tag:ioswWPbGyb9rXkFxmAmeQw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:lMN8Y6FG68eAd9xi,iv:qi91Yz72bWwv+C1NpFbfF749ZduL0X36nOVzKIvQkp0=,tag:n1rk5j9r4KYMDZRMhkK1mA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:ZpD2QQl6kyX7yg==,iv:juEKCkiZjWK3OmapUP8zTpHK9ZbYpCZ2zDNi5n2eojM=,tag:m3bJxh2VM2aTHWxviQfSYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VC9pa2Y3aW9leVhUVkMy
            bm12a1U5VDZwZFo2RUorR3l1bytvV29ISDA0Clo0WnEzV2VNTW8ra3dkZ2Q3QUFl
            d2UreER2NEs1dVBOcVFNM2VlanNoanMKLS0tIHZWZXlUTEhrdkpxRWx1T2NwS3k3
            anBlL29oWGF0TEtDYjdxRnNYcXBvc0UKWJhl8yEvzZ/TL6klnOGJOg9SmICp1rlx
            9nZj7S3vaH59e/l3pTXzWNsK4hZlmoEEDKSso3rz/LAHR2Kar+/Wbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:K9GzyWieO5wT+fdPqVZkQJMwAsdlE8UNzH1VkxW+AK+m9BQwBwR/8KrZGPbvt8AIPVUBrCeqhXstH7yJCXdxbwL/fg4+Er2AWJDAIipjrOzxWQ6dYIKT+KZA7uRE3x+xFAMkEMO3W82/kiF5TDi4sb5yA5ULWUvhPpKVb+YJcI4=,iv:QUSD3Q/J0YasHd+7wjvqV7HCrXc7AvEYRce0dbB2btE=,tag:UHCKh8bxHwtV9iADkYjWMw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
