PUID: ENC[AES256_GCM,data:BIul0g==,iv:VMCpc8vz0ln6biIb7voEjX43A01cu5IbJOF+YdM+ahk=,tag:u0axRJLZ491nDyi+y7B0vw==,type:str]
GUID: ENC[AES256_GCM,data:h4Excg==,iv:hJhKOKY5Z4mcea32sb8D0NxQP88euCnrdXVHmxJYk20=,tag:vdn1FWs7mS5CkRfzjOylIA==,type:str]
TZ: ENC[AES256_GCM,data:E0ZHib2bgTI2FD5rzFJupczEtw==,iv:RL9wu9LA6Ez3IxtZe/rliqdXqssHrxhPKHMM1aREZfQ=,tag:6Xa0Xk45G67quIwELpqSew==,type:str]
BASE_PATH: ENC[AES256_GCM,data:UAV0t7aoG0bOuMsrbFBX2UoxDJCj,iv:CDZWD2V7sVEn/VyQwm82a9N8MfFRQFSa5yAogsfFptY=,tag:NVZ0GRAyz+J4Kt14L1gVRg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:+m6TNfeK65QYdc/L,iv:EC3XXf4U20MAriUl4TSmNkaY4tExVPBhj+6Sks58Ci8=,tag:P3Jjypptsx1WJcIzt2Jo9g==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:1tAZkuJSO/NoDQ==,iv:jK1griUGCGcDUJt05uD1ARV2ZSqJNXsJDLHboRwz4gE=,tag:y+HccJu4ytDjmsKzhVwNMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZ3pCUUMzcSsxS1F6RU9m
            WUNQTWlidTZkakdHWmJiWlFDbjNaM3lXSVRJCklaTktBQU5PM21YbUFnN2Judysy
            V2pqUFhqSWhhSmswS3ErVzZHRUw2L1kKLS0tIGdqZGNlWk96eXhXRjk1QnZMNEQ0
            Ni9LandPOXEyUmpqbHBKb0JObVQ2eG8K/8EAI4VL3u1Oy4VDMr5ZN9kJeZnDti10
            hCFVcTjWvKu6B1eWNVR4kvCXkVrAKZsCI3zDOWuBloXNSndmpH8BEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:/aiBNAGxoS0GiV/oZGxrMasl3qnHOyIS5HGJxoohH4C0A+6Hg6398V6c21lZR1HFOF9uVgoPzwZiIXx8Xh4E2QRDFlwrTEQqXpbrfWnKDu2yvcHuCbpxvMuVY6b/6RNKW2xAXQlPqhPNcxUcNtj30xADWQFdBlyrSYQooZ0+b/E=,iv:DadJ+/AumEWIInk4VcVZAbkMZT5+bbforA2DEXETa7c=,tag:ZVYqe39sSwes+HGAsPCRiw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
