PUID: ENC[AES256_GCM,data:MzcaqQ==,iv:9zkq9+klKUAuBF/OT0MxN66UXKINPJ/hcBAeRrGBN8g=,tag:8cF2I7LbzTfS6SKZSPFT/Q==,type:str]
GUID: ENC[AES256_GCM,data:klMMVQ==,iv:gqBtf9t8+U1elRQ1a+OvpMcHBxMbXCj+K5ZdKLWZSsI=,tag:Ar9DuFq7dR4wOGrUJST4LQ==,type:str]
TZ: ENC[AES256_GCM,data:d8yoAnBPfV5hnSzEjdHG2vjZjA==,iv:+/I9Z8YCqitPvTPZ1tDphLOXXo6A8uwrJR2wqSWsieY=,tag:rxqrf4QF2uJY5Qn/A/235g==,type:str]
BASE_PATH: ENC[AES256_GCM,data:wKICk706eZlq5FghEy6HLQVVvOC+,iv:3ANPVpDjYR5ZvaQr3PWFJXr6Po6y6tEdUL6BjTIQZA8=,tag:BZf9wqpo1z0H+qdbvVGauw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:k+nf7loKGTTsZGcR,iv:PuvC5w4AUblTlEeGcF3HWNEXRo+NAls3ybTsrWvPS9U=,tag:uL+bd+wnt91eaWP8NQdm6A==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:e5I1era1t2TSlA==,iv:oXwqsQhdmk5irFtauV7s17e2xzcUXy0iL4n6xyjhho4=,tag:+qXBQrCDJ7qLJcMmw/0aZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNmRUZEtzK3dBY3FqNW81
            c084YWZ1WCt2VGx6WExKUE5vd05HM25mRHhrCldwRzlHQTQvMHFFQWRHbG05QWVz
            VDFqdVVEUDY3YkhmK0JLUkdUNXA2bFUKLS0tIFNRQnI4eFRFUS9hamo4amZCd01i
            eFRaaDF6VnpKbGVTd2d3T0tiMWFBYlUK5jlE1u5orJH8CniZOpICezn/V6vQGSJ2
            dpdPu6gE/L29nph7gDzsSVGm08sZv3jvhhoP2vlHVkD9ZnwX/c/LUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:zsJhDjWOaWWK0LQHN6yBGJ2ryKG316JM3qqPlAL5n7/twxg4+Cob9ZjydM5bU3oGrZ7Fxiq5So2mNTzAWu5qyw1vrWnCTZNDS+ePI5THKz2jXQCtJ32FR0g13NJ62TF6oUjxnMC0p1FixRLLyroq3hNDHBtHzCeidLJBQ1mGzd0=,iv:zQvFf923CPyVAFA9M3T/xoCqtW4o/shN1Q5h9RmHTgQ=,tag:5HkLjuOl7ccf6AYiSTVoMA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
