PUID: ENC[AES256_GCM,data:LTq8Sg==,iv:vaVI06ZoqQUrC3WPx+V9WJB799NoTMp94evUmMrz+88=,tag:wAFnDQ/NhrKFpJNpqVTUgg==,type:str]
GUID: ENC[AES256_GCM,data:oVbsEg==,iv:4jyUhdUlpBjtABke5wdpfQ4Uebi4b6KqnOaXFUEiDrI=,tag:5DosGcMYnnXkmHBiyYtv8w==,type:str]
TZ: ENC[AES256_GCM,data:TXYu+IAdjh+Nldx7BQF4jkQ8FQ==,iv:gs1TSfCmijmraY6kdaO1RPnLlzQgpbT8TE4ZQ9XgeTI=,tag:O3e1URP6eQs/pphXCnJREg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:OvbshDXMX39i/qXfNvedjDwVNfFP,iv:jf6bGXm0S/AbG/N0tX0XijMHY6ZZhjOXyrS8HwnUJys=,tag:Cus8lxt7gXV54Vt9c2GAWA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:H0f6lTvxdth6bGre,iv:bMmUKY7beORxhqgs01l6OeviYs9JIEssVfQa+umqfVg=,tag:oJqMSK4Ef6Ni29t6QdYHMg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:pzMDtOhKVv6Y8Q==,iv:k1Q+s6b7wi5rliIXFsWMMqpe0IYgZI7tyCZLMvbvTw8=,tag:qEG7kH/UKGvW6uomS6w0qA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBka3BkNmx0WGtuaGJDWTZQ
            d21WVXBsVXpFdlFoOEpuK3IxaCtiZTlNRVQ0CmpobnVLcjkyalBZQUVCRkYzUXlq
            VGZNdmRtSXNDVjRaUmVKblZFZmw3azgKLS0tIHF2RVJNbFZscjZrczRiYUJaZGNX
            TEV5MGNDait1MitlTm1rcTlnN1BkZW8KJq6TTU6atMsAZCmZv3GMGkBhLlj7qNyU
            suFEXcRzevJOx0armbM2/xYoKoOInHOSVhiMfr1i0M59C/pTecKcJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:SvkJ6bzS9KNMj0SGvMoOrthDFpYqQztj10h0bhKFqFoPePcc9yQkHmEXCiMeqMKrVOGfwLZASF/bJdQ5Uno0m/3vorjJDF/oknftkhRBs9PvLsW/TCKq7A0KD3Zb0UNSc1zEJCXDfrTzvHQEbXhz8DPymYnIdOz7fIdM1iCgZ1s=,iv:SbUOdRctkOi0hXYmL7TE0I7x861W8psJ4YOoSw92BVg=,tag:P7Py/dGUvA6y0Vh4vlb19w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
