PUID: ENC[AES256_GCM,data:EKdDBg==,iv:1/msTRpae6TnsGj2fd4zwEP847MJQdNne49N4+wWiEY=,tag:0tZa8+R0X8O3i73ZugY8mA==,type:str]
GUID: ENC[AES256_GCM,data:AZ+w8g==,iv:y4Tt8FT6br7gcILLJoRRTPiTOyXxxmtQUwu43GfrYPk=,tag:MsCh+VVT9lAlCNkX2cxycg==,type:str]
TZ: ENC[AES256_GCM,data:pVZExtK9+zqn75b+rKCNWXvWHQ==,iv:S7lbr6A2bL9XI3bXNTDujOqmzlssCqIlagNgKI+8WP8=,tag:S1JfDam30NyNkVaBj4N4Dw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:sEViUoz4XXJsBKm7ArKJ5+lbB8ff,iv:cvKIPKUxJLtyiP+6yQjr3aFxeeRqwZE36iubpsFl0CE=,tag:kFnvwfrmuNqOc65M7YIK1g==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:zBLQBCudyyElvJoL,iv:M3Yki5pA5m5y3lp5c9PXPUutIDLwoCOUeOr4J7TTmgk=,tag:pVQnpyiMiWvS2csZWqHgBg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:wUh4gn367//Q7g==,iv:+EeWTmMb19YkiZT288ocdp4YzCB9P/SVoCnKgyrT+NQ=,tag:51CUILO63z00S9XLS3JuCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4M0hrR2ZENGVMc2x3Wmp2
            Q2N1aGtWTXR4bEQrWlVVbmZmVEl4YXBrem0wCjY5ZmFhaEl2YTFsLzVZRGcvNjRa
            ZlptbzU5ZkRibUFuUlhRVUxHWGFnYzQKLS0tIEZsQUgzdG1FNlpGeGo3Y2lXVnVp
            aG9KQms2RVJmQ2x4U3ZaTERrZk9GMVkKTpUGwy/0XsAGaEdre85mtx6c6gmkor/N
            35PWrvcShRDLIEsq6LLHM7MlQUjtLy2R6mo6w37Yqmdod/ac1pNiKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:17Z"
    mac: ENC[AES256_GCM,data:ydmGofwFNYekEP0HTvEl5/XxY8FF3YCNjAi4SWzd7HHBS7dJAukSXuEmy9FhVphmRx/At9n4+E2fzeiH04kIyLWTJkCtAhkIOQCNvEGJY60nz4HrskJ4El0ChqwMW+vJF3sw8A9f4XzuQovDhOpoK0H3zOU/JKLYUCWG/6EZtWQ=,iv:QVUnaH1nx+Dh5ptbEr4PI0mxl1RupT39V/MMm3Smw3c=,tag:a7LvuzAPgabYvcbTQzAhrw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
