PUID: ENC[AES256_GCM,data:4SboxQ==,iv:H0QC4yWmRnAUuuMl/6YvHZheIzZpViDS9399ofnNaH0=,tag:BAhBx6tFqGPAVdVCNT1Xgw==,type:str]
GUID: ENC[AES256_GCM,data:50/dVw==,iv:o9VpzTMYpyOydzR3ZlTGmAloQ3y2u9k/2F5xWRv6CP8=,tag:Mesi9fvnel74waPDpndP1Q==,type:str]
TZ: ENC[AES256_GCM,data:opDFX+5NC1ndZyOpB7SX85mZFw==,iv:91nYqpFrCovNCIEA3fLQr6HZpocLEGR8lpnr5RUJljI=,tag:iMNj1DRlwNCKb6d8z1SikQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:L5fz+AyiBItL9ecp06xL0KZFADdX,iv:np4k+1pAI2f2dVk+8DGYyXjjib8htrXJ3vWJMwKg8go=,tag:zWVpg4rEzQ6ZUueQSCqumQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:qeIqOnUE1VMYFq2B,iv:crqQTtEgEl3h5QMV1p0dafumGQua4hVEFQI/ON79uC4=,tag:wi/ka00/MZXat7O5XNiM5Q==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:WXR0TDIJfK6dUg==,iv:hakDoPJvzG9+cqrAHklYl3DQ4SvpVRtJPi60YePZm48=,tag:LVcjZki5XKhXtllfCE5kQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQ0lpemxiUWg5dldDZTBW
            MWhFM3oxbExjWkNvVU4rMVV2WlRkT3l2Z0FJCitDM0RtbnBUUEZuNVRYN1R4SjJB
            UWgxcGJrVGxDMUxFbi9hVUR1VHpUUEUKLS0tIGI4SThQZVg4TUtVQmpIdEdkUzM1
            SVYzcG1ob0NKVWl3dTl2b2lURmRrNVEKZIg+LtXl2IYtgKCczuShYUffB+YEO7uv
            /HysfpBNwe6OKCLxTs5XrDyonTcHCfvP0oZH50hARExEh2jNpqeTnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:JbOYZsj/E9ypVlM1r9eVfOh+TUw/hQ3BdeUU3ZMgh5oKNKs9rbTEK5EFsLlPc9f8Cqe3Y6y23fwNu0HiyqwbZITuLR/vSJiXZKdgrxmoWVv77WqTRm4qZ/HqC1bMKiUS0jv1jLg/sdW4+SF/D+lCMtlMAUknChaYjRwdDehY8oc=,iv:sW9tv2DJF13pb41+4PZr/9upr7XXHxETHabuRlxUojA=,tag:YU9gvs85R2rGqXurseRrAQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
