PUID: ENC[AES256_GCM,data:BWoJ8Q==,iv:fk7uA96NIxyGpcPtLMyTlRJU1X/u2wukArNwyCrmFq0=,tag:ABnut9xPtRjjQ14hnWc3Pw==,type:str]
GUID: ENC[AES256_GCM,data:Spy+FA==,iv:wzzYaazhDmMC7El4aN5ZGmJIUtmGozW8B4FxePZldAw=,tag:1F59a5bezO7WPDwQWerXlw==,type:str]
TZ: ENC[AES256_GCM,data:GeafFZf+unpSj4NESv4IYBPaxQ==,iv:5JOEZBVLxqBOPrweoPM/DPWgYJst/0kyoUQim1Yp3h4=,tag:tFbTPAwyt+ZIiFhIn8WMKw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:xUSPHCC0CfYTJN6Yiy3PYfa21jX8,iv:zPnJUk/DnhGGi06T/fEE8ZC8x6TIKpTttxzc0bUT+mU=,tag:AkixlVd9dhUjx/oFCPzP3Q==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:iuPWSHMYt1AYh3vD,iv:yFMH9BrzZXUCI7jo8j6QR0sK5cAMb4sr2fGNTtHU6mk=,tag:tk+8LStLh+/s9VIG134Jhg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:ZJPmHa+/uuMIvA==,iv:OJmSjILwFMNPLaRqYf+0mWHlYeECBkiadOioFgGXA0U=,tag:+aO1TkREl2XAsgFk0mtx+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQ1Nxc0JyN3pwUmNRRlNC
            cmJ3SjNjL05OUDlCSHNreURiOFErSFdKOEFNCm1DeDh1Q2ZSWGo0MTJlcUNhd29j
            RytlY1ZZT2ZoNmFxVHF5SitoUnRWYm8KLS0tICtzS1pad0lSLzJwT0plWHk3eFBT
            MFFVcEJ0MjJyNHk0QnNGZ210OW9SNU0KLXkcecKmrqWxwYCblETh9NuBw6jzT+mC
            lArOTETGekuYnP4XyWZklpY/nGy1OBgAF8IA0g4prmX4CB79kttisA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T18:25:26Z"
    mac: ENC[AES256_GCM,data:o9D1JWqQt3q7zuKmrrMmea35JGxt0CqR2ythOwGYZxfFaKNPPde7wuYynVIISQ/ys6hS+GXszjVwGwkiGIkWE1ZGjXVf0rJVDv0qT93sNwm/QR9a8GpvGnLuO2WH6flEMdFjqdf2WSABr+8AZCc6LXMyK8DlGoWX66aeZ8JU4ck=,iv:HrgArFkV6wAYMyvxSfHKrLeZBmToayI0GUZlPMKCsiM=,tag:p8fuWwHs3bQn9spVhx5poA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
