PUID: ENC[AES256_GCM,data:zLNmSg==,iv:CIw9Krf2KWjN2Iz0NsqmTgD9rxfOYvEbKNSelrJSm/A=,tag:8bXe6OkUxvlzFeZ0aAfGgA==,type:str]
GUID: ENC[AES256_GCM,data:MrT4Ig==,iv:msNkxfd3f2Y2+WzrFBKXU7paKxOCtCAvLWHUGw/4bCA=,tag:sF4lx/Q7Yf+ukLuUnWpKGg==,type:str]
TZ: ENC[AES256_GCM,data:/ahlQCQxWDNWA8WtebFGGlr0dA==,iv:OodsrO44WkfURNrtvfSiv810BCUMr+haB9lJP2RBx+c=,tag:vshxS5tOeozcpka6avf2Tw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:rh5Mutc77sheKYWMH1Cqp9ReNkg7,iv:gh0ML1BVV4iCxhVUoBl8odyqkrvmHn7sCiZCi97I+eQ=,tag:HF451BQP5Tuj5hwLj4IBJQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:muT2qYuwobUNZn4n,iv:2W3QB5L1Vsi5HJUQNGhJ/nx7zyswpOsOoB17lyTLpwU=,tag:ZGHjV4WN0CIqP5P8NNCeDQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:EPIiUlqWkws7Hw==,iv:MyBYFXRFTOeKbkn21Al09bEITOQQwALBHe9Nqrq8v/I=,tag:PNdFUfkcu6FPfaJ4cIo7OQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTzl4cTRiTkx6Q2JsazFs
            QUphdVkyZTU3bjFEc3ptWUllVTgwYVNwdVRNCks5ajRpZEF2dE45MGVSWEd4LzZW
            U0g5ZDJxYTlNVFJxUno1UW9leUkwUWMKLS0tIHgrQUttY29kWXp6OGdlcVBXaDlG
            WXkxOG11MzhVNjhmbGJ4OUFRT2dPWU0KYdtf+kuXikHUwKwlMuCpZmS8P+yytxa+
            GAckxa7J79iWVPYk1J5BjXkV03IcKgJNPADFGz0tPTIO4NDD/82kKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:17Z"
    mac: ENC[AES256_GCM,data:zeccIvBn7eBLQEVtiGi34x8pYNLOIl1N9/aL/5crG8JtaaRzG5zdvmIEGtn/2N/45nvgAvS/OrdylWLLd2NO8BJFy/l9RiIHBQXuDVWgp/BfSjRZc6ZNnkuCTrssxU6kMlUe86xb8hnBvN0oXzF/gP5wlmiVTNvr8XdR8MLqCno=,iv:2PKNYVY6fgzOmDOh/2ghGoCMHz8YQzT4nvK4v8lyP5U=,tag:QF9hYzBpIcfpOd1mBmYqoA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
