PUID: ENC[AES256_GCM,data:qeRd4w==,iv:x7D9I478vOX0eucZfB1HpaY+tJrWHt71QXUSmAtRNIo=,tag:ZW0bkFxxg+34y0NHDpuR6g==,type:str]
GUID: ENC[AES256_GCM,data:m8LjmA==,iv:yezG9IJpnUKfeAUD1HQlUlmCrGwd3RpJGbZi7/pfoO8=,tag:4uneMQvU4lpnhqmrlOPJvg==,type:str]
TZ: ENC[AES256_GCM,data:o6/P1At+HSc3jhWZY56f+DulWA==,iv:x1BdtsbJmFm/iEfNPM4A/ZgJWayCC+6fYWIpEN7sofA=,tag:2RRElMP928W2XxBUxnOVMQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:CfkSn9J7b7aI5vj7bzR6Y3CKkMZl,iv:wtd3wtJtooo5VVFw86DjCJonmhtGGOTBRURzR2k6n5k=,tag:8ZYIu0Bi011ZqhJkq4mDfQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:0NhTsKyqCZV9YR2k,iv:i/6D8rgOEQKVojMUwkYltsborimseiusXK60QqPXzDg=,tag:3qM3KZ7U6mmQ4xX5WTgcWg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:Ry/2Q351lsaM7Q==,iv:+7TwGfQRAgOXu+hkjR906HtJYxCAxQALX1zdLTzul/s=,tag:OCgG8DU38iZVvpiEjOD5sg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUkdTcGYvVUdqcm44K0J5
            eVErdmxEVXJldmMwZDdSQlZ1THVNa0tBd0U0Cm5pL3dlcGdVSW5CT2x0cUR5UC9Z
            Vjk2VWJYL3ZoVWtjcXpmeUNkT3dLM2cKLS0tIGNzSGtWMm90S1N3eG9BNDZUS3Nj
            U0tHL0taZDBGK01DSHJFOU5GZUxjN3MKIZxssfP0eZ4SVFWRhYKSiZR7OpC0rr9K
            3WnmRbOLc8S+gBiYxPW0yZyL2+jT1tpbYUqm71j/J4cAQhyyhGWn5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:j+RkOuX3jabBEbbZLgg2H1VdKpAv2P/3qTRYSm/rbLRBWyCVDFCo6AzbxmIvAqLkgUFS4Fm7mEfg7IeOHszTEdaopUN7MJfPC3W+V5Rb4BzO+ONKmv6/e6aQ07WVD4peERI+u9k9F+ubNpugWtAMgTo/AgfrDlT08tSztAVq4NM=,iv:cTR6t21sZM6/mxZZOOW+tT+kxkLAkXLTFT8+Nv8WhL0=,tag:71yIUquUAC91YsdeGnZALQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
