PUID: ENC[AES256_GCM,data:Y4UMPQ==,iv:tIrCuDjzX64GdgBewx67KXJwPJBwmMy9L0sTsmof/tM=,tag:evnz0pAQZHXHp0t/XMbL5w==,type:str]
GUID: ENC[AES256_GCM,data:UzSQDw==,iv:tgKvUpvBe1Ye/+nU8gVL72vwdHhydaDHiZYxcnXMgm0=,tag:snLiCDe1TRLqhCvYr5POaA==,type:str]
TZ: ENC[AES256_GCM,data:LoOxjVHd7M20fq0UgDu8BtIS7w==,iv:5djnvQd24Ln5lWG+kh7W1jkMbpQrcqY3BRcOXf1jjds=,tag:gn14M8GExcKTIPOqeBCLlg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:pz9WWFe5Sc0gOXQCXnQVyxc73AlD,iv:inFlabjQoPL4DMt5DS0dNAOjqo81QEWFUe7Gy999JsQ=,tag:4ECUgOu9lGG7+5tcI8aNLw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:8zv8USUGsIfiDFJh,iv:DQ/keW/4glcZofTA5V4TC2ahaAnPUk29t2wfMdS/jlM=,tag:Nnf5pJVa1m1rh2ZqoAUC8Q==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:REB6F9UZlpNYjg==,iv:tTKSAtUhq/8BXF1EgAUNc/Q05dN+H0bu5BIM+6oA5Hk=,tag:cTaWvh7dDaNCqzC8L3L3YQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQVlXVWtCbG9sZW1GUFBv
            eFh2YVN1UDhPUy9XMW0vNHNvOU4yQmtRdmo0ClAwREJ4RTJTU3J3K1ZZbTN3TFp3
            djYyUzdEVE9JeVBZSy93TkwyNlJ6Rk0KLS0tIDJJWERaejBHSTEzWERXNzY3RDd3
            ZmV5YU8yK2J0SGFsKzlUZUFVcCtJWnMKh1CxJYvU0cWRqwmHdsMp0wRwvAFRG+I3
            BOR0GBKJfH8b3TXjS7Dz8vf5Byk3LMRCKFrgernyOo3We+JzahhF7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:u8qbAGn5Bw+msNAJZwCWxS+0Z9oMRs6TXw9cie+JbuDOM3lnnv67W99v3phJuYd8cCtPW9k3tWSucf33Wu56Ts9tueKGaO8h4voX+cVsPpC1ySPh0UYX0GfV5ZLO2PEhsS60QV6B6JBEpLIGiO2cET/KKAoIwkNEo4q65QTAHIs=,iv:jEI7lk2mX/LtvMlddtlrDYSdVvxtvlmzCSFpJgFgt4k=,tag:UT024iCPU3ecR29rdpsSFA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
