PUID: ENC[AES256_GCM,data:le4QDw==,iv:iA0pIfsVObhqROvF9XOuQUlM+90ArQ18kX/0MldCAEo=,tag:5RnslWtshWiAXxEceePQpg==,type:str]
GUID: ENC[AES256_GCM,data:ezwi7g==,iv:YsHaQxGByDxyki2Pv4ItMMBMb2e3CFaLBmrfxltJ9TM=,tag:6RxeE1gKFRNQtLBuvVcaCQ==,type:str]
TZ: ENC[AES256_GCM,data:y0D7IsSIr7pxFh8wmMFGByIXOA==,iv:4/FeT3lYel7Ii48d8c4iirBytUGPZXwDYS/8Drg4s6g=,tag:3s9pBK58LvslKtyjnhOGmg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:1bWdyT88j9WuLwwKHySUfrCUV9n9,iv:F3Nav5l6gOfB7mfPYLlGogMD9IQbvB66ncdV73K2Y/E=,tag:LlqjnsZQ+qQeib7g8eGcuw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:xsNkxVmSKCy9CLU/,iv:F0AfgCrpq2a/OTh29nkg6R5spNp0iNvldqBIwZLnbmw=,tag:d3sgQkv0CO9OSbywlbw77Q==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:aQDtVB75JNvizg==,iv:Bs5y0abw8NWNphyVPlEO5I3rU65WCnmeePgZkT+tOZA=,tag:0/INMZvutzoSjhOyWVMwJg==,type:str]
PIA_USER: ENC[AES256_GCM,data:bsQ7jhyvM6Q=,iv:66sMK3wvMSHSfTB/mU4nHD8x2ajOYGSceED83XswJlg=,tag:ClyT4WszDb4KATkwiFsWGw==,type:str]
PIA_PASS: ENC[AES256_GCM,data:W2Q+7LI5C5vTkSUNbhih,iv:GXrflVmdSLln15Y8ft4e5k+ag7UyBUCTzdTBPcF29uQ=,tag:AUQAHbfIEwIvEcWbJz8P2A==,type:str]
NZB_USER: ENC[AES256_GCM,data:68uOSsgXpR8=,iv:ct4y7fStiiRl07ARfIY8sBSa1PVlUyXa+CztKEC8NsA=,tag:mpVpECP0CZmmERY86dcoDA==,type:str]
NZB_PASS: ENC[AES256_GCM,data:O6yn9/DXkiKXiA==,iv:aDyKkfEDbWEH0dnk++cYe4f908l4RYOn7sdqSgyW4P0=,tag:gaOR24HoanfehE1ua31wxA==,type:str]
HOST_IP: ENC[AES256_GCM,data:fZL7KEh3yOCFVEE0qpp6J3Y=,iv:rItrHSVES8jjSdZ6X2Hek5uta9YVPFMEn/lJZifYLDw=,tag:AZFvG3jZn+BgLmInnBRT2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SVZxUnNKbEQ1OUlMOFVL
            Ymp3Z3VWV3JCM2h3b3dPU2RSTXMzSTEwRHdZCm14VXd3b1dZZWREU3N6bzZCNDZD
            ZXMxRWYycXJUaTR3ZzU4eTlEaUYxcUEKLS0tIGxuTXFvdk16TWdCYmRzTmdKUWgy
            dy9iamNGRzEyU3JRdDlJQU9WLzNjS2cKB5Fv8x0lMj+Zuk2kms0eDolIj7j21uRr
            Kz5LI1KNEJUWEB/1YyzQ/k6wPSaAY/5aSBI22eK6GIFtEfAZzd8NYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:3Aq/xxE2VRKa9++13pxsWrgqiEbFVlOk2BkySoN8PDukquu/fhDw/bho2x2DwCe7mTEbxIx/60x3Jt9eXzwRBOdRkuyVcrnEREhPsJMiJSEV1Urz72WTsCNKzfnmn5TE/y35HOR8btygei8fM2E3bFD0pezaxa2bcB9EiIj8TjM=,iv:bwri4tR55Drylkyn9rbCIRsGLy5UzgkjHSD4t+XGarE=,tag:ufFEixZQ1LR/upMiQ/dCYA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
