PUID: ENC[AES256_GCM,data:X05DuA==,iv:7sTZSU2ZTMXw48oaM3ktEySjx5ZEMdxWvlNickZNVbA=,tag:8v2xzB0Qx1Vw4H5/wY3ebg==,type:str]
GUID: ENC[AES256_GCM,data:hC7RRg==,iv:msxMKCypLlLFMEw20MI8AoCo/+P6oMIRzpAqdNAbxSk=,tag:bZ557C0F1O3P1ZAX0ZYI+Q==,type:str]
TZ: ENC[AES256_GCM,data:1uXf6s+VaTcPMMu0urc9vJjW6g==,iv:fvgUwb7qD8ov12/hdmPXvilUoIseA1q+NaKmMqbWQHQ=,tag:RX33qJ6eCUdLdVVv3/+owA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:qV3QA6KwB5xykRNC1FFtcKLMTMY1,iv:Jna/HrjttIiSj9PL2hGybybN3qufxqwh6lHvO5pKe8A=,tag:luz2Nn6RJWkslFoZAJIwVg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:Dji/KOr3uq9WTIkH,iv:4eILlT7dYa6Y4HeCZdBB5EHS+YZHRYgYPG/1BFLcnLM=,tag:psDy3kSVOnpgAmVM8R/neQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:8bLpGbfhngYSVg==,iv:YzyHyggLn5VtBjytDOJTfV8XWAexSXRtqgUbQ69FyOM=,tag:c684rcbyP8qWhxoW4k97Dg==,type:str]
PIA_USER: ENC[AES256_GCM,data:BHLwEGpw0rE=,iv:XHCzZaCzuZXbSjwjobp13/9mz9Hc/ryS6qlgdY+URVs=,tag:8ZgNwSotsNfgbNYj4cMgDg==,type:str]
PIA_PASS: ENC[AES256_GCM,data:v3+ZrlniDZRRw1x/sJRI,iv:AaPKu0BXvGX/20xTz4LBrUtX+dEvVrQUpnTv8HW+D3E=,tag:XO+cV8wI+/KYyXFUo5ub0Q==,type:str]
NZB_USER: ENC[AES256_GCM,data:NQfOyXorQ+0=,iv:A9cwuKWRRagO2qRKORPaxZ+OfiGpb9xPsSvtPZOWKXs=,tag:36lTBiz2ypKfC5iFpIZsPQ==,type:str]
NZB_PASS: ENC[AES256_GCM,data:tMSdoC9F4t5GjQ==,iv:ITVuaxLis8hlJTAtMhs7DmlUqw/XUz1lgW0yaD5j7TA=,tag:m6nOxF/i9VeJ/miw9pCdKQ==,type:str]
HOST_IP: ENC[AES256_GCM,data:2McAr+idNcDbzvrfpkjT6Ak=,iv:3UWW9JhfaNYA49L57fbmycdNYIkZ0aYJw80sr3scC5o=,tag:z+1j0968iCAfgV+JQYbjhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNG15UnF5YlBvcWl2ME1u
            UmFFZGM2V2NxVklkMUxYUXJ1OUlTQlp0N2dzCmlLaE51RWpmN3NMT09mUWs2cmhs
            OHZzTVY5ZTliR1RMM21TYlgxcGJoNU0KLS0tIFM3K1JIRVQ5U0o2bm5WVkFpUklu
            STJVQzFLS2F6aVFnRzNmdWgwNDFHMUEKdpzFRt1UBXLY1fcocFNufF0H5FXtacNe
            H4pYJ683txlQhV+hECO4o1sJWdXtwF1ulbWFqeyST0S+nCvdGAAgaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:08Z"
    mac: ENC[AES256_GCM,data:RZ7je3dx18r0XSnbejToozSE5/MQSEfK4s2b6NSGJZYa7/y++AllYqaCfPZjmucGC74U2cUVZfLYVk9pv3COqA2P152N2a69VBlrXCJ+clflqgABvzIuF8aA6x345u/1Hj/e16qL4ZbeqzJ+OWyB2noL0zkI3iKrrPRgrWy6o+I=,iv:RXRrLdHK5lImaIizmOcqpwk4km/VLSwhwdPxc6XTRTI=,tag:/QjDnUeb6B71Js5ewIZF5g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
