PUID: ENC[AES256_GCM,data:dwVpfw==,iv:hMnAtM3+Cicsp+KC8DmcFQD/0bViCSWIrbzfN1f9Z+c=,tag:a6PcxbKOzP6Vho/u7r64PQ==,type:str]
GUID: ENC[AES256_GCM,data:jlu7kA==,iv:ldadz2vjJF73lsWfksY2A+j/PlOdML+F9BKLgRJoR50=,tag:RDQv66h1nM12emhhjHikkA==,type:str]
TZ: ENC[AES256_GCM,data:vYW2UeP4iat3S8Dt1Yv0VKQJ2A==,iv:Rb7sTfO7Ww51BDg73zLRwbesKDa99LvgApZL84kY7nY=,tag:lTSH841lyKtVUh7BvaMr9g==,type:str]
BASE_PATH: ENC[AES256_GCM,data:MQKiU4EzAlEdT7tJQDEcQ0mKf6cC,iv:dxem2dF7XTJVoIQGWM3ruytMI/bIqnoMl7AaCx8Hzd0=,tag:jCMmLiln/j4HVjzn99uM/A==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:eQcXgWZEEzfGc+nV,iv:hVU1hZF+jz/RPyCxyyKDRpPa5v7o8BirdqG5wxeL5Og=,tag:RuJpSc9jMm4cdhqfOQinsA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:aVzLdJdtdrOt4w==,iv:4dWUCkyFCeFbZHOtKiUDMq69Rf0D0r1ycdqQcgIkoXA=,tag:CdqIb5kUVbFZIF9x/SpuMg==,type:str]
PIA_USER: ENC[AES256_GCM,data:2iWLqCCp4lA=,iv:6B15xd1Uto2uoVHCQVJomkaheLr725LH7NH9BajOxuk=,tag:a2rsgn/cRoxhyH2G099M7Q==,type:str]
PIA_PASS: ENC[AES256_GCM,data:/DCrZQdoU5P0zk3OWkpG,iv:gZmUaBRKoXCYCrUY1tL+pnL9OTWews54Ant5yqTQwJc=,tag:Wu+wwrncgLAN4ynI9kvWPA==,type:str]
NZB_USER: ENC[AES256_GCM,data:VPc5lFY70JM=,iv:oh7hs31qIEY5liNpRXJj6N4T1hdvlUm788yAOO5VLNQ=,tag:lF1K4kwp+Ztrk38IxARxZQ==,type:str]
NZB_PASS: ENC[AES256_GCM,data:UacnZcjZMMeciQ==,iv:AbhsVzA4bbHDszPvsPoVw2pxSFbqz/GDTq/DTlcRHZw=,tag:nHe2s0qHdTz9DYFN2z+9/g==,type:str]
HOST_IP: ENC[AES256_GCM,data:elSmvGMCLZiZbCz9LeKdM2Y=,iv:utKTouufqdqiumA0PjgGmJXdVlj9xRMH3218q225I2E=,tag:Xsm7NVs/bp4yr/FWy9BRlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSG5UQVZuVnIrUDJVSHkv
            UkoycnVKeTNLZ1paZ3p3VDA2SlVQamZDZ1VNCmlnTi9ySExkRVhLYlppU0pYdWRa
            a3JrbFRGaGM2SHYyOHZCU1pxR01xeFkKLS0tIE1RMy9LVXJtRFQzc0tuWFAxdkNT
            SWM5cVRrR2ZQUkd3SHlTU2M4OXFHOFUKiY3A1p6WSuUa3DKaDB6JmQo+orjsDyG1
            ny29c+5Veetxtc1MydP78MQDM9n95pNPg5oRnSPWPcBuuwZzMTxS7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:zDB2BlbsOrUqWrkXLMuRjVy4K1LD256sJ3jQC/hdSAZMl4GUCAdfJGUFr0nSnXtYmQAPbCgm1wUM3K1Dx76SJr1TwghRyTP6TMs50qyi7ciOMmGN/dn/6O1HvLG9JSLW54czfcFnWpsKIpQS9oudEJLcyljZGpz2+PUKq99DaIs=,iv:OwcbDLrvbnvySM7nqWTwo1bxcjMCVmJrxvoPtBqNk9s=,tag:NP2eO/xeMCWi5gZqWAAgSA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
