PUID: ENC[AES256_GCM,data:VQ1ngQ==,iv:nLX7qCJYOqe6xrj0qrsMB0VUE0hDfgbLnLyrdRRTIeo=,tag:nLe366dnddZBajfVCn4x6A==,type:str]
GUID: ENC[AES256_GCM,data:fJOhzA==,iv:B6eUTa8yasDVpc0tFrjA5TKOC3wAhRttYMFT1hadNA8=,tag:/AVrZArCgn2fz5xo5vUy0A==,type:str]
TZ: ENC[AES256_GCM,data:Zp0jAF0RSzpOj91bf3gbuscg9g==,iv:RirxhEEylQOzkA2v144UQeY7jJIhP/yuC6fKAT+2iz8=,tag:wD3cBnC8mGAdSJCWmCyU2w==,type:str]
BASE_PATH: ENC[AES256_GCM,data:rWwo8C5xT21bcr8heBnCqgUPfPa2,iv:eHdG74VXkbRcrRWf0FOfQsG9HkrrWKMTPlMs/m0bzTQ=,tag:COjbpbuXNjqrJxwDmGdHWw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:fuWO5lMF4SrI/0x/,iv:UP52pQHOgvRp0z7IcnHLTa1Mi3ZDJ0N0h0NhNaWBZSo=,tag:0fjj8KRJL0Y+89uUdgdqNQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:sv/VCuvoSMux2w==,iv:wd2tA3VsTZPEVXbUUckq+Uw/fvOH+XSumPL8vnY+5so=,tag:7ZCwkzjDcTWi8xnK5FUq9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVmpBbmloRkFSbHhCV0c2
            TjhEZkV4RU1qSUJpZ2dTOTdKR1ZVOCtjaFhFCjY4ekM5NHdtYkxFQmRSMURpTzJB
            Sk9EeGl3OGtJN3MrRGFrNk5WbUlPMXMKLS0tIE1taTlGRXozRFBoVHJnRUljdm8y
            aUREYU11TWRxMzU0U2dCaThVQlcrL3cKDM/gdxoj5JKeoxC79F8Z98yte+Is5mUd
            2sTNHInF2OQQrqmQf3HWWUZZrJ5LEsDQU0iNLifTpl4mG/yl+Vx8rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:U1/Cu5oxzx2LI8EmUTY8W7f9qqhTripA+HnVoG4GNsE7ouj30bbnrLJpFdFizyNLbS6JfqhMMORoPHgI9WyFbKH0M2AoykjuV73bvhBDAVxNr8wbNtXzMV095mz7clb91GfCCeSyNTReLDn15u6xlZkoAMA2uUDy7thjD0TwUKA=,iv:+f0mjsltNRAjmLY7AKNgup3ECxqvxdHsyUKoA2xrMA4=,tag:+ozoOZRd4nxHwGci0zacbA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
