PUID: ENC[AES256_GCM,data:md5cHA==,iv:MLzRxeMR2tvDi3g4bTRn4EgaEh4JwKPi2IJbU/Qa5Do=,tag:9opWoi05hYiHCCcSd69N1w==,type:str]
GUID: ENC[AES256_GCM,data:brXKDA==,iv:IbqLGNJSs2dK3gkWC+93psLQ1Cb8ORD4YIHfIb8Ek/k=,tag:likkS3gQSUb0+sOAFnppBQ==,type:str]
TZ: ENC[AES256_GCM,data:G0krsgYin/JsvJ1JIm8wFt6tfQ==,iv:4PmVQSSozFOLm32Qj4Z8wdaVs1Dmu+u//oQurP/cV/c=,tag:kaKNZ0YwQo1ydhJaEEAjRw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:hp+/Dm8LUKzVMdLvsMIDANmlHoMn,iv:R9HydgaGnONPzvZV13BCG4HkNw/6YebhQWltJZ+RAtI=,tag:OkKnlRk7VeOdJFRNt1rGMA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:t2v9UB11igkVCVU+,iv:yHBUnmek1Y1P3eyKATT9PVIV6LXHysIhnFR4e3bprZ0=,tag:Go9izdtnF2MZqLNRFejkJw==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:yTM6brKR8H+i0g==,iv:m/rdqTEcZ61+UcAmRzRyY6jP5LSFYM57JNsuoTh9csk=,tag:Kt4Pab5zn2c7qh/mYSwFXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QUozTlhTMEZ6Mi8yd3gr
            T2hDSlZFcFUwcG5GTnpJU0ZWeGRLL2NodlhJCkpLeDRTMSs3Mzd3YlQ5UVQ3RWRx
            VDhMWjhDTVYzZDlMWDBLZHl3eC9WM00KLS0tIGpTaWp5aFR4ZzByb3hSRmtMdWR1
            ZXBodVNlNnBKcUVTaDNBMnFjUTZCMFUKHsvPogLqSB3xxGR1KA5U/RQnv4jfYdMd
            dSzkXY4jSBlaVU2tkn38YVDpSZ1JsakujY2DYULFo5oHLAIfbEvAcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:MRVm68eRai7bURGOgAOtZQRw0mmnefi4Uv1h//I2/ATBmfmXUiO92NIy0ZkIKANpPaRty2Yn/yi9tTW7uuuGJMd7wayK5GrHWYefUh9RqLiHu8PgabDyTq3vZ+tqbPPa1nBHwqc/8M0sXKldttByuEDmO8tkw9uvNz8qd8nzT5A=,iv:JjL+BM3LxhE9qpglWZjTAqsbPiinE0/t8jnosODPB6Y=,tag:fMD9BvNXCg9Y5z9E5rhmLA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
