PUID: ENC[AES256_GCM,data:Idiw4g==,iv:VfoQxuhdgVFdgI02MGGWDyhA9gIB01xu0WuZkQqthFA=,tag:B0HfbrUSVgzZ2/US9BROQg==,type:str]
GUID: ENC[AES256_GCM,data:JBBLQQ==,iv:wVFN0pKXwefpswiLMaEakc4wsSStcc4wUr8ivlirYEY=,tag:UuDlVb4mT1cQzpQpJoZPaQ==,type:str]
TZ: ENC[AES256_GCM,data:DiqAhvPFj6b69/7S27zXT/mISA==,iv:6+uA7oJSwo/AlUuhKsxHap7aFdkKO1CzXQyDgLF//bo=,tag:WVZRXUKdNPu3TNDL4V0JWQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:IOds6Uj9DrJZ0T4t+6sVvt9r1jzL,iv:Qm5ZnZfU3L5X2m2QDwrKyrQ8yPjAXGriDFsV1r9fS5Q=,tag:4gy5r57g/vk5Boya751Gtw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:M0MkJL6BiOcGD5h/,iv:i+Hk4TckkBZJARTmYG5VBgkPgvMyb4oxjzAV2KsfayM=,tag:kKYspG8+H6DjiK4lNS5hfA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:J4g6qiW86LvjgA==,iv:lJcmG2o2T2yGd+BQD6jFaXtakgmOjFFvpU/PBPIbTgw=,tag:ewtDpM8+ARxtO8i/17n8aQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYkxLRzF3TmU0YVZOc1dO
            Wlczb1VsV0hGeE0zUjRPSHAyeGhHNTk0UmdnCkRoRUw2K2hSZCtBVy9MZVdhd2dm
            K2FFVVBvZzdtcnc3UERBUDR2UkhLWTQKLS0tIHlzbGliV1NHemRYQW9VbzFJZUFP
            VSs5MzlUcXZLcC9OT0F3R1VZeFF3cTQK13td+ZlYaKUqq1nKVzduaVdAxfA/HXFk
            woXjP09hp9k1hQ9TiWyJNvFrvCyuqOba126porlVH8e/enp8mBceFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:aK0Tfrx9soqmW3587dd9MGci+UbFg7nBav8vH6rdt9u8GvjDEiYfY2M9EuJ6gKSZ2VU2fxZgwsbAs+3p4bMvwCrkHCz3b9ihvs8I4zi8/z3BUupiIVO8xFxySvedzT/SKmGwyZRPKVySVlYslqjYvGgXQ+gu8JN3T5GuO9FCH48=,iv:AeUWzzXCk3a2v7/6R2d3Zb1lrfGJTLglgI2hXUm1DwY=,tag:DoUAn2bGgcVCwX2RU4be1g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
