CF_API_KEY: ENC[AES256_GCM,data:0IZZjeGqoBbEpz6/QaB3aOOZP3GtKIz3LSQI1OHATG2C9C3kwEZLdg==,iv:N/MkK64baf/wJqBn6i+6IjNJbN1SkBn0aMurfrO282M=,tag:tZ2rRiwAt/WzbKDNX+dpzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweGdKQkFVVzVJSFo5QjMz
            MGdXcTlRODdodEtXTDBEaVNNdGg3TC9ZUkJjCjJaTy9FQkNqaWVYcyt0WFBuOXpS
            K3ErOFBxTmV1NDc0WmNRNXpQVkVaOVUKLS0tIDJjeWdTbzdNUE5tOThXd1ArY1Ar
            MVdXVlJPcTZJSE1BTk5GeUZvb3FZZ2sKa0HGXgUMkK+WHI1j5HbBNvrvTRYsbL6d
            1ffEeHSNCvLj1n2qfCBxNTGeJVR2ah6naOcCSM8tfLiFCFjdis7ozA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:Q+KbJ1VAcbxgO7aj0MFWq5QUGwKFquWxGgsKRveF1omYhUhUD8R+aWBiETGGBuQDzdtvleWNWGLviqAIqWYCLcHsWd9KhRnBl1RR8J3UDxV4OK+mYE2l2S9CMmE7dRpDDCIBdrphpA9D4sET2k12baddvCOeNXfAeDZjN7tlEkI=,iv:p3RF8UgRCcQjMMNMsaYEv95c3Vk58oQB0q7jjXtUEwc=,tag:QY1COCcZo9r8TJfCyhA3pg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
