CF_API_KEY: ENC[AES256_GCM,data:GcWNxs3b2LoDzl1OvbT9ypYe0MC+eOattDr/79o1xD/+9S3tv62IiQ==,iv:fqjYSGv49q5sIN1E+05w3E96j8ijs9B0T9hezWWJY2s=,tag:3+iKP6FzbX03aXe3CtZM2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cFBZR0YyNit0WnNybkNy
            RHVsQXlJcytjZWU4UTRMOXE1ckdGZkxUWlZFCjAvS3M5YnQyMlc2Q1gwVVB5TGxz
            TUFwbTF4VjV4akxTMzRoME1VaGU1SW8KLS0tIC9icGpTSlRNWnRlVXdrTzJ2Tllo
            YXB3Wm93VGttZ3F4WGJxME9NOFMvUlUKoljPL8zpvDtt+1eTYb8mLm2fZq2in4es
            ABtjP4Nq/TaRxuyIEoMdZq3JjAV2tOye74ryEgP6/HcxSDpinqCH6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:TF00n0skXcvFRxXd6GLNRQowW6KkeyVQS3dsxlg1mZhDzkwLB89lDeLcHXXEQRAxoPsSdhAuI05LRtXX8+D8jauO5n1vHSHbNNyyBPOuamOOTaO22JLCwkeCc/53kEYvl/KU7c7kbWaZnOsYWxr6D99Wh8AuzXhs07gUIoPD+v4=,iv:rJdv35sFmD9wst4pMTuiL9G5IAoMMDi9qmrQazUCJxM=,tag:KT/pFS+efgEXxS2DpcPUsw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
