CF_API_KEY: ENC[AES256_GCM,data:wBZLEM2WnbeWK2buHGJL+7u5OB7GPfRp4RHJRPfusKRhm2Q0MZDu8A==,iv:MBKsGidaAy7PSMrQwuf9AitZgTWQ2lgkh56npxpYY2Q=,tag:gBrXrfMP7/zeWZESaQvhOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNkExUHhjOXo1RzFiRHlJ
            eVNTTFphU2JPYk5PR3IreWUxQmxBT3NwWXpBCkhjWElSUHNtRTZ1aWl2am9yaWQ2
            a0ZnbUg0NU1nYll5UndIWFF6cHhrc0EKLS0tIG5QWjZMMWZPS0ptYTNDeTlNTnRk
            aThxaW01VEJqLzJHRkdoNERaTGxSbmcKWL9AVcyHbSdBYuZmoC1y+snpbwq72t3D
            KSkD8GaJDWYiy3bccois2l+PAWGfryIrYhDdP9F5SSqW/9jdWc5LKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:Nn95vowq0erQDmAkalvfEh/X4dUbz0bwBcwVrwo4UuG/j4l2V0eY+BCcHj90nGP2F4yLL4zN1HpSeaBC2M0gkkSGilR6NRTxGnHUlaCyf3DGay/RWJaKIcDbwBCYgYrWXPbEDQHB7CTZ2id/bIraFDxeOUZgbe8u2ZIRW7+MPdM=,iv:rKITPjq4kP8QRGFa/6zSQjLeGLsZJ6cYFRoCCGh/TtQ=,tag:Q4GsBCP1+tiybC4HhYysGQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
