PUID: ENC[AES256_GCM,data:aIoS5A==,iv:KWWR/wQs9g5yBXl3U8SSLUtr/N0/udry5XphRLQbF6E=,tag:18yUbDt0pNQHJovuepyzJg==,type:str]
GUID: ENC[AES256_GCM,data:lMrlmg==,iv:epog4RHjGWVfyoNJbRLKumh198gD4BaGMjKyjTmD/14=,tag:3voVpkGQ7IsdxgKQVz2aug==,type:str]
TZ: ENC[AES256_GCM,data:zKkwXsO6BthGGLwWydPra8bEPQ==,iv:yEXlDKcMJEGqYQvqzANk0fiV23Gz+8GBZF6+Y/mwVe4=,tag:ONh8QrzQeeGp6xdH6LnyBA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:nBug4rx/h1RepdPcUPHD1dYgNWzh,iv:q7MsvQ9nxML9eH9wEdh1juHJasGi7qkv0Ru8JF8V1B0=,tag:G60HU+aF0ZI9KSooqtyUsA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:9WDRP8dBMMqVydFP,iv:TRD5O53lQNtFB7/w0cBb+SsBHBR5VMpkp6fi606VG8g=,tag:l7WANeQOPHyhXSPINqNBnA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:RfTh6+0NrOduhw==,iv:CfcBLhT27GYuUs/9FMIcdFadTxlEPW1poB2eTj7SP4U=,tag:LdS8AJJjpL3KO5jg4u784A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOGNDRy9JR0pzdElFZnBx
            eEJkakNFUCtNb1RzNm9ZZnBqYnk5UDVZTVNFCjRoaFg0RlBUSkhUSlluc3lrK0Ry
            UTVUQnAzRmdpQ1htbEVxc2NKQWRnL2sKLS0tIFoydkJtWHA0Q1FzRkdXQnd6dFM5
            a2JCNzhYWWxNSTdySjNtQVdEMlljQTQKKgArmC5GRmNl0/dcJp8/xS4rNvmJnXll
            tPSI5yMX+Eh7WmQSX61+2cB8ssLjSIm3+i8kqc9PZephRP1aiAyIGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:CLYzmKXcTLwSyrnOmeSfSnvlSpp7QVp0WgKc429p/ipY/tZvefGUZVvxnJW1rmzGcWYiLduMe08yrmct7r1TCOk2fBJdB5skgtde/g47tHOujIC/n2iHdN5xvshHRSbFhGDZ97u4Cxq4V5mMcRxsOK6kj6BnLNVuGzczOutIVak=,iv:VuGv0AitsCpF7fgEi47fFbfS4/+7wyteyHXBgN7nouk=,tag:bTZug9SVWWNXfLijkek9LQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
