PUID: ENC[AES256_GCM,data:WTdBZA==,iv:dVOZLRH0FAclbyprX1BIWwAlde3k5ZD/k4hk0Ar+q1k=,tag:Dlv1N1Q+Vj/hHzl7rrx1Dw==,type:str]
GUID: ENC[AES256_GCM,data:wSQKjw==,iv:Ib5MJRqvSbLOBdWxSVblkn1iETZZKEHdX7htDx4rcvU=,tag:BGk1OMVOpRY6YTEjs1WEMQ==,type:str]
TZ: ENC[AES256_GCM,data:mshi7LPmg4Nh62PMYp8jMYm24w==,iv:g9Dwt+2ul9DQnA8Ky0pJo+QnS4GYgVN8rT70l46h9pE=,tag:NT5wa4dCf5q90miAZH/8bw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:d+gP0P3FF8xOa62CBhHn+l7ZER5E,iv:6AFkpDZR9/VWqHfPduZONVxGgwTM+WPSVsOxWtPLE34=,tag:W83hzco6EhdMGXLqk92ctA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:TmI4P4W+j3ueIE8G,iv:F8TLG0+skisOV+wmxhWM2hpXMyu57n8inNpGdzWKBRc=,tag:WusAuB2mug+jgy3em40xZQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:AerBX6+WFvoASA==,iv:CirSZlTuZDqGCToAIblF+iBDlle00g1Ob4AYN4atvnY=,tag:QSyzj1APvxwmHlinPH/gdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNE1qZGJpbTRDSE13eXNM
            N2w3clBYNjJiN3huMDY3cVd6ais1cGN3N0VRCkRhTXJUMlZXSjdEdjlObUMwbXZz
            V2FVd1dOb1FCYkxFMWJmbmpNMjlLRk0KLS0tIGVGU2JQaVpwc3N5MlVtV2xoMnJo
            UVl4QTJWOCsxUjZBNTZuSmVNeGlWTkEKAD2cLQ8I/twkP7KDCQjs6JdebnR0tZ6d
            cm7cpMoZ9fZDrQ88F6YGQZzEall1fwZZX/cyEPZi67+IZousz1Wrgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:dZP2lKKpyAl0aBlx4cBYSMvg0UjlyILiD3rY57Sr9GSVcsbRf/nvPn/9eht8ZBEd5S5KJbZD3aipGsW+PLR8QIL1Wd60llGlwIw55+3/N+z+M48GuZN1tDPt6YBwYK8TvZThOBGFu+V48/SKImcb2N9+nhncxdocm0dpd0PGFuo=,iv:wccInAlVcKj03oxVyzBprgnC7Qxi0+QuEa6NtqugX40=,tag:kWzGw/FYOln95UKXl9JUKg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
