PUID: ENC[AES256_GCM,data:GAYLKg==,iv:g3w25yLOqobD/fk9wTRhCd8PSMQStPAN9ky5qGtnU3c=,tag:XfMH/pl9vVgzCnOYa8vosw==,type:str]
GUID: ENC[AES256_GCM,data:kFnQrg==,iv:voh0sYeHDeLYy/7wHOwvd4bQy1x/5IjMWwbQcCQm/l0=,tag:sPXz77dCYlJkYYjpoa44Pg==,type:str]
TZ: ENC[AES256_GCM,data:8/saOVGmNygeS+H+P0HraVEZpQ==,iv:BY4hkReBJoS9zxl2k03e/hXXYf7CXHwj9rT/VMLauo8=,tag:EUjQzqOXh6xYwgcKGScomQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:e/Zmv0+fEA03n9q4L5EjGDDD3xHy,iv:szIsujhG72eo+sBlCHtrwX4IkoKr5L4X6xbZG1LUyb8=,tag:H7Z7xA28a1+QdiV7Qcrd+g==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:31Eiv8h+78M3/VCQ,iv:Tvjn3qJOo7zB3oFZ4i667ua7+OfRlr7icixgB6CxT5o=,tag:KJZdR1UWmZ2XLWh54hRJzA==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:WxaSH+3rScA03g==,iv:qFmR1RmSiTn4Ia8aDAvTFHon2asYPP1LNC47vIfT0a4=,tag:bcSE6HG7pd6gZM4w06H86g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRlFyeTVmWG1CU0tTanMx
            T3U5YVNFcUhBcTl5bUJ3bGh4cUxFTWdXTFUwClNTVEpwM1MwN1VuTE5ZTDFEalVs
            ekV2bitUQWhkWmZ2MmpzaVN0MjU4SEEKLS0tIGEvVWdtRlo2c3pLSzZyRXR0ZHN4
            VnJIS0dtR1drQnUvTXFkaXExWUVuSXcK+ogB6PqzXixiGbvS/b6McLCreh/WSjv5
            eVu+Y+ZFRrTJrZ3oj1jhDV/snlTZVbJt0fpNOXd2NZo3wByTX7s6Rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:GywZoXeVnFby49TAd+PvezLcodGlJl3Vnt9IeAB/XP6UuxMgSWWKq1cpyALeUY0L5KlRZaz3ii4L1HlIkkoDlPw91/Nh2uued8Zyr5DzVv/JYkBAiKoivY8K3G332tCCvErRUxUpGlwvjXMB05Z1k/Sn02Pgn/wqPF9DaccGYOM=,iv:gQqScNfSAqiz4oeiEoltFd3yzdDm4ciATmfVcxJ/IBg=,tag:ZgO24NUfiw1rb62QwqRJnw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
