PUID: ENC[AES256_GCM,data:bSF/0Q==,iv:rin1gTBl7yesyDq2ABTyr3dLNZEbukc7S+0IOsOvCfY=,tag:DkeWdOlIWlx9HKO8dB9R3Q==,type:str]
GUID: ENC[AES256_GCM,data:5RVBWA==,iv:yWH5+GJGeinagDaOBRCe5Eb6qqYbwyXcp1i0JRM2CU8=,tag:TrTV7Rpz5erQEdMNIXt9mQ==,type:str]
TZ: ENC[AES256_GCM,data:UwqRYoOViaU+6LAk8wS8IM5IWQ==,iv:Z7LVk+hNMje+mi0sjacSoFmdhfDtEBFPftR8KxGU5Ao=,tag:RP8EvyF/Ler0MyL4inZXBg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:V4o5HCAr39N8v3t41RdkfJVfSWdh,iv:KSfAKB2kE5iOK/TIyf1UfRHUH9uE1L0hp3Wy2Po5u2k=,tag:RdnItsV7PhqSBgQq3PXwjw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:QKoE+8WfWJGejGiT,iv:ZjppqAgvCjWoVKWARtezECOxp1DkuVezxRrtAEWpSu8=,tag:u/3Mh6VfNgjkdAGN9/cz9Q==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:d+h0ogTvLlDmCg==,iv:6LDkhDlJIPAfyovTLs+BaYrQgpAg4C/2wYovD4gCAK4=,tag:wvYLFPc09GI7vKYixgxvSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SEJHdkNKMjIxL2V2NHdn
            Q01jTGhwMkt2NFJFZWpQT1R4Wmg1LzlOeXo4CnFKWTZ6azM4bmxEWUEyam5tTXQ5
            RmorNVhzWkh5M05jc0ZJeldsVUxFL0UKLS0tIGZsaDhEcGZ2WGExbnZFSXBWRmNh
            VDZxMG85YzBLYzZkMFVLTEV1ZTNNTXMKVP39U+2U5CYTe2jnLzDyxcdejhh/4Qh1
            ZTTMViOXzmucZbRf+lBphSk+nKekCeLmIEHpM4wmiOO/AyDTd2FIng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:17Z"
    mac: ENC[AES256_GCM,data:68/9GZfexJNsVp+/88CblioznWgMjqQCAqJX8b3sQFWjbal9xTXWXHbn8xt6YcGj7Pg1N/ymMDDN+UmUhqGeHtg6ba7niIuHaqBh2nENarVnlHaDOuyP2iklXNxxWcMk+kzDnpMtWl4HIb99BiskJUCtMuiUFMOT0E44Bpwv118=,iv:NBKxZHAvknkkSXE6GnnLfnlamSJDpZ8DmvB8utLBqYU=,tag:MgRxc45x99I1fchVVB39pA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
