PUID: ENC[AES256_GCM,data:2qBpBw==,iv:ghpPoDF+QTa9ffnRGIGjw+UYfMTNEf09AMp54H067hs=,tag:8MQSnhF9DuKxu759tuBJ+Q==,type:str]
GUID: ENC[AES256_GCM,data:seZdMQ==,iv:mcrSWmxQSkiPMHxorXMZiw+vvgg5sE1YTzytch5n974=,tag:/nFV9DUUOrgf4pDCHqDplw==,type:str]
TZ: ENC[AES256_GCM,data:lFirC55rrdskT6gdBQPO0NsJzA==,iv:a1XcZqyxoeunFDpzliIHF1Pa/LyMCAUZYz6d7c1gyqY=,tag:kyg2vrPSxmhImv5ipBL4dA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:+DVgpdKJjKDVHReopNR96mSzzFWy,iv:GOmzvh5NPF8i5IUNB88eIq83dGjHf661QePJi5MVnFg=,tag:N+s1Jr6BssiZFMC8/of0iA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:4IRnNsHxgoCxGA9q,iv:8WakwgyqILzSLY4efmzBvMpy+G4Eycma6ywYLN9t0V4=,tag:3qU3VWFwXKXpuCHVllI/rg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:USnKTHHTLYmJOQ==,iv:PM7QLTVHXNTdwfTmDVX30QW4y1PhUCJGVQD6WbTHOks=,tag:IbjG/6M6GsloLL/IeRvxaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSXF6SHQ1bnE4WFhacEdG
            Z0szVGhKUU92SksvNGQ1bmx3NTh3dVBSQ3owCmtCRGltclBPdjBWSkQrSjFRbHd2
            S2NGRDZoN3pLb0pPTGpWSmdJd0YwMWMKLS0tIGlUVDFZd0ZtZDFTbGprNmNHMFdX
            ODZtSFB1a2pnT2tvams3YVNQdDh2SlkK92gwDjKAJ9tyZNYXLuCc0bMCA2IJb+rP
            +d0FFuU7nKxYjT7NZTwNZp5ap6LWjEO/jIzVdTvVLxiojIMIJUgsVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:5gP8OCS+5ClgP3yntSxjbaobFqQFdUUYUEYB5qvsUXNGmM5x5LM8S9S4qmI1FcSFRgQXY9b/NmiFD+GiRSWe5bNe3csJEK9PKe/A6R21a8GHRtYYG8lRd6VWpsxvXy3ZRMEN15CDv+7t+rQ0ICEXhA8Pc778QfgeWjrrYAaWWYk=,iv:j0FlSzt1ZAdT262dpK9dJHoClkTTwLgbwAvga1zpGZI=,tag:A85j0kuh0U4E6UfjxhF6dg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
