PUID: ENC[AES256_GCM,data:ApR9Kg==,iv:KE8CTnx2B7oLFTQ2RWDn6aKAl5RSP6mEHWN0VciMovg=,tag:1qZjaJAwrZ7sZluDCFJy5g==,type:str]
GUID: ENC[AES256_GCM,data:gFDPXQ==,iv:h5P3CPKQ+5LSgVttYsf2LHgkdj/tS/BfTE0arX6IU/g=,tag:/FGEXfv43/uyZ2//tRkR3w==,type:str]
TZ: ENC[AES256_GCM,data:Dn91Q4rObyBNujN3HFb0DEEIUw==,iv:c99ahkmB3Pcxz+ft8ZSJbqMaz+mB8YfTK60xznguVco=,tag:5VbYP9RC2vD94TvnrA8BHg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:bGBLPdCmv7DUXoT2qLOAywkvGADZ,iv:bNOc+I9kX62eK/pe27J3I8u/T1HkhZuoAcBkcYe3Loc=,tag:bc/iQaoGtNfb/pejr4cAMg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:bSIkCxypo+PjTRc0,iv:l8dhNxCxzvH1h0MjFOtvUW2z3u8MQLWJh3N70Tq9RS4=,tag:V8IGPZ0ga2D1ffv6TZuYbQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:QbaZNB9y/Ze1EA==,iv:EBd5Cegje+Gl0VaWgbLdmwirtqLvZyQJp+5EtVJe2DI=,tag:Tv4V9IhFq116MhMONvTZWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobHNWbFZId0poaksrUUkv
            ZGdJVjJiSjVlVnJINkNyd0dEYWt0ZlZSOXpBCmxmZlcxaUZ3QUJ1WjYzc2poOG5C
            Yi8wOEVlUXBWajFkSDV2WEtpMTFzaVkKLS0tIGJuM0xTYmQyYTRiaGV6OFR1K1Z3
            SnljbXV4TnRzaTJwL0RpeURMYnJ6U0kKDlQRaoZaFkOHJUpRLu245bT0U4pf0g1S
            dCvxv0h5ol0I26H9L9wwwkvyuhZi+RU+poNW42la125nftE9wB+Lvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:xl9vC3SWVUaOcOtcqMCrNi3NcRkD2iGtch2IRuYkvetDsUBY/XOls85K98SVN+X/0aq4QFispI7ySKuDSycL+ROjn52hGh5lfEHD9kfPqfWKZsCFphHfLXkUZ3IPbP6bYhzVgFWKP+dWZuR4olBvVCpFOOhvyXVilX+K+CyjXC0=,iv:uUt+1qTleVja2lmzpAb+W2z9HF9RutFxgL4mYdp9+yA=,tag:fEtgu8I0bO65FANBJdkD5Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
