PUID: ENC[AES256_GCM,data:5oz7Rw==,iv:/GmJCepD7I7pBPqli9iPCxJP35m9Lw4IbZermVxOXQ8=,tag:VsmQdJ3daSPVPiZ0L0xQLA==,type:str]
GUID: ENC[AES256_GCM,data:EfoKEg==,iv:YXBbb5pYi70CH9w//y3WIuXSMn8/etdwZJgym7zuWWA=,tag:nvCj45btHJblwiPSRTJw0g==,type:str]
TZ: ENC[AES256_GCM,data:l2KegNtlKHc1DSFlJNnTHHK9iA==,iv:70550B/LgYeFwpCLfDnk/l5jrDqg8i6BrsIw0k6b92c=,tag:eiqTu0Utg4EzgCDfQIZwuA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:HKsoquA2Kqxx19Qdu8UhOhQKw84h,iv:cPzuBQqRL7aYWA74DIfXNhEd8/ZHqgps2CS/f/NwfeI=,tag:E69GM5/eGkAU0NvxTJJ5ng==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:Nvkju8xGTMDfDIwM,iv:aug8zRnBZHH17noXbHM2o1kNOq7WUvrdGg9EPJzF6Cg=,tag:LSByJAoMjA6iFXNBc86gUg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:4qd2X4x5BOqWUA==,iv:Ips6G4Pz7zVtfUAfzPOMAUt0TPtbR3/QpikkSmcHFT4=,tag:jL65D+PpgHw/pgV4Hz/Egg==,type:str]
HOST_IP: ENC[AES256_GCM,data:QyGNKIEI5+PokhuQ,iv:DQBLN+HBxT11agrxWNzaHyGmarNYm+J6YTikQ54i1No=,tag:UXPpp3qdceUajSJXWkEsSA==,type:str]
QBIT_USER: ENC[AES256_GCM,data:ss58aWvVfmI=,iv:bC8LOtZpB6wq8kWIOy83WTbrVpwPJl1RenL16OKeBl8=,tag:x+k5hMrS8klGINwqEEYqvw==,type:str]
QBIT_PASS: ENC[AES256_GCM,data:AH83pNj+pHRWZg==,iv:hHVb26xKHdlvq/GffUkvQVrwu8SdAJ5UptKQxvr6Q+0=,tag:bXER/aBSNCIRzGtscu7qiA==,type:str]
PIA_USER: ENC[AES256_GCM,data:53eAcJeqcmg=,iv:avwVXXiagoryAOvdzUZII/rZGSrTxUmYx4xCshUem2U=,tag:IwROTyb3tilEJOs0IHnnKA==,type:str]
PIA_PASS: ENC[AES256_GCM,data:xBwQP65nNwEMct5px4Ui,iv:8+MNZjLumFB5OAMHNeGAC5iEXRgk0QdBGoHv5K5tuKY=,tag:RuN/SOul8r753MSXmxB7vA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1d0paNVVWdXpiZzB2R1JP
            SnJRNllaN1dYS2RnMDBSSHJUWk11YjZVWjNFClBiL1VuaEdzSjhKSUFrd0ErcXFz
            ZjZBOTh2RTZoRW5BaVRkZ05EYlVYSE0KLS0tIG8vY0U2dktxdGhzUUdlcUlKbFVi
            cWpwdHRVREhOak9QOWN1b3d5eXIwOUEKPEp6ds2nglsjux4+1eLt757DWCWI/wZ8
            0fIu2kW5ATfYSEwqDwbIhiDsjGYqOMZ2Ez8vRQyr/0ap/GLFTVV1KQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:UntDchDyQ8AZts4wzGzJwOt+WFbu0BRq3bWy9EpnWH8B9ns/qrGPqHY/CXIhNt7xN1Xv0BF/4ddaK39F1qX64ctuTJ56JIsTqQHqbJQD6FIaBcH2kgy9vf6iKc5O5hGj74WQR1ek1vqQQ/Vzxqxvf6B8Uaz0NcKuEnylm2AaL5k=,iv:7hpB9TatzNvESNm9PHvnMHwRVu5Rppg7edQIzTuKJdE=,tag:ItX0nB1Uh8r9yyrjIN8wAw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
