PUID: ENC[AES256_GCM,data:tzPB6w==,iv:PqUF9WMK+sYMMg7QU8bdBwnLX0yyCYF3Aaf7UPwBTs0=,tag:q9O6hSYt3+ImkMeK5kBCrQ==,type:str]
GUID: ENC[AES256_GCM,data:xpivuQ==,iv:rj6Pk7WHhk8tz4gFCLX2YshXdTbvRSXl3+/P2a/ZtsA=,tag:5Hf2+gKkpRhz32UZBLTy9g==,type:str]
TZ: ENC[AES256_GCM,data:apNLvStfdElvNyl9Hp9jOoPkBg==,iv:xJAJV5a+gGJFsqIJAQsh4lctzb982reME9UpPH9WNzU=,tag:xp/vPtkCU/azXAgta/u9xw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:Vz3Dk0dUTAsev5PAVioEw7YAEK2z,iv:U9cpH6M2tSqhcIYBKT3aKjYcS+S5aSKoWMThY8Z33cY=,tag:ZZ51Z04oVIhw4tWUUH4WVQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:5rgOMOfkqKRfQyFj,iv:H+gmmbzapL2HYmHpAIe0HlgcJ0ge142SRs889Dh94Ek=,tag:dQOM8gzouK+6STG1xhOa1A==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:DERQwuVmieXHXQ==,iv:6RBW6wseyspZi4h48wIRgV0D3zIfHe2eFElDrR3vAgg=,tag:vLigjG/8DwIWpyzlIRj5/Q==,type:str]
HOST_IP: ENC[AES256_GCM,data:i763lj1Xo3EX1vEh,iv:Ydm05SJtOhfU1SMEqZfs0o66148+imhmNDtP2DZWpac=,tag:8PxvkH8AFkwL2m4bpl7p2g==,type:str]
QBIT_USER: ENC[AES256_GCM,data:drDQ/kLXaA8=,iv:gvk6SRNMqb5MjV/1cA5kLoZv0AqGLk29mP7yFcNlq9s=,tag:2KEwq4OHbODq0a+QpOPQ3g==,type:str]
QBIT_PASS: ENC[AES256_GCM,data:W2JUsglET3AL/Q==,iv:5bTJdmJBZIZXZ45DTbzo9feN8CXHaJakpPcvBa/SwPc=,tag:8y7YdagvAuIjp5hedRI3kw==,type:str]
PIA_USER: ENC[AES256_GCM,data:Q44es8n69j4=,iv:K+YsMUL2zMROxmK4axTv5auu7OOBUExU0U+hLnL9B0Q=,tag:ZCC3NC3feWsyobbwJFtTcA==,type:str]
PIA_PASS: ENC[AES256_GCM,data:GhgX+FQ8Euw9/e3/d0I6,iv:5sfTIH3ugkOP+sHU9097FYYtp59VEKUEx9mfw9PfknU=,tag:0W/fxWYrz7HsHkJtR5bwTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsM0JZQjBaUU9aZkVDSERD
            aGYvWHQvZ3RSbnZoWE9WbXg5djBmcTlSNVhvClNiYVNGc1J3dERibTRSMGxUTFlT
            TlhiNDgwYUN3Rm90dFhHODg2UkRyMDQKLS0tIGdvOHYvYXowRVorUy9HWUd4SGtt
            Q0hab2VYT0cxSEs5c0h6Y2RoTnYzb1EKohewpNxCYxsoqqlMOgbH+6TpUJW7wXI6
            tS4/crk6SgXvrO50pNyEOdOCLIbUWtyO6RHfFYT+SayfwE4mtwhs/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:08Z"
    mac: ENC[AES256_GCM,data:7hW2EGc+H72ZpJZ3P1OXFrGkzrvB/pIWFP2+YVCHDXhV+GzIa0SVB4Y7jft0JfZvXjpyog9eeLHIGRlM0wsEF80V2hKQ8O7YWEheaDe9B61SSCOPMBveaqd3oeEXhqBy4xulspjU8MmPu9g6FiXbI2rjXpbBgVbV73KM9rf3BQM=,iv:fd+KqB8eLIsT6NJZeZI+LoSFiQRmFAwj7SZUdPNQyjM=,tag:9IzHKeeY5mnDSHqKi/2OIw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
