PUID: ENC[AES256_GCM,data:dQun8A==,iv:eUI7h2Lv1QIcPDvja7VQEWUbZ96JX/yRVDgtzpnq7Dk=,tag:0eXepvfeDLDh6yqEVNbpiQ==,type:str]
GUID: ENC[AES256_GCM,data:TDbUsQ==,iv:ubCPLGrA0xK1AFV0r3yaNahdCp9aFAEPxl4+tY536ss=,tag:Rzb1Dl0GmZjYWi2rB6ukAQ==,type:str]
TZ: ENC[AES256_GCM,data:hBKnACkSD5zqi0VRiF+BGl1vDw==,iv:FE6L//mu1A1M9kWcv/yDa6GzmmUet3EPipLTWJ7j8jk=,tag:AKjM/GZR/rptl9b+W2MKwQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:gWLpKxrdmr9ECSv31OORS4pQ+dwz,iv:bl2Fs4Gv2rKBhqKrDUrphv+p2G1EyDp+eTueNeAQqLg=,tag:tw3BQYOlg3snK1jmIuqpbQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:aVCTlt0hwrdpPH4A,iv:R/uDcn0D1/8/7LNksODdyAghnl6q2XGDKrGJEOnzV7s=,tag:i6nTa92qazjCqN3aVKsW8w==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:zo2WgqzqBJ7yEA==,iv:+OWz/2jARygsJhlKNc2VXIubgBEpNd7VK++TDn2Hvp4=,tag:zE0IPjd6RFWg02rtz5b/fA==,type:str]
HOST_IP: ENC[AES256_GCM,data:dVLMDx6hX+dbW9rJ,iv:91DXd+LMgnNagRtUBZ2rRLrYbBAqfTlerTYn/9ybIf0=,tag:6W89Wfb5WI5VomComKmVBQ==,type:str]
QBIT_USER: ENC[AES256_GCM,data:Cc+aZ2J66d0=,iv:6ypujD/P4yw43x65KB8oKmB1omnQX0eKYOdJdlSiVyc=,tag:5qB1/e8ijmF/82HKZ6l3EA==,type:str]
QBIT_PASS: ENC[AES256_GCM,data:pwSHORqWspfIWQ==,iv:V2O4oZI0BRObokIxOyr6wU+PK0UaT62u7qxSr4m0c2Q=,tag:TM6X8rDk6OqnVGKRd4QreQ==,type:str]
PIA_USER: ENC[AES256_GCM,data:HhPPrrvntdQ=,iv:08yJR88lmXfVJWuxfKioo00Ohniyqlz0EDcW8fAi+pg=,tag:9Qdb0xGpiCt1A/4pWXkh2A==,type:str]
PIA_PASS: ENC[AES256_GCM,data:AwfbVE1xuF5j/BwIoOX/,iv:1DcCgYveJ1hbZIwkMVa4F2WZs3knszEqADsaxRmaO4A=,tag:4X/1tsQ1rfqDw/irvpEhHQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4YVFMTjI4eStOVVBRNzVE
            SGJta0xJSjBYNkxZNHNHdDJMN2Y0aGdHUlJ3CnJXRDdPVmRPeVNGc01pRXRsR1Fa
            ZHJ3RnFBSHNJOXJrRFU5djJJSElmcVEKLS0tIC9zcEpLOFV6cGdDTlRNbUVzTmQ4
            eEd0dXF5alRRVEJ2T0lIYXRXMjJNQXcKFV+3loQIzIe/ND6BuyRaDHmzNAo4ChBW
            uDVwaBl5/eIQPZL1gKpAU8GPS4stu9ZwnAtQPCRB/BxGbSFmV+/zxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:18Z"
    mac: ENC[AES256_GCM,data:tBI2XKGC184oOQxPB274tXHIZQ7OopxEnv7IE/O+1YTKJNdlz2+bYGPDlAbJgtjgjZgb8adI2OLoJVjKLiLNOTzncBHR9LYBbOtcMa9hwc7ZSvxGaDxAIPv43i1NCT/C7qHrUPrwHulYteZrG7/4nwAOjzi2arkjs906wEVPERw=,iv:Bg6iu58X+9c9XK3CmrRg6zuu16yM6uS8ind+fam1QX8=,tag:+MUivUEWFleARW6V4DBA+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
