PUID: ENC[AES256_GCM,data:ncLCzw==,iv:cviNYDlKyMALWZgFUMypPoq129USxjHnFf0+fEshk44=,tag:itNALzcDc526zvSzLuYbaA==,type:str]
GUID: ENC[AES256_GCM,data:7bpoSQ==,iv:j0QPs7ZRO1DQXVgxsT7PQqbYc36V/QosGeQO6ohxh40=,tag:R3uJlcaV4HON+AFaeWcT8A==,type:str]
TZ: ENC[AES256_GCM,data:rt+BCEjwpnlB9+2VeahL0fBgRA==,iv:UbgZWmZkFyZ8VFoN9kdZG3LCxVG9+F7VkbYvKei3Eso=,tag:B6uCcN18uudnudy2f+7Ugg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:8aeD9/K5xLSdaSOGWHxHVF45KTB3,iv:E/JToiOM0HS/mz2NCmR9i0S+hBGHnn6fVEPaCm2qs8o=,tag:nf0kp0Hg+AVPfOS4cILVbA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:cl8s1MfAH9nqAWo4,iv:vBBc4iQJM4mnM+JsfUjtbkguhlxvSFMT9ELNrUp00UA=,tag:3lnjQKWnfM0lhEiuLbh55w==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:9mFq1swItkbjYw==,iv:xCEXDdKUYqNq7XRqNo6V4/QgvB8IZdbH6euGYIYtpvU=,tag:Pyy+DV2CGK85Nc5tEEphDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQ3A1M29GMy9lRld5c2l4
            eFRlN1N4VmN5ZVJwQldMaWtIT2dFSURzb1Y0CmlGd25uVWdqUkpJVkhZdDQ3dHJ5
            eWRKUE0vb21lMTFHYVE5azM3ckFYbVEKLS0tIGd1VFVLcDF2WmR1VmpoRjNscXdP
            YkhmSG1ST2VpYkdkaSt6a3hmRjBJQjQKpCMC4RDlAhULaTNDk1zH5Jh4+8JqH6q9
            RthgY3029qo+HIV0soCvHiCgrrj/nGdcNwczwTfIdTC8t0DRR4Uzxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:YQ2n4zVtR5R22mKddFpz3KHnCadi5SwPXgl9EtnNUO31eVnWRG8ANoR/9sCogAyK3a4bXOF7JmJsBeXEhWaVatuLEdLCXCjRU2t99mL3jeZjSOw60YKc/MAvdCepudwAmCTIiJxc95tM3c8wOQgiWsonn3E+fFnldrIOCiyzGKo=,iv:kKEgnq710t47+9adh/gTUVNHke4odQzLKapZFddfOpM=,tag:88FXHGwt6DwyVVIySmreVA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
