PUID: ENC[AES256_GCM,data:ZVbpUw==,iv:diIus1n29zv/83r+4U/WtrzUNhWhsonhvror647kHXk=,tag:nUEif0peg84JAMKb896TMg==,type:str]
GUID: ENC[AES256_GCM,data:AgHe/A==,iv:kPwyBeayECXrq7STobGW9gT42PbNUgvdm6givyooPyw=,tag:Hr80YDw/tk1G4TLfO7tPew==,type:str]
TZ: ENC[AES256_GCM,data:PyHSow0pEFhqCgjnwz74p/6QHg==,iv:HqQMarEj5XyjR5LyqCTpGYWgwCUQsygVct/gwzT1q80=,tag:nPFXEllT6BVh2aSEI2JSSQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:LkADH/JO+BASPE6Tc6dSqAnIFLrT,iv:oPspOlft0FqN1IjU4tTuN08fBr9IsnPUA0nwfo4IYGk=,tag:C2VoPgXsuO8Oyq9PxvHMLg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:2jnwQpDVSBZOXhVX,iv:99GzEaPA+kyZHbihI73nU6302nBdhRvD0ty8C11Z/bA=,tag:Oe2SLylnZNH6mvvr5Y0K6g==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:iK09gyG3PFjNiQ==,iv:LJdUdhKrKTZ3P6FLYq8J3yYSEf3E27/b9lmd7CEM29I=,tag:kJL30Cj+R7rv7ZbP0swI3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWT0g1RzF1VDl5aFZaNStJ
            UmxrRXZsRVFLNGNoSUJIZ0xjOS9BdXZHaW5RCnVOZGNmZVJhTkdmYm5DRlBRTHU4
            NWJpZGx5ZEFFZlJLS1JNUXBzbzNtMUUKLS0tIDZ3Z1d0UWdjVitSRVQ2LzNYb3JP
            R2JFMnZ6YStCUWxWeDVKQXg4cTVyTm8KM/gpghwC8lXqahU+nHK3QQKTQH4vToY2
            LpQVhJ8B3NZHp7j8NIFZscSoqgdtvO8WARiisvXK/iSx4Pmci13zIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:Oxfbj+rMTFnCvTIm9wUVxGxNmltK6qniZ6ez49WS8aQBHxFpJqHwudF0yiBJ57952PX8cS7dtyxdHcH3asw7gTBxCdS/7khKk3QTnyVh4tJRB4h9Bj5jcJ7cUkvrLbDELQ+KksuJ2Dt68F828K9w+aIHl0IO5SFNfQtVQQAs1eM=,iv:z6rxPm8ze607MFOyQiViG0zH2WPps9uQuOb2GoLjL9k=,tag:BKKpdZ95xvLcUxgDWtk4JA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
