PUID: ENC[AES256_GCM,data:nI1qPQ==,iv:Pk+QwtMBlSGMr+NGjYGXZOobLq2gB4EPACQ8UTr7a1A=,tag:EudorG2MH3fX30FQCX3Cpg==,type:str]
GUID: ENC[AES256_GCM,data:lVu4Rw==,iv:EisvbimgIOgz1B/y5/SOwFh0cQiJ0MzNvoFpdnmEwS8=,tag:4n5tEjN8LwKtxoNbu6vi2g==,type:str]
TZ: ENC[AES256_GCM,data:NteFJdxs5o61jL1kk+wIspG06g==,iv:HVyxw76msnS+gSLlSxf8ykaVzKRzw9grcYS+YFNbXws=,tag:wQUdz5/kVIr1mWjRN1VEwg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:5v+6hSPna+FEAT2K3V+9OihXYLd8,iv:xVJ5dZ+nj0yiNwxIAi1Ogxf4Uw0swVreHbM5WbnY7DE=,tag:7Cyd77D7FTbI05bkRtRvng==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:3CJ8NxX+u8borKe8,iv:Xk/60Q1nB/bB86G+jnyNrIHfnF6IE2vassGOIu5xOvg=,tag:z/8xK6XtK72N1Tf8mVAX6g==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:78fTfKqejia5mA==,iv:yC8LepE6LXk74O01MQLGOa8LRJRtA9jkxqrWcrKsRns=,tag:TeMA1tZSXix0q/3XCl7KSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cXFrUnd1QzhLU1RVek9Z
            NU5MRm1qTVhPSHJaakM4UC9JTkgyRFBKelRJCkVGaHNseTRVcVliaXd0VVFZbmJa
            YysvVTJsd0FwYlJWdzIvMzdtbCtCY0kKLS0tIGMra1pEQjFKYWFONFFJVXM0cjEy
            ZGN0QUVyTHg2aTZOUG41UFIxc0NCRXMKVsG/uOu66PSQeP9C8tKZjB5Q4vA2js7v
            Tmkg0/94dm1hNw2BubdfPeoXJ13yib5AxMgdC88O8S8uR3meCm8lCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T22:38:07Z"
    mac: ENC[AES256_GCM,data:BisgAvAVWsXBlrfYFZFa6dApVMWtQ3238d9uOai98sU9ttRSPSob7NVTjTSZXmfI0xNXnKhW0CIFmj9p6tbSwdhsA6aD2Eia89645l1MXHMDGWKKcFJlUDe8KN8RcLk/lZ4dRRQ5xX8SxXGGe3DgliIATb9PgYVKMTa/IVwo43g=,iv:69JoMB87GKJEZFvGykAU6GFLwJ4bxB3HbDZGgku+aP0=,tag:Gnnzpzu07K2mEz0fZ2s3lw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
