## This file contains files and directories that should
## be preserved during an upgrade.

## Backup this file
/etc/sysupgrade.conf

## Wrapper for opkg to support hooks, this is a wrapper to replace /bin/opkg, so it auto triggers the backup script below
/bin/opkg_wrapper.bak

## List of all installed packages and option to backup select IPKs
/usr/bin/opkgscript.sh
/etc/config/opkg.installed
/etc/config/opkg.ipk_cache_list
/etc/opkg/ipk_cache/*

## Backup main files
/etc/init.d/vxlan-nm
/etc/vxlan-nm.conf
/usr/bin/vxlan-nm
/etc/config/wireless
/etc/config/network
/etc/config/firewall
/etc/config/dhcp
/etc/config/mwan3
/usr/bin/vxlan-tester.py
/usr/bin/failover-tester.py
/etc/scripts/
/etc/rc.local

## Backup All progress .bak until everything is working and optimized perfectly. 
/etc/config/dhcp_NoWDS.bak
/etc/config/network.backup_beforePart1.bak
/etc/config/dhcp_SoClose.bak
/etc/config/network.bak
/etc/config/dhcp_SoClose2.bak
/etc/config/network_bakWDS.bak
/etc/config/dhcp_WDS.bak
/etc/config/network_NoWDS.bak
/etc/config/wireless_NoWDS.bak
/etc/config/firewall_NoWDS.bak
/etc/config/network_SoClose.bak
/etc/config/wireless_SoClose.bak
/etc/config/firewall_SoClose.bak
/etc/config/network_SoClose2.bak
/etc/config/wireless_SoClose2.bak
/etc/config/firewall_SoClose2.bak
/etc/config/network_WDS.bak
/etc/config/wireless_WDS.bak
/etc/config/firewall_WDS.bak
/etc/config/network_withMGMT.bak
/etc/vxlan42_NoWDS.bak
/etc/vxlan42_SoClose.bak
/etc/vxlan42_SoClose2.bak
/etc/vxlan42_WDS.bak
/usr/bin/vxlan-network-manager.sh_SoClose2.bak
/usr/bin/vxlan-network-manager_NoWDS.bak
/usr/bin/vxlan-network-manager_SoClose.bak
/usr/bin/vxlan-network-manager_WDS.bak
/usr/bin/vxlan42-monitor.sh_BeforeDebianStyleScript.bak
/etc/init.d/vxlan-network-manager_SoClose2.bak
/etc/config/wireless_BeforeBond.bak
/etc/config/network_BeforeBond.bak
/etc/config/dhcp_BeforeBond.bak
/etc/config/firewall_BeforeBond.bak
/etc/vxlan42_BeforeBond.bak
/usr/bin/vxlan-network-manager.sh_BeforeBond.bak
