PUID: ENC[AES256_GCM,data:TuwArw==,iv:+Aa64RxutI3vGK1DOVT+E1BZdBBTVbANE4WuS7XYSn8=,tag:9FeO12PIdfcLtjC7nEtriQ==,type:str]
GUID: ENC[AES256_GCM,data:sR8o6Q==,iv:XZJ3K3Sef6qNClglM6NQeOqTM1oIUWX07aLRehHqaRk=,tag:IKwzAfHDh96zxYSPJMwPIQ==,type:str]
TZ: ENC[AES256_GCM,data:CvAGIzv/R7Fx7PdnPCa/7w7BJg==,iv:1nHSxANZtkPovDgQt02r8wNunvpf2Z4RmED8ZotJbak=,tag:3aeDgGZw4ypdbgotJ/gXrg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:SVKDHskF2Ri/tdW9IN6709pBo3KZ,iv:7lT8yqEujw2mJeXrNIBmEujh2LcjRQXjfGqxWqD196k=,tag:LhcW6GCXJ6VfFxKuW0RmNQ==,type:str]
PASS_HASH: ENC[AES256_GCM,data:7LWiPDDsozPn8c5uglp7nlP4gy6ert2fmtMaaBflhob08NBcpJhUsQsgmmIkUsyQGJRxrQtUcKzynuWkcG0n,iv:9qZJx4pWThMs7U32JyNjMY8I4qytpDi1WBRxuHEL2ds=,tag:cOo0L7IvCFnTo9SsA/Qz1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbnFxN1pFeFBMRFlxZWlP
            TkhCRUx0YmxGTENzN00wNFg4aS9USHlWL1U0CmhYK3c5VDdNbG5MVUE3WmltL0Jy
            NFU5VmdQbDQ4czhlM1VlUklZb3R1WjgKLS0tIDlXek9zclE2VEFjcVg4SFlzR2pu
            dFZib1lZWWVGdHRoanA2T0dpL082QWcKxRRb+ZRewo5M2rTKdFuQydPIWTAtSD+T
            YhjGTRaQG48Yogt08iENTqQ1qIIjo3Wrvr/PhtkG2teq8oF/T+AqLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:KZ9S5oq7mIqQGeO4+tiVbO3g6JDno6ss3Ii6RwvVD8hWvAAsNrJ7NBg5jzBTQFZR/DrVx0BifVdqdvarn3klbVPyhdDgs+SfsrzImUfjJRfLLrIVY9fObyh9luMWQcoyN5Ct8msq2ef0i4Sdplm8ey4ApAIErbXDVgWAmBbiyS8=,iv:ckG3M8tCNk+edGiIRJcQJOLjiijWpLhog/HS2Q4kjQM=,tag:UWcEtbOTcJqhWMyIC6nXkQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
