PUID: ENC[AES256_GCM,data:0oxTYw==,iv:Dg7b4SQU86Uvib1nZSGIU+yohBuUvHE0iu9m4dq+F7w=,tag:p6+mJIhXFYB+bEehf8zzBQ==,type:str]
GUID: ENC[AES256_GCM,data:sFDuhA==,iv:2uqIvAsJ1qpiNTxyHXQIME4uP1suCCQjp9ebQ5kMkqo=,tag:ElRkK8nCJbfYCyoVHAJgBg==,type:str]
TZ: ENC[AES256_GCM,data:a10GgzGDqUir1h1uewb1aqpG6w==,iv:GFxrq+kSKP80CLbsqUByPlKM9ypLp1EsPeamwuw7dbU=,tag:Ph8qNuAzauw2og59pZSiGg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:rYTljF/0EKi+I1cMUV1QukjPXuYS,iv:E2hpy2GiPtqD9MZyVqFk2DYqYdEOVzc2aJ0lIvuaK9E=,tag:X6ol77yu43U504mYGn/2zQ==,type:str]
PASS_HASH: ENC[AES256_GCM,data:H/H9cOQXi0oARsTgqNkWfEZpbmA/XpT8V3MfNvlPlr3cf0AlT5v5RM8bv8dGVX3/Xno69ibpnqIyHMG2hWRC,iv:ZG7romYV1M2VOlQIJM77XjbGk/9OKadj7OHyRahO0XE=,tag:qdMT5HSh3AFU6MCM08uRQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWE44Vzc2aEpQNXMxNkt2
            VDJXdUc3akVvS3k3UHMxbWNVWTliNUxvZmlvCjVDUHlveDJhUjEzV3NhL1l3dUNs
            eFJORHRVM0UzcUxBMVFFZ2F4S0NwLzQKLS0tIHd2bVdvdndXVlhyTlpOL0lyVi82
            K2RUNTZ1ejZPRGtoOUVYSEw2bjBiZkUKgBBJnLYcKD6yMibMDPzkI78lALfFi2HS
            dTWwTVpIla64thH/lTE5u6qurBdTRZ0BmF6z0ZfmYWBQZ8/fM9Hvlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
    lastmodified: "2026-10-08T22:22:17Z"
    mac: ENC[AES256_GCM,data:gQJ8J/LLN5O5ikF5v2NShL6f5cg8ZlGJNr3e9BLg5kirQcNKotBfSseh6vlyFWhNl4h+vhg+/xOAtBCvsbcBYbmGQ/lbD1OsDeybhvY0Pm+pd919V20KAe+Vq5g0SZs1ckHVC1ybdo8QwqPsXJHJZU6BWxzOgGSuzhgJtT0lOS8=,iv:8C7jAxBX6P+vX4njAN9ZI/iIs+VKI/6WeRp8ymYNJJA=,tag:2hOEH0QwvS0BaI+sqWxkKg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
