PUID: ENC[AES256_GCM,data:VR1LMw==,iv:n+kkQkhEz8JwAXE+qVDL57u2zLi6gz8ga+n3sx8cxIE=,tag:7ITqdCqnkEOz98FXsIiXFQ==,type:str]
GUID: ENC[AES256_GCM,data:4SL/qA==,iv:UiWSw5nmSB/lW9pUpunUgz1hbCNsSpxyeuzvqKU9xB8=,tag:+PiqsGxFZkXRVWvQgNnehg==,type:str]
TZ: ENC[AES256_GCM,data:CcYfYRTGJZtukHBx3pUNqSgTUQ==,iv:95qUrYdrVtbzP/UIO47WoTzczhKRtRgxqJCNq3KTM0o=,tag:uf6ZUvHaD5j4gNYVft3N0A==,type:str]
BASE_PATH: ENC[AES256_GCM,data:jr9Fgw6NBbWIaLIvTxTiWXuknK51,iv:XY3jP74ckmKaHeFOz/cFJW7ste5BfKTNf3PR4vTtBnQ=,tag:q3Qz0t2/3Ofwh2sMDq73iQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:vOBdbkaBuEYT6TE5,iv:pdXOdOWnGhXSLj8fXY8YFLl8Z05DDs5ctJo0v7vmfSU=,tag:YgNSVU4dxiYFhMeEO3Ywdg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:W9fxILcVX1jKxA==,iv:hFD9jOt7trSD+Y234N8neoXXFoao6pF1X5SOfAYMPIY=,tag:18ZLc9BF149UpFox8LNeuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTGUwODMvUnFKd3ljcU12
            dmYrM0ZSN3VNeU56RWZVS204bjFjaDd6T3hvClIzTjRRSm1XaUlPT0puK1pmL2JQ
            dnJLNFdxK2tjSXhCOWxoNUVtKzRxVmsKLS0tIC9QaFZ3QTJRYndJdjFYYXZtSWlE
            QVhtZDNaM3ZyL00rc1B0WEpVK21QODQKtrebCRxEV2CfYQkKBz7TNecSsuIUTSf9
            kUgOCz0VL54/pGu+0eAq40b71nC8mtyRBiIcEEYqzf6YAe0ZYABquw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:06Z"
    mac: ENC[AES256_GCM,data:ywADWsrKpu8LJjXV4rDDlU7VbSlmF23r1E+E3sGlS7uIx6qkWIDXfXUNNQAeI9VJDhji0Yja6ut1GV6VusfgOxTqkXSlyVJao3qpPUhTgl9eiylsQ0PXTThiGCPOLhnveS/rxGF0+0cIjZibQGSVBD2XaUrztBCRhIKnBO0aSS0=,iv:15ooIXVZ+hQSYFgTJvUkGbg1SYcz4SCH+j7i8SAMqmU=,tag:DfZFZwDL7TWcfIcvkIZY4w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
