PUID: ENC[AES256_GCM,data:GNRDrA==,iv:3Pw0U7s/Hz9UnczgllmPEAUUvhjQKJ4EKi6JfXwWA+s=,tag://pwuquIa++VjPr4isDmHA==,type:str]
GUID: ENC[AES256_GCM,data:qoxikw==,iv:OqjZGCgirIRCA42tT8m3x62M5+Eb9znfmKv5Y83c9EI=,tag:oiasYDAopmr9x8jcY6+NJw==,type:str]
TZ: ENC[AES256_GCM,data:LHNgF9MtpdLMhOlzX5/wtNsZSA==,iv:ntcS2iEmZA+WFltAgE02I3yFwndauH2mMUko/L7FZm8=,tag:RYdw5dYP2hTMZXAnTIhINQ==,type:str]
BASE_PATH: ENC[AES256_GCM,data:3Z6TIHOOAhdmDBeAwVSSM8phOD98,iv:m1FAfraIL+mj9Ov6KT+1B5jOg7+rIO3sE2LGF/td4Wo=,tag:LRsLhzdU9jknBXzNFssW2g==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:Ovt5PppnUaNJ4FxZ,iv:yiUXzIqdYDhWMoOBkoNX9+GBLmOzfXQvIA0CIqjHKGE=,tag:yyUP1OE1UgtJMKzfzgU9rg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:1Pc1VYZfLUghiQ==,iv:L1XtQXSYl0B7pe1m322X8htGSEPdtqnihLKLKcPy8Ag=,tag:T9HCBx/7CBYqbdDLhb/2QQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUU0xkblZZWFl3OEh0M1ky
            UjY3a3NKRmo4RGNYeFRvMFR1SVU4YzZHR2lNCmc5a0JPM3ZIeVREL2RKT1REQTNP
            YkZNOVBaK1ZybFJwZElhWmxYczRTdzQKLS0tICtIWTJ0dG0renFGNDJBMCsyT1p2
            Y0RrWk5pQytNNEJxNUloTWxwMXF3c0kKHalniysEzAxulgKgrUlWFfppYsOVJ4Gd
            As7GjMoy05dfXygaIbu4Hn+WabvPH+kjW/gpU4P+6T21KwDUsxcoAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:52Z"
    mac: ENC[AES256_GCM,data:3+VWdGU5YdC+wS21J2wdA7aK0/7KVc5grGPlrGEBSeb4jUPi8Gj/v9CB4SSU0y/E8X2Mijk2tkwO0/Jm0KpKyxba+dH3LVi1Fnsnr6KiMs1godFrhlpV9hHy7vIsEKCBobGAAYLlEIepDOrNl8elAZZMAn205WrtYQEwCMS+WPU=,iv:3UYzVLLlg+jnzXheM2NSC7RJV9ELH4fQV6xg6HVTpys=,tag:Kb5NWnlQflvfcqO8Swb4fg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
