PUID: ENC[AES256_GCM,data:onXkzA==,iv:AJU+BF4bCbc0DMVXiWw1k9AQSyw/vVOZX52eJ3EAcGw=,tag:sCC/iQbHXiiOPog7fBFvTQ==,type:str]
GUID: ENC[AES256_GCM,data:hDVdtQ==,iv:wLsy4gOL5vn4impcrhehQ5hZrQTl1NWSacQ8Jyck2dI=,tag:aU4cc/vNRNh8A/qfHQHayw==,type:str]
TZ: ENC[AES256_GCM,data:G8rbNPLH2fcoymeMjaBm9RCkXw==,iv:nI5b3i1ZWc6cgmz0YE2GD6nm2vUvSaffaho8iZxwebE=,tag:GnHO+0gHXM8xUvJC0lUUNw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:pkXHqHyIk0keR+9jIkZF+ymKCEJD,iv:FaW7j70IkQMW1M9RSmkh8P7SnmP9HR8HO7DbPu3jDsQ=,tag:gk8Sido7OLs0HeQiNJ0LRg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:uZLwrf+M+RM+QQOr,iv:mQSUm2LBGRUZNwxCRXaEyjLdukH82wYmvNI10r59CDg=,tag:8SrVJIYFRXnE1YN5EuPNCQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:KZCfuO78csg7cg==,iv:y8Of5+HnoKqwgLNm/ZzkO9nwK3pUVh92DlUItvhqDH4=,tag:5m56gBSHzMwKUnw+KuqpEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdlMvVDBUL3ZranhmS2VC
            M1ZYNlJRVWpxRkVPYmw0YWxYVW5yZVJOVUFzCmZlMFVRNzlObm5SeUpjdGtkc1Bk
            a2dDTFpLUk9kWFpMZktrYVdkZU9iZGsKLS0tIFUyVXQzUDIrTFdLWkpwaWhnL1RE
            eDZFOGtkdng3RWhpZnpiUjQ1TVlPOTAKA19mxb1rvBtYxbjqJgDr5AJpn7a7qyz0
            gylOrwFLLZmOA/3LRvqXTWrVE4ndTEVA/lMc/eB6h6OxeSrpjR9aMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:ynh8KCwQ/NDgVvFUgVojlxh4kEAKbByZCzfoWTEJKGTjeJMGbs+lJWlPZ552vZFh9GLJqajdbuFiot/l4KY8RlnzIGDtwjkzaStFYwd1DH4DmwHy8bdhR5RSh78lwVruXL1Zy3lIq9CbSC4ILMFJ1g6NJj02mogngHNTfbWKKmw=,iv:0Hvg99MXYBYUEd07nK6JbdHUEVfMp4kghpPzqyO0MXk=,tag:dHZdLHjZ13lu1o2cVcD1Tw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
