Tunnel_Token: ENC[AES256_GCM,data:xTmuTACI6/c0GzZAdN27w4NmHA8PPRI/MrwkLwfihAK/3UBMBHcDe0kA0YUJGazpRPdOpvqt8n2OD3u7p4HtATcC7x0+rBFV67uQ6q0GHlSZLdY0qYKGXQdXEeDGHPcPOfLrh7qUn/woKD/ho/fZfO9l3pA1r2mi31xpYiWqMvkT0KQ5t6TBJdzbznrsbtDIDbB8fzvE8oA+WeNNwwVLFvCCxGbzEyukYJyYY9lb44mh4bttbcmNYg==,iv:WtxeYCzGspfC5vhP+rY+N6rvSNHGNSWFmvoRgIAsVgc=,tag:Fb7pO8NJhsNHMpQdDcDtJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVTZDN0VObWpGUXJTTFUr
            a0MwS0d3Z1BrRDAvUnVSVE93RlJjNEt2dG5RCnJNcDRqVEFPQ21LNXc5L2U0b2tz
            Wm9hTVJUdVBuSmVRZDlBQ1NlZnJUVlUKLS0tIDc1Q2JzdnFmS21nbVJtNnJrTnEx
            TVBDSDMzZzR1U0hvb2VKVHBOVVczODgKN4Ragq767qGryUMGG9n772BKw4xQEqku
            NovUu7qFPBFlpXmhuW2vJ9jKlw3lxqep/L9zc55F2iBOWr9oPqMosw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:aT7Gqn2+FeoiHnp/VnC0/WfV5JYdloyb5njga0/24goTfHKhBLHC0tZjND4gI9IdGL0CT+U9UlLRIpAroTtKLbO0y1q9yHunsvqyR7fRzoD3uLOYsWhPc92PhMlg9RGDdcl9thGPKg5DTp0MxJumrYuO5w+8Ff3FixjtSkGSqq0=,iv:yMh5Ab//Rlh3+d4CqAJtwtIlIXZ/Cn+p9MHgoSf3RqI=,tag:W334C8cK5ARMJG/pAIyA+g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
