Tunnel_Token: ENC[AES256_GCM,data:x3JqQh+wAOB7O0td2OR58sy90igguiTG9bPFDbXNN860822oDCqv0T57oFgprrOsh2+Hv/78ey1nE7egdcl88TnVmIk9RLhCbBUfIO7jTgg2w84oK3itPxZQN5yMnrnbzK5Lv8SOD81Zi0Qly12jT4JCuK1WumAXHbrNpVXl/h2E0gYfsJz6NbU1EDK1N+UnpQ7D5HaeAERTNrdHjgC1ZZ6/+lGF/8KBJW3T8xKrtXwTpAYeHuVBAQ==,iv:Ad3sGTSytrKYMTgKLPTZQbl+KLOLaCXYPt+TnUY9YhY=,tag:43kyX0MY9c3acUpoPi1X9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmM0ppbkNkR2puVXBHSWZG
            OEFtVlMzS0NQc2E4TlJOaEF2K1kvc3loWGpBCkJRWDlLczFCeWxBNUNJYzg5eGd6
            T3Yza0xNSFVWRUtBVHR3RE05UkFUK0UKLS0tIGpBVGNJWjA0N0NLR3QzTjVMT3pn
            MzJWTnlNSkJzL3grS1BaaXRYU0ZOenMK3LvEZNT440Qr+P57dTWp0U1SuFLbtupv
            0jslky3IJDdpXG8xhZyVtXR2uyK4B9RgaxXGWAZ3kEqjGdIbs7E/2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T18:25:26Z"
    mac: ENC[AES256_GCM,data:NlR4O60ZvavZPSv7AYEijYVfU7mX9RRKgKBbZXoVhsClMxJCCWc+hukbQo7V46YQMpnPAMBWn2EBRwQrVzYa8lPrBHi2RjTW6tfkDzuJInuIPK4/BRxVSUd896jLTZNkNkJDUy83mqObkg/IC+GbjEPjTQTVg0nvDCZ2M1Ybv3g=,iv:lduU6oG1I5myND03fyMBKDBBYlCSL55UnmjhU5DZ8wg=,tag:Z2qwwv2HoDhcyZpEaMXpug==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
