Tunnel_Token: ENC[AES256_GCM,data:Nz7OLdjj/fko+0V61hEegfTgfSHmiuR/swvAzj9sZA/fRD9j7zB80qr06jNa0223WoVFfchPCr2R7pDQ6lwL6jQHCjLxLBfv92cJh38Pp+OC3uPoi3wx7Wr2R3yolWK6fnWvT10J6QzUaIINyjrV3hXpbyhM1125pjTJKzLzVlR1p63wEouC7XfQCa8U3REvSylSjZrMTbNLlCgrRhRK4VVWko3sqnLlgYlMjvgNun7x3c6OmlUFuw==,iv:x1y7pudndLMsJK4TLNiZrY21cd5/C+aB3NRZp9ZnvlM=,tag:UVZiJcSc2hIrI255mxMyMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZWZjWnBIaXFMQ0pPSWpp
            UFVVWjVwN24rVCtQUHlUdDRqdFhPbExYYlhNCjlXU253UXZoYXlvbmliRWliZjdY
            VU95em1uQS8vemZ3UCtYQnBCK2JqZFUKLS0tIDJPTHNZYmN1T2N3YUJqVU5IU1pX
            WCtwTzJaTWhqZHZteWt4V2ErUGR4WDgKNCqwHeGMNySlH0OB1ZHtVi1083BYr4KK
            FZqylDrEewgTaad46gBhmk+jQa6GacUNXbOTGwQ3QHjTbet5c42ulQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:RI+P/GgEUz3UaZOleNgvIF0w15XRr1EMuI7bVMYuMDVW0MVZwpLf0g1nLGoLqimXUPH/BwnU/XlhLNdbsuxF2hniaiyXPVatnkUuGEPZ4x7K0GTsbC+fhij8LJBguV3QvcPuqBzvm0AVEi2APta6yt9M7utL+yBLK9wjgdcK0Vk=,iv:v1DRs0Wc9lyoLCuoM+anugV+E3pCfj3ScqBLfxCDxmk=,tag:Lsm8Mqa6jjzo7Jd5Y5bhcw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
