PUID: ENC[AES256_GCM,data:bv5ydg==,iv:DzEXwlOZkUfB4ibIiSybrliXW9PMa3X1I3ArOctkDlE=,tag:dUnd0j8ImmNlK83MLoZzOA==,type:str]
GUID: ENC[AES256_GCM,data:2Hz7OA==,iv:MeeeXHW1Dr7y+zTpoy4RzaXs2lUULAStm3tcrQF88Co=,tag:oeRN/RF/L4csmI+0z9pu6A==,type:str]
TZ: ENC[AES256_GCM,data:bL9ykafutMeToLGRLeXBv+N/ig==,iv:IOWF2ylfgBXvAqaDDuofa2NbE6CB7AlIxZpdKQfB8Ls=,tag:E30vJeTDZuu4WuguzLNIMA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:y9ke3oUv/h03O9naAIZr5o/D0tBY,iv:/a1P9Gw9duxa4Wk49Qv3vxQ/NJUAXMjldFO/BbetgbI=,tag:2WgklUjgSiHfWtwq41F8Gg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:Dy3FkIaUZAZBLS3z,iv:Sdj8fs+LPDvDwBiOYsspVHp7f8KsEEOrDfCkTY/k0qs=,tag:pYX+h4J+BysS6T8rnOGs7A==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:4QdeLM4ILcKeQA==,iv:JlvEZ6A/NDOK8CZo/pg9CN5MBvymNLoLx+SaOPCKNqE=,tag:CToG9MZBBV+81cDUWugytg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cHhlVTlMcjFrV1lQYTRV
            YVFZeDdSUG1YMkFCYzNYWEgxQ0w2YWlGYmdFCjJNajU2WGFDNGpPUURYR2lDMk5B
            MEwrb2ZoVVRxL09hV0xGa2RiWkZUeGMKLS0tIHdVWnIvWFByRlhlZVJlck52bmh5
            aytJdHU0OEU1R1QxbExYZVo1bUlQaVUKxMBqapt0/n3fXQ6olcrMmWFMcbEWpHiT
            Vy1ZssD+XhXLUxNxoAUu4TclJrwy0ca3XUjXmkFE4NIEKAneNsfz/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T08:41:51Z"
    mac: ENC[AES256_GCM,data:qZmiRdsYnaM2j8F6mdSnrHC6+K1PJOCriLwUZFGQPf1g6BIllCAT6Srl6HBq13aPjbhvDdtk8eS94QxX7cJ4uOv9XsuaHkk+0pmqf4izZ+dhWBuD16ouxU0/Cq/mrousZ615gmB5YweheeIpSxUKhx31r2DEBFKXezcGvg5Oxog=,iv:5KjwM9O5GW4CVNRweusHU6Gr00rckkOz821xrj4YYGI=,tag:0Ryj1yZOSHRQXwYGhkK5ug==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
