PUID: ENC[AES256_GCM,data:ucnQBQ==,iv:zhWgvN91xp7qbeXZsqQu1PTpAL+0Tpcg3ZlQamb/Sh0=,tag:8Ateo0Rp/KOPfJtkILh3NQ==,type:str]
GUID: ENC[AES256_GCM,data:F5hlSQ==,iv:kQhhljAcUwj00oxKGvmeccRazhBc/0Tunh6uPzQVO3g=,tag:fwzP9kAmAml1QgoLvdzO2g==,type:str]
TZ: ENC[AES256_GCM,data:+4DYgvXrxb+pZv1J7efTm+bNaQ==,iv:ObVg7jyS68ijvWeSexf775+VnG5ikB7VZIHXGH+ft2M=,tag:X3vjEx1BCHk44MAuGNRXEw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:Tg6cjhO/DJ6bfEmbjL2BGhyofhVI,iv:i+kA6PXw1g061Haem2ognW+DD+EDBrQK1klghtfP/jU=,tag:CinSaThuZX5SnPNc30PeYA==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:NySQzt/6xVivj2sU,iv:7KVS5L0IVAnMzknOP7qmmeryD9YPL9WKuUT30ExzaMM=,tag:cWH9FCMhfNFpyX0o7cWQdg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:gBnw0EJH2XhiDA==,iv:fae2wREoMWP1sBDqEY+B4G7zRH4VOgGZelRfLvh5R3o=,tag:vUMOfFId5oBNAUOmrIc2dA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRE45MzEyQ1J2Tjh0UzRt
            QkRQNUtKTUR0T0dDUEdSb0EwMThkcWpkZmxnCnBiWlc4TGFYM3BOTVBsWVVhUTNl
            RXovNzJOdTh2OVFDdDdvbmxNaHp0S0kKLS0tIG1WMHNQdjVJcDI5QVU0RGh2VXZQ
            MFFKeUdValNZYlduNHZFN3U3WG9hQ1UKuEsfnMT8LO8WAYLY4n5MXjQuPC9L48b2
            YzF7/ngFSgoM4AGtplY68PtQEOgcOEw70Jt21PyuSaIvF2CeArGmgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T18:25:26Z"
    mac: ENC[AES256_GCM,data:/GyPUIHG+nIjPHpSdwbnroHVLs7OdZPHXjYUhQbeXKVkyAImTqs6/AAta5cl/6qXu5tRsSynQ8dOmktHQQ1G12ISobA3Rc3ByM1mlx/Tk9aZJ38Lx9bm5/CazrVX9iScsPVptCywT/uJxYwmbNYJk27Mht0IOJJVVnTLm3BOwNM=,iv:hyOFZWcdE5fs8MUOWNFUV5hfhtYQkTXSlfUjVjw2sIk=,tag:RHIgpeokr5/1YyowI1T/dQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
