PUID: ENC[AES256_GCM,data:JT7qOQ==,iv:+czm+rlp5b+z7+5sOrzXs8EgWpqIOvl7WLDINgcVkt0=,tag:j5fgvVf12vmV2C0mCaQ17g==,type:str]
GUID: ENC[AES256_GCM,data:sB5PjQ==,iv:gG4dG5qPgoE4LM1Yz1afA9O1HurltqGI4/VRR+89hrU=,tag:DNIgxgGZhNdQOI3qVx7HlQ==,type:str]
TZ: ENC[AES256_GCM,data:gVdnNoxnw5HhGU6GxRjVI42CMQ==,iv:p0d2+zdK2hkeKGjYUTz59PeTNxewKxofUrbc2WnCKbo=,tag:w2DoE60g40kiYdtrcWXdJw==,type:str]
BASE_PATH: ENC[AES256_GCM,data:vJBK6r25n7Gp69wLy1qZlKZ76myQ,iv:ib2uZZOtum9gCOt9lk83/MFZTdhmTlxj5wczxBGXWdw=,tag:RUhj5NPXyZi8ckYvWFtuXg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:Bj0gqJrCl4l4JWVp,iv:5kqs7czyIWi4L2Um3g2Yz6gUXf2Znp5gqp1f072nwC4=,tag:nLWtkZuj5EfEfB1Avu93xg==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:v8ShDKl908ne4w==,iv:pXkEuWtco0GQo8v/wBFL3txdRSpZz664pDM2Dfmeu9Y=,tag:iJgvu01hBIty2xuBm0dUbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0elZ1Z2dUZ05pUTZSSExv
            T1VJbkZoRFFkNXptb0pvWVlGUUdLRURTcFhzCmdPblRhTXdLYmlMUVdMUE1EbzBv
            VWFHOGM4Rk16bmczV1RaVndYUVVacDQKLS0tIE44NXY0Y1V6bmIxZGYxRGxpUmZs
            THVsMFpIYyt4MUJkTjBTaG1uT2hkY1UKFReSp2Sv5ctbnQhcY1RRS5VeZpnSHfCY
            rqACOTIXDJ/+FNQn4Nl0yKFxqhZMCAgo/DGjoeog9FOfhJLjsa2ixw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:Jk9x0BF79U20wOWUsa0pJgOVEqFohzjHgkCX5KkSU0rZZEh+sucIi4FZwgZxZCh3sy5YmralUOE2zGbKeoKflNokesDg49N2pxelbqlhxNr3FDJXact1axTs1BHH4EXCVfWZDxAK3nPzHTFqnEHYXhCBxIAa6CX6T06mWu9u1FI=,iv:UwApOIDRe9xO+Wt3mQiRWgPXp0ICdAvI3TrLuH3XdlY=,tag:yxAzWtuiOcZjuajLX8gIOg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
