PUID: ENC[AES256_GCM,data:yHd43w==,iv:NrglWS/Iyjk8IIyIGl+uaHUyC2jaj9iWlpvmCBYw5Xw=,tag:i2droJ6isCfXzFxMX8g9Ng==,type:str]
GUID: ENC[AES256_GCM,data:Nfg4Qg==,iv:wAqxn5M11HeWzso0pc5ZyP0OjA51oSodYTywQU1Dft0=,tag:DWBy+qxmqqkIc25/oxHY5A==,type:str]
TZ: ENC[AES256_GCM,data:vbI82Qn5BTiCNxi+BUQjp5vgiA==,iv:lh7Ui1t50xTZpEk8eNLwUnXee9GWJnUbEQVOR/DwRJg=,tag:uqS00+8U73iqHsLtSx4LHg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:71ARcFR09K3iJ2IsGNtSz5IPVkvk,iv:j9+lgQKDUDji1QrtE0h9k1rAxFgGavP3vx9BSQug/24=,tag:GBsw/L9WCa35DRA3GdfNFQ==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:vYj1UiQ8Ef1UPERS,iv:46RN3uMAh+C8K9Ltr4QSQlp2QdiXaSZRGOlTvgPmXYw=,tag:NJlvsJ8VTWwGxRKiCM0tTQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:4XLazljbxWtQ+A==,iv:8zc7t2BXDB6uDx7/GcwogsoCTbDTVlWKDkj8VwEXEsQ=,tag:StJ5Cx2MbKUa3ONYkddCOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cis3LzFnMC9rc3FoR1VH
            VlY2amdKcDh2T0JVVjNYT3Jka203MGN2QkRNCjVxQlAyNk5kbWx4R3ErV2ZIZWh3
            bXR5T0JpbjYwemEraklZbkhvRXFUVU0KLS0tIEhxUzdyZG9CL2QwVEFEU2RGVThU
            aU52dzlSQzd5V1JjOWtxNmFEUGo5YXcK7xZfb4C/KahuoulIfndJdeXTI6tXdlgO
            wNUiTv/oUlz0cbe59mpIfZYhjj58SVlGUw6AlFgy2TDkLPwzHnbMgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T02:36:23Z"
    mac: ENC[AES256_GCM,data:3MYZFkSISYLNWztsXEq8a0i1a3KTgeTqsUSG9gIMHuxNAcYqS5GwsD6XgxD+zMnSv80bdUc76fKtBbyLTkRio+eu1sbcwVN2wHfWXMZJf0GyLLcSP6d5hBZ7kjhYfCpZparVZ71fQhFTrARw1RWEux0FiB10A7Hn6gH2cHybU3s=,iv:aqm22ALltFQgfN/ijalt1yZcz05jDBZp1BEgY18yLuU=,tag:xXVJYP4o9vsGLQuTH0AUIQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
