PUID: ENC[AES256_GCM,data:za7pZA==,iv:j5OPZzwzAVX5U88HA9fJA1BVn0EU1kC5eokzrpgZS6Y=,tag:egYT7jy33rJMfCYVzq3tvA==,type:str]
GUID: ENC[AES256_GCM,data:8Kgs3A==,iv:oIr59Kpg5mnVuSEra3tTzGAXdtm+fvl0TJCy4nJfAEQ=,tag:cn6AIErC9x+cdCgYsYS64A==,type:str]
TZ: ENC[AES256_GCM,data:1AzoYSAEO4It8yB/VgnYjsQzFQ==,iv:bTf2u0cD4RTXiUV9mEFd9ZcgQVoEXi5GL6rDgd5McFU=,tag:UJeF6R0SdhzR/NpqLuDmXg==,type:str]
BASE_PATH: ENC[AES256_GCM,data:XoDpKBvJouthMh8GlIs6fFRTzDbx,iv:01EYxNXoIzMGlw4bA9arfGy/v15B/rA8efGUcmaOKCI=,tag:VcVyJQ7kg3WKjsFTQ/8Wfg==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:pDh89U9MUofDdy03,iv:R/t27eBp95NGWVdcQZs/YwJuZNrbMghCy1jT7LF1xBo=,tag:A8Z7TvhpxijaZgKL3rsd4A==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:JXPbE9QCtUxX6Q==,iv:rVillC412ZQmlGiyvbA2f+ZW5tfiE5ntK/J9b/G9yWo=,tag:xLHvf9WIbVMar4rS+sqr+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyenpPLytiN3Y4c3lwQStT
            ZWozcGc4a3lGdno4cHpxdkd6aXkyaXBEc1cwCkdhUmhpQnJTRmh6blFVcWlveHIy
            TUZ6Z2VQcU4vWlVQN1hjTDhxK3AvWVUKLS0tIGszbUdRRmhydUJJODVwdC9xeGl6
            NVlUWkh2VGtSdmpQdkxwRTZLbTFwaVEKDl2EBidoqcWadL3hC6p7UECTtQwZBgCV
            pVC/XNYAJDVWuUmw4pR0kmTcMFOHKNgjTccxj3VDDABfTsbOW/3OGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T02:31:07Z"
    mac: ENC[AES256_GCM,data:WrnJQJ1CG2z6GMTaZQbQZyUOqqF3qQTD8K1ELwAjmrCsA11930QhjGuS5kUdf9nclKL4mBcnF8VaiybsOHkbeC0NjCi9wMTSGFeF6j+HwfVSO5fF3wBPeSXtgyOyXoNA9PDq76pqRHsfcO4m43huNGkzi1qpd3vBU1oSW9s9o/4=,iv:gelzegdwk5LSK3csD+NyvyNC2ylBF1oj1qx6wS+udu8=,tag:SqRdF6+Of6NzLCuHWNcRWQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
