PUID: ENC[AES256_GCM,data:aiyKpg==,iv:5xQYRgmYbWR5qSIUHsJkPRhdMovruCN+a+1I9jEA5tE=,tag:PvXKvszPiXqOw6Z1ER7BMQ==,type:str]
GUID: ENC[AES256_GCM,data:GnKkSA==,iv:jjHM1HK2HYire/Uzpfdptay5nBP1Z61AN8n+bWlyrX4=,tag:IZX4DC6wAnA9tSlOTxz0PA==,type:str]
TZ: ENC[AES256_GCM,data:GHJ5SrW84/xuN3BpJxWMvtIwWw==,iv:8kjmT9JDRJeSzEaBGUArB7e5DKR4VaILVFdSHt3k9mI=,tag:MMtOe0W5Ag14PRz2KyaEoA==,type:str]
BASE_PATH: ENC[AES256_GCM,data:NOZy0Ue8FCcUU8SvXSIoPbXCr/j1,iv:W0b0a+qgFQyP68pRuJROvmNeAqfiwkPF9c8D6HiYYIw=,tag:dU3fzQwCvQXJ9Apkqn8Rzw==,type:str]
NFS_SERVER: ENC[AES256_GCM,data:tw110ahfrTY7Cz+C,iv:m3u/zfy9+Q7trb9bliKf2j0+sfq3bdEEzxE+Q/aJblE=,tag:QeVVJ3BSg7jbQ6HY+qBQdQ==,type:str]
NFS_MOUNT_POINT: ENC[AES256_GCM,data:LP9EnUOpQS6tFQ==,iv:ig+xMwn2Ebk3HHYOmZh9yRV9unZpAe1NzLdoVOlfx/U=,tag:OT28oIJWdUQX8sp+15Ia4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqmzhsl58talkkax7g6xwj9xs68rqm2efxa5z0zg2u566m3dzeusj96x5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUENPZVZ3cWNoQmZ3eklv
            N3JlM2pVditQaDFLT2crdzBiN0M5SnNuVHlzClNMWnhzbDhDK1B0cG0xU1o4cXhy
            Szl4NWlXZHJzWkRydG03QWMrb21BQlEKLS0tIFpDU1VzTDQ2eGtOelJoNjFHbEhD
            TTJsUW15RGU0L0ZUaDdnQ05maGJTSFUKdrxd0omzzcW9dZq3+ZwpCdHtSnzvEQh7
            oPUn5LqWOh8VkRl3WvH3g7jDVgfVRrYnZ2VvHue/s6EKJXQ8F91YrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T18:25:26Z"
    mac: ENC[AES256_GCM,data:bFCFrWsFf2LuF6uNLaW3HNwvVnYqPYxoxz8a4RYKolM1INz92FI6+T+6z+zX9LPP7yswl7ZvBGy2heYpWV6CptAloJMfpXYdVsHP/dbrKs+xLMO+RPS7aDKM6D4+2hTUl9fnDMpGSfzC3hjpZ87qh0Rumtsq18YpUm8XN9ffRE8=,iv:9XgqKqj3Cxq45duznq8caQ0pbM8cRfR9ZqEXIll3Jew=,tag:p5CpEVOzIdnzV3k+nzRBIg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
